### ISSUE TITLE
spin deploy output formatting issue

### ISSUE THREAD

**Issue by rajatjindal** [fermyon/spin#1002]
this is another variant of #988  (notice %20 before wildcard)

happens if the route is `/xyz/...`

```
Uploading http-go-test-1 version 0.1.0+rf7202d34...
Deploying...
Waiting for application to become ready...... ready
Available Routes:
  http-go-test-1: https://http-go-test-1-koc82ijs.fermyon.app/xyz%20(wildcard)
```

**Comment by itowlson** [comment]
I can't reproduce this.  Could you post your full `spin.toml` and the Spin version you're using please?

**Comment by rajatjindal** [comment]
I apologize,  I just realized I was running v0.7.0 of `spin` binary. (while v0.7.1 has the fix)
