### ISSUE TITLE
`/healthz` endpoint for http apps no longer functioning as intended?

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#1006]
In spin v0.7.x, it seems like the dedicated `/healthz` endpoint as mentioned in the [docs](https://developer.fermyon.com/spin/http-trigger#routing) no longer functions as intended (or at least as related in the docs).

As an example, let's look at an app based on the stock [http-rust](https://github.com/fermyon/spin/tree/main/templates/http-rust/content) template.

If the HTTP path is declared as `/...`, the `/healthz` endpoint seems absorbed into this rule, returning the same result as the main component.

Spin version: `spin 0.7.0 (73d315f 2022-12-15)`

```
$ curl -i localhost:3000
HTTP/1.1 200 OK
foo: bar
content-length: 14
date: Wed, 21 Dec 2022 20:13:08 GMT

Hello, Fermyon

$ curl -i localhost:3000/healthz
HTTP/1.1 200 OK
foo: bar
content-length: 14
date: Wed, 21 Dec 2022 20:13:10 GMT

Hello, Fermyon
```

Whereas with spin version `spin 0.6.0 (12a5037 2022-10-21)`, we see the behavior as relayed by the docs:

```
$ curl -i localhost:3000
HTTP/1.1 200 OK
foo: bar
content-length: 14
date: Wed, 21 Dec 2022 20:17:01 GMT

Hello, Fermyon

$ curl -i localhost:3000/healthz
HTTP/1.1 200 OK
content-length: 2
date: Wed, 21 Dec 2022 20:17:04 GMT

OK
```

If the HTTP path is declared as `/hello`, the `/healthz` endpoint returns 404:

Spin version: `spin 0.7.0 (73d315f 2022-12-15)`
```
$ curl -i localhost:3000/hello
HTTP/1.1 200 OK
foo: bar
content-length: 14
date: Wed, 21 Dec 2022 20:14:12 GMT

Hello, Fermyon

$ curl -i localhost:3000/healthz
HTTP/1.1 404 Not Found
content-length: 0
date: Wed, 21 Dec 2022 20:14:14 GMT
```

Whereas with spin version `spin 0.6.0 (12a5037 2022-10-21)`, we see the behavior as relayed by the docs:

```
$ curl -i localhost:3000/hello
HTTP/1.1 200 OK
foo: bar
content-length: 14
date: Wed, 21 Dec 2022 20:17:58 GMT

Hello, Fermyon

$ curl -i localhost:3000/healthz
HTTP/1.1 200 OK
content-length: 2
date: Wed, 21 Dec 2022 20:18:01 GMT

OK
```

**Comment by vdice** [comment]
I do see the following PR which appears to start the process of deprecating the `/healthz` endpoint -- but perhaps in Spin v0.7.0 we still do expect it to function, though maybe to be fully removed/replaced at a later date: https://github.com/fermyon/spin/pull/836

I suppose since it appears support is fully removed, whether intentionally or not, we use this opportunity to update docs to use the `/.well-known/spin/health` endpoint?

All looks good with that route when using Spin v0.7.0:

```
$ curl -i localhost:3000/.well-known/spin/health
HTTP/1.1 200 OK
content-length: 2
date: Wed, 21 Dec 2022 20:30:58 GMT

OK
```

**Comment by itowlson** [comment]
Yeah I think this is a docs update issue.  At the moment, I think `deploy` considers both health paths (to allow for a transitional period with Cloud), but `spin up` no longer exposes the old `healthz` path (because there are unlikely to be compatibility considerations when running entirely locally).

**Comment by itowlson** [comment]
#870 is where the old route got removed.

**Comment by vdice** [comment]
Ah, thank you @itowlson!  I'll let the linked PR close this one out when merged.
