### ISSUE TITLE
Create directory for `static-fileserver` template

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1022]
When a user runs the `static-fileserver` template, it asks for the directory from which to serve files.

If that directory doesn't exist, it would be a nice touch to create it.

**Comment by mikkelhegn** [comment]
Implication is that `spin up` fails if the directory does not exist.

```
> spin up
Error: Failed to prepare configuration

Caused by:
    0: Failed to collect file mounts for assets
    1: Cannot place /Users/mikkel/code/temp/new_fileserver/assets: source must be a directory
```

**Comment by itowlson** [comment]
We should improve that error message too!

**Comment by jasonwashburn** [comment]
I came here to add a similar issue. It seems you also get a confusing error even if you create a folder afterwords (ie: ./assets) but you don't put anything in it. Starting with a blank fileserver template, if I add the assets directory, but don't add anything into it, I get the following errors when trying to `spin up` 
```shell
Error: Failed to load manifest from "spin.toml"

Caused by:
   0: Failed to load Spin app from "spin.toml"
   1: Failed to load component `test-fileserver`
   2: Couldn't resolve `/private/var/folders/2v/tdl9yh_55ls951rm1f8mpf040000gn/T/spinup-cfMZ4R/assets/test-fileserver`
   3: No such file or directory (os error 2)
```

however, if I `touch assets/index.html` and run it again, everything is fine. If I remove the index.html file, the error returns.
