### ISSUE TITLE
Cargo audit fails because of `time`: Potential segfault

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#1024]
See https://rustsec.org/advisories/RUSTSEC-2020-0071

> Users of time 0.1 do not have a patch and must upgrade to an unaffected version: time 0.2.23 or greater or the 0.3 series.

```bash
$ cargo audit
Crate:     time
Version:   0.1.44
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.44
└── chrono 0.4.22
    ├── spin-cli 0.7.1
    ├── oauth2 4.2.3
    │   └── bindle 0.8.0
    │       ├── spin-publish 0.7.1
    │       │   └── spin-cli 0.7.1
    │       ├── spin-loader 0.7.1
    │       │   ├── spin-trigger 0.7.1
    │       │   │   ├── spin-testing 0.7.1
    │       │   │   │   ├── spin-redis-engine 0.7.1
    │       │   │   │   │   └── spin-cli 0.7.1
    │       │   │   │   └── spin-http 0.7.1
    │       │   │   │       ├── spin-testing 0.7.1
    │       │   │   │       └── spin-cli 0.7.1
    │       │   │   ├── spin-redis-engine 0.7.1
    │       │   │   ├── spin-http 0.7.1
    │       │   │   └── spin-cli 0.7.1
    │       │   ├── spin-publish 0.7.1
    │       │   ├── spin-cli 0.7.1
    │       │   └── spin-build 0.7.1
    │       │       └── spin-cli 0.7.1
    │       └── spin-cli 0.7.1
    ├── liquid-lib 0.23.1
    │   ├── spin-templates 0.7.1
    │   │   └── spin-cli 0.7.1
    │   └── liquid 0.23.1
    │       └── spin-templates 0.7.1
    └── liquid-core 0.23.2
        ├── spin-templates 0.7.1
        ├── liquid-lib 0.23.1
        └── liquid 0.23.1
```

**Comment by vdice** [comment]
Is the work item here to upgrade the `time` crate and ensure functionality is unaffected?  If so, Do we feel the test automation we have in place is sufficient to cover our needs here?

**Comment by itowlson** [comment]
@vdice it looks like we only consume `time` via `chrono`, and `chrono` has supposedly broken its dependency on `time`:

https://github.com/chronotope/chrono/commit/4c351b1e720a30a6e32068fe386293b36d0e86fd

So we might be able to just rev `chrono` and have the problem go away ~~in favour of some exciting _new_ problem~~.

**Comment by itowlson** [comment]
...well, coercing `chrono` to 0.4.23 didn't seem to remove the dependency.  Very weird, what I see in the Cargo cache and what I see in the release history don't really match up...?!
