### ISSUE TITLE
"Reserved" names for components

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1038]
If I create a Spin component using the `http-rust` template and I name it `static`, the rust component cannot be built, as the function will take on that name.

I've made similar types of "errors" with the .NET SDK 🤔 https://github.com/fermyon/spin-dotnet-sdk/issues/33 and https://github.com/fermyon/spin-dotnet-sdk/issues/36

Having a way to make sure the naming of a component, does not impact the ability to compile it through "reserved" names or appending / prepending how that name is being used in the component would be good to avoid anyone having to spent time trying to figure out while a component will fail on build right after being crated through a template.

**Comment by mikkelhegn** [comment]
And a shameless plug for a live demo gone wrong due to this :-) https://www.youtube.com/watch?v=Uaqy4MHhk14&t=317s

**Comment by itowlson** [comment]
I definitely prefer the strategy of munging the generated function a la `handle_{{ name }}` e.g. `handle_hello`, `handle_static`, etc.  Trying to build in lists of reserved words would be a significant mare.

**Comment by itowlson** [comment]
Indeed we don't actually have to incorporate the name in the function name - `rust-redis` just calls the entry point `on_message`
