### ISSUE TITLE
spin plugin -> spin plugins

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#1042]
Super minor nit. Currently the top level command is `plugin` and is aliased to `plugins`. Should the top level command be `plugins` instead to match the plurality of `spin templates`?  Still aliased to plugin for convenience. Thoughts welcome.

**Comment by kate-goldenring** [comment]
@itowlson and I were discussing this on the aliasing PR: https://github.com/fermyon/spin/pull/994#issuecomment-1358408185. +1 for changing `Plugin` to `Plugins`. I am happy to take this on
