### ISSUE TITLE
move sdk/rust and sdk/go out of spin repo

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#1046]
The rust and go sdks were some of the first SDKs written for spin and have lived in the Spin repo since they were first written. There isn't much of a reason for them to live in the spin repo while the rest of the SDKs currently available live outside of the Spin repo. Let's move these SDKs under the fermyon/ org into their respective repos with the following steps (preserving as much history as possible along the way):

- [ ] Move WIT files to a separate github repo and re-add to the Spin repo as a git subtree ([reasoning below](https://github.com/fermyon/spin/issues/1046#issuecomment-1402610719))
- [ ] Move `sdk/rust` into [spin-rust-sdk repo](https://github.com/fermyon/spin-rust-sdk). Add wit files to new repo using git subtree. 
- [ ] Update all references to the rust sdk in the Spin repo to point to the new repo
- [ ] Move `sdk/go` into [spin-go-sdk](https://github.com/fermyon/spin-go-sdk). Add wit files to new repo using git subtree.
- [ ] Update all references to the go sdk in the Spin repo to point to the new repo

**Comment by michelleN** [comment]
The rust and go sdks, several crates in Spin, some examples, and some Makefiles all rely on the wit files being available in the repository (for the wit-bindgen tool to use to generate bindings). If we move the current `wit` directory into a separate repo and add into the Spin repo as a git subtree, it would make moving the rust and go sdks to the [spin-rust-sdk](https://github.com/fermyon/spin-rust-sdk) and [spin-go-sdk](https://github.com/fermyon/spin-go-sdk) repos much easier. We wouldn't have to keep a separate copy of the wit files.

As part of this issue, I created a new repo, [spin-wit](https://github.com/fermyon/spin-wit/tree/main/ephemeral), which houses the WIT files used across the spin project. This will allow us to add the wit files in a directory in any github repo with the `git subtree add` command. See example below:
```
git remote add witfiles git@github.com:fermyon/spin-wit.git
git subtree add —-prefix=wit/ witfiles main
```

This is a good primer on git subtrees: https://medium.com/@v/git-subtrees-a-tutorial-6ff568381844

As part of this issue, we'll also need to build tooling or process around how to update WIT files. If WIT files are updated in a commit on the Spin repo, we'll want to use CI to also add those changes to the spin-wit repo or we can require that any changes to WIT files be made in the spin-wit repo and then be pulled into the Spin repo using the `git subtree pull` command. See example below:
```
git subtree pull —prefix=wit witfiles main
```

**Comment by itowlson** [comment]
Would it be worth doing a SIP first so we can get a sense for how all this is going to work?  I'd like to understand how this is going to affect versioning and developer experience and all that (if the answer is 'not at all' then great but the multipage tutorial on git subtrees was a bit alarming **grin**).  Thanks!

**Comment by michelleN** [comment]
Absolutely I can put together a SIP for this work.

**Comment by michelleN** [comment]
SIP provided here: https://github.com/fermyon/spin/pull/1067

**Comment by itowlson** [comment]
This is done :shipit:
