### ISSUE TITLE
Support Wasmtime's "trap missing imports" flag to enable using Leptos with Spin

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1051]
If you try to use Leptos with Spin, you will get a runtime error, as Leptos has imports which are not compatible with WASI. There are known workarounds for this, and a Wasmtime flag to not break at startup. For more context see here: https://discord.com/channels/926888690310053918/950022897160839248/1062807294909353985

The proposal is to support this Wasmtime flag in Spin.

**Comment by lann** [comment]
Ref https://github.com/ThePrimeagen/rust-wasm-serverless/issues/1

**Comment by lann** [comment]
I'm looking at a more targeted approach here. Wasmtime's `--trap-unknown-imports` turns many useful deploy-time linking errors into runtime errors. If we can stub out just the missing imports that match known patterns we can retain most of that deploy-time safety.

**Comment by lann** [comment]
@dicej Already prototyped a tool to stub Wasm binaries in place; he is looking at resurrecting that to fix this issue.

**Comment by lann** [comment]
I built a minimal leptos ssr example and see "bad" imports from just two modules: `__wbindgen_placeholder__` and `__wbindgen_externref_xform__`. It seems like we could get away with just stubbing out imports from those modules, at least for this restricted case.

**Comment by mikkelhegn** [comment]
There's a workaround using this tool: https://github.com/dicej/stubber

Example relevant to leptos:
`cargo run -- -m __wbindgen_placeholder__ -m __wbindgen_externref_xform__ < input.wasm > output.wasm`

**Comment by itowlson** [comment]
I dunno what changed but seems like Leptos now works?  If not, please reopen.
