### ISSUE TITLE
Spin CLI should notify the user if an update is available

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1073]
If an update to either Spin, templates or plugins is available, it would be convenient to get a notification about that update, while using the CLI.

This could either be on every command, or when using a specific template or plugin, that the update notification is provided.
It would be great if a user can opt out of the notification, and then only get one the next time a new upgrade is available.

**Comment by tpmccallum** [comment]
This is an excellent idea @mikkelhegn 

TL:DR Can we make a first tier command called `spin update` with its own `--help` option?

---

Could we:
- have a single brief message like "Updates available"? (Keeping the message super short might negate the need/want for users to opt out.)
- also include a copyable/paste-able CLI command (on that same CLI output line) which allows the user to dive into what updates are available, i.e. `spin update --help`

Perhaps using this `update` command on the first tier will align nicely with each of the existing lower tier subcommands (and their respective `update` and `upgrade` subcommands).

**Comment by itowlson** [comment]
A `spin update [--check]` is a nice idea.  Rust does this via `rustup`, which decouples _managing_ your tools from _using_ them, reducing clutter in the day-to-day tool.  I have extremely mixed feelings about tools that _pester_ me to update as part of my inner loop.

**Comment by tpmccallum** [comment]
Hi @itowlson 
So each of the `update` and `upgrade` subcommands (which are housed within their parent subcommand i.e. `plugins` will have their own `--check` option (that sits alongside the respective `--help` command)?
If I am understanding this correctly, it sounds pretty neat. Users will see the `--check` option and description which explains what `check` does (and this type of CLI output can go straight into the CLI reference docs).
Makes sense.

**Comment by itowlson** [comment]
Hmm, I was thinking about your proposed top-level `spin update` command.  But yes, we could have a `--check` option on `spin plugins update` as well, although `spin plugins update` doesn't do what you want it to do.  (Templates are problematic and we need to think about how we manage those.)

Yes, I would definitely use a 'show me available updates' flag (such as `--check`), separate from and alongside the 'show me command line help' flag (which is `--help`).  If nothing else, how would the user get help on the update command options... *grin*

**Comment by itowlson** [comment]
Is this sufficiently addressed by the `check-for-updates` plugin?

**Comment by mikkelhegn** [comment]
I think so. As the person who opened this a logno time ago :-) I'd be ok closing this issus.
