### ISSUE TITLE
Remove confusing "project" terminology from `spin new` and `spin add` components

### ISSUE THREAD

**Issue by calebschoepp** [fermyon/spin#1074]
From what I can tell the terminology we expose to our users is that a Spin "application" consists of multiple "components". However, in the `spin new` and `spin add` flows we refer to what they're making as a "project". I find this confusing because I wasn't sure if "project" was the same thing as an "application".

I haven't found anything in the documentation that indicates we want to use the "project" terminology. I propose that we modify the `spin new` and `spin add` flows as such:

## `spin new`

Old: 
```
$ spin new
Pick a template to start your project with: http-rust (HTTP request handler using Rust)
Enter a name for your new project: My project
Project description: Description of my project
HTTP base: /
HTTP path: /...
```
 
New:
```
$ spin new
Pick a template to start your application with: http-rust (HTTP request handler using Rust)
Enter a name for your new application: My application
Application description: Description of my application
HTTP base: /
HTTP path: /...
```

## `spin add`

Old:
```
$ spin add
Pick a template to start your project with: http-rust (HTTP request handler using Rust)
Enter a name for your new project: Second component
Project description: My new component
HTTP path: /...
```

The "project" terminology used in `spin add` is extra confusing because you're not even creating a new application, you're just adding to it. I thought this command was broken at first when it asked me for the project name. Ideally we use component terminology here.

New:
```
$ spin add
Pick a template to start your new component with: http-rust (HTTP request handler using Rust)
Enter a name for your new component: Second component
Component description: My new component
HTTP path: /...
```

## Potential issues

One potential issue with this change I wanted to highlight is that it appears that `project-description` is baked into our templates. If we wanted to rename that key too we might have to update all of the templates. I'm not fully up to speed on the implications of that.

**Comment by itowlson** [comment]
Agree, the "project" terminology is very much inherited from when we only had `spin new` and what you were creating was an application _with_ a component.

You are correct that if we changed a key we would need to change it in all templates.  This is not an issue for `project-description` which is defined within each template: if a template changed the parameter ID, it could also change its placeholders, and vice versa.  But is is an issue for `project-name`, which is a key defined by Spin itself.  If we changed that, users would need to update all their templates in sync.

However, we could easily change the _prompts_ without changing the parameter ID.  Template authors would still need to know about the old ID but users never see that stuff.

And if we were really bothered, we could change Spin to inject both `project-name` and `the-new-name-name` with the same value, so old templates would still work with new Spin, but template authors could use the new name instead.

One limitation is that `spin new` and `spin add` currently share prompts.  So if we changed the prompt to "Enter a description for your new application" (for `spin new`) we could not currently have `spin add` display "Enter a description for your new component."  Addressing this would be fairly simple (I think), it just won't happen automatically!

**Comment by calebschoepp** [comment]
> And if we were really bothered, we could change Spin to inject both project-name and the-new-name-name with the same value, so old templates would still work with new Spin, but template authors could use the new name instead.

This seems like a nice easy fix that avoids updating templates in sync. FWIW I think it would be ideal to move away from `project-description`/`project-name` b/c that is just going to be tech debt years down the road.

> One limitation is that spin new and spin add currently share prompts. So if we changed the prompt to "Enter a description for your new application" (for spin new) we could not currently have spin add display "Enter a description for your new component." Addressing this would be fairly simple (I think), it just won't happen automatically!

Good call.

@itowlson Is this a small enough change that I could just spend some time opening a PR and we don't need to have a big discussion about it here?

**Comment by itowlson** [comment]
@calebschoepp sounds like a great way to learn your way around the templates code - go for it!
