### ISSUE TITLE
Pre-install the default templates as part of initial setup

### ISSUE THREAD

**Issue by ingride** [fermyon/spin#1084]
To optimize the first-time user and the "batteries included" experience, it will be nice for Spin to come with a pre-installed set of templates - for example, the `default` ones, without having to explicitly run `templates install.` Since the initial install step already needs network calls, tying template download in should avoid a big performance penality.

The new workflow will then be: 

```text
1. install spin via curl, which also downloads the templates 
2. spin templates list will now show the default list of templates
3. spin new to start a new application
```

**Comment by itowlson** [comment]
Was there a consensus to do this as part of the install script?  If so, it looks like that lives in the `developer` repo now (I guess because it gets put on the Web site); would be make sense to move the issue?

**Comment by itowlson** [comment]
This is now done.
