### ISSUE TITLE
Implement `spin up` from an OCI registry

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#1086]
#1014 implements running a Spin application from an OCI registry through the `spin oci run` command while we validate the implementation.

Ideally, we want to integrate this functionality with `spin up`.
This issue tracks updating `spin up` to accept a reference from the registry and start the application.

**Comment by fibonacci1729** [comment]
closed by [#1146](https://github.com/fermyon/spin/pull/1146)
