### ISSUE TITLE
Implement `spin registry login`

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#1087]
As of #1014, the `spin registry` set of commands can interact with an OCI registry.
Currently, these commands will reuse the credentials in `~/.docker/config.json` to authenticate to registries, as most registries have instructions on how to authenticate the Docker CLI.

While Spin should continue to use the credentials in `~/.docker/config.json`, and it should continue to allow users to use registries they already authenticated for using their existing toolchains, it should not depend on the Docker CLI being installed on the target machine.

As a result, Spin should implement:

- `spin registry login --username <> --password <>`
and
- `<echo-password-or-get-it-using-cloud-specific-tool> | spin registry login --username <> --pasword-stdin`

This would mirror the default ways to authenticate to container registries today.

**Comment by lann** [comment]
Does this need a e.g. `--server` flag?

**Comment by radu-matei** [comment]
Up until this point, the intended experience for this command was `spin registry login --username <> --password/stdin <> [registry]`, so it would be passed as an argument.

**Comment by radu-matei** [comment]
Here are some more details on how I am thinking about this feature.

I believe we should continue to re-use the existing credentials for a container registry. There are a lot of tools built around the container registry authentication that work together with `docker login` and that are specific for target registries (for example, `gcloud auth configure-docker gcr.io`, or `aws ecr get-login`).
These tools work by getting the authentication for the target registry or repository, then invoking Docker's credential helpers (or alternatively, they are the credential helpers) to securely store them.

First, a look at how `spin registry push/pull` currently deals with authentication:

- the registry client will attempt to read the `~/.docker/config.json` file that has encoded credentials or references to a credential helper that securely stores the credentials (such as OSX Keychain).
- it either reads the encoded credentials from the file (if present), or uses the `docker-credential-helper-<>` tool referenced in the configuration file to ask for the credential, then returns the authentication data to the OCI client.

I would like to propose the following workflow for `spin registry login` targeting a container registry:

- it first checks if `~/.docker/config.json` exists. If it does, it will either use the configured credential helper to store the new credentials and server. Otherwise, it will encode them.
- if `~/.docker/config.json` does not exist, it encodes the credentials and stores them in a similar manner to the Cloud token (this is hand-wavey because we eventually want to improve how that is stored, so they should be addressed similarly).

This has a few advantages:

- users who already authenticate to registries as part of their workflows using existing tools (`docker login` or registry specific helpers) can continue to use them; also, in CI, the existing actions for authenticating to popular registries can be reused.
- users who have Docker configured can continue to use the same mechanism for storing credentials as for other tools targeting container registries (this is a common pattern for tools that use registries to use the existing credential helpers)
- users (or systems) that do not have Docker or associated tooling configured will be able to `spin registry login` without any other dependency.

**Comment by lann** [comment]
I would maybe tweak the workflow to only _read_ from `~/.docker/config.json`. Having `spin registry login` _write_ to docker config seems more confusing; if someone wants to update that file they can presumably `docker login` instead. Using credential helpers from docker config seems fine, or at least practically necessary.
