### ISSUE TITLE
CLI: build --up options

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#1089]
The `spin build` command offers the `-u/--up` option to run the spin app after a successful build.  When using this option, all valid up options/flags can also be used.

Currently, the cli presents the following:
![spin-build-old](https://user-images.githubusercontent.com/9322017/215820612-1f5de484-cb78-45f9-88ae-ab47743b787e.jpg)

I'd propose we improve the experience and discoverabilty of which up 'args' are available.  It might be a better experience if the cli presented all of the up opts/flags in another section below the main `OPTIONS` area, titled `UP_OPTIONS` or similar.  Note that `spin up` currently offers default options as well as dynamic trigger options based on the app being run -- I assume we'd want to present both applicable sets in this case.

We might _always_ present these up options on `spin build -h` _or_ it could be neat to only show them on `spin build -u/--up -h`.

**Comment by cardoso** [comment]
Is there any practical difference between using `spin build --up` and `spin build && spin up` ?

**Comment by itowlson** [comment]
None whatsoever.  The `--up` option literally delegates to the `up` command.

**Comment by cardoso** [comment]
If there's no difference, I find it hard to justify the effort in maintaining it. The 6 characters saved are even less compelling if you're using options. There's also completions, which is probably impossible with it. 

Could it be deprecated and removed after 1 or 2 0.x releases?

**Comment by cardoso** [comment]
What if `spin up` would build as needed like `cargo run`? The only option `spin build` has is `--file` and the same option with the same meaning is already in `spin up`. If I'm not missing something, that's all the pros without the cons.

**Comment by vdice** [comment]
Sorry, I missed the most recent comments here @cardoso.  I see the points around how `spin build --up` might not necessarily bring pros in proportions to its cons (eg non-trivial CLI maintenance/presentation overhead).  Relatedly, there is some work being explored (see [the spin watch PR](https://github.com/fermyon/spin/pull/1164)) that may render `spin build --up` moot or at least present the opportunity to revisit its usefulness.  Indeed, the upcoming 1.0 release would be a good opportunity to decide on which way to go here.

**Comment by calebschoepp** [comment]
> Sorry, I missed the most recent comments here @cardoso. I see the points around how `spin build --up` might not necessarily bring pros in proportions to its cons (eg non-trivial CLI maintenance/presentation overhead). Relatedly, there is some work being explored (see [the spin watch PR](https://github.com/fermyon/spin/pull/1164)) that may render `spin build --up` moot or at least present the opportunity to revisit its usefulness. Indeed, the upcoming 1.0 release would be a good opportunity to decide on which way to go here. Thoughts @itowlson @michelleN @calebschoepp ?

If/when we move forward with `spin watch` I would advocate to remove `spin --up`. I was going to include that in my `spin watch` PR but didn't want to make too many changes.

**Comment by michelleN** [comment]
Would it be alright to close this issue as the current plan is to remove the up flag on `spin build` in 2.0? https://github.com/fermyon/spin/issues/1783
