### ISSUE TITLE
Where should plugins store their local data

### ISSUE THREAD

**Issue by karthik2804** [fermyon/spin#1091]
Currently, there seems to be no convention on where a Spin plugin can store data like user configs. As the update mechanism for plugins is to uninstall the plugin and install a newer version, the directory where the plugin binary is stored cannot be reliably used to contain the user configs as it will be deleted during upgrades. Should there be a directory inside the plugin's directory that is persisted and is passed as an environment variable to the plugin? Or should the data reside anywhere else?

**Comment by itowlson** [comment]
I'm not sure we can offer specific guidance on this (other than, as you say, "don't use the program directory", which is always a good plan).  A plugin might want to store data alongside an application, or in a cache, or in persistent data directories, or as configuration.

We don't sandbox plugins - they are full programs with full access to the file system (until we can get Wasm plugins of course!) - do we need to do anything except let them follow OS conventions and their own design needs?

**Comment by karthik2804** [comment]
This sounds reasonable to me. I was just wondering about the case where there are multiple plugins and each writing in its own directory, it could be hard for the users to find each one. I was just thinking about if we could offer a convention to make it simpler if plugin authors do decide to adhere to it.

**Comment by karthik2804** [comment]
The question has been answered. The plugins are not sandboxed, so they should follow the OS conventions.
