### ISSUE TITLE
Change HTTP routing algorithm to "longest matching prefix wins"

### ISSUE THREAD

**Issue by lann** [fermyon/spin#1098]
Currently, the matching of routes is dependent on the ordering of component configs in `spin.toml`. I would like to remove this ordering dependency and instead use the longest matching route, with "literal" routes taking precedence over "prefix" routes.

For these routes:
```
/
/...
/blog/...
/blog/new
/static/...
```
The following routings would apply:
```
/ -> /
/fun -> /...
/blog/my-post -> /blog/...
/blog/new -> /blog/new
/static/img.png -> /static/...
```

**Comment by itowlson** [comment]
_abruptly stops work on unreachable route detection_
