### ISSUE TITLE
Move default `spin up` log dir for local apps

### ISSUE THREAD

**Issue by lann** [fermyon/spin#1111]
For "local" apps (those with a local `spin.toml`), change the default `--log-dir` to `./.spin/logs`, relative to the `spin.toml`.

**Comment by lann** [comment]
Implementation note: the path to `spin.toml` should already be available in the locked app metadata under the `origin` key as e.g. `"origin": "file:///path/to/spin.toml"`.

**Comment by itowlson** [comment]
Another implementation note: we'd want to add `.spin` (or only `.spin/logs`? need to define) to the `.gitignore` files in the templates.

**Comment by fibonacci1729** [comment]
At a glance, it looks like local app loading doesn't use the locked app. Am i missing something (w.r.t the impl note)?

**Comment by itowlson** [comment]
`spin up` builds a lockfile and hands that off to the trigger (https://github.com/fermyon/spin/blob/b1685404e933fc080825674890a42a42ee363241/src/commands/up.rs#L204).

**Comment by fibonacci1729** [comment]
Ah yes, right. ⚡

**Comment by lann** [comment]
> add .spin (or only .spin/logs? need to define) to the .gitignore

Based on https://github.com/fermyon/spin/pull/1035 I would expect to ignore `.spin`.

**Comment by michelleN** [comment]
Another solution could be to not store logs unless a user explicitly specifies a flag to do so (`spin up --logs-dir <path>`)
