### ISSUE TITLE
Consistent user directories

### ISSUE THREAD

**Issue by adamreese** [fermyon/spin#1113]
Currently Spin stores user configuration and data to XDG directories. The two outliers are Spin logs and cloud credentials to `~/.spin`.  Cloud config can move to XDG_USER_CONFIG.  For logs there's a couple options, use a local relative directory (`./logs/`) or use XDG_DATA_HOME.

**Comment by lann** [comment]
ref #1111

**Comment by lann** [comment]
Cloud credentials are currently in `~/.config/fermyon`

**Comment by adamreese** [comment]
Closing in favor of #1111
