### ISSUE TITLE
move cloud commands under spin cloud

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#1117]
Going forward, it would be nice to move cloud related commands under the spin cloud command.

$ spin login -> spin cloud login
$ spin deploy -> spin cloud deploy

For convenience, we should leave aliases for `spin login` and `spin deploy` but all other cloud related commands should be added under `spin cloud`.

**Comment by bacongobbler** [comment]
> we should leave aliases for `spin login` and `spin deploy`

Slight technical blocker... I cannot create an alias from `spin deploy` to `spin cloud deploy`.

Clap has a feature called `replace`, but it is marked unstable behind the `unstable-replace` flag. There is [no support for this flag in `clap-derive`](https://docs.rs/clap/latest/clap/_derive/index.html#documentation-derive-reference), which we use for aliasing commands in the Spin CLI. It sounds like the `replace` feature [is expected to be removed in the future](https://github.com/clap-rs/clap/issues/2011#issuecomment-678751211), but the last time it saw any activity [was in 2021](https://github.com/clap-rs/clap/issues/2836).

How should we proceed?

**Comment by itowlson** [comment]
We could leave the Deploy and Login subcommand enum variants (hidden if desired), with the variants having the same payloads as the matching Cloud commands?  It will be duplication rather than true aliasing, but nobody would know... (I hope)

(We will need to be sneakier than this when `cloud` becomes a plugin, but we'll likely be figuring out clap sorcery at that point anyway, e.g. to make `cloud` appear in help text.)

**Comment by bacongobbler** [comment]
That seems like a possible solution. Calling `spin deploy` won't actually point you to `spin cloud deploy`, but close enough. 🤷🏼 

Okay, I've marked those commands as hidden, so now you see this with `spin help`:

```
><> ./target/release/spin help
spin 0.8.0 (fd67c3d 2023-02-14)
The Spin CLI

USAGE:
    spin <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    add          Scaffold a new component into an existing application
    bindle       Commands for publishing applications as bindles
    build        Build the Spin application
    cloud        Commands for publishing applications to Fermyon Cloud
    help         Print this message or the help of the given subcommand(s)
    new          Scaffold a new application based on a template
    plugins      Install/uninstall Spin plugins
    registry     Commands for working with OCI registries to distribute applications. The set of
                     commands for OCI is EXPERIMENTAL, and may change in future versions of Spin.
                     Currently, the OCI commands are reusing the credentials from
                     ~/.docker/config.json to authenticate to registries
    templates    Commands for working with WebAssembly component templates
    up           Start the Spin application
```
