### ISSUE TITLE
spin cloud plugin

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#1118]
Building on #1117, it would be nice if `spin cloud` was a plugin under the hood that called out to separate binary.

1. It would allow the current cloud functionality to be updated independently of the spin CLI.
2. It would open the door to deploying spin apps to multiple clouds without having to touch the core spin codebase

**Comment by itowlson** [comment]
Long since done _grin_ https://github.com/fermyon/cloud-plugin
