### ISSUE TITLE
consider a modsurfer checkfile in spin repo

### ISSUE THREAD

**Issue by nilslice** [fermyon/spin#1120]
Hello Fermyon friends!

We're starting to roll out checkfiles for WebAssembly ecosystem projects and organizations, so that before deployment, users can run validation checks on .wasm code to better ensure:
- ABI compatibility with destination host environments
- host/platform security / policy compliance 
- resource management (binary size limits, code complexity / CPU exhaustion risk etc)
- & more...

Here's some GitHub Actions running the [`modsurfer validate`](https://github.com/dylibso/modsurfer-validate-action) command along with example checkfiles (a `mod.yaml`) for each variant of Spin ABI (trigger types): https://github.com/dylibso/modsurfer/pull/16

Take a note of the comment I've left in the PR about why it would be helpful for the checkfile to instead be hosted in the `fermyon/spin` repo. 

If you're open to it, I'd be happy to make a PR to contribute these files, and equally happy to discuss / review their accuracy and make any improvements to them.

Thanks!

**Comment by itowlson** [comment]
Thanks for the offer - this is super interesting.  I am honestly not quite sure where something like this would best live - in a way, it's more aligned with the SDKs than with Spin itself.  (Some SDKs currently live in the Spin repo, but longer term they're likely to be in separate repos, so there'll be no common home for them.)  And specifics like size limits would relate more to the Cloud than to Spin.

@mikkelhegn What do you reckon?  I can see this being a question for other third-party tools integrating with the Spin developer ecosystem.  Do you have a sense for something that connects Spin applications up with a third-party dev tool would go?  Or do you think manifests like this are better placed with the tools they integrate?

**Comment by nilslice** [comment]
I see there is also a https://github.com/fermyon/actions repository, maybe that makes sense? Though the action would still best be hosted by us (unless there is some reason to make a custom Ferymon one..), maybe some related CI files could go in `actions`?

**Comment by itowlson** [comment]
Yes, I'd expect the action still to be the dylibso one, just with the Spin/Fermyon checkfile.

Maybe we should be pragmatic and put it in the Spin repo for now, and reorganise if we ever have the "dozens of third party tools' files" problem (I would _love_ to have that problem, but right now, uh, no).  But I don't want to rush a decision while the discussion is percolating across time zones!

**Comment by mikkelhegn** [comment]
I think this is great. I'd suggest we just go the pragmatic route and put them in the Spin repo for now.

**Comment by nilslice** [comment]
Ok, thanks! I'll get a PR ready - we actually have a few improvements to the checkfile format, so I will wait until we integrate those first.
