### ISSUE TITLE
Flagless `spin up` application source

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1155]
Instead of having to write `spin up -f ~/myapp/spin.toml` or `spin up --from-registry ghcr/me/myapp:v1`, the user should be allowed to write:

* `spin up ~/myapp/spin.toml` - Spin detects it's a file and runs it
* `spin up ~/myapp` - Spin detects that it's a directory and, if it contains a file named `spin.toml`, runs it
* `spin up ghcr.io/me/myapp:v1` - Spin detects that it's not a file and "looks like" a registry URI, tries to pull the artifact using the OCI protocol, and runs it if successful

The strategy will work like this:

* If no application source if specified:
  * If the current directory contains a file with the default manifest name, use it
  * Otherwise, display help
* If an application source string is specified, try to access the string as a file system reference.
  * If it exists and is a file, use it
  * If it exists and is a directory:
    * If it contains a file with the default manifest name, use that
    * Otherwise, fail with a "directory doesn't contain a manifest" error
  * If it doesn't exist, or isn't a legal filename, try to parse it as a registry reference _[to do: consider heuristic checks first, TBD]_
    * If the parse succeeds, try to pull from the reference (respecting cache etc.)
      * If the pull succeeds, run the artifact.  _(In future, if there are multiple registry protocols with "similar looking" references, this could be elaborated with e.g. check for well-known servers of different types, fail over to the other type, etc.)_
      * If pull fails, fail with a registry error
    * If the parse fails, fail with a "don't understand this source" error

The error messages alone will be glorious.

There should also be a flag that the user can set to force a specific interpretation of the source string e.g. `--source-type file`, `source-type oci`.  The default will be `--source-type auto` which tells Spin to use the strategy given above.

As we are aiming to move from Bindle to OCI, this will not support bindle IDs.  For the time being, the existing bindle-related flags will remain available to support this scenario.

**Comment by itowlson** [comment]
I was using `oci_distribution::Reference::try_from` to parse registry references, but that appears to choke on `https://` prefixes.  Is that expected, or should they be allowed?  (Asking because when @fibonacci1729 pointed me at a sample he included the `https://` prefix and `try_from` didn't like it.)

**Comment by itowlson** [comment]
But `oci_distrbution::Reference::try_from` _does_ accept `spin.toml` as a valid reference, so we need to augment its heuristics anyway.

@radu-matei What do we reckon an OCI reference "looks like"?  Ideally I would like to understand this entirely statically, without attempting to contact an OCI server.  The `:version` suffix is indicative but that's not required is it?  And if the bit before the first slash looks like a domain name then that's indicative too, but Docker Hub references can omit that right?

**Comment by calebschoepp** [comment]
Would we continue to support the `-f` flag? Or would we immediately deprecate it? If we do continue to support it for a period of backwards compatibility will `-f` or the positional argument take precedence?

**Comment by itowlson** [comment]
@radu-matei Oh, the exists case all works.  The trouble is the error case, where I go `spin up spin.toml` and `spin.toml` _doesn't_ exist.  In the current draft that tries to pull an artifact named `spin.toml` from Docker Hub and gives a surprising error about the pull failing (rather than the file not existing).

@calebschoepp My current thought is to retain `-f` (and probably `--from-registry` because I don't think this will make the 0.9 cutoff) but hide it.  I'm totally open to keeping it visible for the transitional period and would appreciate feedback on this.  If you specify the positional argument _and_ `-f` you will get the usual "you can't specify two sources" error, just like if you specify both `-f` and `--bindle`.

**Comment by calebschoepp** [comment]
@itowlson sounds like you've thought about it. Sounds good to me.

One further question. Will we be changing this for `spin build` too because that is using the `-f` pattern as well.

**Comment by itowlson** [comment]
Making `spin build` would be consistent and I don't immediately foresee any issues with it, but these feel like words that could easily go on my tombstone.

**Comment by itowlson** [comment]
This has foundered on a technical issue to do with how we capture the arguments to be passed on to the trigger.

As a 'next best' proposal, we could rechristen `-f` as `--from`, and do the 'file/dir/OCI' inference under that.  This could also lead to the nice readable disambiguator of `--from-file` and `--from-registry` (or `--from-oci` to allow for other registries, since it would be used only when disambiguation was needed).  I  like these more than `--app-source-type` though they do clutter up flag space rather more.

Thoughts?

**Comment by itowlson** [comment]
I should have noted, I am greatly indebted to @lann and @fibonacci1729 for discussion of the issue and solutions, and for the proposal above.
