### ISSUE TITLE
Offer a multiselect plugin upgrade experience

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1173]
You can currently upgrade plugins via `spin plugins upgrade foo` or `spin plugins upgrade --all`.

We could also allow `spin plugins upgrade` without the name or flag to launch an interactive experience similar to the templates one, in which it displays a list of plugins and the user ticks which one to upgrade.

**Comment by lann** [comment]
I would vote for plain `spin plugins upgrade` to be equivalent to `--all`.

**Comment by itowlson** [comment]
Heh... that was what I originally did with templates (so to get the multiselect UI you had to do `spin templates upgrade --ask`).  But other people preferred "ask by default and have a flag for `--all`".  I'd be happy to go back if a wider sample of opinion says otherwise.  But regardless, I think we should use the same default in both places.
