### ISSUE TITLE
Add `spin up --app-state-dir`

### ISSUE THREAD

**Issue by lann** [fermyon/spin#1175]
We're starting to move some per-app local state (logs, default KV store) into a `.spin` dir adjacent to the `spin.toml` file, which we'll start calling the "app state" directory. This should be configurable, with different defaults between "local" (`spin.toml`) and "remote" (Bindle, OCI) apps:

- Add a `--app-state-dir` flag to `spin up`
  - Local apps: defaults to `.spin/` relative to the local `spin.toml`
  - Remote apps: defaults to being unset

The value of the app state dir will impact a couple of existing features:
- If `--app-state-dir` is set (local default):
  - App logs (stdout/err) will be written to `<app-state-dir>/logs/...` (when #1111 is done)
  - Default KV store will be `<app-state-dir>/sqlite_key_value.db`
- If `--app-state-dir` is unset (remote default):
  - App logs will not be written to disk (still written to stdio by default)
  - Default KV store will be in-memory (not persisted)

**Comment by itowlson** [comment]
For the local case, it seems like there would be no way to unset `--app-state-dir` - is that correct?  (I don't see a lot of value to doing so, but just want to be sure that we're making that decision intentionally.)

**Comment by lann** [comment]
> way to unset `--app-state-dir`

We can probably safely interpret `--app-state-dir ''` as "unset" which would at least be useful for testing this code.

**Comment by lann** [comment]
Rethinking my own name suggestion, I'm not sure "state" really captures what we want to use this for (logs aren't really "state"). Maybe `--app-data-dir`? Just `--data-dir`?
