### ISSUE TITLE
Response.WriteHeader actually sets status code only

### ISSUE THREAD

**Issue by smsohan** [fermyon/spin#1178]
The code here https://github.com/fermyon/spin/blob/a4079e321f69227632b82963cc2a5279a1cfa3ad/sdk/go/http/response.go#L33-L35 looks as follows:

```go
func (r *response) WriteHeader(statusCode int) {
	r.status = statusCode
}
```

It looks confusing.

**Comment by rajatjindal** [comment]
Hi @smsohan, this is a standard function that `golang` expects in a `ResponseWriter` [interface] (https://cs.opensource.google/go/go/+/refs/tags/go1.20.1:src/net/http/server.go;l=95) implementation.

**Comment by itowlson** [comment]
Closing as answered - please reopen if more info or action is needed!

**Comment by smsohan** [comment]
I was expecting WriteHeader(statusCode int) to write any header, not just the statusCode. A better name for this could be "WriteStatusCode"

**Comment by rajatjindal** [comment]
Hi @smsohan , I understand but unfortunately golang enforces us to use that name for this interface, and therefore we cannot use a different name for this function. Happy to chat more about it, if that helps

**Comment by itowlson** [comment]
@smsohan For what it's worth, I agree with you that the method is confusingly named.  But as Rajat notes, the `ResponseWriter` type is defined by the Go standard library, and the confusingly named method is defined there (https://pkg.go.dev/net/http#ResponseWriter).  It's not in our power to use the better name you suggest - at least not without building an entirely custom response type that would run against the stdlib types that Go devs expect.

As this is a Go stdlib issue, you'd need to raise this to the dev team and community for Go itself.  Sorry we can't be more helpful.
