### ISSUE TITLE
Implement pulling/running a Spin application by digest

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#1181]
Currently, you are not able to pull or run a Spin application by digest.

It should be possible to run:

```bash
$ spin registry pull ghcr.io/<username>/<app>@sha256:aaaa
# and
$ spin up --from-registry ghcr.io/<username>/<app>@sha256:aaaa
```

**Comment by itowlson** [comment]
When this is done, update documentation per https://github.com/fermyon/developer/pull/455/files#r1134899435

**Comment by itowlson** [comment]
@radu-matei This appears to work already; am I misunderstanding what is being asked for?  (Or does it only work in specific cases?)

```
ivan@hecate:~$ rm -rf ~/.cache/spin/registry/
ivan@hecate:~$ spin up -f ghcr.io/itowlson/osf@sha256:0a867093096e0ef01ef749b12b6e7a90e4952eda107f89a676eeedce63a8361f
Serving http://127.0.0.1:3000
Available Routes:
  WILDone-sixty-four: http://127.0.0.1:3000 (wildcard)
```

**Comment by radu-matei** [comment]
This works indeed!
