### ISSUE TITLE
Convention (or config) for routes that are available during development but not at runtime

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#1183]
ref https://github.com/radu-matei/spin-kv-explorer

I would like to have the option to access certain components during development, but not to deploy them at runtime.

Two ways this could be achieved:

- convention for known routes that are not exposed (i.e. `/_internal`?)
- "dev components" that don't even make it to the registry.

I think I have a preference for the second option, as it doesn't clutter application packages with development time artifacts.

**Comment by itowlson** [comment]
+1 for the second option.  This would extend to other triggers in a way that a route convention would not (I dunno if it would necessarily be as useful in other triggers but there's no reason to rule it out).

**Comment by radu-matei** [comment]
Closing in favor of #1229
