### ISSUE TITLE
Warnings on clean build of new Rust app

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1186]
We had this before, I think, and got rid of it, but I can't remember how, sorry.

![image](https://user-images.githubusercontent.com/865538/220213237-6391c96e-9892-4735-b6c8-949a05f9948c.png)

**Comment by itowlson** [comment]
Previous occurrence was #793 which was fixed in #862.  Looks like the fix is to rename the example and test crates?

Is this worth having an integration/SDK test to detect?

**Comment by ThorstenHans** [comment]
@itowlson this happens for me with spin `spin 0.9.0 (a99ed51 2023-02-16)` any way to get rid of those warnings locally?

**Comment by itowlson** [comment]
Not that I know of, I'm afraid; they seem to require changes in the repo.  The Cargo issue linked from #793 doesn't mention any workarounds / suppressions, but I admit that's as far as I looked.
