### ISSUE TITLE
UX around unknown commands seems confusing

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/spin#1187]
I'm writing this as a "newcomer" to the project after the Spin 0.9 release.

The "unknown command" UX seems confusing as a new user of the Spin CLI. I'll demonstrate a typical scenario, like fat-fingering the `version` command. I'll present what `spin versio` shows, and contrast that against other CLIs.

Output of `spin versio`:

```
><> spin versio
Unknown command: plugin 'versio' not found at expected location /home/bacongobbler/.local/share/spin/plugins/manifests/versio.json: No such file or directory (os error 2)

spin 0.9.0 (a99ed51 2023-02-16)
The Spin CLI

USAGE:
    spin <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    add          Scaffold a new component into an existing application
    bindle       Commands for publishing applications as bindles
    build        Build the Spin application
    cloud        Commands for publishing applications to the Fermyon Platform
    help         Print this message or the help of the given subcommand(s)
    new          Scaffold a new application based on a template
    plugins      Install/uninstall Spin plugins
    registry     Commands for working with OCI registries to distribute applications. The set of
                     commands for OCI is EXPERIMENTAL, and may change in future versions of Spin.
                     Currently, the OCI commands are reusing the credentials from
                     ~/.docker/config.json to authenticate to registries
    templates    Commands for working with WebAssembly component templates
    up           Start the Spin application
```

It shows the version number in the text output, which in the case of `spin versio` seems to answer my original question (what version of Spin am I running?), though a large amount of help text is thrown in my face, as well as the concept of a plugin. What's a plugin?

(again, coming from the perspective of someone who just downloaded Spin and has no idea Spin has a plugin system)

Contrast this to `git`'s output:

```
><> git versio
git: 'versio' is not a git command. See 'git --help'.

The most similar command is
        version
```

Or NPM's "typo-checking" CLI:

```
><> npm versio
{
  npm: '8.19.3',
  node: '18.13.0',
  v8: '10.2.154.23-node.21',
  uv: '1.44.2',
  zlib: '1.2.13',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.51.0',
  napi: '8',
  llhttp: '6.0.10',
  uvwasi: '0.0.13',
  openssl: '3.0.7+quic',
  cldr: '42.0',
  icu: '72.1',
  tz: '2022f',
  unicode: '15.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}
```

IMO, the output from `git` seems the most optimal: it points out the issue ("versio is not a valid git command"), presents the user with a helpful suggestion ("see 'git --help' for a list of available commands"), and a possible solution ("was this what you were looking for?"). NPM can be quite helpful too, but I prefer the helpful output from git ("git gud, n00b").

I want to pose the question to the maintainers: is the current output the intended UX? Thoughts/opinions?

**Comment by itowlson** [comment]
+1.  The 'guess plugin by default' happens because we have to treat all unknown commands as potential plugins, and the plugin engine reasons 'I LIVE to run plugins and I was TOLD to run this plugin'.  But if the command _doesn't_ resolve to a plugin, then the plugin engine should recognise the likelihood that it wasn't meant to get involved at all!  Then it or top-level Spin could give the 'unknown command, see the help' response.

The 'most similar' suggestion would be extremely nice; I'm not sure how easy that would be to implement but we can always come back to it after doing the easy bit!
