### ISSUE TITLE
We print the local key-value store quite a lot

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1193]
```
~/github/spin/examples/rust-key-value $ spin up
Serving http://127.0.0.1:3000
Available Routes:
  hello: http://127.0.0.1:3000/test (wildcard)
Using /home/ivan/github/spin/examples/rust-key-value/.spin/sqlite_key_value.db for key-value store
Using /home/ivan/github/spin/examples/rust-key-value/.spin/sqlite_key_value.db for key-value store
Using /home/ivan/github/spin/examples/rust-key-value/.spin/sqlite_key_value.db for key-value store
```

As far as I can tell this will never change over the lifetime of a Spin session; is it necessary to print it on every request?

(Apologies if this belongs in another issue, I recall Radu talking about the message but can't find an issue for it.)

**Comment by radu-matei** [comment]
Would you mind trying again on `main`, please?
I think this was addressed by #1160.

**Comment by fibonacci1729** [comment]
Can't repro; appears to be fixed on `main`.

**Comment by itowlson** [comment]
Confirmed no longer happening.  Thought I was up to date; sorry for the noise.
