### ISSUE TITLE
flag provided but not defined: -wasm-abi when building a clean Go template

### ISSUE THREAD

**Issue by rhjensen79** [fermyon/spin#1221]
I'm trying Spin, and using the redis-go template.

Running "spin build" without any modification, causes the following error 
```
Executing the build command for component spin-go: tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go
flag provided but not defined: -wasm-abi
```

Any help would be appreciated.
Thanks

Go version : `go version go1.20 darwin/arm64`
Tinygo version : `tinygo version 0.27.0 darwin/amd64 (using go version go1.20 and LLVM version 15.0.0)`
Spin Version : `spin 0.8.0 (7086236 2023-01-31)`
OSX : 13.1

**Comment by vdice** [comment]
Thanks for the issue @rhjensen79.

Can you try with the [Spin v0.9.0](https://github.com/fermyon/spin/releases/tag/v0.9.0) (or later) when convenient?  In that release, tinygo usage was updated to avoid the error you've encountered (see https://github.com/fermyon/spin/pull/1165).

Note that you will need to update your local/cached templates via `spin templates upgrade` to fetch the latest/v0.9.0 versions, including redis-go and its updated tinygo usage.

**Comment by rhjensen79** [comment]
Thanks @vdice 
That worked perfect :-) 
I will close the issue here.
