### ISSUE TITLE
Create release branches in release workflow

### ISSUE THREAD

**Issue by lann** [fermyon/spin#1226]
We ran into a permissions issue with the 0.10.0 release when trying to push the Go tag:

```
! [remote rejected] sdk/go/v0.10.0 -> sdk/go/v0.10.0 (refusing to allow a GitHub App to create or update workflow `.github/workflows/code-coverage.yml` without `workflows` permission)
```

Investigating, we found the root issue is related to the `workflow` scope:

https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps

> Workflow files can be committed without this scope if the same file (with both the same path and contents) exists on another branch in the same repository.

In this case it appears that the workflow was updated during the release process, leading to the push rejection. This issue can be avoided by having a branch at the release commit during the release process. I manually created `v0.10` to unblock this release, but we should automate this process and probably protect branches e.g. `v[0-9].*`

**Comment by vdice** [comment]
We now [create a release branch](https://github.com/fermyon/spin/blob/main/docs/content/release-process.md) for all major/minor releases; closing.
