### ISSUE TITLE
Key/Value implementation for Redis

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#1242]
The "Future work" section of the SIP that adds key/value support for Spin (#1045) describes alternative implementations and being able to use multiple stores, defined in Spin's runtime configuration file.

This issue tracks adding a new implementation for a store based on Redis, and the configuration required to make that possible.

User story:

_As a user of Spin, I can get started and build my application using the default implementation of the key/value store, and when I need to (either because I have outgrown the performance of the built-in store, or because I want to better control the data), I can point to a different backing store without having to change my application or even recompile it._

Note that we already have the functionality to talk to a Redis instance in the `outbound-redis` crates, so for this work item, we need to adapt that to the shape of the key/value API, and to tie in the runtime configuration to be able to define additional stores and their connection.

cc @kate-goldenring @lann @dicej

**Comment by vdice** [comment]
@fibonacci1729 @michelleN this can now be closed per https://github.com/fermyon/spin/pull/1365 and related work, right?
