### ISSUE TITLE
FreeBSD build from source does not complete spin-cli

### ISSUE THREAD

**Issue by patterns** [fermyon/spin#1260]
I must be missing some dependencies. The steps I used:
- sudo zfs clone zroot/jails/basejail@13.1-p7 zroot/jails/nodejs
- sudo service jail onestart nodejs
- sudo pkg -j nodejs install rust
- sudo pkg -j nodejs delete rust
- sudo pkg -j nodejs install git
- sudo jexec nodejs login -f drowned

next inside the jail environment:
```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup target add wasm32-wasi
git clone --depth=1 https://github.com/deislabs/bindle
cd bindle && make build
mv target/debug/bindle-server ~/bin/
mv target/debug/bindle ~/bin/
cd ~/devel && git clone --depth=1 https://github.com/fermyon/spin
cd spin && cargo build --release
```

The build seems to work up until spin-cli, with this tail end output:

> 
>    Compiling spin-plugins v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/plugins)
>    Compiling rusqlite v0.27.0
>    Compiling zstd v0.11.2+zstd.1.5.2
>    Compiling wiggle v5.0.1
>    Compiling wasi-cap-std-sync v5.0.1
>    Compiling wasi-tokio v5.0.1
>    Compiling spin-core v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/core)
>    Compiling wit-bindgen-wasmtime v0.2.0 (https://github.com/fermyon/wit-bindgen-backport?rev=a39003fadce6c7a8654e3e044fc39fc80d81ec7b#a39003fa)
>    Compiling spin-app v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/app)
>    Compiling outbound-http v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/outbound-http)
>    Compiling spin-loader v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/loader)
>    Compiling spin-key-value v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/key-value)
>    Compiling spin-key-value-sqlite v0.1.0 (/usr/home/drowned/devel/spin/crates/key-value-sqlite)
>    Compiling spin-config v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/config)
>    Compiling outbound-mysql v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/outbound-mysql)
>    Compiling outbound-redis v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/outbound-redis)
>    Compiling outbound-pg v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/outbound-pg)
>    Compiling spin-trigger v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/trigger)
>    Compiling spin-oci v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/oci)
>    Compiling spin-redis-engine v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/redis)
>    Compiling spin-http v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/http)
>    Compiling spin-bindle v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/bindle)
>    Compiling spin-templates v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/templates)
>    Compiling spin-build v1.0.0-pre0 (/usr/home/drowned/devel/spin/crates/build)
>    Compiling git2 v0.15.0
>    Compiling spin-cli v1.0.0-pre0 (/usr/home/drowned/devel/spin)
> error: failed to run custom build command for `spin-cli v1.0.0-pre0 (/usr/home/drowned/devel/spin)`
> 
> Caused by:
>   process didn't exit successfully: `/usr/home/drowned/devel/spin/target/release/build/spin-cli-e8a3e12fa041bf91/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rustc-env=VERGEN_BUILD_TIMESTAMP=2023-03-11T23:49:52.561737649Z
>   cargo:rustc-env=VERGEN_BUILD_SEMVER=1.0.0-pre0
>   cargo:rustc-env=VERGEN_GIT_BRANCH=main
>   cargo:rustc-env=VERGEN_GIT_COMMIT_AUTHOR_EMAIL=lann.martin@fermyon.com
>   cargo:rustc-env=VERGEN_GIT_COMMIT_AUTHOR_NAME=Lann
>   cargo:rustc-env=VERGEN_GIT_COMMIT_COUNT=1
>   cargo:rustc-env=VERGEN_GIT_COMMIT_DATE=2023-03-10
>   cargo:rustc-env=VERGEN_GIT_COMMIT_MESSAGE=Merge pull request #1252 from lann/build-v-branches
> 
>   ci: Run build workflow on v* branches
>   cargo:rustc-env=VERGEN_GIT_SEMVER=1.0.0-pre0
>   cargo:rustc-env=VERGEN_GIT_SHA_SHORT=60976e4
>   cargo:rerun-if-changed=/usr/home/drowned/devel/spin/.git/HEAD
>   cargo:rerun-if-changed=/usr/home/drowned/devel/spin/.git/refs/heads/main
>   cargo:rerun-if-changed=build.rs
> 
>   --- stderr
>   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:131:31
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 

Do I need a dependency for the spin-cli step?

**Comment by itowlson** [comment]
Some Linux distros need build-essentials, pkg-config and SSL.  I'm not sure any of those (or their BSD equivalents) would cause the error you describe though...

**Comment by itowlson** [comment]
I'm a bit stumped on reproducing this (I tried to create a FreeBSD VM but couldn't get it working, sorry).  I am wondering if you would get a clearer error if you tried it without the custom build script.  This requires setting some version-related environment variables but you can use dummy values:

```
mv build.rs __dont_build

export VERGEN_BUILD_SEMVER=2.3.4
export VERGEN_GIT_SHA_SHORT=123
export VERGEN_GIT_COMMIT_DATE=1231123

cargo build --bin spin --release
```

Sorry not to have a better answer for you (and I admit I have tested the above only on Linux, sorry).

**Comment by patterns** [comment]
Thanks for your help! To eliminate my local environment, I tried to trigger the CI pipelines at TravisCI and CirrusCI in the hopes that their FreeBSD environments are tested. I'm copying the [YML from a project](https://git.tu-berlin.de/felixmoebius/tokio/-/blob/tokio-0.2.13/.cirrus.yml) that specifies FreeBSD 12. However, none of the GH app integration is triggering, and Cirrus has a red cloud representing issues from GCP. So I will try tomorrow and see then.

**Comment by patterns** [comment]
This is the [task output from the Cirrus build log](https://cirrus-ci.com/task/5835672007737344) (https://cirrus-ci.com/task/5835672007737344). I used the `RUST_BACKTRACE=1` env setting which revealed some more information, and it mentions a `full` value is possible which I haven't tried yet. Is it not happy from the `has_wasm32_wasi_target` check? (also attached the .cirrus.yml that I used.
[dot-cirrus-yml.TXT](https://github.com/fermyon/spin/files/10973912/dot-cirrus-yml.TXT)
)

>  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:131:31
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
     2: core::result::unwrap_failed
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::run
     5: build_script_build::has_wasm32_wasi_target
     6: build_script_build::main
     7: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...

**Comment by itowlson** [comment]
When `has_wasm32_wasi_target` calls into `run`, the command it runs is `rustup target list`.  The error suggests it's not finding the `rustup` command, which is very weird given you used it to execute `rustup target add` so it should be on the PATH...

**Comment by patterns** [comment]
Thanks so much! that was the piece I was missing. I needed a symlink for `bash`. Doh! Inside the `run` process function it expects the shell. Now the spin cli completes build 🎉 Sorry to go through this whole ordeal!

**Comment by itowlson** [comment]
This is great info!  Thanks for closing the loop, and for your patience in seeing it through!

**Comment by radu-matei** [comment]
Really glad you were successful, @patterns!
Closing the issue, feel free to reopen if you have questions.


Thanks!
