### ISSUE TITLE
Error message when `spin.toml` doesn't match schema is not helpful

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1322]
I had an issue an `s` in `key_value_stores` in `spin.toml`.

The error I received when running `spin up`, was

```
Error: Cannot read manifest file from "/Users/mikkel/code/devrel/redirect/spin.toml"

Caused by:
    data did not match any variant of untagged enum RawAppManifestAnyVersionImpl
``` 

It would be great to know that it's a schema validation error, and what key or value has this error.

**Comment by itowlson** [comment]
I had a look at this but it got a bit hairy - our loader already has a bunch of patches on top of patches, and we also have subsystems that are interested in extremely specific bits of the manifest which are also carrying that complexity burden.  I can for sure hack something in, but what I'd really like to do is rework the loader to bring out its pipeline nature, and fit this fix into that.  But that will take a bit longer I think!

**Comment by itowlson** [comment]
Or we could just string replace `spin_version` to `spin_manifest_version` before we deserialise the bloody thing and Never Speak Of It Again

**Comment by vdice** [comment]
I'm seeing a few related PRs on this topic: https://github.com/fermyon/spin/pull/1378 and https://github.com/fermyon/spin/pull/1396.  Not sure if either or both directly fix this issue or not - but would be good to link if appropriate.
