### ISSUE TITLE
`spin watch` watching direct mounts, gives no indication that a reload happens

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1335]
I'm serving an `html` page using the static fileserver. Hot-reload of the edits to the `html` file works great, when using `spin watch --direct-mounts`. However, I don't see any indications from Spin that the content was reloaded. It would be great to get a small line in the console that a new version of a file has been loaded.

**Comment by calebschoepp** [comment]
Not sure I understand the use case here. Are you saying that you want `spin watch` to print out that it has restarted and additionally print out which files caused it to restart?

FWIW whether you're running `spin up` or `spin watch` in this scenario makes no difference if you are passing the `--direct-mounts` flag.

**Comment by mikkelhegn** [comment]
Thx Caleb. I think I need to read up on what the `watch` command does in those scenarios. Closing for now.
