### ISSUE TITLE
[question] how to compile wasi from GO's spin-http & wasi-outbound-http ?

### ISSUE THREAD

**Issue by iapicca** [fermyon/spin#1336]
### Description

I'm attempting to create a package to use [Dart](https://dart.dev/) with `spin`,
starting with the http package I'm trying to create a binding from `wasi` compiled from `go/http` C files
using dart's experimental [wasm][dart-wasm] package (yes, it does [support wasi][wasi-support])

Unfortunately my perfect plan derailed.

Below you may find the issue I'm having compiling `wasi`, 
but maybe I'm off-track, if you have a better idea on how I should proceed
I'm all ears

### Step to reproduce

1.  Install [wasienv][wasienv]

```console
curl https://raw.githubusercontent.com/wasienv/wasienv/master/install.sh | sh \
&& source ~/.wasienv/wasienv.sh
```

2. Download [go-http][go-http] files

```console
curl -O https://raw.githubusercontent.com/fermyon/spin/main/sdk/go/http/spin-http.c \
&& curl -O https://raw.githubusercontent.com/fermyon/spin/main/sdk/go/http/spin-http.h \
&& curl -O https://raw.githubusercontent.com/fermyon/spin/main/sdk/go/http/wasi-outbound-http.c \
&& curl -O https://raw.githubusercontent.com/fermyon/spin/main/sdk/go/http/wasi-outbound-http.h
```

3. Compile to WASI following wasienv [docs][docs]

```console
wasicc spin-http.c -o spin-http
```

### Expected behavior

output a `.wasm` file that I can use to generate bindings for the package

### Actual behavior

throws
```console
In file included from <built-in>:1:
/Users/yakforward/Library/Python/3.11/lib/python/site-packages/wasienv/stubs/preamble.h:30:9: warning: 'ESHUTDOWN' macro redefined [-Wmacro-redefined]
#define ESHUTDOWN 0
        ^
/Users/yakforward/Library/Python/3.11/lib/python/site-packages/wasienv/stubs/preamble.h:28:9: note: previous definition is here
#define ESHUTDOWN 1
        ^
/Users/yakforward/Library/Python/3.11/lib/python/site-packages/wasienv/stubs/preamble.h:116:62: warning: declaration of 'struct sigaction' will not be visible outside of this function [-Wvisibility]
__attribute__((weak)) int sigaction(int signum, const struct sigaction *act,
                                                             ^
/Users/yakforward/Library/Python/3.11/lib/python/site-packages/wasienv/stubs/preamble.h:125:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
/Users/yakforward/Library/Python/3.11/lib/python/site-packages/wasienv/stubs/preamble.h:134:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
spin-http.c:2:10: error: 'spin-http.h' file not found with <angled> include; use "quotes" instead
#include <spin-http.h>
         ^~~~~~~~~~~~~
         "spin-http.h"
spin-http.c:4:22: warning: unknown attribute 'export_name' ignored [-Wunknown-attributes]
__attribute__((weak, export_name("canonical_abi_realloc")))
                     ^
spin-http.c:19:22: warning: unknown attribute 'export_name' ignored [-Wunknown-attributes]
__attribute__((weak, export_name("canonical_abi_free")))
                     ^
spin-http.c:92:16: warning: unknown attribute 'export_name' ignored [-Wunknown-attributes]
__attribute__((export_name("handle-http-request")))
               ^
7 warnings and 1 error generated.
```

[wasienv]: https://github.com/wasienv/wasienv
[go-http]: https://github.com/fermyon/spin/tree/main/sdk/go/http
[docs]: https://github.com/wasienv/wasienv#using-wasienv-for-c-projects
[dart-wasm]: https://pub.dev/packages/wasm
[wasi-support]: https://medium.com/dartlang/experimenting-with-dart-and-wasm-ef7f1c065577

**Comment by itowlson** [comment]
Thank you for this detailed report with all the useful links!

Some of this may be a difference in which C compiler is being used (or in the compiler settings?).  I know with the .NET SDK (which uses the `wasi-sdk` build of clang) we needed to manually change the angle brackets on headers to quotes.  But that still accepted the `export_name` attribute.  And it looks like `wasienv` uses clang as well; so not _just_ the compiler I think.

I noticed that the `wasienv` examples are all plain `main`-style programs that import WASI but don't export anything (except the inherent `_start` function); I wonder if `wasienv` doesn't support the component model?  There is an issue in the wasienv repo (https://github.com/wasienv/wasienv/issues/49) that asks about "dylibs" - when we compile Rust with exports we have to set the type to `dylib` so I wonder if this is the same problem?

Confusingly, the README they link to for this (https://github.com/dart-lang/wasm/blob/main/wasm/README.md) shows them compiling _not_ with wasienv but directly with `clang`.  So I am a bit puzzled as to what they are recommending people to do.

@dicej you're more familiar with toolchains than I am... have you come across this?

A couple of other notes:

* The example the post gives of using wasienv is to build C functions Wasm which Dart _native_ consumes via Wasm interop.  So I may be misunderstanding what you are trying to do - host Spin modules in Dart, or use Dart to author Spin modules?

* I also saw in the article you linked that Dart targets Wasm-GC.  Spin's underlying runtime is wasmtime which does not currently support Wasm-GC.  So if you are aiming to build Spin components with Dart, please be warned that even when you resolve the compile and link issues you may not be able to run the resulting Dart program on Spin.

* Please be aware that `spin-http.c` calls a function `spin_http_handle_http_request` which is forward declared in `spin-http.h` but not implemented in the C files - it needs to be resolvable at link time.  In the case of the Go SDK it is implemented in cgo at https://github.com/fermyon/spin/blob/a217f84056b6be17ec229e09e23bdca30daf57aa/sdk/go/http/internals.go#L16 (and hands off to the user-defined function); I don't know it would be handled by the Dart FFI but it will need to be there somehow.

Hope this helps - it sounds like a fascinating experiment!

**Comment by vdice** [comment]
Hi @iapicca, checking in to see if you've had more success with this effort or if we can help further.

**Comment by iapicca** [comment]
> Hi @iapicca, checking in to see if you've had more success with this effort or if we can help further.

Hi @vdice, thanks for checking in!
yes I have done some work, see branch "http" of this [repo](https://github.com/iapicca/spinda)
, but lately I'm ultra busy because I'm moving to Iceland and I haven't tested it yet.
I'll get back to it as soon as possible.

**Comment by iapicca** [comment]
@vdice apparently dart ability to compile to wasm is heavily dependent on d8 and js...
**_when things will change I'll pick up from there_**, 
I'm closing the issue for now.
thank you, @itowlson and others on discord for the support
