### ISSUE TITLE
Compile warning from `watchexec` dependency

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1337]
Building with Cargo 1.68 reports `warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2` (the problematic feature is uninteresting but you can get it via `cargo report` if you are keen).

nom 5.1.2 appears to come in as an indirect dependency of `watchexec` via `clearscreen` and `terminfo`.  nom 7.1.3 is also imported, by various other crates (but doesn't seem to cause the warning).

**Comment by calebschoepp** [comment]
Some googling indicates that this is fixed in versions >5 of `nom`. I'll file an issue with `watchexec` to try and upgrade their dependency on nom.

**Comment by itowlson** [comment]
Fixed via #1401.
