### ISSUE TITLE
Re-export HTTP items from SDK instead of assuming dependency.

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#1340]
Currently the rust sdk requires the consuming Cargo.toml to have a dependency on the http crate. However, It seems pretty standard for macros that are generating code to use symbols re-exported from the crate that exports the macro itself (i.e. if someones cargo.toml is missing "http" some pretty nasty errors are thrown). I want to suggest that spin_sdk re-exports HTTP types used by the macro so that the macros can reference those, e.g.:

```
// in the spin_sdk macro crate

impl From<spin_http::Method> for spin_sdk::http::Method {
    fn from(spin_method: spin_http::Method) -> Self {
       ...
    }
}
```

**Comment by itowlson** [comment]
The consuming `Cargo.toml` no longer needs a dependency on the `http` crate and can use `spin_sdk::http` objects exclusively.  (Indeed this is the template default.)  It only needs `http` if the app developer prefers to use those types.  Closing as fixed; Brian please reopen (and transfer to the new SDK repo?) if still needed.
