### ISSUE TITLE
[Rust SDK] Should the `key_value::Store::get` return `Result<Option<Vec<u8>>, key_value::Error>`?

### ISSUE THREAD

**Issue by rylev** [fermyon/spin#1355]
The `key_value::Store::get` API currently returns `Result<Vec<u8>, key_value::Error>` and specifically `Err(key_value::Error::NoSuchKey)` when the key is missing. This can lead to some awkward code that cannot fully take advantage of Rust's `?` operator:

```rust
match store.get("my_key") {
  Ok(e) => todo!("handle when key is present"),
  Err(key_value::Error::NoSuchKey) => todo!("handle when key is not present"),
  Err(e) =>  return Err(e.into()),
}
```

or 

```rust
store.get("my_key").or_else(|e| match {
  key_value::Error::NoSuchKey => todo!("handle when key is not present"),
  e => Err(e),
})?;
```

If the API were to return `Result<Option<Vec<u8>>, key_value::Error>` instead such handling would be a bit easier:

```rust
match store.get("my_key")? {
  Some(e) => todo!("handle when key is present"),
  None => todo!("handle when key is not present"),
}
```

Of course, in the case where the program expects the key to be present becomes a bit more complicated. Going from:

```rust
let value = store.get("my_key")?;
```

to

```rust
let value = store.get("my_key")?.ok_or(MyError)?;
```

When using the SDK, I was caught off guard by the API not returning an Option and was wondering if there's any desire to see that changed in the future.

**Comment by itowlson** [comment]
> the case where the program expects the key to be present becomes a bit more complicated

I wonder if there should be one of those `get/try_get` pairings, where `get` expects the thing (so returns only a Result) and `try_get` is not sure (so returns the `Result<Option>`)?  This might be more feasible to do without breaking backward compatibility too...?

**Comment by rylev** [comment]
This was done in https://github.com/fermyon/spin/pull/1880
