### ISSUE TITLE
File mounting treats relative path as "file pattern"

### ISSUE THREAD

**Issue by rylev** [fermyon/spin#1356]
In my spin.toml, my component is mounting a single file:

```toml
files = ["foo/foo.txt"]
```

However spin treats this as a so called "file pattern" and does not allow `--direct-mount` to be passed to `spin up`. Instead I get the error:

```bash
this component cannot be run with `--direct-mount` because it uses file patterns
```

I would expect instead that users would be allowed to mount individual files.

**Comment by dicej** [comment]
I don't think this is technically possible.  WASI preopened file descriptors need to be directories, AFAIK -- they can't be files.  So there's no way to mount a single host file directly without mounting the directory it contains (and thus everything in that directory).

**Comment by dicej** [comment]
Per, https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md#-preopentype-variant, I don't believe this is possible, so closing.
