### ISSUE TITLE
sdk/go: Support GOOS=wasip1 / Remove CGO

### ISSUE THREAD

**Issue by tillknuesting** [fermyon/spin#1376]
To support the upcoming wasip1 support in the next Go release, it would be great if the Go SDK of spin supports this. The issue is that GOOS=wasip1 does not support CGO, and therefore the SDK needs to be refactored to be pure Go code.

Happy to get some pointers here on what the blockers are to port the C code to Go in this case.

Just for reference how to get the latest Go version from master:

```
go install golang.org/dl/gotip@latest
gotip download

cat > main.go <<EOF
package main

func main() {
	println("hello")
}
EOF
GOARCH=wasm GOOS=wasip1 gotip build -o main.wasm main.go
```

**Comment by tillknuesting** [comment]
@rajatjindal Do you have some tips on the best way to achieve this?

**Comment by rajatjindal** [comment]
cc @adamreese - he has most context around Spin Golang sdk

**Comment by adamreese** [comment]
wit-bindgen generates bindings that require CGO.  The SDK would need to be written from scratch.  I don't have enough experience with go at that level to know the level of effort it would take.
