### ISSUE TITLE
Print the configuration of key/value store at startup

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#1380]
`spin up` with no configuration will print the location of the database file for the default key/value store:

```bash
$ spin up
Logging component stdio to ".spin/logs/"
Storing default key-value data to ".spin/sqlite_key_value.db"
```

When passing a Redis instance as runtime config, that is not logged:

```bash
$ spin up --runtime-config-file runtime-config.toml
Logging component stdio to ".spin/logs/"
```

ref #1365

**Comment by fibonacci1729** [comment]
Would something like `Storing default key-value data to Redis` be sufficient? I'd be worried about printing the URL here that might possibly contain sensitive data / credentials.

**Comment by radu-matei** [comment]
Yeah, good idea.
That should be enough!
