### ISSUE TITLE
Dev Loop Test Failure

### ISSUE THREAD

**Issue by suneetnangia** [fermyon/spin#1385]
When running `make test` spin is not present in dev container/system path which results in the following error:

---
running 1 test
**"/bin/bash: line 1: spin: command not found\n"**
""
thread 'spinup_tests::key_value_works' panicked at 'command `cd "/workspaces/spin/crates/e2e-testing/../../tests/testcases/key-value" && "/bin/bash" "-c" "spin build"` exited with code 127', crates/e2e-testing/src/utils.rs:50:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test spinup_tests::key_value_works ... FAILED

failures:

failures:
    spinup_tests::key_value_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 20 filtered out; finished in 0.00s

error: test failed, to rerun pass `--test spinup_tests`
error: 1 target failed:
    `--test spinup_tests`
make: *** [Makefile:64: test-kv] Error 101

**Comment by rajatjindal** [comment]
Hi @suneetnangia 

thank you for reporting this issue. Could you please confirm if you have Spin in `target/{release,debug}` directory? I think we should add those dir to PATH before running the tests.

**Comment by suneetnangia** [comment]
Hi @rajatjindal
Confirmed, spin binary does get created in `./target/release` dir, I had to manually copy it to /usr/local/bin/ to make the tests run.  Agreed, adding the above release/debug dirs to PATH should fix this.
