### ISSUE TITLE
remove description and http base from spin new experience with http templates

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#1391]
I never update the description and http base and path options. I know I can use the accept-defaults flag but I'm wondering if we've given thought to getting rid of those prompts altogether and letting the user edit these in the spin.toml as the default experience?

**Comment by ThorstenHans** [comment]
Hey @michelleN thought about that also couple of times in the context of `description`. 

However, I think setting the `path` is a quite common thing. 
Although, being able to set the `base` is quite handy, I think in the case of `base` its more likely that users want to change or actually provide a base other than `/` when they're done with implementing their HTTP app and want to integrate the API with other parts of a bigger system (e.g. frontend).

**Comment by vdice** [comment]
I believe `base` is already removed (or intended to be?) in 2.0 cc @itowlson @lann

**Comment by lann** [comment]
We didn't get around to removing `base` entirely; I just made it optional.

**Comment by itowlson** [comment]
It's been removed from the `spin new` experience though

**Comment by michelleN** [comment]
Currently, path and description are the only fields prompted for and I think that's a good experience for now. I'd like to consider switching --accepts-defaults out for the default experience and making the current prompt experience optional for a future major version release. Do we feel we can close this issue for now or are there objections?

**Comment by itowlson** [comment]
Your approach sounds good to me.

One thing that occurred to me - as a post-2.0, non-breaking change - is to have an environment variable for `--accept-defaults` so that folks who find the prompt experience frustrating could set it in their profile and never see description and path ever again.  But we can discuss that later!

**Comment by michelleN** [comment]
That's a great idea!
