### ISSUE TITLE
[cli] Spin CLI should print a warning when outdated

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin#1397]
The Spin CLI should warn the user when it's outdated and a new release is available.

This would smoothen the experience, especially for developers that use Spin only occasionally.

## Considerations

- I'm not sure if GitHub enforced rate limiting when asking for the latest release endpoint (https://api.github.com/repos/{owner}/{repo}/releases/latest)

**Comment by radu-matei** [comment]
I think there is a rate limit.
A simple way to do this would be a Spin application deployed _somewhere_ that returns a metadata object with the latest release.

**Comment by ThorstenHans** [comment]
This is addressed using the `check-for-update` plugin now. Alternatively, users can rely on package managers (currently `brew` is supported) to stay current with their local `spin` installation
