### ISSUE TITLE
Tests do not respect `CARGO_TARGET_DIR`

### ISSUE THREAD

**Issue by rylev** [fermyon/spin#1400]
This is similar to #1385 but different enough that I think it warrants its own issue.

I use `CARGO_TARGET_DIR` to set my target directory to somewhere in my home directory. The tests, however, assume that spin is located in `./target/{debug,release}/`. Ideally we would use the `CARGO_TARGET_DIR` to detect the location of the target directory and form the path correctly.

**Comment by rajatjindal** [comment]
Hi @rylev thank you for reporting this ticket. 

do you think if we add logic in Makefile to use `CARGO_TARGET_DIR` (with default set to `target` in current dir), and then append `debug or release` to that path will be ok?

**Comment by rylev** [comment]
I think that will probably work. We should give it a try!

**Comment by vdice** [comment]
This one appears to have been resolved by https://github.com/fermyon/spin/pull/1422.
