### ISSUE TITLE
Add MQTT trigger

### ISSUE THREAD

**Issue by nicolascrochet7** [fermyon/spin#1415]
Hi,

It would be interesting to add MQTT as a trigger for Spin.

Spin lightness and speed would especially complement well MQTT-SN, where it is possible to send data through QoS -1, for example in IoT use cases where data is streamed, such as geolocalisation.

Spin routing could easily apply to MQTT topic.
(In a similar way, AMQP could also offer an interesting trigger)

Unfortunately I am not mature enough with Rust and Spin to develop such a plugin.

**Comment by Mossaka** [comment]
I like this idea! The MQTT trigger could be added as an implementation of the [wasi-messaging](https://github.com/WebAssembly/wasi-messaging) world.

**Comment by itowlson** [comment]
@lee-orr has a messaging trigger at https://github.com/lee-orr/spin-message-trigger - I don't think it currently supports MQTT but that might just ('just') be a matter of adding a new broker, but I am very ignorant of all this!  @lee-orr what do you reckon?

**Comment by lee-orr** [comment]
Should be as simple as adding a new broker, though I know nothing about MQTT so I could be wrong

**Comment by lee-orr** [comment]
In the mean time - there is also a mqtt adapter for NATS, which the messaging trigger already supports. https://nats.io/download/#connectors-and-utilities

**Comment by lee-orr** [comment]
@nicolascrochet7 - MQTT support is now available with spin-message-trigger - https://github.com/lee-orr/spin-message-trigger
