### ISSUE TITLE
HTTP CONNECT method not supported

### ISSUE THREAD

**Issue by nicolascrochet7** [fermyon/spin#1416]
Hi,

Running a simple code to test CONNECT seems not to be supported : 

```rust
use anyhow::Result;
use http::{Method, StatusCode};
use spin_sdk::{
    http::{Request, Response},
    http_component,
};

/// A simple Spin HTTP component.
#[http_component]
fn handle_connect(req: Request) -> Result<Response> {
    println!("{:?}", req.method());
    let (status, body) = match req.method() {
        &Method::CONNECT => {
            (StatusCode::OK, None)
        }
        // No other methods are currently supported
        _ => (StatusCode::METHOD_NOT_ALLOWED, None),
    };
    Ok(http::Response::builder()
        .status(status)
        .body(body)?)
}
```

**Comment by lann** [comment]
Indeed CONNECT is not supported. I'm not sure there is a reasonably way to implement it in Spin's application model; could you describe your use-case?

**Comment by nicolascrochet7** [comment]
It is usually employed for establishing an initial connection to speed things up for next requests since most middlewares are capable of caching connection details.

Of course an empty GET still works, but the proper method is actually CONNECT.

**Comment by lann** [comment]
Interesting; I've never seen CONNECT used that way.

If you need to prewarm a connection with an HTTP request I would recommend using HEAD or OPTIONS.

**Comment by nicolascrochet7** [comment]
Well to be more precise it usually when HTTPS is invoked and you might require going through some proxies before final URI. (not sure I am wording that correctly in english)

**Comment by lann** [comment]
CONNECT would only be applicable if spin itself was operating as an HTTP proxy. I don't think it would make sense to add that functionality to spin given its current execution model.

**Comment by nicolascrochet7** [comment]
No problem with me, I was just testing all methods.

But on your last comment, wouldn't Spin still require to respond to CONNECT if a client request it through a proxy? (Spin being the final URI)

**Comment by lann** [comment]
CONNECT is only (typically) used in a connection _to_ a proxy server, not in the traffic tunneled through the proxy.

**Comment by lann** [comment]
No specific support for CONNECT expected at this time, though a future revision of the interface will likely allow requests with any method.
