### ISSUE TITLE
`spin watch` should only warn about missing config if no components have config

### ISSUE THREAD

**Issue by calebschoepp** [fermyon/spin#1420]
For the use case of only building it can be annoying to be constantly reminded that your components don't have watch config. We should really only do it when no components have config.

**Comment by itowlson** [comment]
Isn't the issue with component that have build config but no watch config?

Consider a Bartholomew site, where the Wasm modules are pre-built.  None of the components have any source code, hence no watch config.  Yet it feels like `spin watch` should not complain in this case: after all,, it can do what the user needs, which is to update whenever anything changes.  It just so happens that there is no source code to change!

(Forgive me if this is obsolete - it mentions "the use case of only building" so not sure if it relates to the `--skip-up` option that no longer exists.  I agree that if that option existed and there was nothing to build then a warning would be in order.)

**Comment by calebschoepp** [comment]
Sorry I did a poor job wording this issue. I filed this issue based on a conversation with Lann [here](https://github.com/fermyon/spin/pull/1418#discussion_r1175308169). Maybe that can give some more context.

**Comment by itowlson** [comment]
That conversation talks about using a precompiled component where there is no build section.  We certainly shouldn't be warning on components that have no build section, and we shouldn't be warning even if _no_ components have any build section (per the Bartholomew example).

I don't quite understand the comment about having to copy `source` into `watch` though - that suggests there _is_ a build command - oh well never mind, my point was just to note that an app built only with precompiled components should not raise a warning.

**Comment by calebschoepp** [comment]
Honestly, I'm a bit confused at this point too 🤣 and I'm not sure this issue is talking about anything concrete. Let's just close it and then we can always re-open it later if it starts to make sense then.

**Comment by vdice** [comment]
Closing per https://github.com/fermyon/spin/issues/1420#issuecomment-1548144407; feel free to re-open if needed.
