### ISSUE TITLE
Resource sharing vs granular deployment: the long term architecture

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#144]
I wanted to capture a valuable discussion from yesterday's Spin call.  This relates to running multiple applications off the same trigger but has deeper implications.

The motivating concern is making better use of resources.  To paraphrase Radu, if we have 1000 applications running, right now that means 1000 HTTP servers, sitting there consuming resources without doing very much most of the time.  This is wasteful at scale.  So it would be good to have those applications _share_ a single HTTP server (and, if necessary, use a reverse proxy to surface that server at different host names).

This can of course be addressed by allowing `spin up` to take multiple application files or bindles, run them all and dispatch based on application base path.  This is acceptable for a development scenario, but in production, those applications will be revved independently.  For example, if a Spin instance is serving all channels of a Hippo application, I want to rev my channel without interrupting Radu testing his channel.  You also start to hit issues like failure management - if one application fails catastrophically, how can we detect and remediate that without affecting other applications?

Many of us will have different mental models for how to approach this - I, for example, am unavoidably reminded of Erlang's lightweight processes, supervisors, and hot reloads.  Whatever those models, we need to capture requirements and goals of a long-term architecture that can support the resource sharing vision.  We also need to decide how to spread that architectural load across Spin, Hippo and Nomad (or other scheduler).  This issue is intended to provide a central location to track and discuss this.

Some suggested high-level requirements:

* Allow applications to share a HTTP server (or other resource-consuming trigger)
  * That is, if I have 1000 applications, I should be able to have <1000 HTTP servers
* Allow (Spin) applications that share resources to be started, upgraded, and restarted independently
  * That is, if I want to add a new microservice, or a new environment to an existing microservice, I should be able to do so without impacting any other microservice
* The user should be able to get metrics and diagnostics at the application level
  * For example, I should be able to get info for the Spline microservice without wading through every microservice it shares a Spin instance with
* The security boundaries should be clearly understood and documented, and who enforces those boundaries should be clearly understood and documented
  * For example, we might say that Spin provides no security boundaries, and if you want to limit visibility of applications (or interaction between applications) then you need to run it in Hippo.

This also opens us up to thinking about a platform substrate that allows us to shift loads around, etc. etc.  So we may want to distinguish (and have terminology, and potentially separate projects, for):

* Spin the command line UI
* Spin the control plane and scheduling substrate
* Spin the execution environment and service provider

We do *not* need to address any of this for 0.1 - the "private dev" solution of running multiple applications within a monolithic OS process is fine for that.  This is specifically about how we trade off our various needs in the longer timeframe.

**Comment by itowlson** [comment]
Closing this as we have a way forward on it.

**Comment by runvnc** [comment]
Hello, sorry to bother you, but I haven't found the answer to this so far. The "spin up" process uses very little memory, but the 'trigger http' process is much more. And that means that my idea of using web assembly as a lightweight modern multi-tenant hosting backbone is not feasible with this setup.

Is there a way to use a single trigger and share it or something?

**Comment by itowlson** [comment]
@runvnc That's a great question with a complicated answer.  The Spin project has kind of two sides to it: the Spin runtime, and the Spin CLI.  The Spin CLI focuses on the local developer experience, and provides only single application hosting.  Specifically, `spin up` and `spin trigger *` load only one application per process.  As you can see from this issue, we explored the idea of a shared hosting process which `spin up` would command to start or stop applications, but we eventually decided against it for the local CLI because it was a lot more complicated to set up.

The Spin rumtime, on the other hand, is eminently suitable for multi-tenant or other multi-application scenarios with different workload requirements (e.g. robust storage, failover, etc.).  Unfortunately, Fermyon doesn't have a public example of an alternative Spin host to show.  (Fermyon Platform uses process-per-application and the Spin CLI under the hood.)  The closest public alternative host we know of is the containerd shim by Deis Labs (https://github.com/deislabs/containerd-wasm-shims/blob/main/containerd-shim-spin-v1/src/main.rs).  That re-hosts the Spin runtime, though I'm not sure what the process sharing model is.  @Mossaka is often around here and on Discord, and could I'm sure cover it in more detail.

So I'm afraid the answer is: yes, you _can_ share a HTTP server, and run multiple applications in one process, _but_ at the moment you'll need to create or adapt your own Spin host to do that (subject to more info about the containerd shim).  It is absolutely possible and supported, as the shim shows: the Spin runtime is designed to be a runtime, not bound to the CLI.  Host developers would be embedding crates such as `spin-core`, `spin-app` and `spin-trigger-http`.  I'm not sure to what extent you envisage the hosting backbone to be off-the-shelf vs custom build, but at the moment I don't think there are any off-the-shelf self-host solutions other than the shim.

I hope that answers the question sufficiently for you to make a decision - sorry the answer is so long-winded!
