### ISSUE TITLE
Option to watch directories for changes and re-start Spin

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#148]
Say you are developing a website that runs in Spin (with Bartholomew, for example).

Because we are copying static assets into  a temporary directory, rather than mounting directly, making a change to a file requires restarting `spin up`.
A workaround is having a directory watcher that restarts Spin (see https://github.com/fermyon/spin/pull/145#discussion_r822241029), but it would be great if `spin up` had this option built-in.

**Comment by joepio** [comment]
Not entirely sure if this is the same usecase but:

I'd like to run `spin build --up` on saving a source file. [Notify](https://docs.rs/notify/latest/notify/) might help with this.

I think `spin build --up` or `spin up --watch` or `spin watch` would be fitting candidates.

**Comment by calebschoepp** [comment]
@joepio Just sharing that I've got a prototype `spin watch` PR out that you might want to check out. https://github.com/fermyon/spin/pull/1164

**Comment by joepio** [comment]
> @joepio Just sharing that I've got a prototype `spin watch` PR out that you might want to check out. https://github.com/fermyon/spin/pull/1164

Awesome, thanks!

**Comment by calebschoepp** [comment]
Closing now that #1237 has merged
