### ISSUE TITLE
Best way to install Spin (if you already have a prior installation)?

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/spin#1516]
We have noticed that if a user has Spin installed (from a past time) via Cargo and wants to just follow the official install docs [1], that the Cargo path can override the /usr/loca/bin/ path (depending on the order of their system path).

In this case I have a new docs PR [2] recommending that the user type `which spin` and copy the binary to that location. However, we are not 100% what best practice is concerning this (and re-installing Spin using different methods). I think we have talked about the idea of an uninstall script for Spin but not sure if/when this is possible. Happy to be advised and guided by you.

[1] https://developer.fermyon.com/spin/install
[2] https://github.com/fermyon/developer/pull/639

**Comment by cardoso** [comment]
Does `cargo uninstall spin` before running the install script help?

**Comment by tpmccallum** [comment]
Thank you @cardoso 
This has been updated in the docs inline with precisely what you are recommending.
https://github.com/fermyon/developer/pull/639
Thanks again
Tim
