### ISSUE TITLE
`spin up` prints `spin trigger http` usage on bad flag

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1559]
```
$ spin up --fie
error: Found argument '--fie' which wasn't expected, or isn't valid in this context

        If you tried to supply `--fie` as a value rather than a flag, use `-- --fie`

USAGE:
    spin trigger http [OPTIONS]

For more information try --help
Error: exit status: 2
```

**Comment by dipankardas011** [comment]
@itowlson how to reproduce it?

**Comment by itowlson** [comment]
@dipankardas011 Change to a directory with a Spin HTTP application (`spin.toml`) in it, and run `spin up --fie`, and note the `USAGE` line in the output:

```
# In a directory with a (HTTP trigger) spin.toml
ivan@hecate:~/testing/dioxus-test$ ls
Cargo.lock  Cargo.toml  images  spin.toml  src  target

# Run spin up with a bad flag
ivan@hecate:~/testing/dioxus-test$ spin up --fie
error: Found argument '--fie' which wasn't expected, or isn't valid in this context

        If you tried to supply `--fie` as a value rather than a flag, use `-- --fie`

USAGE:
    spin trigger http [OPTIONS]

For more information try --help
Error: exit status: 2
```

USAGE should refer to `spin up` rather than the internal `spin trigger http` command.

**Comment by dipankardas011** [comment]
@itowlson what was the use of -i before

from the spin up -h
```
-e for environment vars
-f for spin.tmol specify
```

**Comment by dipankardas011** [comment]
Currently these things  are present in spin up
```bash
spin up -f spin.toml -e SECRET=342we3 -L logs --listen 0.0.0.0:9090
```

**Comment by dipankardas011** [comment]
Also found this https://developer.fermyon.com/spin/cli-reference#spin-up-http-trigger

**Comment by itowlson** [comment]
This is an error case.  `--fie` is an invalid flag.  `--bibbly-bobbly` would do equally well.

You're right to identify that Spin is trying to invoke the HTTP trigger, and that this is why the USAGE section references it.  The (minor) bug is that the error message - which comes from the HTTP trigger - is inviting users who enter a bad flag to run `spin trigger http` (which is an internal command that users should never run) rather than `spin up` (which is the user-facing interface).

**Comment by dipankardas011** [comment]
okay got it
So to summarize for any invalid command it is suggesting a internal command (gets exposed) for the users to run which is not meant to be used by them

**Comment by dipankardas011** [comment]
sure will check the source code and see where it is issue

**Comment by itowlson** [comment]
Awesome, thanks!

**Comment by dipankardas011** [comment]
> Awesome, thanks!

btw havn't contributed to rust projects before 😄

**Comment by dipankardas011** [comment]
but got it where to look into

**Comment by dipankardas011** [comment]
This file https://github.com/fermyon/spin/blob/ced6f0e9a04631de351e0d137873be301d7e08bb/src/commands/up.rs#L115-L158

**Comment by dipankardas011** [comment]
It also gives this when invalid sub-command is present in up sub-command
```
spin up dcsc
error: Found argument 'dcsc' which wasn't expected, or isn't valid in this context

USAGE:
    spin trigger http [OPTIONS]

For more information try --help
Error: exit status: 2
```

**Comment by dipankardas011** [comment]
It happens for all the commands
```
spin watch sdcefvdscef
Executing the build command for component d: cargo build --target wasm32-wasi --release
warning: skipping duplicate package `http-rust-router` found at `/home/dipankar/.cargo/git/checkouts/spin-91500438ac5656d2/28655d5/examples/http-rust-router`
warning: skipping duplicate package `http-rust` found at `/home/dipankar/.cargo/git/checkouts/spin-91500438ac5656d2/28655d5/tests/watch/http-rust`
    Finished release [optimized] target(s) in 0.04s
Successfully ran the build command for the Spin components.
error: Found argument 'sdcefvdscef' which wasn't expected, or isn't valid in this context

USAGE:
    spin trigger http [OPTIONS]

For more information try --help
Error: exit status: 2
```

**Comment by dipankardas011** [comment]
so the problem is in how these sub-commands are invoked

**Comment by dipankardas011** [comment]
@itowlson found the problem
This function is making it print
https://github.com/fermyon/spin/blob/ced6f0e9a04631de351e0d137873be301d7e08bb/src/commands/up.rs#L379C1-L381C2

**Comment by dipankardas011** [comment]
but not sure how to resolve it

**Comment by dipankardas011** [comment]
so the up command indirectly calls all the http-rust templates to the spin trigger http

**Comment by dipankardas011** [comment]
so the main problem is it might not be having validation of arguments as it is directly passing to the internals

**Comment by dipankardas011** [comment]
```rust
self.trigger_args // it is not tested for validation
```

**Comment by itowlson** [comment]
Yes, but here's the nub of the problem: `spin up` _can't_ validate the trigger arguments because it _doesn't know what arguments each trigger takes._  `--bibbly-bobbly` is invalid on the HTTP, Redis, SQS and Timer triggers, but it might be valid on a future user-authored trigger.  So `spin up` _has_ to hand all the extra arguments to the trigger unvalidated.  But that means that when validation fails we are already inside the trigger...

**Comment by dipankardas011** [comment]
> Yes, but here's the nub of the problem: `spin up` _can't_ validate the trigger arguments because it _doesn't know what arguments each trigger takes._  `--bibbly-bobbly` is invalid on the HTTP, Redis, SQS and Timer triggers, but it might be valid on a future user-authored trigger.  So `spin up` _has_ to hand all the extra arguments to the trigger unvalidated.  But that means that when validation fails we are already inside the trigger...

That's the problem
But if we change the trigger usage then it will lead to inconsistency

**Comment by dipankardas011** [comment]
This issue should be very important
The lower level components are shown to the users

**Comment by itowlson** [comment]
Well, they are only shown if the user makes a mistake, and it's not like these components are _secret,_ and realistically few people read the USAGE.  If I make a mistake I usually go, "oh, duh, I mistyped `--lsiten` when I meant `--listen`, I'll just cursor up and fix it."  So I would not say very important - it's just nice to be tidy.

Obviously we would consider it more important if people were reporting it as causing problems for them, but at the moment it's only me being pedantic I think!
