### ISSUE TITLE
Confusing error message when trying to install older version of a plugin

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1578]
I was trying to install a local build of a plugin, which was not a newer version of an already installed plugin, and got an error message which was confusing.

1. Tried to install the local plugin:
```
spin plugin install -f ./cloud.json
Error: Newer version 0.1.1 of plugin 'cloud' is already installed. To downgrade to version 0.1 set the `--downgrade` flag.
```

2. Followed instructions:
```
spin plugin install -f ./cloud.json --downgrade
error: Found argument '--downgrade' which wasn't expected, or isn't valid in this context

	If you tried to supply `--downgrade` as a value rather than a flag, use `-- --downgrade`

USAGE:
    spin plugins install --file <LOCAL_PLUGIN_MANIFEST>

For more information try --help
```

3. Found that the proposed flag was on a different command:
```
spin plugin upgrade cloud-plugin -f ./cloud.json --downgrade
```

**Comment by kate-goldenring** [comment]
this flag should also be added to `install`. Good find

**Comment by mikkelhegn** [comment]
In this particular case, what is the difference between `install` and `upgrade`?

**Comment by kate-goldenring** [comment]
Fair point. I think we could do that if the plugin already exists, you need to do an upgrade to modify it. Seems like we need to fix the error message rather than add more functionality (the flag) to install.

**Comment by kate-goldenring** [comment]
I also find it unnecessary to require the plugin name for a plugin installed from a  local or remote endpoint. 
```sh
spin plugin upgrade cloud-plugin -f ./cloud.json --downgrade
# instead would be better:
spin plugin upgrade -f ./cloud.json --downgrade
```
If this felt weird, i might open an issue to make name optional in this case and better mirror the install experience

**Comment by kate-goldenring** [comment]
created https://github.com/fermyon/spin/issues/1592
