### ISSUE TITLE
Help info on plugins such as `spin cloud` don't display top-level `spin` command

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/spin#1601]
On Spin `v1.2.0`, `spin cloud --help` states usage as `spin cloud <SUBCOMMAND>`

```sh
$ spin cloud --help

spin-cloud 
Commands for publishing applications to the Fermyon Platform

USAGE:
    spin cloud <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    deploy    Package and upload an application to the Fermyon Platform
    help      Print this message or the help of the given subcommand(s)
    login     Log into the Fermyon Platform
```

However, since Spin `v1.3.0` uses the cloud plugin for the command, it displays usage as `cloud <SUBCOMMAND>`:

```sh
$ spin cloud --help

cloud-plugin 0.1.1
Fermyon Engineering <engineering@fermyon.com>

USAGE:
    cloud <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    deploy       Package and upload an application to the Fermyon Cloud
    help         Print this message or the help of the given subcommand(s)
    login        Login to Fermyon Cloud
    variables    Manage Spin application variables
```

Is this an issue? Is there a way to update the usage to display `spin` as the top-level command?

**Comment by itowlson** [comment]
I think this would need to be addressed on the `cloud-plugin` side.  I think by adding a doc comment to the app struct at https://github.com/fermyon/cloud-plugin/blob/eeb5339623d6c42f11807fcbde9f1d8506f360ba/src/main.rs#L23 - that seems to be how Spin does it.

**Comment by kate-goldenring** [comment]
@itowlson I changed the binary name in the plugin. I wonder if we want to set this as a precedent/recommendation for plugins executed from the Spin CLI?

**Comment by itowlson** [comment]
We could, but the help presentation is going to be very variable per plugin anyway (like a plugin written using that Go CLI library might present its help quite differently from one written using clap), so I'm not sure there's a lot of value in trying to standardise.  It's something to keep in mind for "seamless" plugins like Cloud though.
