### ISSUE TITLE
Cargo feature to use only "interface" bits from HTTP crates

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1608]
The `spin cloud deploy` command needs to understand the app info endpoint for checking update deployment readiness.  The schema for this is defined in the `spin-http-trigger` crate.  This currently brings in a whole lot of Spin runtime goodness from `spin-core` all the way up to the Postgres crate.  It would be good to offer a Cargo feature on `spin-http-trigger` to allow the plugin to import the app info type without the entire runtime.

**Comment by fibonacci1729** [comment]
This is addressed by #1634

**Comment by michelleN** [comment]
@itowlson @fibonacci1729 is this issue resolved?

**Comment by fibonacci1729** [comment]
I would say so! I'll close. @itowlson feel free to reopen if you desire.
