### ISSUE TITLE
Go SDK SQLite support

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1618]

**Comment by itowlson** [comment]
@adamreese From conversation with @rylev, he is interested in doing this but is not sure what the current plan is given the work going on for v2.  What's your advice for something to be delivered in the 1.4 timeframe?

**Comment by adamreese** [comment]
The v2 work is only for kv and redis. SQLite support can be added to v1.

**Comment by dipankardas011** [comment]
interested in adding support, but don't know the starting point for this Issue
Can anyone provide me some context and which things to look for?

**Comment by rylev** [comment]
@dipankardas011 thanks for volunteering! Work on this has already started with https://github.com/fermyon/spin/pull/1630, but that work is currently stuck. I'm looking at a possible work around. If I can't get that to work, we might want to search for alternative approaches. I'll update this issue in the next day or so with what I think are the next steps. Unfortunately, there are multiple things in play that make adding this support not super straight forward.

**Comment by itowlson** [comment]
This exists in the v2 Go SDK (https://pkg.go.dev/github.com/fermyon/spin/sdk/go/v2@v2.2.0/sqlite).  Closing as fixed.
