### ISSUE TITLE
Detect malformed configuration variable keys before up/deploy

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#1622]
The documentation for [dynamic configuration variables](https://github.com/fermyon/developer/blob/main/content/spin/dynamic-configuration.md) specifies that `Configuration keys may only contain lowercase letters and underscores between letters`.

Currently, if i deploy an application with a malformed configuration key (e.g. `LOG_LEVEL`) my application will serve `500` and my logs will contain angry shouting about what the proper format is for keys.

I think it would be ideal if we somehow validate configuration keys pre-deploy/up or ask the doctor to do it.

**Comment by itowlson** [comment]
Yes, it looks like Spin validates the names only at run time (i.e. this happens locally not just in cloud).  I am not sure why - I think this has come up before but can't remember the outcome.  I'll take a look - thanks for flagging this!
