### ISSUE TITLE
misleading error message for application variables

### ISSUE THREAD

**Issue by upachler** [fermyon/spin#1628]
It appears that spin does not like uppercase names for application variables - but it complains with a misleading error message:

`2023-07-02T17:47:48.611690Z ERROR spin_trigger_http: Error processing request: host component error: invalid config key: "PG_ADDRESS" must start with an ASCII letter`

When changing the variable name to `pg_address`, it works. Clearly, the uppercase characters of `PG_ADDRESS` are valid ASCII, including the underscore `_`. I assume the requirement for lowercase config var names comes [from here](https://developer.fermyon.com/spin/dynamic-configuration#environment-variable-provider)

It'd be great to fix that error message, and also make the docs a bit more [verbose here](https://developer.fermyon.com/spin/variables) about the matter.

I use spin 1.3.0

**Comment by fibonacci1729** [comment]
Hi @upachler ! Thanks for the report. This was recently addressed in #1623 and will be fixed in the 1.4 release.

**Comment by itowlson** [comment]
Thanks for the feedback @upachler and sorry for the frustration.  We can have a look at how to make the definition stuff more prominent in the API guide.

**Comment by itowlson** [comment]
@upachler Between the earlier PR, the linked error improvement PR, and the linked documentation PR, would you be okay with us closing this issue?  Thanks!

**Comment by upachler** [comment]
hi @itowlson, sorry for the delay; I'm only able to look at these things in my spare time - and that that time is scarce.

I've had a look at both commits that you linked. Judging from diffs, this looks fine!
