### ISSUE TITLE
failed to start containerd task "" missing field `spin_version` on AKS

### ISSUE THREAD

**Issue by OliverMKing** [fermyon/spin#1638]
* Spin version: 
1.3.0
* Installed plugin versions
```
cloud 0.1.1 [installed]
js2wasm 0.4.0 [installed]
k8s 0.1.0 [installed]
py2wasm 0.2.0 [installed]
```

I'm attempting to run on AKS and followed all instructions on [Spin Azure AKS](https://developer.fermyon.com/spin/kubernetes). My Spin application pods fail with the message:

```
failed to start containerd task
            "1a97dc0b4e317ac935d5b2c894b3fba9ef40c9d432bce01dd2894647ea4072c9":
            missing field `spin_version` at line 14 column 1: unknown
```

I saw that another user had the same error [here](https://github.com/fermyon/spin/issues/1069#issuecomment-1586195017). I removed the `watch` field from the components in my app as suggested but this didn't fix the problem.

[Manifests used](https://github.com/OliverMKing/WASMamba/tree/main/manifests) match the instructions in the docs as do the cluster and nodes.

Will debug myself some this weekend but wanted to file an issue because I saw others were also affected. Thanks!

**Comment by Mossaka** [comment]
AKS Wasi Nodepool currently supports a much older version of `Spin` which uses `spin_version` as the field name instead of `spin_manifest_version`.

**Comment by Mossaka** [comment]
I digged into the AKS Wasi Nodepool and the `wasmtime-spin-v1` runtime class name is referring to a shim that uses pre v1.0 spin version, which doesn't have the `spin_manifest_version` field. I would suggest ot use `wasmtime-spin-v0-5-1` runtime class, which uses v1.0 spin.

**Comment by OliverMKing** [comment]
Thanks! Swapping to `spin_version` and using removing `watch` from the `spin.toml` worked in combination with the `wasmtime-spin-v0-5-1` runtime class.

**Comment by davidgamero** [comment]
thanks this worked for me too!

**Comment by michelleN** [comment]
Closing this issue since it seems to be resolved but feel free to re-open or open another issue if there is anything we can do better in the Spin repo!
