### ISSUE TITLE
CLI option to use Spin's standard error for components

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#164]
When developing, it would be really helpful to redirect the standard error (and potentially output?) of components to Spin's standard error.
This would make it easy to see the logs and errors while developing.

**Comment by ecumene** [comment]
@danbugs https://github.com/fermyon/spin/blob/42f34d931dae746cb9a5eeea3ee73f6c51319864/crates/engine/src/io.rs#L94

Could this be implemented as an enumerator here, then handled in the up command?

**Comment by ecumene** [comment]
I see -- `--follow <FOLLOW_ID>` and `--follow-all` does this!

**Comment by radu-matei** [comment]
Yes!
Thanks for catching this!
