### ISSUE TITLE
`spin plugin install` fails if latest plugin version doesn't support current Spin version

### ISSUE THREAD

**Issue by rajatjindal** [fermyon/spin#1661]
on trying to install the plugins with spin 1.3, we get following error:

```
$) spin --version
spin 1.3.0 (9fb8256 2023-06-12)

$) spin plugin install js2wasm --yes

Error: Plugin is not compatible with this version of Spin (supported: >=1.4, actual: 1.3.0). Try running `spin plugins update && spin plugins upgrade --all` to install latest or override with `--override-compatibility-check`.
```

It seems because the latest release of js2wasm plugin has compatibility with spin version `>=1.4` only.

It might be useful to identify and install the `latest compatible` version automatically rather than failing the installation.

**Comment by rajatjindal** [comment]
one more thing I noticed is that you can't install the latest version by using a `--version` flag:

```
$) spin plugin install js2wasm -v 0.5.0
Error: plugin 'js2wasm' not found at expected location /Users/rajatjindal/Library/Application Support/spin/plugins/.spin-plugins/manifests/js2wasm/js2wasm@0.5.0.json: No such file or directory (os error 2)
```

**Comment by itowlson** [comment]
@rajatjindal #1548 tracks the second issue

**Comment by itowlson** [comment]
I have a candidate fix for this, but I'm having trouble wrangling it into a test harness - either my fix is in the wrong place or I need to also tweak some layering.
