### ISSUE TITLE
If local tar file doesn't exist, `spin plugins install` gives unhelpful message

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1663]
If you do a `spin plugins install`, and the manifest references a local package path (tar file), and that file doesn't exist, it prints "file or directory does not exist (os error 2)".

It should say _which_ file or directory doesn't exist.

**Comment by michelleN** [comment]
@itowlson is this a bug or enhancement?

**Comment by itowlson** [comment]
@michelleN I don't really know... one could call it a bug because the current error is unhelpful, but one could call it an enhancement because the feature _works_ and this just wants it to fail in a nicer way.  I'm not sure how we classify issues like that...?
