### ISSUE TITLE
Build succeeds but application does not run.

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/spin#1666]
If a user creates a new Redis trigger application and manually adds a new component to the manifest, the application will build successfully but not run. Is it possible to not allow the following `spin.toml` file to build and possibly give the user an error?

```
spin_manifest_version = "1"
authors = ["tpmccallum <tim.mccallum@fermyon.com>"]
description = "Testing config for Redis Rust"
name = "redis-rust"
trigger = { type = "redis", address = "redis://localhost:6379" }
version = "0.1.0"

[[component]]
id = "redis-rust"
source = "target/wasm32-wasi/release/redis_rust.wasm"
allowed_http_hosts = []
[component.trigger]
channel = "one"
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "redis-rust-2"
source = "target/wasm32-wasi/release/redis_rust_2.wasm"
allowed_http_hosts = []
[component.trigger]
channel = "two"
[component.build]
command = "cargo build --target wasm32-wasi --release"
```

Build and run

```
$ spin build
Building component redis-rust with `cargo build --target wasm32-wasi --release`
    Finished release [optimized] target(s) in 0.08s
Building component redis-rust-2 with `cargo build --target wasm32-wasi --release`
    Finished release [optimized] target(s) in 0.07s

$ spin up
Logging component stdio to ".spin/logs/"
Error: Failed to instantiate component 'redis-rust-2'

Caused by:
   0: failed to read component source from disk at path '/Users/tpmccallum/Fermyon/testing-component-config/redis-rust/target/wasm32-wasi/release/redis_rust_2.wasm'
   1: No such file or directory (os error 2)
Error: exit status: 1

```

**Comment by tpmccallum** [comment]
Part 2 on this topic ...

Is it possible to have a single application listen to more than one Redis channel? The reason for curiosity is that `spin add` does not facilitate tacking on additional Redis components in the same application:

```
$ spin add redis-rust
Template redis-rust doesn't support the 'add component' operation
```

**Comment by itowlson** [comment]
The user has added the component with the wrong path.

We can't error on the build because the build has succeeded - both build steps have correctly created the same output, at `target/wasm32-wasi/release/redis_rust.wasm`.  It's the path in component 2 that doesn't match the build.

**Comment by itowlson** [comment]
It would be easy to add `spin add` support to the Redis template - just nobody invested the time to do it.

(If you're interested, I can show you how - otherwise please raise a separate issue and I can do it.)

**Comment by itowlson** [comment]
Oops sorry missed part of the question.  The recommended application structure would be similar to HTTP - subdirectories under `spin.toml`, and component per subdirectory using `workdir` to hook them up to `spin build`.

**Comment by tpmccallum** [comment]
I would be interested in adding `spin add` support to the Redis template. Yes please.

**Comment by tpmccallum** [comment]
Great! I love that subdirectory and `workdir` config; it's neat!

**Comment by tpmccallum** [comment]
I will close this and contact you for a `spin add` tutorial :)
