### ISSUE TITLE
`spin add static-fileserver` creates folder based on component name (still have to create `assets` dir manually)

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/spin#1669]
Version: 
`spin 1.4.0 (7aab1fe 2023-07-11)`

Issue:
When adding a `static-fileserver` component to an application, Spin creates a new directory based on the component name which the user provides. For example:

```console
$ spin add static-fileserver
Enter a name for your new component: component-name
HTTP path: /static/...
Directory containing the files to serve: assets
```
If a user only provides a name `component-name` and then presses inter twice (accepting the defaults) Spin creates the following application structure. The component name directory is empty by default:

```console
$ tree .
.
├── Cargo.toml
├── component-name
├── spin.toml
└── src
    └── lib.rs
```

If the application is built and run as is, the following error message is returned:

```console
$ spin build --up

// --snip--

Finished building all Spin components
Error: Failed to collect file mounts for assets

Caused by:
      Cannot place ~/http-rust-app/assets: source must be a directory
```

If the user creates a new assets directory manually, the build works:

```console
$ mkdir assets
$ spin build --up

// --snip--

Available Routes:
  http-rust-app: http://127.0.0.1:3000 (wildcard)
  component-name: http://127.0.0.1:3000/static (wildcard)
```

Problem is that we a) had to manually create the `assets` directory and b) the application has an empty directory called `component-name`.

```console
.
├── Cargo.lock
├── Cargo.toml
├── assets
├── component-name
├── spin.toml
└── src
    └── lib.rs
```

Related: 
- [Create directory for static-fileserver template ](https://github.com/fermyon/spin/issues/1022)

**Comment by itowlson** [comment]
I was going to claim that this would require some changes because the template system _always_ created the new directory... but the `redirect` template doesn't.  Time to do some figuring!

**Comment by itowlson** [comment]
It's because the fileserver template contains a `.gitignore` for the `.spin` folder, which is appropriate for a `spin new` (because the application might get statey later and we want the ignore ready for it), but not for a `spin add` (where the `.gitignore` belongs in the root and should have been set up by `spin new` anyway).  Fix PRed.  (It doesn't address the linked issue though because that _is_ harder.)
