### ISSUE TITLE
Spin build - js2wasm error on Ubuntu 20.04

### ISSUE THREAD

**Issue by asankagit** [fermyon/spin#1676]
I came up with bellow error messages while i am try to build
OS ubuntu 20.0.4
`
.local/share/spin/plugins/js2wasm/js2wasm: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found
.local/share/spin/plugins/js2wasm/js2wasm: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found 
.local/share/spin/plugins/js2wasm/js2wasm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found  
.local/share/spin/plugins/js2wasm/js2wasm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found
.local/share/spin/plugins/js2wasm/js2wasm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

Error: Build command for component demojs failed with status Exited(1)
`

* Spin version (`spin --version`)
  spin 1.4.1 (e0bd911 2023-07-12)

* Installed plugin versions (`spin plugins list --installed`)
cloud 0.1.1 [installed]
js2wasm 0.5.1 [installed]
py2wasm 0.3.0 [installed]

**Comment by itowlson** [comment]
@karthik2804 What Ubuntu version do we build the js2wasm plugin on?  It looks like we might be building on 22.04, which produces binaries that aren't compatible with older Ubuntu versions (as Spin found out to its cost).  It's best to build on the _oldest_ supported OS because forward compatibility is generally okay.

Might be worth checking the Python plugin as well.

**Comment by dicej** [comment]
We're currently using [ubuntu-latest](https://github.com/fermyon/spin-js-sdk/blob/331bb1327e14a143b579f490e0ca1a60fa262581/.github/workflows/release.yaml#L45).  Addressing this should just be a matter of changing that to `ubuntu-20.04`.

**Comment by dicej** [comment]
I've opened https://github.com/fermyon/spin-js-sdk/issues/182 on the `spin-js-sdk` repo to address this.

**Comment by dicej** [comment]
Ditto for the Python SDK: https://github.com/fermyon/spin-python-sdk/issues/49
