### ISSUE TITLE
Can Spin support new WASI from golang 1.21.0?

### ISSUE THREAD

**Issue by rts-gordon** [fermyon/spin#1688]
Hi there,

  Golang has released new [version 1.21.0 ](https://tip.golang.org/doc/go1.21)that support WASI preview 1, it is more powerful than Tinygo, you know Tinygo can't compile [many go libraries](https://tinygo.org/docs/reference/lang-support/stdlib/). So is it possible that Spint support new WASI from golang 1.21.0?  Thank you.

**Comment by itowlson** [comment]
@adamreese any idea about this?  It looks like the `wasmimport` directive might serve for Spin host APIs but I think we noted a limitation with _exporting_ trigger entry points - am I remembering correctly?

**Comment by adamreese** [comment]
There was a blocker but I don't remember either.  I haven't done any testing with the new go wasi support recently.  Now that  go has released support it's worth looking into.

**Comment by adamreese** [comment]
I did some investigation and @itowlson was correct. Go version 1.21.1 adds the `go:wasmimport` but `go:wasmexport` isn't implemented yet. https://github.com/golang/go/issues/42372
