### ISSUE TITLE
Investigate wasmtime compilation caching

### ISSUE THREAD

**Issue by lann** [fermyon/spin#169]
Compilation caching can speed up spin startup a _lot_, which is important if we want to scale up from zero on-demand.

Its easy to enable caching; it just needs [`cache_config_load_default`](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.cache_config_load_default) called on the Config and the default config file created with `wasmtime config new`. However, we should understand cache invalidation, disk usage, etc. and whether we want to tune the config before doing so.

**Comment by radu-matei** [comment]
ref #413
