### ISSUE TITLE
Templates on spin for rust need to point at main for their spin-sdk dependency

### ISSUE THREAD

**Issue by macolso** [fermyon/spin#1733]
Reported on Discord [here](https://discord.com/channels/926888690310053918/1148522244277014568/1148654246787555378) by @ThorstenHans

**Comment by ThorstenHans** [comment]
I looked up the source code for the install script at [https://github.com/fermyon/developer/blob/main/downloads/install.sh](https://github.com/fermyon/developer/blob/main/downloads/install.sh). It executes `spin templates install --git url --upgrade` in [line 130](https://github.com/fermyon/developer/blob/7f99d957c7d3498b75ca48da97991dbcd88df908/downloads/install.sh#L130)

So my first naive attempt was to execute 

```bash
spin templates intall --git "https://github.com/fermyon/spin" --upgrade --branch main
```

Which will force cloning the main branch as implemented in `crates/templates/src/source.rs#L141-L147`

https://github.com/fermyon/spin/blob/089e135f7fc4e76bf67561c079cc6bfd184a9b4c/crates/templates/src/source.rs#L141-L147

So at this point, users will end up with templates from the `main` branch. Unfortunately, those pin the `spin-sdk` also to `tag = "v1.4.2"`

https://github.com/fermyon/spin/blob/089e135f7fc4e76bf67561c079cc6bfd184a9b4c/templates/http-rust/content/Cargo.toml#L19

After that I tried digging deeper to find the proper branch 😄. So I stumbled upon `llm-sdk`, however `http-rust` template of this branch pins `spin-sdk` to `tag = "v1.4.1`:

https://github.com/fermyon/spin/blob/ca520925df9dd57524041a0cecbed704341253a9/templates/http-rust/content/Cargo.toml#L19

**Comment by mikkelhegn** [comment]
This should be
```
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "canary" }
```

**Comment by kate-goldenring** [comment]
Our templates system does not currently support pointing to canary IIRC so this is not a simple install script update (unless we want to do some wild sed parsing). We could add a note to the script when the canary flag is passed that templates will need to be updated to use the canary tag.

**Comment by itowlson** [comment]
I don't understand the difference between `canary` and `main`.  If you install canary Spin, you _get_ `main`, unless you hit it in the brief window between a commit landing in main and the resulting canary being built.

I agree with pointing to main but we need to fix the automation for it to work.  Currently there is makefile (called from a GH action) that revs the SDK references in the Rust and Go template SDKs, but when looking for references to update it currently looks for a `v*` pattern:

https://github.com/fermyon/spin/blob/09de06b9fc20bda3dc24fb05918530046d0443dd/templates/Makefile#L19
https://github.com/fermyon/spin/blob/09de06b9fc20bda3dc24fb05918530046d0443dd/templates/Makefile#L8

This would need to be changed to allow replacing `main` as well.  (Which is not a blocker, just a thing to be aware of.)

**Comment by vdice** [comment]
As @itowlson mentions, we'd need to update the templates Makefile and automation for this.

Do I have the ideal world picture right?
- Templates should reference the `v*` SDK versions when the ref of Spin or Spin version is itself also `v*`, e.g.
  - `spin templates install --git https://github.com/fermyon/spin --branch v1.5.0` regardless of spin version installs templates using `v1.5.0` SDK versions
  - `spin templates install --git https://github.com/fermyon/spin` using spin version `v1.5.0` installs templates using `v1.5.0` SDK versions
- Templates should reference the `main` branch for their SDK versions when the ref of Spin is `main` or Spin version itself is a pre-release version (eg `canary` or built from `main`), e.g.
   - `spin templates install --git https://github.com/fermyon/spin --branch main` regardless of spin version installs templates using `main` SDK versions
  - `spin templates install --git https://github.com/fermyon/spin` using spin version `v1.6.0-pre0` installs templates using `main` SDK versions
  
Which seems like it would boil down to `main` SDK versions being referenced in the templates in all git refs (branches/tags) of spin unless the ref is a `v*` tag (in which case, they are pinned to `v*` SDK versions).  Does that sound right?

**Comment by itowlson** [comment]
That last sentence sounds about right, though I think you may be thinking of `spin/template/v*` refs rather than `v*` refs - that is the tag format that `spin templates install` uses to locate templates that match the Spin version.

In process terms, I believe templates on `main` should always point to the SDK at `main`, but templates at a `spin/templates/*` ref should point to a numbered SDK (and so that ref should probably be on the release branch rather than on main).
