### ISSUE TITLE
Trying out Serverless AI getting started - "Error downloading the file: spin-canary-macos-aarch64.tar.gz"

### ISSUE THREAD

**Issue by ChristianWeyer** [fermyon/spin#1745]
Hey there :-)

I am trying to download the canary on my MBP Pro with an M1 Max CPU.

I am running into this error, though:

```
(base) ➜  ~ curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash -s -- -v canary
Step 1: Downloading: https://github.com/fermyon/spin/releases/download/canary/spin-canary-macos-aarch64.tar.gz
Error downloading the file: spin-canary-macos-aarch64.tar.gz
```

Any idea what could be the issue?
Thanks!

**Comment by rylev** [comment]
Seems like GitHub has been having some issues today. I ran into the same issue you're seeing, but once I ran the script again, it worked. I suspect this is just GitHub having some load issues. Can you try to run it again and see if you see the same thing?

**Comment by ChristianWeyer** [comment]
After several tries, it worked 😌.
Thanks!
