### ISSUE TITLE
Support for multiple trigger types in a single Spin application

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1755]
This has been frequently mentioned in conversations, and also in issues (E.g., #1005), but I couldn't find an issue to track the request, so here it is.

A frequent Discord thread laid out a relevant scenario as well: https://discord.com/channels/926888690310053918/1149614859185569852

**Comment by vdice** [comment]
This is also being discussed in https://github.com/fermyon/spin/pull/1753

**Comment by carlokok** [comment]
I made a start (work in progress) on this: 
https://github.com/fermyon/spin/compare/main...carlokok:spin:feat/multiple-triggertypes

However before I continue, I would like to ask if this is an approach you'd all be oke with. (Note it's not done yet). 

Essentially, trigger_type in up/app_source.rs returns a vector, and it spawns multiple trigger commands at once.

If this is oke, I'll continue working on it and do a PR when all works & tests are updated.

**Comment by itowlson** [comment]
@carlokok Thanks heaps for taking this on!  The approach looks good to me, although there may be some nasties in the details (for example, `spin up --help`, the outbound HTTP to `self`, triggers using the same name for an option).  Many of these will be fine to defer though.

+ @lann who has thought about this issue more deeply

**Comment by carlokok** [comment]
One thing I need to fix is that HTTP and REDIS use the old "trigger" field in the .lock file, instead of triggers. Once that's up I should have a working PR.
