### ISSUE TITLE
"Bad file descriptor" issue on HTTP fallback using Spin 1.4.2

### ISSUE THREAD

**Issue by voigt** [fermyon/spin#1762]
Hi,

I'm using `v0.0.2/spin_static_fs.wasm` for static files produced by hugo. This is the `spin.toml`:

<details>
<summary>Click to toggle contents of `spin.toml`</summary>

```
spin_manifest_version = "1"
authors = ["Christoph Voigt <voigt.christoph@gmail.com>"]
description = "My Personal Website"
name = "christophvoigt-website"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "hugo"
files = [ { source = "static", destination = "/" } ]
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "HUGO_ENVIRONMENT='production' HUGO_ENV='production' hugo -s ../ -d ./spin/static/ --minify --baseURL 'https://christophvoigt.com/'"

[[component]]
id = "api"
source = "api/target/wasm32-wasi/release/api.wasm"
allowed_http_hosts = []
key_value_stores = ["default"]
[component.trigger]
route = "/api/v1/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "api"
watch = ["src/**/*.rs", "Cargo.toml"]
```
</details>

It is worth pointing out, that Hugo creates links like `/about/` while the actual content resides in `/about/index.html`. So a fallback on `index.html` is desired behavior. I noticed a different behavior in static file serving between Spin `v1.3` and `v1.4.2` (did not test intermediate versions...) using `spin up`. I assume that this default fallback is not working as expected:

### Behavior using Spin 1.3:

```
$ ./spin_1.3 up                  
Logging component stdio to ".spin/logs/"
Storing default key-value data to ".spin/sqlite_key_value.db"

Serving http://127.0.0.1:3000
Available Routes:
  hugo: http://127.0.0.1:3000 (wildcard)
  api: http://127.0.0.1:3000/api/v1 (wildcard)
Cannot find file /about/. Attempting fallback.
Attempting directory fallback /about/index.html
Cannot find file /now/. Attempting fallback.
Attempting directory fallback /now/index.html
Cannot find file /posts/. Attempting fallback.
Attempting directory fallback /posts/index.html
```

### Behavior using Spin 1.4.2:

```
$ spin up       
Logging component stdio to ".spin/logs/"
Storing default key-value data to ".spin/sqlite_key_value.db"

Serving http://127.0.0.1:3000
Available Routes:
  hugo: http://127.0.0.1:3000 (wildcard)
  api: http://127.0.0.1:3000/api/v1 (wildcard)
Cannot find file /about/. Attempting fallback.
Cannot read file: Bad file descriptor (os error 8)
Cannot find file /now/. Attempting fallback.
Cannot read file: Bad file descriptor (os error 8)
Cannot find file /posts/. Attempting fallback.
Cannot read file: Bad file descriptor (os error 8)
```

I only noticed the change in behavior as my Spin Cloud deployments got broken. I used Spin 1.3 locally for testing & deployment, but Spin Cloud probably runs on a later version... :)
You can use my repository to reproduce: https://github.com/voigt/voigt.github.io/

I talked to @calebschoepp on WasmCon about the problem, who recommended opening this issue.

* Spin version (`spin --version`)

```
$ spin --version 
spin 1.4.2 (4ae1127 2023-08-30)
```

* Installed plugin versions (`spin plugins list --installed`)
```
$ spin plugins list --installed  
cloud 0.1.2 [installed]
js2wasm 0.5.1 [installed]
py2wasm 0.3.0 [installed]
```

**Comment by voigt** [comment]
Additional info to rule out that it is a Hugo issue:

Create following files and serve them:

```
mkdir -p static/link
cat <<EOF > static/index.html
<html>
<head>
    <title>Spin Website</title>
    <body>
        <h1>Welcome to Website</h1>
        <a href="link/">Link</a>
    </body>
</html>
EOF
cat <<EOF > static/link/index.html
    <html>
        <head>
            <title>Spin Website</title>
            <body>
                <h1>Welcome to Link</h1>
            </body>
        </html>
EOF
```

Redirect to `index.html` works in Spin 1.3, but not in Spin 1.4.2.

**Comment by mikkelhegn** [comment]
Just a quick confirmation that you are using fileserver 0.2 in both case? There was a change to this logic in fileserver 0.3: https://github.com/fermyon/spin-fileserver/compare/v0.0.2...v0.0.3

**Comment by voigt** [comment]
Fileserver 0.3 works indeed - so I think we found the issue!

Remains a usability issue: How can we notify users about the availability of a new fileserver version and/or incompatibilities with the existing version?

Spin add > "static-fileserver" still adds version 0.2 to spin.toml 😅

However, the issue of this ticket is resolved for me, Thank you @mikkelhegn!

**Comment by radu-matei** [comment]
@voigt I think updating your templates should bump the version of the file server used:

https://github.com/fermyon/spin/blob/09de06b9fc20bda3dc24fb05918530046d0443dd/templates/static-fileserver/metadata/snippets/component.txt#L2

**Comment by mikkelhegn** [comment]
[The template in `main` is updated](https://github.com/fermyon/spin/blob/main/templates/static-fileserver/metadata/snippets/component.txt), so you would need to run `spin templates upgrade` to get the newest templates locally https://developer.fermyon.com/spin/managing-templates#upgrading-templates.

If you use the Homebrew installer or the install script, both will upgrade the default packaged templates.

**Comment by voigt** [comment]
I used the installer script from `spin/README.md`, which didn't update the file-server template. Coincidentally, I still have my terminal buffer available... :D

![CleanShot 2023-09-13 at 11 02 10](https://github.com/fermyon/spin/assets/2982698/f735bb7d-b93d-44de-bde2-4c56b7f9402e)

I fear `spin templates upgrade` didn't work as (I) expected either 🙈

![CleanShot 2023-09-13 at 11 06 11](https://github.com/fermyon/spin/assets/2982698/59c62911-7a60-41dc-8b53-eef93798e09f)

Explicitly selecting `https://github.com/fermyon/spin`:
![CleanShot 2023-09-13 at 11 15 43](https://github.com/fermyon/spin/assets/2982698/afd22044-8619-4a8f-80b7-af208794cd94)

I suspect it is related to my specific setup and will investigate further. My initial issue is resolved, so we can close this thread!

**Comment by mikkelhegn** [comment]
Thx for sharing! @kate-goldenring @itowlson - just wanted your awareness of the above.

**Comment by kate-goldenring** [comment]
This is unexpected that a `spin templates upgrade` would not update the templates to pull in the ones for the current spin version (which has the latest [`0.0.3` static fileserver](https://github.com/fermyon/spin/blob/v1.4.2/templates/static-fileserver/content/spin.toml#L9)).

**Comment by itowlson** [comment]
@kate-goldenring the update to 0.0.3 was post-1.4 and it looks like the `spin/templates/v1.4` tag has not moved on since 1.4.0.  I think 1.4.2 did not rev the templates because there were no SDK changes.  In retrospect we should probably have done it anyway.

**Comment by kate-goldenring** [comment]
@itowlson i see. So the `spin templates upgrade` command is working as expected. Is it worth retroactively updating `spin/templates/v1.4`

**Comment by itowlson** [comment]
We probably should, even though 1.5 is already cut, just so that the 1.4 line gets left in a good place.

**Comment by itowlson** [comment]
@kate-goldenring I have bumped the `spin/templates/v1.4` tag, possibly even correctly

**Comment by itowlson** [comment]
Closing as @voigt has a solution and we believe the new tag includes the 0.0.3 fileserver; please reopen if required.
