### ISSUE TITLE
Allow plugin settings in the manifest

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1768]
A user is working on a `spin clean` plugin.  The files to delete on a clean may be language and application specific (e.g. in Rust the `target` directory, in JS the `dist` directory, etc.).  Noted troublemaker @mikkelhegn suggested the info could be stored in `spin.toml` as e.g. `component.clean`.  But this would make the Spin loader reject the file because we deny unknown fields when deserialising.

We could simply allow unknown fields.  This would be a simple change.  However it would create the risk that a plugin author uses a field called `foo` and later we, all unawares, use `foo` for an "official" field.  It would also impact our ability to provide validation / intellisense / a schema because if someone wrote `biuld` then we could not be sure it was a typo.

A safer change would be to allow unknown fields in dedicated sections (e.g. `[component.build.extra_info]`) or in a distinctive format (`x:clean`), though this makes the native/plugin distinction in-your-face.

Options:

1. Stick with denying unknown fields. Plugin authors must use parallel config files, and if users have to maintain two files then so be it.
2. Allow unknown fields because the risk of a clash is relatively small and schema validation is never going to be perfect anyway.
3. Allow unknown fields subject to some limitation or restriction.  What might that look like?  Would it be friendly to users who have to author the `spin.toml` file?
4. Something else?

**Comment by fibonacci1729** [comment]
I'm definitely weary of option 2. I think this is the most risky decision. 

I'm not strongly opposed to the idea of a `component.tool.clean` where `tool` is effectively like `package.metadata` in `Cargo.toml`. Generically we reserve `tool` (or whatever) and allow customizations under this section.

So I guess some combination of 1 & 3 where the value of `tool` is a simple untyped toml value.

**Comment by itowlson** [comment]
@fibonacci1729 And similarly at the top level I guess, in case a plugin wants to associate app-level info, e.g.

```
spin_manifest_version = "1"
# etc.

[tool.frobnicate]
reticulate_splines = false

[[component]]
id = "foo"
[tool.clean]
files = [...]
```

I like this.  We'd need to define at what levels the extra section would be allowed (e.g. could you have a `component.build.tool.clean`) but it feels like we should be able to make it not too obtrusive - depending on TOML syntax restrictions anyway.

**Comment by fibonacci1729** [comment]
I'm definitely weary of option 2. I think this is the most risky decision. 

I'm not strongly opposed to the idea of a `component.tool.clean` where `tool` is effectively like `package.metadata` in `Cargo.toml`. Generically we reserve `tool` (or whatever) and allow customizations under this section.

So I guess some combination of 1 & 3 where the value of `tool` is a simple untyped toml value.

**Comment by itowlson** [comment]
Another question about this: suppose we do as proposed and have a `tool` map at various levels.  Should this be propagated into the `LockedApp`?  My first guess was not but:

1. if a plugin uses the loader rather than the schema then it will get a `LockedApp` not a "manifest"
2. it's possible people will write plugins that work on OCI images

Thoughts?

**Comment by fibonacci1729** [comment]
I would also assume that tool-specific settings would not make it into the `LockedApp` however i share your concerns about plugins that operate on OCI images. Is there a precedence for plugins that can only operate on the `LockedApp`?

**Comment by itowlson** [comment]
I don't know of any today (apart from custom triggers, which use the standard trigger sections for their settings).  I can imagine plugins that want to work with registry apps, but I'm struggling for scenarios where those would require settings that travel _with_ the app rather than being selected when the plugin runs.

**Comment by fibonacci1729** [comment]
To me, these `tool` settings seem to be the developer side of things like what `runtime-config` is to runtimes. It seems counter-intuitive that these would end up in a distributed artefact given that they are really settings per developer. But am definitely in the same boat as you thinking-wise, i don't feel great about entirely eliminating that possibility without great justification. Maybe we can make the assumption that these don't get propagated to the LockedApp for now and revisit when there is a compelling use-case? What do you think?

**Comment by itowlson** [comment]
I think that's okay.  Adding them to the LockedApp in a future release would be a non-breaking change.  I'll go ahead on this basis.  Thanks!
