### ISSUE TITLE
Update info message to contain clickable link

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#177]
When running `spin up`, there is an info message with the address of the application:

```
Serving HTTP on address 127.0.0.1:3000
```

It would be really helpful if that was clickable in modern terminal renderers.

**Comment by lann** [comment]
This original issue appears to be fixed, fwiw:

```
Serving HTTP on address http://127.0.0.1:3000
```

**Comment by radu-matei** [comment]
Closing in favor of #385, as the original issue has been fixed.
