### ISSUE TITLE
Canary install error: no cloud.json available

### ISSUE THREAD

**Issue by jasonwashburn** [fermyon/spin#1771]
While following the new AI tutorial (https://developer.fermyon.com/spin/serverless-ai-tutorial), when installing the canary version of spin using `curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash -s -- -v canary`  I get the following error near the end of the install:

```
Step 5: Install default plugins
Plugin information updated successfully
Plugin 'js2wasm' is already installed with version 0.6.0post.1694638055.
Plugin 'py2wasm' is already installed with version 0.3.0post.1693957212.
Error: failed to connect to endpoint https://github.com/fermyon/cloud-plugin/releases/download/canary/cloud.json: HTTP status client error (404 Not Found) for url (https://github.com/fermyon/cloud-plugin/releases/download/canary/cloud.json)
```

When looking at the release page it does appear the most of the rest of the releases have a cloud.json artifact, however canary does not.

**Comment by vdice** [comment]
Thanks for reporting @jasonwashburn and sorry for the failed install.

Oddly, the last CI run for the `canary` release of the cloud plugin was green, but as you've pointed out, the `cloud.json` asset was missing -- and I'm perplexed as to why.  I kicked off another run and it is now attached, so you should be good to re-install when convenient.  This has also alerted us to a window of exposure with how the cloud plugin release workflow runs, which I'll look into today, so thanks again for your trouble here!

**Comment by jasonwashburn** [comment]
> Thanks for reporting @jasonwashburn and sorry for the failed install.
> 
> Oddly, the last CI run for the `canary` release of the cloud plugin was green, but as you've pointed out, the `cloud.json` asset was missing -- and I'm perplexed as to why. I kicked off another run and it is now attached, so you should be good to re-install when convenient. This has also alerted us to a window of exposure with how the cloud plugin release workflow runs, which I'll look into today, so thanks again for your trouble here!

No worries, the install actually completed "enough" that I was able to work through the tutorial successfully, just wanted to report it so it didn't go unnoticed. Appreciate the work you guys are doing!

**Comment by vdice** [comment]
Thanks again for notifying!  Closing as resolved for now.
