### ISSUE TITLE
Spin watch needs to restart, if watch configuration is changed

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1817]
If I have `spin watch` running and does a change to the watch configuration in `spin.toml`. Watch does it's thing (build and up), but the change to the watch configuration is not being picked up. Only if I stop the watch command, and restart it, will this happen.

It would be great if that was not the case.

**Comment by itowlson** [comment]
I have great news for you https://github.com/fermyon/spin/pull/1784

**Comment by mikkelhegn** [comment]
Love it when issues start to be fixed before being raised 😆
