### ISSUE TITLE
Issue Running Spin in Containerd: Runtime "io.containerd.spin.v1" Not Found

### ISSUE THREAD

**Issue by FerrazArthur** [fermyon/spin#1818]
Hello,

I am relatively new to Wasi/Wasm development and have encountered an issue while attempting to run Spin in a container using Containerd. I followed a tutorial that didn't use Kubernetes, and I'd like to avoid it as well.

Here's my Dockerfile:
```
FROM scratch

COPY ./spin.toml /

COPY ./echo/target/echo.wasm /echo/target/echo.wasm

COPY ./hello/hello.wasm /hello/hello.wasm

CMD ["/"]
```

I successfully built the container with the following command:

`docker buildx build --platform wasi/wasm32 --provenance=false -t <my registry> .`

However, when I tried to run it with this command:

`docker run -dp 3000:3000 --name=wasm-example --runtime=io.containerd.spin.v1 --platform=wasi/wasm32 <my registry>`

I encountered the following error:
```
docker: Error response from daemon: failed to create task for container: failed to start shim: failed to resolve runtime path: runtime "io.containerd.spin.v1" binary not installed "containerd-shim-spin-v1": file does not exist: unknown.
```

I've ensured that I have the latest version of Containerd installed, and my /etc/docker/daemon.json configuration is as follows:

```
{
  "features": {
    "buildkit": true,
    "containerd-snapshotter": true
  }
}
```
When I run `ps -aux | grep containerd-shim`, I get the following result:

`graphic+   51157  0.0  0.0   9236  2304 pts/0    S+   11:04   0:00 grep --color=auto containerd-shim`

I believe I need to install the Spin shim on my machine so that Docker can use it.

Versions:

    Spin Version: 1.5.0 (ca08dd9 2023-09-13)
        Cloud 0.2.0 [installed]
        js2wasm 0.6.0 [installed]
        py2wasm 0.3.0 [installed]

    Containerd Version: ctr containerd.io 1.6.24

    Docker Version: Docker version 24.0.6, build ed223bc

    System: Architecture x86_64, Linux Mint Vanessa (Ubuntu Jammy)

I've discovered that Docker CLI currently lacks native support for the Wasi shim, which is available only in Docker Desktop. Unfortunately, I'm unable to use Docker Desktop due to hardware limitations related to KVM support. I'm still actively exploring alternative methods to use the Spin shim with Containerd without relying on Docker. Ideally, I'm hoping for a solution that involves having a 'containerd-shim-spin-v1' binary located under '/usr/bin.

I've had some success with installing the 'containerd-shim-wasmedge-v1' binary using [runwasi](https://github.com/containerd/runwasi), and I wish to achieve a similar result with Spin.

Any assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by Christof23** [comment]
This worked for me from another github repo issues:

To get it working I disabled both features and restarted docker desktop.

After this I enabled containerd and clicked 'Apply & Restart' and then I enabled wasm.

**Comment by itowlson** [comment]
Also, depending on the version of Docker Desktop you may need to drop back to Spin 1.3 or 1.4 (and matching Spin SDK references).  I am not sure which containerd shim versions Docker Desktop uses, but only shim v0.9 supports Spin 1.5, and that was released only recently.  Let us know if you need more info on this.

**Comment by FerrazArthur** [comment]
I've discovered that Docker CLI currently lacks native support for the Wasi shim, which is available only in Docker Desktop. Unfortunately, I'm unable to use Docker Desktop due to hardware limitations related to KVM support. I'm still actively exploring alternative methods to use the Spin shim with Containerd without relying on Docker.

**Comment by FerrazArthur** [comment]
I found the binaries i needed in the repo [deislabs containerd wasm shims](https://github.com/deislabs/containerd-wasm-shims)

**Comment by itowlson** [comment]
Great to hear @FerrazArthur - thanks for letting us know!  Is it okay to close this issue, or are there questions or problems outstanding from it?

**Comment by FerrazArthur** [comment]
> Great to hear @FerrazArthur - thanks for letting us know! Is it okay to close this issue, or are there questions or problems outstanding from it?

No more questions, thanks!
