### ISSUE TITLE
Vanity domain for the Go SDK?

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#182]
The Go SDK is defined as pointing to GitHub (to a non-existing repository ...):

https://github.com/fermyon/spin/blob/3204836441233ef0b62325dae331e9ead9284fdb/sdk/go/go.mod#L1

So importing it currently looks like:

`import "github.com/fermyon/spin-sdk/http"`

Do we want to have a vanity domain early on, to avoid breaking the import?
We could use something like `fermyon.dev/...`.

**Comment by itowlson** [comment]
Is this still something we want to pursue?

**Comment by radu-matei** [comment]
This is still on my list of "nice to have", but I don't see an actual need, other than, well, "vanity".

I think it's safe to close for now; we can reopen if it becomes a need in the future.

Thanks!
