### ISSUE TITLE
Component model support

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1839]

**Comment by tschneidereit** [comment]
I guess we can go ahead and close this, or is there something you meant by this and that we're still missing, @itowlson?

**Comment by itowlson** [comment]
This is not a me issue I was just the one who transferred it from the Spin 2 project board.

You are a better judge than me of whether this is complete.  I have a boatload of questions but I am guessing they are documentation/understanding rather than any lack of "support."

**Comment by tschneidereit** [comment]
Ah, that makes sense, thank you! And yeah, we certainly have a lot of things to work through, but we should track those in a more specific way, so I'll go ahead and close this.
