### ISSUE TITLE
Use resources in Spin world interfaces

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1841]
Instead of using pseudo resources like we currently do (e.g., modeling a kv store as a `u32`) we can switch to using wit resources. This should have minimal impact on how the code looks, but will make maintenance much easier.

**Comment by rylev** [comment]
Here are the subtasks I think we need to do to complete this:
* [ ] Move pseudo resource usage (i.e., sqlite and kv) over to real resources
* [ ] Add resources to other interfaces that currently leak their resources (psql, mysql, redis)
* [ ] Create an adapter module for Spin 1.0 worlds to this new world
* [ ] Move all language SDKs over to this new world
