### ISSUE TITLE
Summarise runtime config at startup

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1852]
Via @mikkelhegn, broken out from #1850:

>  I still think at least an acknowledgement of what runtime config was loaded would be great. ...
>
> `Using [llm_remote] and [key_value_store.remore_redis] runtime-config from /mikkels/fancy/setup.toml`
>
> That level of detail I think would be a good balance.

(Ivan again) Printing the file name is particular attractive if the runtime config is coming from an environment variable where it's not visible on the command line.

**Comment by mikkelhegn** [comment]
Thx @itowlson
