### ISSUE TITLE
Add ability to load OCI with pre-fetch artifacts

### ISSUE THREAD

**Issue by jsturtevant** [fermyon/spin#1858]
### Background

This issue in runwasi https://github.com/containerd/runwasi/issues/108 and the approach outlined in https://docs.google.com/document/d/11shgC3l6gplBjWF1VJCWvN_9do51otscAm0hBDGSSAc.  Also the changes proposed in https://github.com/fermyon/spin/issues/1857

### Proposed changes
In kubernetes based environment, the OCI artifacts might be already pre-pulled but the OCI client requires pulling them:

https://github.com/fermyon/spin/blob/362c75d98e3ac2cb1b760b661fbcb18f0eced118/crates/oci/src/loader.rs#L25-L29

It would be nice to have a function similiar to `let app = spin_loader::from_file(PathBuf::from("/spin.toml"), Some(working_dir.clone())).await.context("unable to find app file")?;`

but for `spin.json` that OCI artifacts use.

I've prototyped this working with this [change](https://github.com/fermyon/spin/compare/main...jsturtevant:spin:spin-oci) used in https://github.com/deislabs/containerd-wasm-shims/pull/164. But there might be better ways to approach it.

**Comment by vdice** [comment]
Thanks for creating this @jsturtevant; it shouldn't be a problem to refactor as suggested and provide an additional method for loading an OCI-based Spin app from an already-fetched config (no pull involved).

**Comment by itowlson** [comment]
@jsturtevant Looking at your diff I can't imagine any reason we'd do it differently (though I might suggest naming the new function something like `load_pulled_app` or `load_from_cache`) - would you like to send a PR, or would you rather we implemented it?
