### ISSUE TITLE
templates: redirect support for 'spin new'

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#1860]
The [redirect template](https://github.com/fermyon/spin/tree/main/templates/redirect) doesn't currently support use with `spin new`:

```
$ spin new redirect redirect
Template redirect doesn't support the 'new application' operation
```

There've been cases of [pure redirect apps](https://github.com/fermyon/spin/blob/main/docs/spin.toml), so perhaps we consider adding support?

**Comment by itowlson** [comment]
I think my thinking was that if you didn't have any components yet then there was nothing to redirect _to_.  You're right that there could be redirects to external URLs though; and although it's unlikely that anyone is going to start a Spin app from scratch _just_ to do redirects, there's probably no reason to actually _forbid_ this usage.

**Comment by itowlson** [comment]
The current template has a pattern for `redirect-to` which is a local HTTP route (begins with `/`), not a full URL.  If we want to a meaningful `spin new` then we need to remove this constraint.  Are we okay with that?

**Comment by vdice** [comment]
> The current template has a pattern for redirect-to which is a local HTTP route (begins with /), not a full URL. If we want to a meaningful spin new then we need to remove this constraint. Are we okay with that?

sgtm 👍
