### ISSUE TITLE
C++ SDK?

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#190]
ref #78 

Do we want to have a dedicated C++ SDK?

**Comment by benatkin** [comment]
I'd like an example of making an HTTP request or a connection to a DB - if an SDK is needed then that would be reason to add one.

I think it should be possible to add middleware to restrict what network services it's allowed to connect to.

**Comment by radu-matei** [comment]
That is correct, @benatkin — we would need to use the generated bindings to make an HTTP request or connect to a database.

The example added in https://github.com/fermyon/spin/pull/433/files should be a reasonable starting point if you are interested in expanding and making an SDK with a cleaner API — happy to help here!
