### ISSUE TITLE
Rust SDK v2: `Response::new` vs `new_with_headers`

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1915]
`spin_sdk::http::Response::new()` provides the flexibility to use, for example, a string as the response body.  This is a massive convenience bonus.

However, if I also want to return headers, `new_with_headers` only accepts an `Option<Vec<u8>>` for the body (https://github.com/fermyon/spin/blob/7daedf563e4fa831c038cef4b1478d668262086e/sdk/rust/src/http.rs#L81).  Could we extend `new_with_headers` to also accept an `IntoBody`?

**Comment by itowlson** [comment]
Also could we allow it to accept non-owned strings, or maybe add a builder?  Or is it recommended to keep using `http::Response` for the header case (it's now simpler which is neat!):

```
    let r2 = http::Response::builder()
        .status(200)
        .header("content-type", "text/plain")
        .body("Hello, Fermyon")?;  // No Some! No into()! Hurrah!
    Ok(r2)
```

**Comment by rylev** [comment]
Yes! [I already have that change in #1901](https://github.com/fermyon/spin/pull/1901/files#diff-0e091f5591f31945a05594cf2bdf7cfaddc5ebe01e8dcabd565f37a374c497bbR54-R64), so hopefully we can land that today. Otherwise, I can open a smaller PR with that change.
