### ISSUE TITLE
redis-trigger: Ony last component gets redis pub message

### ISSUE THREAD

**Issue by seungjin** [fermyon/spin#1920]
I've noticed that if I have two components listening to the same channel, only the later one receives published messages, while the first one doesn't receive any.

This is my spin.toml.
```
spin_manifest_version = "1"
authors = ["Seungjin Kim>"]
description = "foo"
name = "foo"
trigger = { type = "redis", address = "redis://foo.com:19539" }
version = "0.1.0"

[[component]]
id = "one"
source = "one/target/wasm32-wasi/release/one.wasm"
allowed_http_hosts = []
[component.trigger]
channel = "test"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "one"
watch = ["src/**/*.rs", "Cargo.toml"]

[[component]]
id = "two"
source = "two/target/wasm32-wasi/release/two.wasm"
allowed_http_hosts = []
[component.trigger]
channel = "test"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "two"
watch = ["src/**/*.rs", "Cargo.toml"]
```
The spin.toml file is set up very simply, and each component includes code at the example level, with both having identical code. However, when my Redis publishes a message, only 'component two' receives the message, while 'component one' receives nothing

**Comment by vdice** [comment]
Thanks for creating this issue @seungjin.  The redis trigger implementation indeed currently operates on a 1:1 channel:component mapping, so we're seeing the behavior of the last one winning in this example (or whenever there are more than one components subscribing to the same channel).  I'll add this to the backlog with the action item of updating the trigger to support 1:N channel:component mappings.
