### ISSUE TITLE
stress test

### ISSUE THREAD

**Issue by inaxium** [fermyon/spin#1926]
I am conducting some stress tests on the side and I'm encountering the following error message:

2023-10-23T14:22:22.852730Z ERROR hyper::server::tcp: accept error: Too many open files (os error 24)

Caused by:
    Too many open files (os error 24)
2023-10-23T14:11:23.585507Z ERROR spin_trigger_http: Error processing request: Failed to open log file ".spin/logs/phone-post_stdout.txt"

What's the best way to address this issue?

**Comment by lann** [comment]
Hello, could you run `ulimit -n` in the same environment that you're running spin? This will inherently limit how many client connections you can have open, though we are certainly making that worse by opening extra log files for each request.

**Comment by inaxium** [comment]
ulimit -n <= 1024

I'm not entirely sure about what Spin actually does. My understanding is that when a REST call to the nanoservice is made, a new WebAssembly (WASM) instance is launched, and with each new instance, a new log file is created.

In this case, it's apparent that thousands of new log files are being generated, and they are all overwriting each other.

**Comment by lann** [comment]
The log files are opened in "append" mode, so they shouldn't be overwriting each other, though I suppose you could see some odd interleaving of writes under high request concurrency. The limit here is on open file "descriptors", which would include each request's handle to the underlying log file.

> ulimit -n <= 1024

This is a very low limit for a load test environment. For reference my workstation's default limit is >500000.

**Comment by inaxium** [comment]
Alright, that's great! You can go ahead and close this issue now.
