### ISSUE TITLE
Auth header to a POST request

### ISSUE THREAD

**Issue by inaxium** [fermyon/spin#1928]
How do I add an Auth header to a POST request (spinhttp.Post or whatever)?

My workaround is throwing a compiler error.

req, err := http.NewRequest("POST", url, bytes.NewBuffer(requestBody))
if err != nil {
	fmt.Println("Request error:", err)
	return
}

req.Header.Add("Authorization", "Bearer YOUR_JWT_TOKEN")
req.Header.Set("Content-Type", "application/json")

client := spinhttp.NewClient()

resp, err := client.Do(req)
if err != nil {
	fmt.Println("Request error:", err)
	return
}

**Comment by itowlson** [comment]
Could you share the compiler error please?

**Comment by radu-matei** [comment]
With the following source code:

```go
package main

import (
	"bytes"
	"fmt"
	"io"
	"net/http"

	spinhttp "github.com/fermyon/spin/sdk/go/http"
)

func init() {
	spinhttp.Handle(func(w http.ResponseWriter, r *http.Request) {
		url := "https://echo.free.beeceptor.com"
		req, err := http.NewRequest("POST", url, bytes.NewBuffer([]byte{}))
		if err != nil {
			fmt.Println("Request error:", err)
			return
		}

		req.Header.Add("Authorization", "Bearer YOUR_JWT_TOKEN")
		req.Header.Set("Content-Type", "application/json")

		client := spinhttp.NewClient()

		resp, err := client.Do(req)
		if err != nil {
			fmt.Println("Request error:", err)
			return
		}
		defer resp.Body.Close()

		b, err := io.ReadAll(resp.Body)
		fmt.Fprintln(w, b)
	})
}

func main() {}
```

I am getting the following error:

```
$ tinygo version
tinygo version 0.30.0 darwin/amd64 (using go version go1.21.0 and LLVM version 16.0.1)

$ spin build
Building component http-go with `tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go`


tinygo:wasm-ld: error: /var/folders/mw/rhg2039n0ds69k0kv4yp9g9h0000gn/T/tinygo1899557397/main.o: undefined symbol: crypto/internal/bigmod.addMulVVW1024
tinygo:wasm-ld: error: /var/folders/mw/rhg2039n0ds69k0kv4yp9g9h0000gn/T/tinygo1899557397/main.o: undefined symbol: crypto/internal/bigmod.addMulVVW1024
tinygo:wasm-ld: error: /var/folders/mw/rhg2039n0ds69k0kv4yp9g9h0000gn/T/tinygo1899557397/main.o: undefined symbol: crypto/internal/bigmod.addMulVVW1536
tinygo:wasm-ld: error: /var/folders/mw/rhg2039n0ds69k0kv4yp9g9h0000gn/T/tinygo1899557397/main.o: undefined symbol: crypto/internal/bigmod.addMulVVW1536
tinygo:wasm-ld: error: /var/folders/mw/rhg2039n0ds69k0kv4yp9g9h0000gn/T/tinygo1899557397/main.o: undefined symbol: crypto/internal/bigmod.addMulVVW2048
tinygo:wasm-ld: error: /var/folders/mw/rhg2039n0ds69k0kv4yp9g9h0000gn/T/tinygo1899557397/main.o: undefined symbol: crypto/internal/bigmod.addMulVVW2048
failed to run tool: wasm-ld
error: failed to link /var/folders/mw/rhg2039n0ds69k0kv4yp9g9h0000gn/T/tinygo1899557397/main: exit status 1
Error: Build command for component http-go failed with status Exited(1)
```

**Comment by inaxium** [comment]
tinygo:wasm-ld: error: /tmp/tinygo1984569072/main.o: undefined symbol: crypto/internal/bigmod.addMulVVW1024

This is the only error you get when there is a compiler error. It's always the same.

**Comment by inaxium** [comment]
But It's look like the chain  just calls at the end

http.NewRequest("POST", url, body)

// Post creates a POST HTTP request and returns the HTTP response.
// The destination of the request must be explicitly allowed in the Spin application
// configuration, otherwise the request will not be sent.
func Post(url string, contentType string, body io.Reader) (*http.Response, error) {
	return post(url, contentType, body)
}

// outbound_internals.go
func post(url string, contentType string, body io.Reader) (*http.Response, error) {
	req, err := http.NewRequest("POST", url, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)

	return send(req)
}

**Comment by lann** [comment]
I don't think we have tested against tinygo 0.30. @radu-matei's test program above compiles for me with tinygo 0.28.1.

**Comment by inaxium** [comment]
tinygo version 0.30.0 linux/amd64 (using go version go1.21.3 and LLVM version 16.0.1)

**Comment by itowlson** [comment]
A colleague says there is a known issue with TinyGo 0.30 (https://github.com/tinygo-org/tinygo/issues/3919#issue-1904545651) and it can be worked around by adding `-tags=purego` to the `build` command in `spin.toml`.  Could you give that a try and let us know if it works for you?  Thanks!

**Comment by radu-matei** [comment]
The full build command:

```toml
command = "tinygo build -target=wasi -gc=leaking -no-debug -tags=purego -o main.wasm main.go"
```

**Comment by lann** [comment]
I am also able to fix this by using go 1.20, e.g. `export GOROOT=/path/to/go1.20`

**Comment by inaxium** [comment]
This works but the compilation time was very long

**Comment by inaxium** [comment]
But the authentication works and the data was written to the database.

**Comment by rajatjindal** [comment]
Hi @inaxium 

Thank you for confirming that workaround works for you.

Just to clarify a bit, the difference in wasm size, that you shared, is due to just adding "tags=purego" to build command or does it also include some other changes?

Thanks

**Comment by inaxium** [comment]
Include changes when I remove them the size is Normal.

Nevertheless, it would be nice if you could optionally pass parameters such as a token.

```
type Payload struct {
	Url         string
	ContentType string
	Body        io.Reader
	JwtToken    string
}

Post(Payload{Url: url, ContentType: "application/json", Body: requestBody, JwtToken: "jwtToken"})
Post(Payload{Url: url, ContentType: "application/json", Body: requestBody})
```

**Comment by inaxium** [comment]
So it's up to you to close this issue. :)

**Comment by lann** [comment]
The extra size comes from referencing `http.Client`. You can avoid this by passing the request to `spinhttp.Send(req)`. This uses the same low-level function as `http.Client` but skips some of its internal code so it may not behave exactly the same.

Actually, it looks like by avoiding `http.Client` you also avoid the original compilation problem here.

**Comment by inaxium** [comment]
Yes. That works.

470175 Oct 23 22:38 phone-post.wasm*

```
// ArangoDB

requestBody := bytes.NewBuffer([]byte(jsonData))

req, err := http.NewRequest("POST", url, requestBody)
if err != nil {
  http.Error(w, err.Error(), http.StatusBadRequest)
  return
}

req.Header.Add("Authorization", fmt.Sprintf("Bearer %s", jwtToken))
req.Header.Set("Content-Type", "application/json")

_, err = spinhttp.Send(req)
if err != nil {
  http.Error(w, err.Error(), http.StatusBadRequest)
  return
}

//---------------------------------------------------------------------
```

**Comment by rajatjindal** [comment]
Awesome, thank you for confirming that. I am going to close the issue now.

Thanks again
