### ISSUE TITLE
HeaderValues in the Rust SDK are not Strings anymore

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1929]
In Canary (as of Oct 24th), the header values returned by the Rust SDK are `Vec<u8>` instead of `String`.

According to @tschneidereit it's because:

> Header values can contain arbitrary values and don't need to be valid unicode strings. Hence, wasi-http encodes them as Vec<u8> instead of String.
> We should probably handle this the same [way](https://docs.rs/http/latest/http/header/struct.HeaderValue.html) the http crate does.

**Comment by lann** [comment]
I believe #1939 addresses this as well as possible for now.
