### ISSUE TITLE
Validate HTTP `base` to be absoluate

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1943]
If I accidentally enter a base without the leading slash:

```
# v1
trigger = { type = "http", base = "boop" }

# v2
[application.trigger.http]
base = "boop"
```

then `spin up` appears to succeed, but it prints a route of `http://127.0.0.1:3000boop`, and `localhost:3000/boop` 404s.

(`spin deploy` also prints a badly concatenated URL, but Fermyon Cloud handles it like a champ regardless.)

**Comment by lann** [comment]
Ah I think I removed the validation because the trigger didn't actually require it, but I didn't think of the ~~children~~ UI.

**Comment by itowlson** [comment]
If it's just the UI I can fix it there.  But I can't actually figure out where it's serving it!

I can implicitly prepend a `/` to the base if that would be preferable - that would remove the need for the user to do it and fix it throughout.

**Comment by lann** [comment]
Ah I read your comment too quickly and missed the part where its failing; will investigate.
