### ISSUE TITLE
`spin up --help` does not print trigger options unless all Wasm files exist

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1957]
Create a new Spin app:

```
spin new emptyish -t http-rust
cd emptyish
```

DO NOT BUILD IT.

Now run `spin up --help`.  It prints the `up` options but not the trigger options section (not even the generic trigger options).

Now do `spin build` and run `spin up --help` again.  It now _does_ print the trigger options.

I think this is because the manifest load operation now fully materialises the app, which fails if a component `source` doesn't resolve (in this case, because the file hasn't been built).

It would be good to be able to see help regardless of build status - the Wasm files are not needed in order to to know what options are available.  (Although yes, this sort of multiple competing needs load pipeline is how the v1 loader got into the mess it did, so care is needed!)

It seems like this also happens if the manifest has no components in it (e.g. `http-empty` template), though I'm not sure I'm reproducing this consistently - first time I tried this seemed to give me the generic trigger options as I expected, now it gives me no trigger options at all.  So maybe it's not just missing Wasm files causing this - I've not dug into it yet.

Thanks to @tpmccallum for spotting the missing options!

**Comment by lann** [comment]
Hmm yeah we should be able to shuffle things around a bit in `up.rs` to pull the trigger type out before loading.
