### ISSUE TITLE
Add TinyGo to devcontainer

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#198]
The dev container should have TinyGo configured (and ideally a few other language toolchains for Wasm).

**Comment by 0xcodeboi** [comment]
Hi Radu. I can add TinyGo to the container, any other specific language toolchains to include in a first-pass?

I'm referring to the [WebAssembly Language Support Matrix](https://www.fermyon.com/wasm-languages/webassembly-language-support) page and I suppose any language that checks all three boxes are good candidates.

One concern is making the container too large. I understand it's not a production deployment target, but the trade-off for convenience is increasing the first-build time for new users. Is it possible/desirable to split up containers by language toolchain?

**Comment by 0xcodeboi** [comment]
Sounds good to me! I'll open a PR in the coming days :-)
