### ISSUE TITLE
Bug: spin watch broken for nested files

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#1981]
Using spin canary (built from main as of https://github.com/fermyon/spin/commit/47e40b9b38950c55355db575cd1b7ac681292621), I'm seeing behavior where `spin watch` doesn't trigger a rebuild upon changes to nested files.

Any app with a nested file entry in the `watch` config should repro, eg `watch = ["src/**/*.rs", "Cargo.toml"]` as seen in the [http-rust example](https://github.com/fermyon/spin/tree/main/examples/http-rust).  When running this example, a re-build is triggered when the `Cargo.toml` file is amended but not triggered when `src/lib.rs` is amended.

**Comment by lann** [comment]
I had assumed this was due to my manifest refactoring but I couldn't dig up anything relevant. Possibly due to #1784 though that merged Oct 2. @itowlson @calebschoepp

**Comment by itowlson** [comment]
I'm pretty sure it worked at #1784 but will give it a try for sure - thanks!

**Comment by itowlson** [comment]
#1784 works so either something broke in the merge, or it's happened since.  IT'S BISECTIN' TIME

**Comment by itowlson** [comment]
OH LANN YOU ARE GOING TO LOVE THIS ONE

**Comment by lann** [comment]
I DO NOT LOVE IT
