### ISSUE TITLE
I/O error with outbound HTTP and streaming responses

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1985]
Maybe this is user error but I can't figure it out, sorry.

I have a server which streams a response over a period of 2 seconds:

```rust
// UPSTREAM SERVER
use futures::SinkExt;
use spin_sdk::http::{Fields, IncomingRequest, OutgoingResponse, ResponseOutparam};
use spin_sdk::http_component;

#[http_component]
async fn handle_stmtest(_req: IncomingRequest, response_out: ResponseOutparam) {
    let response = OutgoingResponse::new(
        200,
        &Fields::new(&[("content-type".to_string(), b"text/plain".to_vec())]),
    );
    let mut body = response.take_body();

    response_out.set(response);

    for i in 1..20 {
        let payload = format!("Hello {i}\n");
        if let Err(e) = body.send(payload.into()).await {
            eprintln!("Error sending payload: {e:#}");
            return;
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
    }
}
```

When I curl this, it works fine; I see "Hello 1" to "Hello 19" returned over a short period.

Now I try to use it from a Spin client, essentially proxying it as it streams:

```rust
// PSEUDO-PROXY
use futures::{TryStreamExt, SinkExt};
use http::Request;
use spin_sdk::http::{IncomingRequest, ResponseOutparam, OutgoingResponse, Headers, IncomingResponse, send};
use spin_sdk::http_component;

#[http_component]
async fn handle_httpouttest(_req: IncomingRequest, response_out: ResponseOutparam) {
    let outbound_req = Request::get("http://localhost:7071").body(()).unwrap();  // running it here

    // Wire up the downstream response sink
    let response = OutgoingResponse::new(200, &Headers::new(&[]));
    let mut sink = response.take_body();
    response_out.set(response);

    // Send the request to upstream, and stream the response body
    let out_response: IncomingResponse = send(outbound_req).await.unwrap();
    let mut rbody = out_response.into_body_stream();

    // Every time data is available from upstream, send it downstream
    loop {
        let Ok(maybe_chunk) = rbody.try_next().await else {
            return;
        };
        if let Some(chunk) = maybe_chunk {
            sink.send(" *** CHUNK INCOMING *** ".into()).await.unwrap();
            sink.send(chunk).await.unwrap();
        } else {
            println!("nowt");
            std::thread::sleep(std::time::Duration::from_millis(200));
        }
    }
}
```

The body processing here is is based on https://github.com/fermyon/spin/blob/8d9a77151179c47b618b9192763132339646e764/examples/wasi-http-rust-streaming-outgoing-body/src/lib.rs#L111, although it's not returning a Result so the error handling is a bit different.

When I curl this:

* curl prints ` *** CHUNK INCOMING *** Hello 1` then nothing more, but does not exit
* the pseudo-proxy prints "nowt" every 200ms - `try_next` keeps succeeding but returning None
* the upstream server prints `Error sending payload: Error::ProtocolError("I/O error: StreamError::LastOperationFailed(Error { handle: Resource { handle: 0 } })")`.  (This happens on the i=2 case.)

I expected the upstream service to keep sending lines, as it did with curl.  I'm not sure where the problem lies or how to diagnose it.

Spin and the Rust SDK are both at current `main` (commit 8d9a7715117).

**Comment by dicej** [comment]
I believe this is due to https://github.com/bytecodealliance/wasmtime/issues/7413 and can be worked around using https://github.com/fermyon/spin/pull/1991 and making sure the `IncomingResponse` lives at least as long as the body stream.

**Comment by vdice** [comment]
@dicej the upstream PR is merged; will we inherit the fix when we bump wasmtime?  Would we keep the approach added in #1991 or revise/remove once the upstream logic lands?

**Comment by dicej** [comment]
Yes, we'll get the fix once we bump wasmtime to a release that includes that fix.  The workaround in #1991 won't be necessary anymore, so we can update the example to not do it anymore, but it also doesn't hurt to leave it in.

**Comment by itowlson** [comment]
@dicej Sounds like this should be okay to close?  I've been able to do bidirectional streaming as part of the service chaining work so...

**Comment by dicej** [comment]
Yes, should be all fixed now.
