### ISSUE TITLE
Environment Provider (Dokumentation)

### ISSUE THREAD

**Issue by inaxium** [fermyon/spin#1986]
Hello,

In the following documentation:

[Environment Provider](https://developer.fermyon.com/spin/v1/dynamic-configuration#environment-variable-provider)

It should be mentioned that the Environment Provider works out of the box, and the following configuration must be done as follows:

```
[variables]
arango_auth_url = { required = true }
arango_url = { required = true }

[component.config]
arango_auth_url = "{{ arango_auth_url }}"
arango_url = "{{ arango_url }}"

Export the following environment variables:

export SPIN_CONFIG_ARANGO_AUTH_URL="4711"
export SPIN_CONFIG_ARANGO_URL="4712"
```

Optional

```
authUrl, err := spinconfig.Get("arango_auth_url")
if err != nil {
	fmt.Println(err)
}

url, err := spinconfig.Get("arango_url")
if err != nil {
	fmt.Println(err)
}

fmt.Println(authUrl)
fmt.Println(url)
```

Issue can be closed.

**Comment by tpmccallum** [comment]
Thanks @inaxium 
I will create see that this gets into the developer documentation.
Just out of curiosity can you please let me know your version of spin via the spin --version command.
Thanks
Tim

**Comment by inaxium** [comment]
`spin 1.5.1 (8d4334e 2023-09-26)`

**Comment by tpmccallum** [comment]
New issue created at the Developer Documentation Home repo
https://github.com/fermyon/developer/issues/980

This one can be closed if there are no objections.

**Comment by vdice** [comment]
Thanks again for the suggestion @inaxium.  Since we have https://github.com/fermyon/developer/issues/980 to track this, I'll close this issue.
