### ISSUE TITLE
Error message for 'non-allowed host' is incorrect

### ISSUE THREAD

**Issue by adamreese** [fermyon/spin#2044]
```
Warning: A component tried to make a HTTP request to non-allowed host 'localhost'.
To allow requests, add 'allowed_http_hosts = ["localhost"]' to the manifest component section.
Cannot send HTTP request: Destination not allowed: http://localhost:8000
```

It should be 
```
To allow requests, add 'allowed_http_hosts = ["http:localhost:8000"]' to the manifest component section.
```

**Comment by rylev** [comment]
The suggested fix doesn't look correct to me for two reasons:
* Schemes are not really a part of `allowed_http_hosts` (though they are technically permitted) so the more correct suggestion is `allowed_http_hosts = ["localhost:8000"]`
* We really want users to move away from `allowed_http_hosts` in favor of `allowed_outbound_hosts` so perhaps the even more correct solution is to suggest `allowed_outbound_hosts = ["http://localhost:8000"]` (note that scheme is required in `allowed_outbound_hosts`).

**Comment by itowlson** [comment]
@adamreese are you still working on this?  I'm thinking I might tag it `good-first-issue` if it's gone quiet

**Comment by vdice** [comment]
Encountered this today as well; would be nice to get this papercut fixed, noting @rylev's comments in https://github.com/fermyon/spin/issues/2044#issuecomment-1794141078
