### ISSUE TITLE
spin new: trouble with name using number

### ISSUE THREAD

**Issue by franxois** [fermyon/spin#2052]
My first chosen names using cli `spin new` were wrong without warnings :

`2023-11-spin` => `spin build` raised an error : 
```
Building component 2023-11-spin with `cargo build --target wasm32-wasi --release`
error: failed to parse manifest at `/Users/francois/Documents/dev/github/franxois/2023-11-spin/Cargo.toml`

Caused by:
  the name `2023-11-spin` cannot be used as a package name, the name cannot start with a digit
Error: Build command for component 2023-11-spin failed with status Exited(101) 
```

`spin-2023-11` => `spin build` ok but not `spin up`

```
Error: TOML parse error at line 11, column 13
   |
11 | component = "spin-2023-11"
   |             ^^^^^^^^^^^^^^
data did not match any variant of untagged enum ComponentSpec
``` 

If I use `spin new -t http-rust 2023-11-spin` I have an error "Name must start with a letter" => OK
If I use `spin new -t http-rust spin-2023-11` no warning but error with `spin up`
If I use `spin new -t http-rust spin_2023_11` no warning but error with `spin up`
If I use `spin new -t http-rust spin-2` no warning but error with `spin up`

BTW, `spin-spin`, `spin2` or `spin_spin` are ok

* Spin version (`spin --version`)
`spin 2.0.0 (e4bb235 2023-11-03)`
* Installed plugin versions (`spin plugins list --installed`)
```
cloud 0.5.1 [installed]
js2wasm 0.6.1 [installed]
py2wasm 0.3.2 [installed]
```

**Comment by lann** [comment]
Thanks for the report! The actual constraint is in starting a "word" with a digit, but the error reporting is bad: fermyon/spin#1950

**Comment by lann** [comment]
See also https://github.com/fermyon/spin/issues/2051 for improving early validation.
