### ISSUE TITLE
Installing plugins from remote URL requires `git`

### ISSUE THREAD

**Issue by karthik2804** [fermyon/spin#2054]
Installing plugins using a remote URL requires `git`. Reported by user on discord 

```bash
$ spin plugin install -y --url https://github.com/fermyon/platform-plugin/releases/download/canary/platform.json
Error: failed to connect to endpoint https://github.com/fermyon/spin-plugins/: Error cloning Git repo https://github.com/fermyon/spin-plugi
ns/: `git` command not found - is git installed?
```

ref: https://discord.com/channels/926888690310053918/1170433556955271339/1170447199130353665

**Comment by itowlson** [comment]
I have no repro for this.  What I did:

1. Start a bare Docker image with my local Spin build mounted and outbound networking enabled:

```bash
$ docker run -it --network host -v ~/github/spin/target/debug:/spin ubuntu /bin/bash
```

2. Install CA certificates (required for HTTPS-ing to the JSON URL):

```bash
$ apt-get update
$ apt-get install ca-certificates
```

3. Confirm that `git` is not present:

```bash
$ git
bash: git: command not found
```

4. Run the `spin plugin install` command:

```bash
$ /spin/spin plugin install -y --url https://github.com/fermyon/platform-plugin/releases/download/canary/platform.json
Warning: You're using a pre-release version of Spin (2.1.0-pre0). This plugin might not be compatible (supported: >=1.3). Continuing anyway.
Plugin 'platform' was installed successfully!

Description:
        Commands for publishing applications to the Fermyon self-hosted Platform.

Homepage:
        https://github.com/fermyon/platform-plugin
```

I think we are going to need some more info about the system and environment to track this down.

**Comment by itowlson** [comment]
Putting the dreaded `stale` label on this one, with a view to closing if we don't get a repro or more info.
