### ISSUE TITLE
Common component test suite

### ISSUE THREAD

**Issue by rylev** [fermyon/spin#2057]
Part of https://github.com/fermyon/spin/issues/2055

Testing the Spin runtime involves running through the following code paths:

* CLI arg parsing
* Manifest parsing
* Component instantiation
* Trigger set up (e.g., in the case of http triggers, setting up the http server)
* Individual trigger handling (e.g., in the case of http triggets, handling an incoming http request and invoking the correct component)

Having to run through all of these steps to test individual functionality means we'll be retesting large swaths of indentical functionality over and over again making testing much slower than it needs to be. 

At the core of reducing this duplication is the need for creating a common suite of test components that can be reused by multiple tests without the need for rebuilding each time. 

## Different approaches 

As specified in https://github.com/fermyon/spin/issues/2055, we want to be able to run against some sort of suite of pre-built components. However, there are many ways we could do this each with their own pros and cons. I'd like to outline them here for discussion:

### Full Spin components built with the SDK

This is closest to what we currently have. We create Spin components using the SDK. The only difference to the current approach is that when running tests, we would not build these components but instead use the pre-built WebAssembly binaries.

**Pros**:
* Easy to move to since it's very close to what we're currently doing.
* Easy to write - the SDKs exist to make writing Spin apps easier and so being able to use them will make writing tests easier

**Cons**:
* Conflates SDK and runtime testing - if the SDK changes, we might either want to change the tests or keep around code that uses old SDK versions (which might be confusing). This is all despite that we're not really testing the SDKs at all. 
* Repeats testing of handling code - since all Spin components need an exported handler, each test would have to repeat boiler plate of handler code. 

### Full Spin components built without the SDK

This is similar to the above just with the components not being written using the SDK. 

**Pros**
* Similar to the SDK approach and has some of its pros
* Does not conflate SDK testing with runtime testing

**Cons**:
* Harder to write than components built with an SDK

### Partial Spin components

This approach would require building components that are not fully compliant Spin components as they don't handler exports. This would only test a single imported interface (e.g., only testing SQLite).

**Pros**:
* Avoids repeatedly testing handler exports

**Cons**:
* Makes running tests much more difficult as these components cannot be tested against "off-the-shelf" Spin compliant runtimes. 

## Proposal

The following is my proposal for how we handle runtime testing:

* The test collection is composed of full Spin compliant components that can be used in their pre-built form by test suites for testing Spin compliant runtimes.
* These components will be built without the use of an SDK.
    * While this will make writing tests a bit harder, it hopefully won't be too much harder.
* These components *do not* include Spin.toml configuration. 
    * These components can be re-used by multiple tests with different configuration as a way to test how configuration changes impact Spin components. 
    * This also means that new configuration options do not need to create entirely new test components but can instead use existing ones that are combined with new configuration. 
* Each component always exports an http handler that behaves in the following way: the request is always expected to be a `GET /` with no headers and no body and the handler returns either a `200` with no headers and no body **or** a `500` with no headers and a body containing the error text. 
     * Testing of exported handlers will be done separately. 
* Each testing harness will need to know how to combine the pre-built binaries with relevant configuration to create actual tests.

**Comment by lann** [comment]
If we are "committing" to our WIT interfaces as supported public APIs then I agree we should probably have non-SDK tests. If we aren't then it doesn't seem worth the extra effort.

**Comment by rylev** [comment]
After merging #2062, we now have a growing test component suite. Closing this as it's no longer actionable.
