### ISSUE TITLE
[Feature request] `spin template info` that shows my installed template info.

### ISSUE THREAD

**Issue by seungjin** [fermyon/spin#2060]
I currently have two different name but the same template 'sqli-cli` and `spin-sqlite-explorer`.

+---------------------------------------------------------------------------+
| Name                   Description                                        |
+===========================================================================+
| spin-sqlite-explorer   A component to provide a web shell for sqlite      |
| sqlite-cli             A component to provide a web shell for sqlite      |
| static-fileserver      Serves static files from an asset directory        |
+---------------------------------------------------------------------------+
 
If I can see its original git repo I installed and its version number, that will be very helpful to remove/organize my spin templates. 

something like `spin template info spin-sqlite-explorer`

**Comment by itowlson** [comment]
Does `spin templates list --verbose` meet your needs?  There isn't really a "version number" concept but it does show the repo.

**Comment by seungjin** [comment]
Aha!  yep. `--verbose` is what I was looking for. 
Then please ignore this feature request. Anyone please close this.
