### ISSUE TITLE
There is no reference documentation for the SDKs

### ISSUE THREAD

**Issue by thesteve0** [fermyon/spin#2064]
This is a web site/doc issue across all the SDKs. I am at the tutorial at KubeCon23 and I can't find any links on the website to pydoc or js doc to describe the Spin specific methods. For example, the Response object in Python. How do I know what methods is has and parameters or responses are available for those methods. 

This is must have for me to work with your SDKs. While the examples and getting started are fine, I am stuck after that. For example, with the Response object above, how do I specify a sub-path or parameters in the URL?

**Comment by itowlson** [comment]
Thanks for flagging this.  We have these for [Rust](https://fermyon.github.io/rust-docs/spin/main/spin_sdk/index.html) and [Go](https://pkg.go.dev/github.com/fermyon/spin/sdk/go/v2) but should make those links more prominent and visible; but you're right that we need this for JavaScript and Python too.  I'll raise issues for the JS and Python SDKs, and take a look at making the Rust and Go reference docs more discoverable.  Thanks for the feedback!

**Comment by agardnerIT** [comment]
I also discovered Spin at Kubecon. I'm attempting to rewrite [tracepusher](https://agardnerit.github.io/tracepusher) in WASM and potentially host-as-a-service on Fermion cloud. Basically trying to do the equivalent of this (`requests` module) and I need to know what parameters `Request` takes:

```
resp = requests.post(
    f"{endpoint}/v1/traces", 
    headers={ "Content-Type": "application/json" }, 
    json=trace,
    timeout=5 
 )
    # print(resp)
```

**Comment by itowlson** [comment]
@karthik2804 @dicej What would it take to get these docs created from the SDKs?  (See per-repo issues linked above.)

In the meantime @agardnerIT I believe `Request` takes:

* method (as string)
* URL (as string)
* headers (as dictionary)
* body (as bytes or None)

(see https://developer.fermyon.com/spin/v2/http-outbound and https://github.com/fermyon/spin-python-sdk/blob/main/examples/outbound_http/app.py)

@dicej please correct me if I've missed anything

**Comment by dicej** [comment]
Yeah, we definitely ought to add docs to both `spin-js-sdk` and `spin-python-sdk`.  The Python SDK API is currently defined entirely in Rust via PyO3 (e.g. https://github.com/fermyon/spin-python-sdk/blob/cf2dd8c9a92bea6496cbe441b12b9fb61863ef8e/crates/spin-python-engine/src/lib.rs#L40-L70).

Apparently all we need to do to add Python-visible docs to those types and functions is add Rust doc comments, which PyO3 will make available as docstrings at runtime (https://pyo3.rs/v0.20.0/module.html?highlight=docstr#documentation).  What I'm not sure of (not being a Python dev myself), is whether that will be usable by IDEs and/or e.g. [pdoc](https://pdoc3.github.io/pdoc/).  Worst case, we can write some .py files by hand which mirror the API defined in Rust.

Regarding `spin-js-sdk`, @karthik2804 is the expert there, given that most of the API is defined in JS/TS files which he wrote, and he's more familiar with JS documentation best practices than I am.

BTW, we're planning to deprecate both `spin-python-sdk` and `spin-js-sdk` in favor of `componentize-py` and `componentize-js` (each paired with an updated Spin SDK tailored to those tools) in the future, so although I do think we should continue to support the former with docs etc., we'll want to shift our focus over to the latter around the time WASI Preview 2 ships.

**Comment by itowlson** [comment]
When we say "we", can we pin that down to individuals who can take responsibility for:

1. Writing the docs.  I am happy to blast out some words if folks show me where they need to go and what they need to look like.
2. Publishing the docs (deploying the docs web site or whatever).  @karthik2804 would you be able to take this on for JS at least?

**Comment by karthik2804** [comment]
@itowlson - yes I can it should be a straightforward step to enable gh pages for the repo. I can make a small PR to get started with the docs on the JS repo.

**Comment by itowlson** [comment]
Awesome, thank you @karthik2804 and feel free to rope me in if I can be useful!

**Comment by dicej** [comment]
I spent a bit of time looking into our options on the Python side, and I think the path of least resistance is to write a set of .py files which mirror the API defined in the Rust code.  It might be annoying to keep them in sync, but they only need to last until we switch over to `componentize-py`, at which point the SDK will be some mix of code generated from WIT and hand-written wrapper code.

I'll get started on the docs and see about publishing them via a GitHub action.

**Comment by itowlson** [comment]
Fantastic, thanks @dicej!

**Comment by itowlson** [comment]
JavaScript docs: https://fermyon.github.io/spin-js-sdk/

**Comment by vkuznet** [comment]
+1

**Comment by dicej** [comment]
Python docs: https://fermyon.github.io/spin-python-sdk/

**Comment by karthik2804** [comment]
@itowlson can this be closed now?

**Comment by itowlson** [comment]
I believe this has been addressed.  As future work it would be good to get things into standard docs sites, but that is better to align with the `componentize-*` iterations of the SDKs.

Original posters, please reopen if you feel the request has not been met!
