### ISSUE TITLE
Switch to semicolon-ful WIT

### ISSUE THREAD

**Issue by lann** [fermyon/spin#2070]
https://github.com/WebAssembly/component-model/issues/142
https://github.com/bytecodealliance/wasm-tools/issues/1205#issuecomment-1766947307

> The default will be switched to require semicolons in early November for wasmtime 15, and the support for not requiring semicolons will be removed in december (wasmtime 16)

**Comment by karthik2804** [comment]
I think this [PR](https://github.com/fermyon/spin/pull/2108) resolves this?
