### ISSUE TITLE
Relax the .cache requirement for `spin_loader::from_file`

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#2072]
Hi there,

I was upgrading the spin shim from spin 1.x to 2.0.0 and found that the `spin_loader::from_file` function requires the work directory to either have `$HOME/.cache` or `XDG_CACHE_HOME` for Linux environment due to the usage of `dirs::cache_dir()`. I want to relex this requirement or at least provide a configuration to specify the cache directory in the API. 

See this discussion: https://github.com/deislabs/containerd-wasm-shims/pull/177#discussion_r1385691274

Thanks!

**Comment by lann** [comment]
Replied inline: https://github.com/deislabs/containerd-wasm-shims/pull/177#discussion_r1388210225
