### ISSUE TITLE
sdk/rust: does not build with `cargo --no-default-features`

### ISSUE THREAD

**Issue by psarna** [fermyon/spin#2079]
* Spin version (`spin --version`)
2.0
* Installed plugin versions (`spin plugins list --installed`)
not applicable

Hi folks, I used to have a dependency on spin-sdk set without default features to avoid exporting duplicate symbols, and now it stopped compiling. The reason is that there's an implicit dependency on `hyperium` in the code, even without default features. The code compiles again when I add the `http` feature, `cargo build --no-default-features -F http`, but it's a regression nonetheless (:

**Comment by lann** [comment]
I think the problem may be this unnecessary (?) dependency in the macro crate: https://github.com/fermyon/spin/blob/3fbff440a53fb45a8d8df25d763f9141c65af614/sdk/rust/macro/Cargo.toml#L13


@rylev Could you confirm?

**Comment by lann** [comment]
Actually on closer inspection the SDK does have a hard dependency on the `http` crate; I just didn't see that it had been renamed `hyperium` there.
