### ISSUE TITLE
HTTP types are currently blocking and non-streaming

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#21]
#14 adds common types between the outbound HTTP interface and the HTTP trigger.
However, those types do not contain streams, and are currently blocking, both due to limitations in the bindings generator.

This issue tracks updating them to use streams and asynchronous functions once they are implemented upstream.

**Comment by ofw5rz** [comment]
> #14 adds common types between the outbound HTTP interface and the HTTP trigger.
> 
> However, those types do not contain streams, and are currently blocking, both due to limitations in the bindings generator.
> 
> 
> 
- [ ] - > This issue tracks updated them to use streams and asynchronous functions once they are implemented upstream.

@

**Comment by rylev** [comment]
This was implemented in #1877
