### ISSUE TITLE
Arm support for spin ?

### ISSUE THREAD

**Issue by theagilecoder** [fermyon/spin#2102]
Is arm32 arm64 supported by spin ? Trying to deploy on raspberry pi.

**Comment by vdice** [comment]
Hi @theagilecoder, Spin does produce arm64 binaries for Linux and Mac.  They are attached to the GH release eg https://github.com/fermyon/spin/releases/tag/v2.0.1.  Spin can also be installed via the other methods mentioned at https://developer.fermyon.com/spin/install.
