### ISSUE TITLE
Improve experience if it takes a while to download a "remote" component on `spin up`

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#2109]
I was on an airplane, and I decided to run a Spin app using the fileserver, with a reference to Github in spin.toml. Now that took a while, as the bits of the fileserver was chasing the airplane across the Atlantic (I'm not sure they ever caught up). In those weird cases, it would be great if at `spin up` a note is fed back to the use, that Spin is currently busy downloading that remote component, so that it's easy to understand what we'er waiting for.

**Comment by UtkarshUmre** [comment]
Hello @itowlson, I'm new here and interested in contributing! Could you please assign me this issue? It looks like a great first task for me

**Comment by itowlson** [comment]
@UtkarshUmre Done - thanks for your enthusiasm!

**Comment by Archisman-Mridha** [comment]
Hi @itowlson, I am new to open-sourcing and this is my first time contributing to Fermyon Spin. I have created a pull request which solves this issue. Please let me know if I need to make any further changes or it's ready to be merged 😊.

**Comment by itowlson** [comment]
@Archisman-Mridha Thanks!  One thing to watch out for is if someone is already assigned - this can save folks from tripping over each others' toes - it might be worth checking in with @UtkarshUmre whether they are already working on this!
