### ISSUE TITLE
Rust SDK: `Request::uri()` behaves differently in Spin and Cloud

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#2110]
I had a program that ran fine locally but gave Internal Server Error in Cloud.  I traced this to doing a `url::Url::parse(&req.uri())`, but the same code was working fine locally.

I tried a minimal repro:

```
use spin_sdk::http::{IntoResponse, Request};
use spin_sdk::http_component;

#[http_component]
fn handle_uritest(req: Request) -> anyhow::Result<impl IntoResponse> {
    let u = req.uri().to_owned();
    Ok(http::Response::builder()
        .status(200)
        .header("content-type", "text/plain")
        .body(u)?)
}
```

I ran this locally and deployed it to the cloud, then curled it.

```
$ curl localhost:3000
http://localhost:3000/

$ curl https://uritest-2x8rltg2.fermyon.app/
/
```

The `uri()` function should behave the same way across platforms.

**Comment by itowlson** [comment]
(The behaviour is the same with IncomingRequest by the way.)

**Comment by itowlson** [comment]
I can work around it using the `spin-full-url` header, but if that's the portable way of getting the URL, then maybe we should back the SDK `url()` method onto it?  `url()` is too darned seductive...!

**Comment by rylev** [comment]
The SDK [sets the URI directly from the `IncomingRequest`](https://github.com/fermyon/spin/blob/18095c1616aaa9ef16d03736ebc6e4937b7808a1/sdk/rust/src/http/conversions.rs#L67) so it would seem that this is a difference between how Spin and Cloud set the `IncomingRequest` uri. I think the expectation is that the `IncomingRequest` would be the same across Spin and Cloud so I think we should close this issue and open an issue in Cloud.
