### ISSUE TITLE
HTTP component sources do not work on Windows

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#2112]
I ran into this while trying to repro #2111.  The static-fileserver template uses a HTTP reference to the fileserver Wasm.  On Windows, `spin up` fails because it is unable to persist the downloaded Wasm file.  The error is "failed to persist temporary file path: The parameter is incorrect. (os error 87)" and the location is `loader/src/http.rs` line 41, `temp_path.persist_noclobber`.

My guess is that Windows dislikes the colon in file names such as `C:\Users\ivan\AppData\Local\spin\registry\wasm\sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f` but I haven't confirmed that.

**Comment by david-wallace-croft** [comment]
I am seeing this as well.

**Comment by itowlson** [comment]
@david-wallace-croft Sorry for not replying earlier. I think once we fix this and #2111 that _should_ sort out the deploy problem. I'm afraid that for now the only workaround for deployment may be to use WSL2, which I appreciate is rather disruptive. I am hoping to look at these this week.

**Comment by david-wallace-croft** [comment]
@itowlson I am able to deploy for the Advent of Spin 2023 submissions by using GitHub CodeSpaces.  I made some notes about my setup here:
https://github.com/david-wallace-croft/advent-of-spin

**Comment by itowlson** [comment]
Oh, I'm relieved to hear that!  And thanks for sharing your setup!
