### ISSUE TITLE
Creating a new spin app with go prints error message export comment has wrong name

### ISSUE THREAD

**Issue by thomasdarimont** [fermyon/spin#2115]
When I create a new go-example app and try to run the app via `go build`
I see the "error" message: `export comment has wrong name "spin_http_handle_http_request", want "handle_http_request"`

Steps to reproduce:
```
./spin new 
Pick a template to start your application with: http-go (HTTP request handler using (Tiny)Go)
Enter a name for your new application: my-spin-go
Description: Go demo app
HTTP path: /hello

...

cd my-spin-go

$ go build
go: downloading github.com/fermyon/spin/sdk/go/v2 v2.0.1
go: downloading github.com/julienschmidt/httprouter v1.3.0
# github.com/fermyon/spin/sdk/go/v2/http
/home/tom/go/pkg/mod/github.com/fermyon/spin/sdk/go/v2@v2.0.1/http/internals.go:16:1: export comment has wrong name "spin_http_handle_http_request", want "handle_http_request"
```

[Application Prerequisites](https://developer.fermyon.com/spin/build#setting-up-for-spin-build)
[Troubleshooting - Rust](https://developer.fermyon.com/spin/rust-components#troubleshooting)
[Cloud FAQ](https://developer.fermyon.com/cloud/faq)

If you still see a bug or problem, please let us know:

* Spin version: spin 2.0.1 (1d72f1c 2023-11-10)
* Installed plugin versions:
```
$ spin plugins list --installed
check-for-update 0.1.0 [installed]
cloud 0.5.1 [installed]
cloud-gpu 0.1.0 [installed]
js2wasm 0.6.1 [installed]
py2wasm 0.3.2 [installed]
```

**Comment by itowlson** [comment]
cc @adamreese

**Comment by adamreese** [comment]
You'll want to use TinyGo rather than Go. Go won't compile it correctly. 
Side note: I think you found a bug in Go because that isn't a comment.

**Comment by adamreese** [comment]
Forgot to mention that you can build using `spin build` and it will execute the correct command.
