### ISSUE TITLE
add example of how to use spin registry push in CLI help text

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#2128]
Example:
```
spin registry push michellenoorali/spin-hello-world:0.1.0
```

It took me a while to figure out what reference should be. An example in the CLI help text would have made things a little clearer.

**Comment by ogghead** [comment]
This should now be addressed by https://github.com/fermyon/spin/pull/2135 😄

**Comment by michelleN** [comment]
Thank you @ogghead !
