### ISSUE TITLE
Outbound Redis test failures in CI

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#2139]
Some Redis outbound tests, although succeeding on first merge, are now failing in CI.  In most cases the message is:

> thread 'runtime_tests::outbound_redis' panicked at 'failed to bootstrap runtime tests tests: `spin up` did not start server or error after 5 seconds.

E.g. https://github.com/fermyon/spin/actions/runs/7091158151/job/19300335277

In one case, we have also seen:

> thread 'runtime_tests::outbound_redis' panicked at 'Test '/e2e-tests/tests/runtime-tests/tests/outbound-redis' errored: outbound_redis#(outbound-redis/src/lib.rs:98) `[RedisResult::Binary([98, 97, 122]), RedisResult::Binary([98, 97, 114])]` did not match `&
[redis :: RedisResult :: Binary(ref bar), redis :: RedisResult ::
Binary(ref baz)] if bar == b"bar" && baz == b"baz"`', tests/runtime-tests/src/lib.rs:133:13

https://github.com/fermyon/spin/actions/runs/7091280422/job/19301340642

**Comment by rylev** [comment]
Ah the order of the results is not deterministic which would explain why it sometimes passes and sometimes not. I'll push a fix.
