### ISSUE TITLE
Add integration test for running the Spin docs website

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#215]
There should be an integration test for running the docs website from `docs`.
This would ensure a non-trivial application actually works.

**Comment by vdice** [comment]
Although the majority Spin's docs have migrated to https://github.com/fermyon/developer, I'm assuming the emphasis here was more on testing Spin itself in CI.  Technically the docs website is still a fully-functioning Spin app, if only with many redirects.  Adding to the backlog.

**Comment by radu-matei** [comment]
The docs website has moved and has its own infrastructure.
