### ISSUE TITLE
CI: static binary builds failing

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#2167]
The static Spin build jobs are failing.  This blocks the release workflow (for canary and v* releases)

eg https://github.com/fermyon/spin/actions/runs/7199803814

**Comment by vdice** [comment]
I'm not sure what provoked the errors earlier today.  They weren't seen during the latest canary release run: https://github.com/fermyon/spin/actions/runs/7202437676

Maybe @rajatjindal can take a peek.

**Comment by rajatjindal** [comment]
thanks for fixing the release tag issue @vdice. I will keep an eye on canary release to ensure it works (or debug more if that happens again).

**Comment by vdice** [comment]
(Removing from milestone as blocker since it hasn't been occurring in recent runs.)
