### ISSUE TITLE
CI: e2e/runtime_tests failure(s)

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#2168]
The e2e-tests job has failed recently.  Another case of non-deterministic behavior?

```
thread 'runtime_tests::outbound_redis_no_permission' panicked at 'Test failed trying to connect to http server: Spin exited early with status code Some(1)', tests/runtime-tests/src/lib.rs:83:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'runtime_tests::outbound_redis' panicked at 'Test '/e2e-tests/tests/runtime-tests/tests/outbound-redis' errored: outbound_redis#(outbound-redis/src/lib.rs:107) `[[98, 97, 114]]` did not match `& [b"bar", b"baz",]`', tests/runtime-tests/src/lib.rs:133:13
```

from https://github.com/fermyon/spin/actions/runs/7198112510/job/19607513202

**Comment by rylev** [comment]
Looks like this might be some sort of race condition. When [I re-ran the job](https://github.com/fermyon/spin/actions/runs/7198112510), the tests pass. We should keep an eye out for this.

**Comment by vdice** [comment]
I usually seem to trigger long-dormant failures once I close issues like this -- but it has been awhile since we've seen such errors, so going to take my chances 😄
