### ISSUE TITLE
Integration with Hippo

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#22]
https://github.com/deislabs/hippo-cli is the command line interface for interacting with a Hippo instance.

To simplify the user experience, it would be gerat if there was a Hippo plugin for Spin which would allow the Spin CLI to interact with a Hippo instance.

**Comment by itowlson** [comment]
This issue is marked as P0 but is 8 months old.  Is it still current?  Is the feature being discussed now covered by `spin deploy`?

**Comment by michelleN** [comment]
I believe so. I'm in favor of closing it.
