### ISSUE TITLE
Cannot create a template with a component and variables

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/spin#2205]
## Problem
I cannot create a template that contains a component that requires variables. Specifically, I am trying to update the KV explorer to use the config store for user/pass credentials, which requires adding variables to the template: https://github.com/fermyon/spin-kv-explorer/pull/27.

This shows up in the Spin tests if you update update the  [add-variables test template](https://github.com/fermyon/spin/blob/main/crates/templates/tests/templates/add-variables/metadata/spin-template.toml) as [done here](https://github.com/fermyon/spin/compare/main...kate-goldenring:test-add-component-with-variables) to include a component that requires the variables added via `variables.txt`. If you then run the [`manager::tests::can_add_variables_from_template` test](https://github.com/fermyon/spin/blob/f324fb208119a6694abbc4c1ac3499438976faad/crates/templates/src/manager.rs#L953), it errors with 

```
thread 'manager::tests::can_add_variables_from_template' panicked at 'called `Result::unwrap()` on an `Err` value: liquid: Unknown variable
  with:
    requested variable=secret
', crates/templates/src/manager.rs:1017:50
```

It seems we may need to expand upon variables support in templates (added here https://github.com/fermyon/spin/pull/1864) to consider the case when a component is being added. 

## Solution
I tried updating the `renderer` and `writer` to process "variables" first but was not successful.

**Comment by itowlson** [comment]
In your sample, this happens because in the line

```
kv_credentials = "{{ secret }}"
```

the template system sees `{{ secret }}` as a reference to a _template_ variable.  Double braces need to be escaped.  From initial tests,

```
{% raw %}kv_credentials = "{{ secret }}"{% endraw %}
```

at least doesn't error; I will update the unit test to verify it produces the right result.  I should also update the docs to tell people how to do this!
