### ISSUE TITLE
HTTP component macro should allow annotating multiple functions

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#222]
Building a Rust component that handles multiple routes can be done today by matching on the incoming path (`PATH_INFO`, to be more exact, which contains the path without the component route and application base path).

It would be really helpful if the Rust macro allowed writing something like this:

```rust
#[http_component(route = "/hello")
fn hello(req: Request) -> Result<Response> { ... }

#[http_component(route = "/goodbye")
fn goodbye(req: Request) -> Result<Response> { ... }
```

This would be internally handled by the Rust SDK, and not a general Spin feature.
Other language SDKs _could_ add something similar if they have language support for it.

Note that continuing to check the request path would still be an option for Rust components as well.

cc @fibonacci1729

**Comment by radu-matei** [comment]
ref https://github.com/fermyon/spin/issues/532#issue-1259820077

ref https://github.com/fermyon/spin/issues/532#issuecomment-1146856450

**Comment by radu-matei** [comment]
I have been reconsidering this over the last few weeks, and I think a reasonable experience would be something similar to:

```
#[http_component]
fn api(req: Request) -> Result<Response> {
    match <PATH> {
        "/todos" => todos(req),
        "/todos/:id" => todo(req, id),
        "/abc/:id/def/:id2 => abc(req, id, id2)
        _ => todo!(),
    }
}

fn todo(req: Request, id: u32) -> Result<Response>{}
fn abc(req: Request, id1: u32, id2: u32) -> Result<Response>{}
```

Expanding on this, a single function marked as the entry point, and the ability to easily extract path segments into parameters that can be passed to functions that would handle those requests.

**Comment by FrankYang0529** [comment]
> ```
> #[http_component]
> fn api(req: Request) -> Result<Response> {
>     match <PATH> {
>         "/todos" => todos(req),
>         "/todos/:id" => todo(req, id),
>         "/abc/:id/def/:id2 => abc(req, id, id2)
>         _ => todo!(),
>     }
> }
> 
> fn todo(req: Request, id: u32) -> Result<Response>{}
> fn abc(req: Request, id1: u32, id2: u32) -> Result<Response>{}
> ```

Probably, it's good to put HTTP method together. Like `match (<METHOD>, <PATH>) {}`. I am curious how we get HTTP method and path information in the current implementation? Thank you.

**Comment by radu-matei** [comment]
Oh having the HTTP methods as well to match against would be great!

@fibonacci1729 had a few ideas in the past — but the change here is that we would be ok with having _a single_ function annotated with `http_component`, which I hope should simplify the implementation.

**Comment by vdice** [comment]
@fibonacci1729 I don't suppose this is still in progress?  I see you are currently assigned here.  Feel free to move to another column for the project board as you see fit.

**Comment by fibonacci1729** [comment]
Thanks @vdice. This needs some design consideration that we aren't currently investing at the time. I think it's safe to table this for now.

**Comment by dipankardas011** [comment]
waiting for this addition

**Comment by fibonacci1729** [comment]
Hi @dipankardas011 !  We've implemented a router (as described earlier in this thread) to address in the interim. You can find an example here https://github.com/fermyon/spin/tree/main/examples%2Fhttp-rust-router

Let us know if this approach doesn't address your use case!

**Comment by dipankardas011** [comment]
> Hi @dipankardas011 ! We've implemented a router (as described earlier in this thread) to address in the interim. You can find an example here https://github.com/fermyon/spin/tree/main/examples%2Fhttp-rust-router
> 
> Let us know if this approach doesn't address your use case!

Thanks

**Comment by vdice** [comment]
Checking in: Is the component macro approach as mentioned in the OP still something we'd like to explore, now that the router mentioned above is in place?

**Comment by itowlson** [comment]
Given that in 8 months nobody has responded to the last comment with "yes we should still be looking into this," I am closing this.  As ever, reopen if you feel strongly!
