### ISSUE TITLE
`spin registry push` adding OCI metadata

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#2259]
#2236 added optional support for pushing metadata in the OCI artifact (thank you, @rgl!)

Should we consider automatically adding the Spin application description, authors (other metadata) in the manifest?

**Comment by vdice** [comment]
This seems like a good issue to track automatically generating and adding annotations to the OCI manifest.  Recently discussed in https://github.com/fermyon/spin/issues/2612#issuecomment-2204029049.

@radu-matei do you envision using the [pre-defined annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) for such auto-generated metadata?  Or do you have ideas on alternate (or additional) keys?
