### ISSUE TITLE
Need to specify the need to install targets in Quickstart

### ISSUE THREAD

**Issue by jdbohrman** [fermyon/spin#227]
We need to make sure users understand the need to install the `wasm32-wasi` and `wasm-unknown-unknown` targets:

```
 rustup target add wasm32-wasi
```

```
rustup target add wasm32-unknown-unknown
```

**Comment by digitalsanctum** [comment]
Related to this I found I needed `rustup target add wasm32-wasi` before I could install on Linux but it's missing from the Quickstart guide.
