### ISSUE TITLE
Having a flag to prevent .gitignore files from being created

### ISSUE THREAD

**Issue by thesuhas** [fermyon/spin#2280]
I think it would be really useful if there could be a flag to `spin new` or `spin add` to prevent it from creating `.gitignore` files. This is especially useful while developing micro services as every time you add a service (in this case a component) by using `spin add`, it creates a new `.gitignore` file for each, making deleting them manually a pain.

This could be something like `--vcs none` in `cargo new` (but just limited to the file and not vcs as spin doesn't initialise a repo)

**Comment by radu-matei** [comment]
I marked this as a good first issue, before realizing it might have a few implications for the template system.

@itowlson -- what do you think about this one?

**Comment by radu-matei** [comment]
@thesuhas — would you be interested in contributing this feature?

**Comment by thesuhas** [comment]
@radu-matei I would! Although I have no idea where to get started. It would be great if you could point me in the right direction

**Comment by itowlson** [comment]
@thesuhas Thanks for stepping up!  Regarding pointing you in the right direction: here are the things I'd be thinking about and the areas of the code I'd be looking at:

1. Decide if this is a per-template prompt or a built-in command-line option.  We can discuss that on this issue.
  a. If it's a built-in command-line option, you would add it in `src/commands/new.rs` and pass it through in the `spin_template::RunOptions` (https://github.com/fermyon/spin/blob/main/src/commands/new.rs#L176).
  b. If it's a template prompt then we need the template engine to understand parameter semantics, which is a new concept but way more flexible in the long run.

2. Determine how to identify which files to exclude.  This might need some design (and might depend on the outcome of option 1).  Alternative ideas:
  a. Have the template engine understand `.gitignore` as a special file that is conditionally excluded.
  b. Use a naming convention for files that may be conditionally excluded.
  c. List files to be conditionally excluded in the template metadata.

3. Implement conditionally excluding a file (or set of files).  The set of files to copy is determined in `crates/templates/src/template.rs`, in the `Template::included_files()` files function.  This is currently fairly static, so either you need to modify it to accept dynamic decisions, or you need to post-process it in `Run::included_files()` (in `run.rs`) - either way, you should have all the info you need at the call site.
  a. My inclination here is to do the evaluation inside `Template::included_files()` and avoid complicating `Run::included_files()` (which is more interested in taking snapshots of the files already deemed included).  This opens up some nice abstraction opportunities where only the `Template` needs to care about how abstract options like "no VCS" map to concrete files in its own particular case.

To be clear, I say this not to tell you what to do, but to support you figuring out how you want to approach this!  I hope it doesn't come across as micro-managing.  Please feel free to ping me if you want to discuss further or need more pointers - I'm very happy to help and support you.

**Comment by thesuhas** [comment]
Hi,
Sorry for the extremely long delay. 
I've added the option as an optional command line flag in `TemplateNewCommandCore`. I am using this flag in `RunOptions` in `crates/templates/src/run.rs`. This is being accessed in `included_files` and I am conditionally filtering out the `all_content_files` based on the value of this flag.
I've tested it locally and it works but the tests are failing. This is due to a build issue in `crates/templates/src/manager.rs` where `RunOptions` is being initialised in multiple tests.
I was just wondering if it could be provided as `false` for all of these tests and if that would be fine?
Additionally, would it be okay if I added a test case in `crates/templates/src/test_built_ins/mod.rs` to verify that the `.gitignore` file is being conditionally created or not?

**Comment by itowlson** [comment]
Yes, setting the new flag to `false` in existing tests is fine.

For testing the flag, it would be preferable to do it in the `manager` tests, which have come to include the `run` behaviour tests.  But if that turns out to be painful then `test_built_ins` would be okay.

Thanks for the update and for staying with this!

**Comment by thesuhas** [comment]
Hi,
I opened a pull request: https://github.com/fermyon/spin/pull/2370

**Comment by itowlson** [comment]
Fixed via #2370 - thank you @thesuhas
