### ISSUE TITLE
Fix or remove `examples/wasi-http-rust-streaming-outgoing-body`

### ISSUE THREAD

**Issue by lann** [fermyon/spin#2282]
Per @dicej, the `/double-echo` endpoint in this example depends on a special "eager" `/echo` endpoint as its `url` target, but that echo endpoint was removed at some point. We should either reintroduce it or remove the example entirely.

**Comment by dicej** [comment]
FYI, the example of interest has moved to https://github.com/fermyon/spin-rust-sdk/tree/main/examples/wasi-http-streaming-outgoing-body

**Comment by rylev** [comment]
I think we should close this issue then since it no longer pertains to this repo. Feel free to reopen if you feel differently.
