### ISSUE TITLE
Support AOT compiled components through the OCI loader

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#2284]
This is a feature request for Spin's OCI loader to support precompiled Wasm components.

There are scenarios where the fast startup is important, being able to load ahead-of-time compiled Wasm components can optimize the startup time significantly (especially when running with few resources).

In this scenario, a separate process would fetch the Spin application and compile its Wasm components, then place them in the OCI cache; from there, the OCI loader could instantiate the app.

**Comment by vdice** [comment]
@kate-goldenring does work still need to be done for this ticket now that https://github.com/fermyon/spin/pull/2318 is in?

**Comment by kate-goldenring** [comment]
@vdice thank you for following up on this. Yes, this is completed by #2318
