### ISSUE TITLE
remove plugin installation confirmation stutter

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#2292]
Every time I install a plugin, I get an installation confirmation prompt. When I select yes, the prompt is displayed again with the final confirmation. This happens when the prompt is very long. If I remove the url from the prompt string, I don't get the stutter or second prompt with confirmation. This also doesn't happen if I use a different crate for displaying the confirmation dialogue like [promptly](https://crates.io/crates/promptly). 

<img width="1266" alt="Screenshot 2024-02-23 at 11 47 24 AM" src="https://github.com/fermyon/spin/assets/1497123/1b9d4c69-653f-4bb4-86a8-a1bb54f5182b">

* Spin version (`spin --version`)
spin 2.3.0-pre0 (78f84e7f 2024-02-21)

Would love for us to figure out a way to remove the stutter.

**Comment by karthik2804** [comment]
Related [open issue](https://github.com/console-rs/dialoguer/issues/295) in the `dialouger` crate for this.  We could split up the metadata and a smaller yes or no line?  Something along the lines of 

```bash
You are trying to install plugin `trigger-cron` with license Apache-2.0 from https://github.com/fermyon/spin-trigger-cron/releases/download/canary/trigger-cron-0.1-macos-aarch64.tar.gz

Are you sure you want to continue? (y/n)

```

**Comment by michelleN** [comment]
yea that sounds good to me! 👍
