### ISSUE TITLE
http-go template points to old sdk

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#2306]
The [current http-go template on main](https://github.com/fermyon/spin/blob/main/templates/http-go/content/main.go) points to the sdk that has already been moved and doesn't exist on main. Should we hardcode the relevant [require line in go.mod](https://github.com/fermyon/spin/blob/main/templates/http-go/content/go.mod#L5) to point to the latest stable release containing the template i.e. v2.2.0 for now?

**Comment by itowlson** [comment]
@dicej I have a vague memory of the plan being to update this as part of the 2.3 template release - is that right or am I hallucinating?

**Comment by dicej** [comment]
I didn't realize we had templates pointing to SDKs on the main branch (though it certainly made sense when the SDKs still lived here).  We should point them to the latest release tag, I think.  And we can bump the versions when new releases of the SDKs are available.

**Comment by dicej** [comment]
Fixed in #2317
