### ISSUE TITLE
Subdomain wildcards

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#2309]
The service chaining SIP (#2290) proposes `widgets.spin.internal` as the domain name for chained requests.  To allow chaining to _any_ other component (a la `self`), it proposes allow-listing `*.spin.internal`.  However, subdomain wildcards don't currently resolve - they parse but are matched literally rather than treated as a pattern.

Should we:

1. Allow subdomain wildcards
2. Special case the chaining domain and allow wildcards only there
3. Use a different convention for chaining

**Comment by lann** [comment]
I think allowing a subdomain wildcard would be fine.

**Comment by fibonacci1729** [comment]
+1 for subdomain wildcards.
