### ISSUE TITLE
Enable `spin add` for Redis templates

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/spin#2315]
While multiple components can be used in a single application,  we can't `spin add` a Redis component to an existing Redis trigger app or an existing HTTP trigger app:

```bash
# Start with a blank canvas; use the `http-empty` template to create a new Spin application
$ spin new -t http-empty trigger-example
Description: An new Spin application
# Change into the new Spin application directory
$ cd trigger-example
# Add a new HTTP component to the application
$ spin add -t http-rust http-trigger-example
Description: HTTP trigger example
HTTP path: /...
# Add a new Redis component to the application
$ spin add -t redis-rust redis-trigger-example
Template redis-rust doesn't support the 'add component' operation
```

At present, if creating a multi-trigger application (using the `spin new` and `spin add` commands) a user must start with a Redis trigger app and then `spin add` the HTTP trigger component. 
The user can't add `spin add` an additional Redis trigger component to this existing Redis app either.

**Comment by tpmccallum** [comment]
The documentation in the https://developer.fermyon.com/spin/v2/triggers file will need to be amended if/when this change is implemented. The triggers page currently gives the following instructions re: multiple trigger applications via `spin new` and `spin add`:

---

Currently, only the HTTP template supports the `spin add` command. If you wish to use `spin add` to build an application with multiple triggers, **including a Redis trigger**, you should begin with the Redis trigger application. Then, `spin add` your HTTP trigger component(s) as demonstrated below. Please note that additional Redis trigger components cannot be added via `spin add` at this time.

```bash
# Start with a Redis trigger application
$ spin new -t redis-rust trigger-example
Description: A multiple trigger example
Redis address: redis://localhost:6379
Redis channel: one
# Change into to the application directory
$ cd trigger-example 
# Create HTTP trigger application
$ spin add -t http-rust http-trigger-example  
Description: A HTTP trigger example
HTTP path: /...
```

**Comment by itowlson** [comment]
Looks like there's a smol challenge here.

A Redis application _requires_ an `application.trigger.redis.address` entry.  When we create a _new_ `spin.toml` file (`spin new`), we can safely prompt for that and include that and all is well.

However, when we add a component to an _existing_ `spin.toml` file, we need to be smarter.  We should prompt for and add the `address` only if that entry doesn't yet exist.

The subsystems to do this don't currently exist in the templates crate.  (Which is not to say they can't be added - they can definitely be added, it just means there's more to this than making a component snippet.)

**Comment by itowlson** [comment]
(Incidentally this would have been a challenge for HTTP too had wise Lann not wisely made `base` optional, the wise fellow.)
