### ISSUE TITLE
Failed to execute plugin js2wasm in NixOS

### ISSUE THREAD

**Issue by byteshiva** [fermyon/spin#2337]
**Description:**
Attempting to run the `spin js2wasm --help` command on NixOS results in an error. The error message indicates a failure in locating a file or directory, with an **"No such file or directory"** error.

**Steps to Reproduce:**
1. Install the required dependencies using the following command:
   ```bash
   nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz -p fermyon-spin zig bun nodejs
   spin templates install --git https://github.com/fermyon/spin-js-sdk --update
   spin plugin install js2wasm
   ```
2. Execute the following command:
   ```bash
   strace spin js2wasm --help
   ```

**Expected Behavior:**
The `spin js2wasm --help` command should provide help information without errors.

**Actual Behavior:**
The command fails with the following error message:
```
Error: No such file or directory (os error 2)
```

**Environment:**
- Operating System: NixOS
- `spin` version: spin 2.2.0
- `js2wasm` plugin version: js2wasm 0.6.1 [installed]
- Dependencies: zig, bun, nodejs installed using the provided `nix-shell` command.

**Additional Information:**
- The `strace` output indicates an issue with file or directory access.
- The command seems to be looking for a file or directory that might be missing or inaccessible.
- It is possible that **spin** may expect a **"Filesystem Hierarchy Standard,"** and the current environment might not meet those expectations

**Strace logs**

<details><summary>Details</summary>
<p>

```
$ strace spin js2wasm  --version
statx(AT_FDCWD, "/home/xyz/.local/share/spin/plugins/js2wasm/js2wasm", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0755, stx_size=38368616, ...}) = 0
readlink("/proc/self/exe", "/nix/store/hp005mv5as3dzkj0qkdqm"..., 256) = 71
futex(0x7fd095dee638, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fd09df0fac0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fd09df0fac0, FUTEX_WAKE_PRIVATE, 1) = 0
mmap(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fd09c0fa000
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_VFORK|CLONE_CLEAR_SIGHAND, exit_signal=SIGCHLD, stack=0x7fd09c0fa000, stack_size=0x9000}, 88) = 116899
wait4(116899, NULL, 0, NULL)            = 116899
munmap(0x7fd09c0fa000, 36864)           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(2, TCGETS, {c_iflag=ICRNL|IXON|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B38400|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOKE, ...}) = 0
write(2, "\33[0m", 4)                   = 4
write(2, "\33[1m", 4)                   = 4
write(2, "\33[31m", 5)                  = 5
write(2, "Error", 5Error)                    = 5
write(2, "\33[0m", 4)                   = 4
write(2, ": ", 2: )                       = 2
write(2, "No such file or directory", 25No such file or directory) = 25
write(2, " (os error ", 11 (os error )             = 11
write(2, "2", 12)                        = 1
write(2, ")", 1))                        = 1
write(2, "\n", 1
)                       = 1
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0x7fd09e2a8000, 12288)           = 0
exit_group(1)                           = ?
+++ exited with 1 +++

```

</p>
</details>

**Comment by byteshiva** [comment]
**Test Failures After Running `nix develop` and `make test`**

**Description:**
After running `nix develop` followed by `make test`, the test suite encountered several failures. The errors seem to be related to the failure of services to spawn during the test environment boot process. The common error is "No such file or directory (os error 2)."

**Steps to Reproduce:**
1. Execute the following commands:
   ```bash
   git clone  https://github.com/fermyon/spin.git
   direnv allow
   cargo build
   export PATH=$PWD/target/debug:$PATH
   nix develop
   make test
   ```

**Test Failures:**
<details><summary>Test Report Details</summary>
<p>

1. `integration_tests::test_outbound_post`:
   ```
   Error: Test failed to run: failed to boot test environment
   Caused by: failed to start services
   Caused by: service failed to spawn
   Caused by: No such file or directory (os error 2)
   ```

2. `integration_tests::test_wasi_http_0_2_0`:
   ```
   Error: Test failed to run: failed to boot test environment
   Caused by: failed to start services
   Caused by: service failed to spawn
   Caused by: No such file or directory (os error 2)
   ```

3. `integration_tests::test_wasi_http_rc_11_10`:
   ```
   Error: Test failed to run: failed to boot test environment
   Caused by: failed to start services
   Caused by: service failed to spawn
   Caused by: No such file or directory (os error 2)
   ```

4. `integration_tests::test_wasi_http_hash_all`:
   ```
   Error: Test failed to run: failed to boot test environment
   Caused by: failed to start services
   Caused by: service failed to spawn
   Caused by: No such file or directory (os error 2)
   ```

5. `integration_tests::test_spin_plugin_install_command`:
   ```
   Error: 'cd "/tmp/t1b33e-11" && CARGO_TARGET_DIR="/tmp/t1b33e-11/target" TEST_PLUGINS_DIRECTORY="./plugins" "/home/siva/developments/spin-ws/spin/target/release/spin" "example"' failed with status code Some(1)
   stdout:
   stderr: Error: No such file or directory (os error 2)
   ```

6. `integration_tests::test_cloud_plugin_autoinstall`:
   ```
   Error: 'cd "/tmp/t1b33e-b" && CARGO_TARGET_DIR="/tmp/t1b33e-b/target" TEST_PLUGINS_DIRECTORY="./plugins" "/home/siva/developments/spin-ws/spin/target/release/spin" "login" "--help"' failed with status code Some(1)
   stdout: The `cloud` plugin is required. Installing now.
   Plugin 'cloud' was installed successfully!
   stderr: Error: No such file or directory (os error 2)
   ```



</p>
</details> 


**Environment:**
- Operating System: nixos
- `spin` version: (Provide the version of spin being used)
- Dependencies: zig, bun, nodejs installed using `nix develop`

**Comment by byteshiva** [comment]
I have resolved this issue and written a blog about it.

blog:
https://byteshiva.medium.com/restoring-filesystem-hierarchy-standard-to-fix-spin-a-step-by-step-guide-66a40feb355b

**Comment by itowlson** [comment]
That's super interesting - thank you so much for sharing your experiences and solutions!

**Comment by vdice** [comment]
@byteshiva Glad to hear you've figured this issue out.  Can this issue be closed now?

**Comment by byteshiva** [comment]
Thanks , You can close the issue
