### ISSUE TITLE
Cache Directory is not configurable

### ISSUE THREAD

**Issue by hffmnn** [fermyon/spin#2339]
## Intro
When trying to run the `spin` CLI on systems with (mostly) read-only filesystem it is not possible to set the used path for the cache directory.

## Example
When running on a system where only `/tmp` is writeable, doing a `spin up --log-dir "" --runtime-config-file runtime-config.toml --state-dir /tmp`* gives the following error:
```
failed to create manifests directory "/home/<user>/.cache/spin/registry/manifests"
```
*Note: The other flags are set so that `spin` doesn't try to write to other read-only parts of the file system.

## Workaround
There is a workaround though: Setting `XDG_CACHE_HOME`, which gets respected by the used `dirs` crate, to `/tmp` works. 

## Suggestion
Looking through the code it looks like everything is already prepared to set the cache dir (e.g. `Cache::new` already expects an `Option<PathBuf>`) but it doesn't get used anywhere:

`spin up` calls `spin_loader::from_file(&manifest_path, files_mount_strategy, None)` where `None` is the Option to set the cache root.

So my suggestion would be to allow setting the cache root through a `spin` specific environment variable and/or a command line flag.

## More Context
There is a thread about it in the `spin` Discord: https://discord.com/channels/926888690310053918/1215979463918096424

**Comment by lann** [comment]
I agree that the cache dir should be settable and additionally this particular issue could probably be avoided entirely by waiting to create that cache directory until its actually needed; it is only required for apps that pull content from the network.
