### ISSUE TITLE
Have `spin_telemetry` support gRPC protocol

### ISSUE THREAD

**Issue by calebschoepp** [fermyon/spin#2353]
Once #2348 lands it would be nice to support eh gRPC protocol.

**Comment by calebschoepp** [comment]
@thangchung #2463 adds gRPC support.

**Comment by thangchung** [comment]
@calebschoepp It's very cool to have `grpc` support, then I will experiment with .NET Aspire then. 

My repo for it at https://github.com/thangchung/spin-o11y
