### ISSUE TITLE
Linting Step Failing in Build Workflow

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/spin#2401]
Since changing our runners to Ubuntu 20.04 in #2378 , the "Run lints on examples" step in the build workflow has been failing in CI.

Workaround is to delete all caches https://github.com/fermyon/spin/actions/caches and rerun

**Comment by lann** [comment]
I think this was fixed by #2383

**Comment by lann** [comment]
Looks like this was an unrelated problem.
