### ISSUE TITLE
"Unknown lint: `clippy::blocks_in_conditions`" warning when clippying Spin source

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#2424]
The `clippy::blocks_in_conditions` lint causes an "unknown lint" warning on Rust 1.75.  Looking at the linked issue it was maybe introduced in 1.76?  The MSRV of Spin is 1.74.  Are we happy to rev that to 1.76, or are we okay to ignore the warnings (since the only reason we mention the lint is a bug that will hopefully get fixed soon)?

**Comment by vdice** [comment]
> since the only reason we mention the lint is a bug that will hopefully get fixed soon

@itowlson can you link to the bug?  Or not yet tracked?  At first take, I'd be inclined to keep Spin at 1.74 and fix the bug.

**Comment by itowlson** [comment]
@vdice https://github.com/rust-lang/rust-clippy/issues/12281

**Comment by lann** [comment]
I think ignoring the warning is appropriate. I have updated this issue's title to be slightly more discoverable if someone else is annoyed by the warning.
