### ISSUE TITLE
Should we trace functionality in `spin-core` crate?

### ISSUE THREAD

**Issue by calebschoepp** [fermyon/spin#2438]
In issue #2352 we seek to exhaustively trace all the important parts of Spin. "Important" is loosely defined as some functionality that is fallible and potentially slow. I want us to discuss whether all/some/none of the functionality in `spin-core` should be instrumented. 

## Pros of instrumenting `spin-core`
- Most of the functions are fallible and potentially slow.
- Certain apps like `spin-fileserver` would benefit from tracing of interactions with FS.
- Spin developers would have an easier time debugging with this kind of tracing available.

## Cons of instrumenting `spin-core`
- Most of `spin-core` is WASI stuff which feels like too low level of a thing to trace.
- There are a lot of things to trace and the code is going to get cluttered.
- In the future Spin users can use WASI Observe to get a roughly similar idea.

## Potential courses of action
- Don't trace anything in `spin-core` ever.
- Wait for significant number of requests from users to add (if ever) tracing to `spin-core`.
- Trace everything in `spin-core` at a debug level such that the user must pass `SPIN_OTEL_TRACING_LEVEL=DEBUG` to see these `spin-core` traces.
- Trace only a few of the functions in `spin-core` that we deem the most important.
- Trace everything in `spin-core`.

Personally I would opt for us to wait for a significant amount of user requests before taking any action here.

**Comment by radu-matei** [comment]
If indeed we would benefit from this kind of information, I'm curious why we _wouldn't_ add this and feature gate it under the environment variable:

> Trace everything in spin-core at a debug level such that the user must pass SPIN_OTEL_TRACING_LEVEL=DEBUG to see these spin-core traces.

**Comment by calebschoepp** [comment]
> If indeed we would benefit from this kind of information, I'm curious why we wouldn't add this and feature gate it under the environment variable:

The two main reasons in my head to not do so is 1) the cluttering of the codebase 2) the overhead of tracing every single host call.

Note that `SPIN_OTEL_TRACING_LEVEL` doesn't really act as a feature gate — more like a filter. The functions are still traced but just don't get exported out to the collector.

If we really wanted to feature gate it we would have to give the Spin crate some kind of Cargo feature that turned off all tracing (which we have considered).

**Comment by radu-matei** [comment]
Do we have a guess / estimate of the overhead for the level of tracing that we'd find _useful_ (for a handwave-y definition of useful)?

**Comment by calebschoepp** [comment]
Spent a bit of time getting some rough performance numbers. Spin versions tested:

- Spin on main.
- Spin with core traced. I just traced every single function — obviously this is way more than we would find useful, but I wasn't sure where to draw the line of usefulness.

I was just testing against a simple Spin app that returned a response and didn't print anything.

## Spin on main
```
Bombarding http://localhost:3000 for 10s using 5 connection(s)
[======================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     20385.33     775.89   21490.43
  Latency      243.80us    18.17us     2.23ms
  HTTP codes:
    1xx - 0, 2xx - 203853, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     3.81MB/s
```

I think this was crashing Jaeger. We don't sample traces yet and I think it was just way too much load for Jaeger to handle.

## Spin with core traced
```
Bombarding http://localhost:3000 for 10s using 5 connection(s)
[======================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     11511.48    2054.04   14054.62
  Latency      432.64us   173.00us     9.81ms
  HTTP codes:
    1xx - 0, 2xx - 115117, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     2.15MB/s
```

This too was crashing Jaeger, unsurprisingly.

**Comment by calebschoepp** [comment]
Here is some testing against the same two versions of Spin with the same app, except this time I'm not configuring the `OTEL_EXPORTER_OTLP_ENDPOINT`. In other words it isn't actually shipping the traces off to the collector.

## Spin on main
```
Bombarding http://localhost:3000 for 10s using 5 connection(s)
[======================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     24168.09     893.07   25615.47
  Latency      205.65us    43.73us     5.04ms
  HTTP codes:
    1xx - 0, 2xx - 241663, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     4.52MB/s
```

## Spin with core traced

```
Bombarding http://localhost:3000 for 10s using 5 connection(s)
[======================================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     23853.92    1528.22   25238.91
  Latency      208.39us    90.50us    13.39ms
  HTTP codes:
    1xx - 0, 2xx - 238475, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:     4.46MB/s
```

**Comment by lann** [comment]
With the initial spike of instrumentation wrapping up I think we should start transitioning from this top-down planning ("Where _can_ we add tracing?") to bottom-up ("Where are the gaps?" / "What are customers asking for?").

**Comment by calebschoepp** [comment]
Not hearing a lot of interest for tracing `spin-core`. I'm going to close this issue. We can always re-open it in the future if we get more end users asking for this kind of tracing.
