### ISSUE TITLE
Invalid character `{` in package name

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#2455]
Since the latest Rust update (I think?), every time I keep getting the following error when trying to build something that imports Spin:

```
$ cargo build
error: invalid character `{` in package name: `{{project-name | kebab_case}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../../../.cargo/git/checkouts/spin-91500438ac5656d2/b86af6c/templates/redis-rust/content/Cargo.toml:2:8
  |
2 | name = "{{project-name | kebab_case}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
error: invalid character `{` in package name: `{{project-name | kebab_case}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../../../.cargo/git/checkouts/spin-91500438ac5656d2/b86af6c/templates/http-rust/content/Cargo.toml:2:8
  |
2 | name = "{{project-name | kebab_case}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Should I ignore it? Is there a way to suppress it?

(this is coming Rust templates for Spin apps, so not from actual Rust packages)

**Comment by rylev** [comment]
The issue stems most likely from a change to how cargo resolves git based dependencies. Cargo searches all of a git repository for Cargo.toml files and then resolves those projects even if they are not a part of a workspace. The template files get picked up as legitimate Cargo.toml manifests even though they're not. 

I don't believe there's anyway to tell Cargo to ignore these files, so we might need to change how templating works to work around this Cargo issue.

**Comment by lann** [comment]
Maybe spin templates could be taught to strip a `.tmpl` suffix from input files?

**Comment by itowlson** [comment]
I found an allusion in https://blog.rust-lang.org/inside-rust/2024/03/26/this-development-cycle-in-cargo-1.78.html to `package.include` disabling git walking.  Would that solve this, or would the downsides be unacceptable?

(I mean I'm okay with the `.tmpl` thing, just wondering.)

**Comment by Boscop** [comment]
This issue is closed but I still get this (on Windows):
```
PS D:\dev\proj\leptos-spin-example> spin up --build
Building component benwis-spin with `cargo leptos build --release && cargo build --lib --target wasm32-wasi --release --no-default-features --features ssr`
error: invalid character `{` in package name: `{{project-name | kebab_case}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> C:\Users\me\scoop\persist\rustup\.cargo\git\checkouts\leptos-spin-8ab45c2d3a8bc267\fe67739\templates\leptos-ssr\content\Cargo.toml:2:8
  |
2 | name = "{{project-name | kebab_case}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
```
It compiles though, but it's still a bit annoying in terms of DX..

**Comment by rylev** [comment]
@Boscop can you provide the version Spin as well as the version of any Spin SDK dependency you have in your Cargo.toml? I would bet that this is due to something being out of date.

**Comment by Boscop** [comment]
@rylev Hm, I just tried with the latest version of this: https://github.com/benwis/leptos-fermyon-spin-blog-demo
And I still get this error:
```
PS D:\dev\3rdparty\leptos-fermyon-spin-blog-demo> spin up --build
Building component leptos-blog-demo-finished with `cargo leptos build --release`
error: invalid character `{` in package name: `{{project-name | kebab_case}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> C:\Users\me\scoop\persist\rustup\.cargo\git\checkouts\leptos-spin-8ab45c2d3a8bc267\7b56e47\templates\leptos-ssr\content\Cargo.toml:2:8
  |
2 | name = "{{project-name | kebab_case}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
```

**Comment by rylev** [comment]
@Boscop I believe that the Cargo.toml in that project needs to be update to a newer version of the Spin SDK. It is currently using an older version. That might fix the issue. Happy to continue helping, but I'm certain this is not an issue that can be addressed in the Spin codebase.
