### ISSUE TITLE
Inferencing with `codellama-instruct` fails locally

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin#2467]
I am not able to use inferencing based on `codellama-instruct`, with the most recent version of Spin  on my local machine.

- Spin: `2.4.2 (340378e 2024-04-03)`
- Host: `Darwin zion 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:37 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6031 arm64`

At runtime, the following exception is logged to the output:

```bash
Uncaught InternalError: Error::InvalidInput("no model directory found in registry for model 'codellama-instruct'")
    at infer (script.js:250)
    at <anonymous> (script.js:333)
```

I was able to reproduce the error with apps in JavaScript and Rust.

Additionally, I took the following steps to verify the problem not being related to my system:

- I re-downloaded the models using the links provided in the [Serverless AI Tutorial](https://developer.fermyon.com/spin/v2/ai-sentiment-analysis-api-tutorial)
- Because I keep models at a central place (in my home directory), I use symlinks to use them from within different Spin Apps
  - I re-created the symlinks for this particular Spin App at `./spin/ai-models`
- I copied the `codellama-instruct` model explicitly to `./spin/ai-models`

Here the `tree` of my `.spin` folder:

```bash
tree .spin -alh
[ 128]  .spin
├── [  96]  ai-models
│   └── [6.7G]  codellama-instruct
└── [ 128]  logs
    ├── [ 18K]  foo-api_stderr.txt
    └── [  26]  foo-api_stdout.txt
```

## `llama2-chat` works ✅

Inferencing with `llama2-chat` works seamlessly with the same Spin App. I applied the following changes to verify this:

- Added the `llama2-chat` model to `./spin/ai-models`
- Granted the Spin App permissions to use the `llama2-chat` model in `spin.toml`
- Pass `InferencingModels.Llama2Chat` as argument to `Llm.infer()` instead of `InferencingModels.CodellamaInstruct`

## Fermyon Cloud

When deploying the same app (without any doing any modifications) to Fermyon Cloud (`spin deploy`), everything works as expected. 

## Cloud-GPU

I also tried the hybrid approach (running the app locally) and using the `cloud-gpu` plugin to offload inferencing to Fermyon Cloud. This approach also fails at runtime with the following error message (me assuming the same underlying error):

```bash
Uncaught InternalError: Error::RuntimeError("Failed to deserialize response for \"POST  /index\": error decoding response body: expected value at line 1 column 1")
    at infer (script.js:250)
```

**Comment by itowlson** [comment]
@ThorstenHans Could you try putting the model at `./ai_models/llama/codellama-instruct` please?  (note the extra `llama` directory)  I know this is not what the docs say, just trying to figure out what is happening inside Spin here...  Thanks!

**Comment by ThorstenHans** [comment]
@itowlson that works 🥳  

Did the desired location for models change at some point in time? All the docs and guides tell users to put models in `./spin/ai-models`.

I tried also with `llama2-chat`. Which also works when I put the corresponding model file in `./spin/ai-models/llama`

```bash
tree . -al
.
├── ai-models
│   └── llama
│       ├── codellama-instruct
│       └── llama2-chat
└── logs
    ├── dotnetpro-api_stderr.txt
    └── dotnetpro-api_stdout.txt
```

BTW @itowlson : Just to verify, I use the folder `ai-models` (dash) - as mentioned in the docs - , you suggested using `ai_models`  (underscore)... is that folder checked as well?

**Comment by ThorstenHans** [comment]
At this point I wonder if we wanna update docs/guides to match what you suggested or - if this is a bug and should be changed in Spin?

WDYT @itowlson 

If we go with updating docs and guides, I'll close this one and open a corresponding issue to update the docs. Otherwise, we can use this to track the fix in Spin itself

**Comment by karthik2804** [comment]
I think the first level of directory is the model architecture and then the second layer is the actual model needed. I have not looked at the code but that is how it is parsed if I remember correctly.

**Comment by ThorstenHans** [comment]
Makes sense to me. I'll close this issue and create a corresponding one, to update docs/tutorials.

**Comment by itowlson** [comment]
@ThorstenHans "Well known" inferencing models (which is currently `llama2-chat` and `code_llama`) can go directly in the `ai-models` directory.  (Embedding models are different again.)  It's only "not so well known" models (such as `codellama-instruct`) that need an architecture directory.

As you've noted, however, it's legal to put well-known models in the architecture directory anyway.  It seems like your docs PR recommends always doing that, but I wonder if we should be draw the distinction of "well known" vs "not well known" so that we don't give the impression that "`ai-models/llama` is where you put files"?
