### ISSUE TITLE
Docs: do we want to bring the url-shortener example into this repo?

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#248]
Currently https://spin.fermyon.dev/url-shortener/ has a link to an external repo, https://github.com/fermyon/url-shortener, which is also private at time of writing.

Do we want to do without the separate repo and bring the example into this repo under `examples`?  One benefit being we don't have another repo to coordinate making public once this one does so...

**Comment by itowlson** [comment]
Any action needed/wanted on this?  (The external repo is now public but I don't know if it's been tested with current Spin.)

**Comment by vdice** [comment]
For the needs of this original issue (visibility/access to the repo), we're good.  Thanks @itowlson!
