### ISSUE TITLE
spin watch doesn't rebuild/reconfigure on manifest file changes

### ISSUE THREAD

**Issue by garikAsplund** [fermyon/spin#2480]
Expected behavior: 

>Manifest file changes must trigger a full rebuild and restart, _and_ must reload the watch configuration (because we may now be watching different paths).  This is currently managed by the ManifestFilterFactory, Reconfiguriser and ReconfigurableWatcher.

_Originally posted by @itowlson in https://github.com/fermyon/spin/issues/2478#issuecomment-2083887235_

Making changes within `spin.toml` while `spin watch` is running does not lead to any rebuild or reconfigurations.

**Comment by itowlson** [comment]
Looks like it's unhappy that the manifest path is absolute.  I'm not sure if this is a watchexec change, or if we changed Spin so that we absolutised the manifest path before giving it to `watch`.  But it looks like changing the manifest path to be relative to the manifest directory fixes it.

**Comment by itowlson** [comment]
@garikAsplund I saw you had 👀 on the original comment - does that mean you're interested in investigating and fixing this?  I'm happy to assign it to you if you want, otherwise I'll pick it up.  (I'm not trying to thrust it on you - just don't want to tread on your toes.)

**Comment by garikAsplund** [comment]
@itowlson If it's quick and easy for you to fix go right ahead! Or I can investigate further tonight if you're busy.

**Comment by itowlson** [comment]
Yeah I can sort it.  Thanks for spotting this!

Context: https://github.com/fermyon/spin/pull/1983 (so we do need the absolute but not sure exactly _when_)

**Comment by garikAsplund** [comment]
Cool! Appreciate the context.

Out of curiosity, what's the best way of testing CLIs, especially with file changes and everything?

**Comment by itowlson** [comment]
I have yet to find a method better than manual testing for cases like this, although with Ryan's integration/runtime test framework we might be in a better position to automate something.  "UI tests" (which store an expected "golden" output and diff the actual output against it, hence also known as "golden tests") can help with some CLI tests - but that wouldn't really help here.
