### ISSUE TITLE
Support exporting application logs through OTel

### ISSUE THREAD

**Issue by calebschoepp** [fermyon/spin#2496]
It'd be nice to consolidate logs into OTel like we've done for metrics and traces

**Comment by lann** [comment]
My vague understanding is that otel logging has pretty bad ecosystem support.

**Comment by calebschoepp** [comment]
That is also my vague understanding — still worth exploring IMO.

At the very least I wan to try emitting `tracing::info!` events from guest logs so that they appear as events on their spans.

**Comment by calebschoepp** [comment]
Closed by #2516 and #2511
