### ISSUE TITLE
spin-v2.4.3-macos-amd64.tar.gz contains the wrong architecture

### ISSUE THREAD

**Issue by jandubois** [fermyon/spin#2502]
I noticed that the `amd64` download for 2.4.3 actually contains an `arm64` binary:

```console
$ tar xvfz spin-v2.4.3-macos-amd64.tar.gz spin
x spin
$ file spin
spin: Mach-O 64-bit executable arm64
```

The 2.5.0 binary has the correct architecture:

```console
$ tar xvfz spin-v2.5.0-macos-amd64.tar.gz spin
x spin
$ file spin
spin: Mach-O 64-bit executable x86_64
```

**Comment by jandubois** [comment]
Depending on how long it will take to fix, it may be a good idea to put a warning on top of the release notes to let other users know that this is a known issue?

**Comment by vdice** [comment]
@jandubois the `spin-v2.4.3-macos-amd64.tar.gz` artifact has now been updated on the v2.4.3 release.

**Comment by jandubois** [comment]
> @jandubois the `spin-v2.4.3-macos-amd64.tar.gz` artifact has now been updated on the v2.4.3 release.

Too late, I've moved on to 2.5.0 now 😄 

j/k, I've confirmed that the file contains an Intel binary now, thanks!
