### ISSUE TITLE
Adding a trailling slash `/` to a domain name in `allow_outbound_hosts` fails

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#2545]
* Spin version (`spin --version`)
spin 2.5.1 (cba6773 2024-05-14)

* Installed plugin versions (`spin plugins list --installed`)
check-for-update 0.1.0 [installed]
cloud 0.8.0 [installed]
cloud-gpu 0.1.0 [installed]
js2wasm 0.6.1 [installed]
kube 0.1.1 [installed]
pluginify 0.7.0 [installed]
py2wasm 0.3.2 [installed]
trigger-command 0.1 [installed]
trigger-message 0.0.1 [installed]
trigger-mqtt 0.2.0 [installed]

If I want to make an http call to `https://myapi.com`, the destination will be allowed using this configuration:

`allowed_outbound_hosts = ["https://myapi.com"]`

But will be denied with this configuration:

`allowed_outbound_hosts = ["https://myapi.com/"]`

**Comment by lann** [comment]
@rylev
