### ISSUE TITLE
Referencing files outside of app root produces bad error messages

### ISSUE THREAD

**Issue by lann** [fermyon/spin#2551]
We intentionally limit file references to be within the "app root" (i.e. the directory containing `spin.toml`). If this constraint is violated the error chain is currently pretty unhelpful:

```
   0: Failed to load Spin app from "spin.toml"
   1: Failed to load component `<component-id>`
   2: prefix not found
```

I believe the source of this error is the `strip_prefix` call here: https://github.com/fermyon/spin/blob/b8e4185597615fe5559ce2c473d5d7d612206690/crates/loader/src/local.rs#L419

**Comment by me-diru** [comment]
Thanks for sharing! The will try to  push a better error message fix for this and look out for potential bad error messages in CLI :D

**Comment by me-diru** [comment]
Hi, I am trying to replicate this error. May I know when this occurs? I tried keeping the `source` route of a component to folder outside the root, and it seems to work when I build it using `spin build` and gives a pretty clear error when I run `spin run` 

```
Logging component stdio to ".spin/logs/"
Storing default key-value data to ".spin/sqlite_key_value.db"
Error: Failed to instantiate component '<component-id>'

Caused by:
   0: failed to read component source from disk at path "<path given in source>"
   1: No such file or directory (os error 2)
  ```
  
  In both cases, I haven't found unhelpful error messages. May I please know when this error occurs? thanks

**Comment by itowlson** [comment]
This is referring to the `files` section e.g.

```toml
[component.foo]
source = "..."
files = [{ source = "/home/ivan/catpictures", destination = "/catpics" }]
#             ^^^-- this source
```
