### ISSUE TITLE
Record OTel metrics in host components

### ISSUE THREAD

**Issue by calebschoepp** [fermyon/spin#2564]
It would be nice to record metrics in host components e.g.  counter `spin.key_value.set` or counter `spin.llm.infer`

**Comment by calebschoepp** [comment]
@me-diru were you still planning on working on this? Totally fine if you weren't planning to.

**Comment by me-diru** [comment]
Hi! Yes, at least the basic metrics are done, and I want to test it after Lann has landed on that patch. I will look into it and see where it takes me.
