### ISSUE TITLE
Build failed (aedc2b8ccc65f41615fa7beb3e427843dd782114)

### ISSUE THREAD

**Issue by seungjin** [fermyon/spin#2567]
Spin build failed. 

```
# git rev-parse HEAD
aedc2b8ccc65f41615fa7beb3e427843dd782114
```
Error msg:
```
error[E0282]: type annotations needed for `Box<_>`
  --> /var/home/seungjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

```
# cargo version
cargo 1.80.0-beta.3 (34a6a87d8 2024-06-04)
```

-----
```
# spin --version
spin 2.6.0-pre0 (13a133fd 2024-06-10)
workspace:~/Works/rust/spin
# spin plugins list --installed
check-for-update 0.1.0 [installed]
cloud 0.7.1 [installed]
platform 0.1.0 [installed]
pluginify 0.7.0 [installed]
test 0.1 [installed]
trigger-cron 0.1 [installed]
```

[Application Prerequisites](https://developer.fermyon.com/spin/build#setting-up-for-spin-build)
[Troubleshooting - Rust](https://developer.fermyon.com/spin/rust-components#troubleshooting)
[Cloud FAQ](https://developer.fermyon.com/cloud/faq)

If you still see a bug or problem, please let us know:

* Spin version (`spin --version`)
* Installed plugin versions (`spin plugins list --installed`)

**Comment by itowlson** [comment]
> `/var/home/seungjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34`

Hmm, looks like an issue in a dependency.  It builds for me and in CI, so possibly a regression in the Rust 1.80 beta since this presumably compiled for the authors of the `time` crate...

We will keep an eye out for this, but probably not anything we can control.  It's not a direct dependency, but quite a few things seem to bring it in, so hopefully it will get fixed before it becomes critical!

Thanks for flagging it!

**Comment by itowlson** [comment]
Looks like it might be fixed already (https://github.com/time-rs/time/blob/aca5c3652aff6fc7df3fbd8591c3e324d3a6ffb2/time/src/format_description/parse/mod.rs#L83).  Could you try running `cargo update` - that looks like it bumps the rev in `Cargo.lock`.

**Comment by seungjin** [comment]
:+1: build succeeded
