### ISSUE TITLE
Spin 2.6 release

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#2570]
This is a test, to start creating issues to track Spin releases.

Last week it was decided to release Spin 2.6 this week: https://docs.google.com/document/d/1EG392gb8Eg-1ZEPDy18pgFZvMMrdAEybpCSufFXoe00/edit#bookmark=id.mqvnq7lc0rxb

This issue will track the release.

Release process: https://github.com/fermyon/spin/blob/main/docs/content/release-process.md

- [x] Release engineer assigned
- [x] Release manager assigned

Blockers/Issues to track
- [x] https://github.com/fermyon/spin/pull/2571
  - [x] Backport: https://github.com/fermyon/spin/pull/2578
- [x] https://github.com/fermyon/spin/issues/2575
- [x] https://github.com/fermyon/spin/pull/2573

**Comment by mikkelhegn** [comment]
Remember: https://docs.google.com/document/d/1EG392gb8Eg-1ZEPDy18pgFZvMMrdAEybpCSufFXoe00/edit#bookmark=id.bswmcj3sc1eu @lann to help write the deprecation warning. #2552

**Comment by mikkelhegn** [comment]
Assigning myself as release manager and issue owner.

Still looking for an release engineer.

**Comment by vdice** [comment]
I can be the release engineer

**Comment by mikkelhegn** [comment]
#2575 is currently blocking this release.

**Comment by mikkelhegn** [comment]
@itowlson - do we have docs queued up for this feature? https://github.com/fermyon/spin/pull/2524

**Comment by itowlson** [comment]
https://github.com/fermyon/developer/pull/1306/files#diff-508d3554fb5ddeccc9029f9f1d60e906e57f4179ca3ec5dfea6e3d77c06ac249R180

**Comment by itowlson** [comment]
I am wondering if we should pull the docs though.  The publish workflow is distinctly early-stage, and people trying to use registry packages by "what seems obvious" are likely to get themselves burned.

**Comment by mikkelhegn** [comment]
In combination with this feature: #2479  - which I got working 🙌🏻 it would be nice to showcase, at least in a release blog, how we're making Spin simply work with Wasm components. Thoughts?

A follow-up on #2479, will this work with any component exporting any handler supported by the Spin installation (including plugins)?

**Comment by itowlson** [comment]
#2479 is HTTP only.

**Comment by lann** [comment]
> will this work with any component exporting any handler supported by the Spin installation (including plugins)?

We don't currently have a way to determine which trigger type to use. We've discussed in the past adding a `spin up --trigger-type <type>` flag for the purpose of running only one of an app's trigger types; that could be reused for this purpose as well.

**Comment by vdice** [comment]
https://github.com/fermyon/spin/releases/tag/v2.6.0 is now out.
