### ISSUE TITLE
Remove HTTP trigger `base` option

### ISSUE THREAD

**Issue by lann** [fermyon/spin#2583]
The app-wide HTTP trigger `base` option effectively prepends a fixed string to every HTTP trigger route. This is _almost_ identical to the equivalent routes, but a couple of the magic `spin-*` headers expose this information to the guest as well.

A [search of Github](https://github.com/search?q=path%3Aspin.toml%20%2Fbase%20%3D%20%2F&type=code) suggests that this option is practically unused after it was made optional in #1803. I'd like to remove this option with Spin 3.0 and redefine or remove related magic `spin-*` headers.

**Comment by fibonacci1729** [comment]
Just to note that it was mentioned in the last spin call that this will naturally fall out of the factors work and isn't a separate action item.

**Comment by rylev** [comment]
I assume this can be closed now that it has landed in `main`?

**Comment by lann** [comment]
Need to update docs.

**Comment by itowlson** [comment]
Created a separate issue to track the user docs changes https://github.com/fermyon/developer/issues/1371, or does you comment refer to other docs updates?
