### ISSUE TITLE
Enable pushing components with `spin registry push`

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#2590]
#1182 and #2524 are part of enabling pushing and pulling components to/from registries.

With #2524 in Spin 2.6.0, there is a gap in how a sinlge component, can be pushed to a registry. If e.g., you create a WASI-HTTP incoming-handler, and want to push it to a registry, you hvae to use a tool like [Oras](https://github.com/oras-project/oras).

The workflow works, using `spin registry push` today, but you can only do that if a `spin.toml` file is present in the diretory from which you push the component.

I'd like to prospoe adding an option to push a component using `spin registry push` - e.g., `spin registry push component ttl.sh/my/name:0.0.1 -f my_component.wasm`, to make this workflow easier.

**Comment by lann** [comment]
There will [soon](https://github.com/bytecodealliance/wasm-pkg-tools/pull/44) be another option here: `wkg oci push`

**Comment by itowlson** [comment]
@mikkelhegn Should we combine this with #2536?  They seem to be asking for very similar things.

**Comment by mikkelhegn** [comment]
@itowlson - Thy seem undoubtfully similar :-) Let me close this one, and we can rack the other.

Closing as a duplicate of #2536
