### ISSUE TITLE
add MAINTAINERS.md file to each repository in Spin project

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#2629]
The [governance document](https://github.com/fermyon/spin/blob/main/GOVERNANCE.md) was just merged and requires a MAINTAINERS.md file in each repo:

>New maintainers MUST be nominated by existing maintainers. Maintainers are to discuss and agree in a private setting adding a new maintainer. Once a descision has been made, a maintainer may be added to the project via a pull request to the relevant MAINTAINERS.md file.

This issue tracks the work to make that change.

**Comment by michelleN** [comment]
Core Spin:

- [ ] [Spin](https://github.com/fermyon/spin)

SDKs:

- [ ] [Spin Python SDK](https://github.com/fermyon/spin-python-sdk)
- [ ] [Spin JavaScript SDK](https://github.com/fermyon/spin-js-sdk)
- [ ] [Spin Rust SDK](https://github.com/fermyon/spin-rust-sdk)
- [ ] [Spin .NET SDK](https://github.com/fermyon/spin-dotnet-sdk)
- [ ] [Spin Nim SDK](https://github.com/fermyon/spin-nim-sdk)

Plugins:

- [ ] [Spin Plugins Index Repository](https://github.com/fermyon/spin-plugins)
- [ ] [Fermyon Platform Plugin](https://github.com/fermyon/platform-plugin)
- [ ] [Spin Test Plugin](https://github.com/fermyon/spin-test)
- [ ] [Cloud Plugin](https://github.com/fermyon/cloud-plugin)
- [ ] [Spin Cloud GPU Plugin](https://github.com/fermyon/spin-cloud-gpu)

Triggers:

- [ ] [Spin Command Trigger](https://github.com/fermyon/spin-trigger-command)
- [ ] [Spin SQS Trigger](https://github.com/fermyon/spin-trigger-sqs)
- [ ] [Spin Cron Trigger](https://github.com/fermyon/spin-trigger-cron)

**Comment by itowlson** [comment]
@michelleN If all the repos are now done except for the Nim SDK, might it be good to close this issue and open one specifically in the Nim SDK?  Or do you want to keep this open here for higher visibility?

**Comment by radu-matei** [comment]
+1 to @itowlson's suggestion to move this to the project as an issue.

From [the governance document](https://github.com/fermyon/spin/blob/main/GOVERNANCE.md):

> Project maintainers MUST remain active on the project. If they are unresponsive for > 3 months, they will lose project maintainer-ship, unless the remaining project maintainers of the given project and the Spin Governance Committee agree to extend the period to be greater than 3 months.

Given the inactivity in the repository, my suggestion (as the only other contributor to that repo) would be to propose we archive the project unless we find contributors interested in the Nim SDK.

Thoughts?

**Comment by michelleN** [comment]
+1 to closing this and opening an issue in the nim sdk project.

+1 to archiving the project. We don't have process around that just yet. I propose we open a PR removing it from the projects list in the governance doc and discuss there. As a separate task, we should also add some text (probably in the governance document) around what it means to archive a project and how to do it.

**Comment by michelleN** [comment]
archive proposal: https://github.com/fermyon/spin/pull/2849
governance task: https://github.com/fermyon/spin/issues/2850
