### ISSUE TITLE
spin.toml with colons in route causes inconsistent behaviour between Spin and Fermyon Cloud

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/spin#2681]
Using the http-rust template,

```
><> spin new -t http-rust test-bad-paths
```

If you change the HTTP trigger route to this:

```
[[trigger.http]]
route = "/:id"
component = "test-bad-paths"
```

`spin up` will happily accept the URL path:

```
><> spin up
Logging component stdio to ".spin/logs/"

Serving http://127.0.0.1:3000
Available Routes:
  test-bad-paths: http://127.0.0.1:3000/:id
```

This becomes an issue because some users are expecting this to be a parameter value, e.g. `GET /$(uuidgen)`, which works with this route with Spin 2.6.0:

```
><> curl -i localhost:3000/$(uuidgen)
HTTP/1.1 200 OK
content-type: text/plain
transfer-encoding: chunked
date: Thu, 25 Jul 2024 14:47:37 GMT

Hello, Fermyon
```

```
><> curl -i localhost:3000/:id
HTTP/1.1 200 OK
content-type: text/plain
transfer-encoding: chunked
date: Thu, 25 Jul 2024 14:49:09 GMT

Hello, Fermyon
```

```
><> curl -i localhost:3000/
HTTP/1.1 404 Not Found
content-length: 0
date: Thu, 25 Jul 2024 14:48:50 GMT
```

Where this gets interesting is in the context of Fermyon Cloud. The parameterized path does not work on Fermyon Cloud.

```
><> curl -i https://test-bad-paths-m77inmpi.fermyon.app/$(uuidgen)
HTTP/2 404
date: Thu, 25 Jul 2024 14:51:20 GMT
content-type: text/plain; charset=utf-8
content-length: 9

Not found
```

```
><> curl -i https://test-bad-paths-m77inmpi.fermyon.app/:id
HTTP/2 200
content-type: text/plain
date: Thu, 25 Jul 2024 14:51:14 GMT

Hello, Fermyon
```

```
><> curl -i https://test-bad-paths-m77inmpi.fermyon.app/
HTTP/2 404
date: Thu, 25 Jul 2024 14:51:11 GMT
content-type: text/plain; charset=utf-8
content-length: 9

Not found
```

**Comment by bacongobbler** [comment]
I don't see anywhere on https://developer.fermyon.com/spin/v2/http-trigger#http-trigger-routes that talks about parameterized URL routes. Is this feature documented somewhere?

**Comment by bacongobbler** [comment]
Thread on Discord where this bug was discovered: https://discord.com/channels/926888690310053918/1024646765149950022/1265815717182439547

**Comment by bacongobbler** [comment]
Looking at https://github.com/fermyon/spin/pull/2464, this might be a new feature that was introduced in Spin 2.6, which would explain why it doesn't work on Fermyon Cloud; Fermyon Cloud is running on Spin 2.5 at the moment.

**Comment by itowlson** [comment]
Internal FC components have been updated but the updates are awaiting deployment.

**Comment by itowlson** [comment]
Re docs - they're at the link you posted.

![image](https://github.com/user-attachments/assets/45b09b2c-b16b-4ae0-9d8c-01c946e85234)

**Comment by bacongobbler** [comment]
Thanks - my 8AM brain must've been looking for a code block 😅
