### ISSUE TITLE
Spin 2.7 release 

### ISSUE THREAD

**Issue by me-diru** [fermyon/spin#2690]
A decision was made on the July 22nd Spin community meeting to have Spin 2.7 release
https://docs.google.com/document/d/1EG392gb8Eg-1ZEPDy18pgFZvMMrdAEybpCSufFXoe00/edit#bookmark=id.mqvnq7lc0rxb

Release process
https://github.com/fermyon/spin/blob/main/docs/content/release-process.md

- [x]  Release engineer assigned @me-diru 
- [x]  Release manager assigned @vdice 

Issues/Commits to track
- [x]  #2683 

Not sure about blockers
Referenced #2570

**Comment by me-diru** [comment]
cc: @vdice, maybe you can be the release manager?

**Comment by itowlson** [comment]
Can this be closed or are there outstanding tasks?

**Comment by vdice** [comment]
Thanks @itowlson we can close this.  The last remaining work item is docs-related (https://github.com/fermyon/developer/pull/1358) but the release has indeed been cut.
