### ISSUE TITLE
Modules with duplicate imports cannot be componentized

### ISSUE THREAD

**Issue by lann** [fermyon/spin#2778]
This is only known to be a problem for [Grain](https://grain-lang.org/) where a Hello World wasi preview1 module produces duplicate `fd_write` imports.

Duplicate imports are permitted in modules by the Wasm core spec but forbidden by the component model, which prevents these modules from being componentized.

Two plausible paths to fix this:

- Get Grain to deduplicate imports in the compiler: https://github.com/grain-lang/grain/issues/2152
- Build tooling to deduplicate imports

While fixing Grain is probably independently a good idea, we don't necessarily control that timing and it wouldn't help for existing modules. A discussion of how to build dedupe tooling can be found in [BA Zulip](https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/duplicate.20imports).

**Comment by lann** [comment]
It turns out this is only an issue for debug builds. [Compiling with `--release` solves the problem.](https://github.com/grain-lang/grain/issues/2152#issuecomment-2315678001)

**Comment by vdice** [comment]
@lann now that the [grain template](https://github.com/fermyon/spin/blob/d83330147584f87618dcbbb75d6422b660f3c39d/templates/http-grain/content/spin.toml#L16) and [language page](https://developer.fermyon.com/wasm-languages/grain) have been updated to use `--release`, do we still want to keep this open?  Untether from Spin 3.0 if so?

**Comment by lann** [comment]
No my understanding is that this is working as intended on the wasmtime side.
