### ISSUE TITLE
`spin new` failing for Rust on latest templates

### ISSUE THREAD

**Issue by calebschoepp** [fermyon/spin#2797]
When I run `spin new` for a new Rust app it fails when I run `spin build`.

```
Building component delete-me with `cargo build --target wasm32-wasi --release`
error: could not find `Cargo.toml` in `/Users/caleb/scratch/delete-me` or any parent directory
Error: Build command for component delete-me failed with status Exited(101)
```

Running `mv Cargo.toml.tmpl Cargo.toml` fixes the issue. I think that our Rust template is incorrectly generating the Cargo.toml file.

**Comment by lann** [comment]
Which template?

**Comment by lann** [comment]
```console
$ spin new -t http-rust -a testapp
$ ls testapp/Cargo.toml
testapp/Cargo.toml
```

**Comment by calebschoepp** [comment]
For `http-rust` template. Have you upgraded your templates to the latest?

**Comment by lann** [comment]
> For http-rust template. Have you upgraded your templates to the latest?

Yep. Also:

```console
$ spin --version
spin 2.8.0-pre0 (65c62d8b 2024-08-30)

**Comment by itowlson** [comment]
@calebschoepp It sure seems like you're running a version of the Spin CLI that doesn't know about the `.tmpl` convention.  But that went in 5 months ago, so it seems unlikely.  Can you check your Spin CLI version so we can determine if there's a regression?

**Comment by calebschoepp** [comment]
> But that went in 5 months ago, so it seems unlikely.

You severely underestimate me.

Looks like I was running `spin 2.5.0-pre0 (2efad6a1 2024-04-16)`. I installed the latest Spin and it works like a charm now.
