### ISSUE TITLE
Track, Agree Upon, and Document Breaking Semantic Changes

### ISSUE THREAD

**Issue by rylev** [fermyon/spin#2815]
Below is a list of the breaking semantic changes to the Spin runtime that will be coming in Spin 3.0. Before we release, we should ensure that we are all of with these changes, and then we should document them.

- [ ] `HttpRequestDenied` used to be returned from `wasi:http/outgoing-handler#handle` but are now returned from `wasi:http/types/future-incoming-response#get`
- [ ] https://github.com/fermyon/spin/pull/2723
- [x] https://github.com/fermyon/spin/issues/2552
- [ ] https://github.com/fermyon/developer/issues/1371
- [x] https://github.com/fermyon/developer/issues/1376
- [ ] Changes to the on-disk format for AI models

**Comment by michelleN** [comment]
@radu-matei @karthik2804 - are there documentation changes for the [llm-factor breaking changes](https://github.com/fermyon/spin/pull/2755) we need to add to this list?

**Comment by itowlson** [comment]
@rylev and SDK folks: do you know if/how:

> HttpRequestDenied used to be returned from wasi:http/outgoing-handler#handle but are now returned from wasi:http/types/future-incoming-response#get

would affect developers using the SDKs, as opposed to programming directly against wasi-http?  It seems like it would still manifest as an error in whatever async "send request" wrapper they use, just internally it would be in a slightly different part of the promise/future/task/whatever.  Does that sound right?

**Comment by rylev** [comment]
> would affect developers using the SDKs, as opposed to programming directly against wasi-http? It seems like it would still manifest as an error in whatever async "send request" wrapper they use, just internally it would be in a slightly different part of the promise/future/task/whatever. Does that sound right?

For example, for users of the Rust SDK, this shouldn't really make a difference as both API points are wrapped up in the [`executor::outgoing_request_send` function](https://github.com/fermyon/spin-rust-sdk/blob/1f07acf1a9aa527bfad10d555271f63680e9866c/src/http/executor.rs#L98-L107) and so it should look the same to the Rust SDK user no matter where the error surfaces. I've not looked at other SDKs, but we'd had to see if any of them don't abstract this away from the users. Of course, for those using the `wasi:http/outgoing-handler` API directly, they will be exposed to this difference. 

Re: the `authority` header:

You can see the full logic [here](https://github.com/fermyon/spin/blob/ac0414b1d3086aeb8a3a087ca64afaef57bd4144/crates/trigger-http/src/server.rs#L435-L450) - the logic changed a bit in https://github.com/fermyon/spin/pull/2747. The authority is determined by the host header or the URL authority (and they much match if both are present). 

Specifically, for a "self" request, the host header is always set (meaning that the host header will be responsible for the authority the guest will see), and it is [set here](https://github.com/fermyon/spin/blob/ac0414b1d3086aeb8a3a087ca64afaef57bd4144/crates/factor-outbound-http/src/wasi.rs#L181) to the [listener address of the running Spin server](https://github.com/fermyon/spin/blob/ac0414b1d3086aeb8a3a087ca64afaef57bd4144/crates/trigger-http/src/server.rs#L247). 

I'm actually not sure what the authority is set to in self requests in Spin 2.x - we should investigate that and document it. 

Does this clarify things?

**Comment by itowlson** [comment]
Thanks for the confirmation re the HTTP error.  I'll double check other SDKs but I think they all hide this (and yep, understood for folks working at the WASI level).

Thanks for the link to the authority code.  Unfortunately the low-level fragment hasn't really gotten me confident I have my head around what this means for application developers, but let me have another crack at some wording:

> Spin now infers the `authority` property of an incoming request from either the request URL or the HTTP `Host` header. (If the request includes both, then they must agree.) This will not usually result in any change of behaviour for "normal" requests from HTTP clients.

(I recognise that "normal" is handwavey here!)

> Spin now adds an HTTP `Host` header on `self` requests (those made using a path only). The value of the header is the listener address of the Spin HTTP server. Consequently, the component receiving the `self` request will always see the URL `authority` as that of the Spin HTTP server, just as if the request had come from an external client.

Does that correctly capture the effect at guest level of these changes?  Thanks!

**Comment by rylev** [comment]
These summaries seem largely good to me.

> This will not usually result in any change of behaviour for "normal" requests from HTTP clients.

This part, however, doesn't really track. Previously the authority was always set to the Spin server's listener address (much like is done now for `self` requests), and now it's based on the host header. So unless the client was making a direct against the listener address (instead of requesting for example against a DNS name that ultimately gets routed to the listener), the authority will change.

**Comment by itowlson** [comment]
Aha!  This is the missing piece.  Let me word it back to check I now have it right:

> Spin now infers the `authority` property of an incoming HTTP request from either the request URL or the HTTP `Host` header. (If the request includes both, then they must agree.)  This means that when a client makes the request through a DNS name, the authority will be that DNS name, rather than the Spin server's listener address.

(and, thus, modifying the text in self-requests about "as if the request had come from an external client")

Thanks!

**Comment by rylev** [comment]
> This means that when a client makes the request through a DNS name, the authority will be that DNS name, rather than the Spin server's listener address.

I think this is largely correct enough. There are more precise ways to formulate this, but for the purposes of change logs this might be the best balance between correctness and terseness.

**Comment by vdice** [comment]
By now we've had plenty of chance to disagree on the breaking changes linked above.  @itowlson's [docs PR](https://github.com/fermyon/developer/pull/1396) appears to cover the documentation front.  Are we good in considering https://github.com/fermyon/developer/pull/1396 closes this issue?

**Comment by rylev** [comment]
From my side, we can close this.
