### ISSUE TITLE
Running some Spin commands from project subdirectories

### ISSUE THREAD

**Issue by karthik2804** [fermyon/spin#2828]
It would be nice to be able to run commands like `spin build` and `spin up` from project sub-directories similar to how `git` works.

**Comment by lann** [comment]
To be explicit, this would search for `./spin.toml`, `../spin.toml`, `../../spin.toml`, etc. by default (when no `--from` is given).

Seems pretty reasonable to me. Probably worth printing a message like `Using spin manifest from ../../spin.toml` when this applies.
