### ISSUE TITLE
Support wasi-config

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/spin#2868]
WASI is moving wasi-config to phase 3 soon. We should consider moving from the [spin variables](https://github.com/fermyon/spin/blob/main/wit/variables.wit) interface to [WASI config](https://github.com/WebAssembly/wasi-runtime-config).

The main diff is the need to add support for `get-all`

Spin 3.0 may be a good opportunity to make this switch

**Comment by kate-goldenring** [comment]
I did a quick check on implementation feasibility of `get-all` for our current providers:
- For redis, taking a quick look, we should be able to keys and then mget on that set of keys: https://docs.rs/redis/latest/redis/trait.Commands.html
- For Azure, they provide a list_secrets command that should do the trick: https://docs.rs/redis/latest/redis/trait.Commands.html
- For env var, we just return the kv pairs for env vars with the expected `SPIN_VARIABLES` prefix

**Comment by lann** [comment]
`get-all` isn't a huge problem for Spin because all variables must be declared in the manifest, so its really just a `get-many`, which can itself be implemented in terms of plain `get` if needed.

**Comment by kate-goldenring** [comment]
@lann your point makes me think that the WASI config interface may want to rename that function. It defines [`get-all`](https://github.com/WebAssembly/wasi-runtime-config/blob/f4d699bc6dd77adad99fa1a2246d482225ec6485/wit/store.wit#L26C1-L29C67) as getting the set of KV pairs:
```
    /// Gets a list of configuration key-value pairs of type `string`.
    /// 
    /// If an error occurs, an `Err(error)` is returned.
    get-all: func() -> result<list<tuple<string, string>>, error>;
```
