### ISSUE TITLE
Proposal: implement the full `wasi:keyvalue` spec

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#2873]
As the champion of the [`wasi:keyvalue`](https://github.com/WebAssembly/wasi-keyvalue), a WASI Phase 2 proposal, I am seeking the Spin support in implementing the full specification of the `wasi:keyvalue` proposal. This would allow us to gather insightful feedback on the design and help advance the proposal to the next stage.

Spin is an [early adopter](https://github.com/fermyon/spin/blob/main/docs/content/sips/010-key-value.md) of `wasi:keyvalue` by implementing the `wasi:keyvalue/store` interface. Building on this, I propose that Spin extends its support to include the additional interfaces, specifically [atomic](https://github.com/WebAssembly/wasi-keyvalue/blob/main/wit/atomic.wit) and [batch](https://github.com/WebAssembly/wasi-keyvalue/blob/main/wit/batch.wit) operations.

* The atomic interface offers atomic operations such as `increment` and `cas`, which would make Spin applications that require atomic operations to avoid race conditions possible.
* The batch interface enables applications to operate on multiple keys at once, improving efficiency.

**Comment by lann** [comment]
Question relevant to Spin: https://github.com/WebAssembly/wasi-keyvalue/issues/48

**Comment by lann** [comment]
See also https://github.com/fermyon/spin/issues/2447

**Comment by Mossaka** [comment]
answered your question over wasi:keyvalue repo

**Comment by itowlson** [comment]
I believe this is what @devigned has kindly put his hand up for!

**Comment by devigned** [comment]
> I believe this is what @devigned has kindly put his hand up for!

That is correct.

**Comment by michelleN** [comment]
chatted with @devigned who is working on implementation this week. just an FYI

**Comment by devigned** [comment]
> Are we good to close this now that #2895 is in?

I believe so for `0.2.0-draft2`.
