### ISSUE TITLE
[OTel]: Spin should support `OTEL_EXPORTER_OTLP_HEADERS` 

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin#2880]
Having support for `OTEL_EXPORTER_OTLP_HEADERS` could unlock several scenarios. For example, we could support OTLP exporters that require header based authentication.

Spin should allow users to specify individual headers that will be used when emitting traces, logs, or metrics.

If the `OTEL_EXPORTER_OTLP_HEADERS` environment variable is present, Spin should configure outgoing headers on both `TonicExporterBuilder` and `HttpExporterBuilder` using the `with_headers` function 

(see https://docs.rs/opentelemetry-otlp/0.26.0/opentelemetry_otlp/struct.HttpExporterBuilder.html#method.with_headers for example) 

More about `OTEL_EXPORTER_OTLP_HEADERS`:

https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_headers

**Comment by ThorstenHans** [comment]
This has already been requested by @endocrimes in https://github.com/fermyon/spin/issues/2816

**Comment by lann** [comment]
Have you tried setting this env var already? The otel library we use appears to already support it (from a very brief code review).

**Comment by endocrimes** [comment]
https://github.com/fermyon/spin/pull/2857 it looks like it should work now

**Comment by ThorstenHans** [comment]
yep. Can confirm that it works 👍🏻
