### ISSUE TITLE
Raise error when trying to push app with local dependencies

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#2891]
When running `spin registry push ...` or `spin deploy` a check should happen on the locked app to be published that yields an error if any component in the app has a dependency referencing a wasm component located on disk.

E.g.:

```toml
[component.spin-animal-facts.dependencies]
"component:animal-facts/animal-facts" = { path = "animal_facts_dep.wasm" }
```

Alternatively, we could package and publish the dependencies transitively but that seems a little too magical.

**Comment by lann** [comment]
> we could package and publish the dependencies transitively but that seems a little too magical.

This is what I would expect to happen for local dependencies...

**Comment by fibonacci1729** [comment]
Fair. I was thinking about `cargo publish` and the dependency restrictions when trying to publish to crates but I suppose it makes more sense in this case.

**Comment by itowlson** [comment]
Removing local deps from the pushed app suggests a general policy of "we don't push deps as part of the app."  (Am I misreading this?  It would seem weird to keep bundling deps that are in the registry, which are presumably in least need of bundling, but unbundle the ones which aren't.)  Is that what is being suggested?

If so, I'd be concerned for issues like:

* deps that used the default registry (what if where the app is run has a different default registry)
* deps that specify a non-exact version constraint (what if it resolves to something different at run time)
* why does the non-bundling rule apply only to deps and not to primary components from registries

The current model of locking the stuff the user tested and including all of it in the app seems much safer to me...

**Comment by itowlson** [comment]
Okay, I had a misconception that we _did_ currently bundle local deps because Worked On My Machine, but that was because we bundle an absolutised file reference.  We don't bundle local deps and I think we should.  Apologies for the confusion.
