### ISSUE TITLE
Introspection API for components of the same application

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#290]
Say you're writing a multi-component application, and wish to send a request from component A to component B.
The issue here is that when writing the multiple components, there is no way of precisely knowing the application base path, nor the route a component will be configured for.
Which leaves the task of sending a request from component A to component B of the same Spin application unclear.

We could choose to expose an introspection API (or some methods on a context object) that would optionally return the different components of an application and the URL they can be reached at.

**Comment by michelleN** [comment]
Is this still something that we want to see happen? Does it still make sense given the current focus on composition and recently added self feature?

**Comment by lann** [comment]
I think the "self" feature covers the main request here. There are probably other introspectiony things that might be nice but we'd probably be better off working from more focused use cases.
