### ISSUE TITLE
LockedComponent` unaware of `tool` section

### ISSUE THREAD

**Issue by smndtrl** [fermyon/spin#2930]
I'm trying to enable a component with a "introspection" capability via a `factor`. My idea was to use the `tools` section as it's one of the few places in a spin manifest where I have the freedom to pass data. However, inside of the `prepare` function of the factor, I'm only able to access a selection of a few common fields and even using `MetadataKey`s, the `tools` section is not exposed.

Did I overlook something obvious? Could a `AppComponent` via `LockedComponent` expose `tools` directly or via metadata like it does with `build`?

**Comment by lann** [comment]
The `tool` sections are discarded by spin itself - they are intended to be parsed directly from TOML by external tools.

Could you say more about what you're trying to do?

**Comment by smndtrl** [comment]
I'm trying to have a arbitrary data object (toml::Table, serde_json::Value, ...) defined in the manifest and accessible by a `factor` for a component and by my `TriggerApp`. The trigger app leverages it to understand the worker configuration for the components. That works well using `app().trigger_configs(...)`. However for the components I haven't found a good way to access some typed data that's component related because the only flexible field in a manifest is `tool`. So for now the factor looks up the manifest path and loads it again to get the tool information there.

I imagined it could either be something like `tool` being accessible in `PrepareContext.app_component()` or something more akin to how the built-in factors use their `MetadataKey` in `app_component).get_metadata(...)`.

I'm fine with reloading the manifest to get component-level metadata that's specific to my weird usage scenario. I was just wondering if there's a better way to get to the data.

**Comment by smndtrl** [comment]
> for now I think you're running into an intentional design constraint.

This is what I thought and that's also fine. What I'm doing might fall more into the "custom-runtime-instead-of-spin" world. Yet building onto Spin makes everything so much easier for me as solo dev. I'm leveraging the config format, the whole loading of components (from oci), setting up/configuring of wasmtime and custom imports but everything else is very different. No triggers in that sense, the app is deployed once, runs and exits. A rather weird hybrid of a `command` trigger where the host environment provides a DAG execution model.
