### ISSUE TITLE
Install templates from a remote tarball

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#2955]
Broken out from #2555 @jandubois: 

> **There is no way to install templates from a remote tarball**
>
> Since we [sc. Rancher Desktop] can't rely on git being installed, we need to install using `--dir` from a local directory because there is no option to install from a remote tarball like this:
>
> `spin templates install --from https://github.com/fermyon/spin/archive/refs/heads/main.tar.gz`
>
> That means we need to download the file ourselves, unpack it into a temporary directory, install from there, and then remove the temporary directory again.
>
> Since we are doing this from a shell script, it means we need curl or wget, neither of which are guaranteed to be installed.

**Comment by jandubois** [comment]
Thank you! This will simplify our `setup-spin` logic, so we no longer need to hunt for `wget` or `curl`. Too late for 1.17.0, but I created a GitHub issue as a reminder.

**Comment by jandubois** [comment]
> Too late for 1.17.0, but I created a GitHub issue as a reminder.

We had to push the release to early January anyways, so still squeezing this into 1.17.

@itowlson Nice simplification for our `setup-spin` script: https://github.com/rancher-sandbox/rancher-desktop/pull/7982/files

The script was not properly cleaning up the temp directory inside WSL2 distros. So getting rid of that code is better than having to figure out what was wrong with it (things get confusing when you manipulate the same directory both on the host, and through the 9p mount).
