### ISSUE TITLE
Better error messages when component dependencies are not allowed to inherit configuration

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#2969]
Using Spin 3.1.0.

My Spin component has a dependency on a component which need access to an inference model. I did not configure `dependencies_inherit_configuration = true` for the Spin component, so the dependency would not get access to the model. The error message I was getting was not helping me track down the problem:

```
> spin up
Logging component stdio to ".spin/logs/"
Storing default key-value data to ".spin/sqlite_key_value.db".
Error: failed to resolve dependencies for component "challenge1"

Caused by:
   0: an error occurred when preparing dependencies
   1: encoding produced a component that failed validation
   2: type mismatch for import `wasi:sockets/udp-create-socket@0.2.0`
type mismatch in instance export `udp-socket`
resource types are not the same (ResourceId { globally_unique_id: 3, contextually_unique_id: 21 } vs. ResourceId { globally_unique_id: 3, contextually_unique_id: 102 }) (at offset 0x227e1ee)
```

The dependent component was built in Python, using componentize-py.

**Comment by itowlson** [comment]
@fibonacci1729 I guess this is something to do with the deny adapter: do you have a moment to look at it please?

**Comment by fibonacci1729** [comment]
Yep yep yep.

**Comment by lann** [comment]
This is a bug in the deny adapter triggered by importing the `wasi:sockets/{tcp,udp}-create-socket` interface(s). We hadn't seen this before because most components either don't import those interfaces (due to dead code elimination in e.g. Rust) or don't use dependencies.

**Comment by fibonacci1729** [comment]
This was a result of some weirdness around implicit imports for transitive uses in WIT and how things were being imported / exported in the adapter. The error a developer *should* see now is "Access Denied".
