### ISSUE TITLE
Feature: Add ability to generate bindle versions with prerelease info

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#297]
* Add a `--pre` bool flag to `spin bindle prepare|push`, wherein, if supplied, spin adds prerelease info for a resulting `name/version-<prerelease data>` bindle ID. The end result must be a unique, sortable, semver-compliant bindle ID.

One common source for prerelease data that lends itself to ordering is a timestamp.  The [Hippo CLI uses this approach](https://github.com/deislabs/hippo-cli/blob/a000de65a7b7126a06b28f56cf88a465ee6717c7/src/expander.rs#L45-L51).

**Comment by itowlson** [comment]
I believe this is accomplished with the generation of build metadata.  Please reopen if it needs further action!
