### ISSUE TITLE
pre-sip: Trigger "plugins"

### ISSUE THREAD

**Issue by lann** [fermyon/spin#302]
Currently we have "http" and "redis" triggers hard-coded in the `spin` bin. We also have `examples/spin-timer` which implements a `TimerTrigger`, but it is missing a lot of the functionality of `spin up`. Third-party triggers would be in the same position.

What if triggers were run by `exec`ing them as separate binaries? We could define a "spin trigger plugin interface" with certain arguments, env vars, open file descriptors, etc. that an external rust binary could implement by linking `spin/engine` et al (like `spin-timer` does). Then `rust up` would be responsible for configuration, fetching/unpacking components, etc. and then `exec`ing that binary.

Git (among other tools) uses a similar model for several features like ["remote helpers"](https://git-scm.com/docs/gitremote-helpers).

We could even have built-in triggers like "http" use this same interface by "reexecing" them as e.g. `spin internal http-trigger` subcommands.

**Comment by radu-matei** [comment]
This is also similar to the way `cargo` external commands work, I like this idea a lot!

This might also be a good time to revisit the configuration split (ref #86).
