### ISSUE TITLE
Spin process cannot be reached remotely?

### ISSUE THREAD

**Issue by mreferre** [fermyon/spin#310]
I am testing the workflow in the tutorial to run the `http-rust` example and it works fine locally (from another shell of the same instance where the process is running): 
```
ubuntu@ip-172-31-51-195:~$ curl localhost:3000/hello
Hello, Fermyon
```

However, if I try to connect remotely (from either a browser or a remote computer shell) the connection is refused: 
```
mreferre@b0de288e8b67 keys % curl http://44.xxx.xxx.xxx:3000/hello
curl: (7) Failed to connect to 44.xxx.xxx.xxx port 3000: Connection refused
mreferre@b0de288e8b67 keys % 
```
This is an EC2 instance with all inbound ports open to 0.0.0.0 (I tested it shutting down spin and starting an nginx exposed on port 3000 and it worked so I know the security groups are letting the traffic flow): 
```
mreferre@b0de288e8b67 keys % curl http://44.xxx.xxx.xxx:3000      
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

Is it possible in any way that spin is currently being configured to only accept local traffic in the way the process bind the local IP stack (or better, is there a parameter that needs to be tweaked to allow no local traffic?)   

Thanks!

**Comment by radu-matei** [comment]
Hi, thanks for filing this issue!

Could you try binding Spin to `0.0.0.0:3000`:

```
$ spin up --listen 0.0.0.0:3000
```

**Comment by mreferre** [comment]
Doh... that was it. I was looking for that parameter with `spin --help` but I have just realized it shows up with `spin up --help`. Thanks. It works now.
