### ISSUE TITLE
refactor: Host components

### ISSUE THREAD

**Issue by lann** [fermyon/spin#311]
Currently, host-implemented interfaces have to be hard-coded in `engine` in a couple of places:
- the implementation state is included in `RuntimeContext`: https://github.com/fermyon/spin/blob/2be403465390f1a767181f16190aa4f14512c9f3/crates/engine/src/lib.rs#L49-L50
- a `link_*` method, which is called in `build_default`: https://github.com/fermyon/spin/blob/2be403465390f1a767181f16190aa4f14512c9f3/crates/engine/src/lib.rs#L106-L108

I'd like to invert this dependency by introducing a new `HostComponent` trait. After a little prototyping I think it can look something like:
```rust
pub trait HostComponent {
    type State: Default + 'static;
    fn add_to_linker<T>(id: String, linker: &mut wasmtime::Linker<crate::RuntimeContext<T>>);
    fn initial_state(id: String) -> State;
}
```
implemented like:
```rust
impl HostComponent for OutboundHttp {
    type State = Self;
    fn add_to_linker<T>(id: String, linker: &mut Linker<RuntimeContext<T>>) {
        wasi_outbound_http::add_to_linker(linker, |ctx| ctx.host_components.get_state(&id).unwrap())
    }
}
```
_Note: The separate `State` type isn't necessary here but is needed for interfaces that use reftypes, which changes their state data type._

The component state would be held in a mapping on `RuntimeContext` as e.g.:
```rust
/// Host components data,
pub host_components: HashMap<String, Box<dyn Any>>,
```

There might be a performance issue here as this HashMap would be referenced once for every host component function call, but if that is the case we could switch to a more efficient form of mapping (perhaps a Vec with pre-computed indexes or even something more exotic/unsafe :grimacing:). If performance is a real problem here I _think_ its a solvable one but its a real tradeoff vs the organizational benefits of splitting things up like this. Other ideas for how to do this very welcome.

**Comment by lann** [comment]
How should configuration work for these? A solution that might fit with our current manifest:
```toml
[host-components]
file-object-store = { root = "..." }
outbound-http = { allowed_hosts = [ ... ] }
```

Longer-term, I wonder if these could be combined with "normal" component dependencies.

**Comment by itowlson** [comment]
Should the configuration of these be in the application manifest, or in an environment configuration?  For example, the object store that backs onto a local directory in dev but onto AWS in prod; outbound HTTP that allows connections to the bank's test environment in dev but the real monies in prod.

This may relate to having a general think about how we divide up developer/operator decisions...

**Comment by lann** [comment]
It "should" be in the environment config, but we haven't got one.

**Comment by itowlson** [comment]
As 'components' is already a heavily loaded word, could I suggest we call these 'host services'?  'Services' is a rarely used term that has no associated expectations, and will never lead to ambiguity.

Seriously... I'm jittery about the name 'component', as in the Spin environment it could easily cause confusion with the concept referred to by the `[[component]]` entries.  The idea of treating them like dependencies which happen to be satisfied by the host rather than another Wasm module is certainly attractive, though.

**Comment by lann** [comment]
"Host services" is exactly what I first thought to call them, and then I was attracted to them being dependencies that just happen to be satisfied by the host. 🙂

**Comment by radu-matei** [comment]
In some places, we have been referring to one of these as a "host implementation for a WebAssembly interface", which isn't terribly helpful either.

**Comment by lann** [comment]
Part of my rationale for intentionally conflating them with "normal" components derives from https://github.com/WebAssembly/module-linking/blob/main/design/proposals/module-linking/Explainer.md#link-time-virtualization

Being able to use host or wasm implementations of an interface interchangeably is an explicit goal of the wasm component model.

**Comment by radu-matei** [comment]
I strongly agree with being able to use "host services / components" and "normal components" interchangeably. 

New proposal that supersedes module linking and interface types — https://github.com/WebAssembly/component-model

(and link to your example — https://github.com/WebAssembly/component-model/blob/main/design/mvp/examples/LinkTimeVirtualization.md)
