### ISSUE TITLE
Rust SDK: Query params seem to be missing from http::Request

### ISSUE THREAD

**Issue by technosophos** [fermyon/spin#313]
If I send a request like `http://localhost:3000/index?foo=bar&baz=sprocket`, I would expect the query parameters to be available on the URI object.

However, if I do `req.uri()`, the URL does not have query parameters attached. This is easy to replicate by just printing the `uri()`. However, since currently every request seems to be automatically printed to STDOUT, you can see this in the log without doing anything special.

Command: `curl localhost:3000/tally\?ulid=1234\&foo=bar` (Note that backslashes are just for shell escaping)

Content of the STDOUT log:
```
Request { method: GET, uri: /tally, version: HTTP/1.1, headers: {"host": "localhost:3000", "user-agent": "curl/7.77.0", "accept": "*/*", "spin-path-info": "", "spin-full-url": "http://localhost:3000/tally", "spin-matched-route": "/tally", "spin-base-path": "/", "spin-raw-component-route": "/tally", "spin-component-route": "/tally"}, body: Some(b"") }
```

**Comment by itowlson** [comment]
This has been a source of vigorous discussion and (to me at least) total confusion.

The `uri` field in the `Request` object is _NOT_ the full URI.  As I understand it, it is the _path relative to the application root._

My advice to young developers such as yourself is to avoid `uri` altogether, and use the various headers which are much less ambiguous about what they mean.  (See https://spin.fermyon.dev/http-trigger and scroll down to "The default headers set in Spin HTTP components.)

@radu-matei Do we document the semantics of the `uri` field?  I thought we planned to but can't see it on the HTTP trigger page.

**Comment by itowlson** [comment]
The discussion is here, and if the final post is still current, further demonstrates my confusion - apparently the `uri` is the absolute path not the relative path.

https://github.com/fermyon/spin/issues/72

**Comment by itowlson** [comment]
Hang on, the Request object passed to the SDK handler method doesn't seem to match the "HTTP objects" described on the https://spin.fermyon.dev/http-trigger page.  So maybe I am completely misleading you.

**Comment by itowlson** [comment]
I think the SDK macro is generating a Rust `http::Request` object from the WIT `uri` as if that was a _full_ URL.

@fibonacci1729 I think at https://github.com/fermyon/spin/blob/2be403465390f1a767181f16190aa4f14512c9f3/sdk/rust/macro/src/lib.rs#L52 you need to be reconstructing the URI using the `params` member of the source object, or using the `spin-full-url` header.

**Comment by technosophos** [comment]
I am not sure what you are suggesting, but inside of a component, the only thing I get is the `http::Request`, and the canonical way to get the params off of the `Request` is to use the `uri().query()` method... and that is empty every time.

**Comment by itowlson** [comment]
Yeah I think the Spin site (and the issue I linked to) covers the "raw" request type and I hadn't clocked that the macro SDK converts it to the "native" Request type (but that the macro contains a bug).  Sorry.

**Comment by technosophos** [comment]
I have been using these two things as reference:

- https://spin.fermyon.dev/rust-components/
- https://github.com/fermyon/spin-kitchensink/tree/main/rust-outbound-http

If you wanna direct me to something else, I'll give it a try.

**Comment by itowlson** [comment]
No, it's just a bug in the SDK, hence tagging Brian with the location of the bug.  Sorry for confusing the issue.

**Comment by radu-matei** [comment]
@itowlson 
We have discussed this at length back when #72 was initially opened, and we  agreed that `request.uri` should contain the _absolute path of a request_, so I am not sure I follow the confusion after resolving #72.

> the canonical way to get the params off of the `Request` is to use the `uri().query()` method... and that is empty every time.

This is how the parameters should be obtained when using the Rust SDK, and this is definitely a bug.
(including the fact that the full URL headers should also include the query parameters)
