### ISSUE TITLE
Publish `spin-sdk` to crates.io

### ISSUE THREAD

**Issue by lann** [fermyon/spin#316]
In addition to adding required fields to `Cargo.toml`, we'll need to remove any `git` dependencies:

- `wasi-experimental-http` just needs to be pointed at the published crate (does that crate need an update?)
- `wit-bindgen-*` aren't published, so we have a few options:
  - publish our own forks, e.g. `spin-wit-bindgen-*`
  - vendor what we need into the crate (I don't know how hard this is with publishing crates?)
  - statically generate the bindings with `wit-bindgen`; this feels best to me, but would require changes to the sdk macro(s)

**Comment by fibonacci1729** [comment]
I have no objections!

**Comment by radu-matei** [comment]
I also have no objections.

We would have to update the release process to also publish the new crates (see how we do it in Krustlet):

https://github.com/krustlet/krustlet/blob/710eae6f7127d5a84dc08f3f1c1949fb44e7d647/.github/workflows/release.yml#L136-L141

**Comment by radu-matei** [comment]
ref https://github.com/bytecodealliance/wit-bindgen/pull/193

**Comment by itowlson** [comment]
I noticed that `libsql-client` is on crates.io and it depends on the Spin SDK, so I'm wondering if the ban on git dependencies has been relaxed?  Or am I missing something?  https://crates.io/crates/libsql-client/0.31.8/dependencies

**Comment by lann** [comment]
Maybe allowed because it is an optional non-default dependency? 🤷

**Comment by lann** [comment]
As of 2.0 we no longer have any git dependencies in `spin-sdk`, so this should be unblocked.

**Comment by vdice** [comment]
Closed by https://github.com/fermyon/spin/pull/2151 and https://github.com/fermyon/spin/pull/2160.  See https://crates.io/crates/spin-sdk.
