### ISSUE TITLE
Rename `config` crate

### ISSUE THREAD

**Issue by lann** [fermyon/spin#318]
After discussion about a better name for application config, we're going to rename the current `config` crate to `manifest` and use `config` for #307 unless we can come up with better names for those two things.

**Comment by lann** [comment]
Do we want to refer to `spin.toml` as a "spin application manifest" in the docs?

**Comment by radu-matei** [comment]
"Spin application manifest" sounds good to me.

**Comment by lann** [comment]
@itowlson we discussed this today in a component registry pre-meeting after-party.

**Comment by itowlson** [comment]
@lann Pre-meeting after-party?!  You folks sure know how to live it up.  Anyway, if the conclusion was to carry on as discussed in this thread, then sounds good to me.
