### ISSUE TITLE
Zig binaries that work with Wasmtime do not work with Spin

### ISSUE THREAD

**Issue by technosophos** [fermyon/spin#321]
Here is a simple Zig file:

```zig
const std = @import("std");

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("content-type: text/plain\n\n", .{});
    try stdout.print("Hello, {s}!\n", .{"world"});
}
```

Build the above with:

```console
$ zig build-exe -O ReleaseSmall -target wasm32-wasi src/main.zig
```

On Wasmtime, this works:

```console
$ wasmtime main.wasm  
content-type: text/plain

Hello, world!
```

On Spin, this does not:

```console
$ curl localhost:3000/zig-hello -v
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /zig-hello HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 0
< date: Wed, 06 Apr 2022 03:07:00 GMT
< 
* Connection #0 to host localhost left intact
```

Server:

```console
$ spin up
Serving HTTP on address http://127.0.0.1:3000
2022-04-06T03:07:00.993155Z ERROR spin_http_engine: Error processing request: Exited with i32 exit status 0
wasm backtrace:
    0:  0x1b1 - <unknown>!<wasm function 2>
```

(Incidentally, same on Wagi)

**Comment by technosophos** [comment]
And to make it more confusing... compiling C to Wasm with Zig works great.

```c
#include <stdio.h>
#include <stdlib.h>

int main() {
    printf("Content-Type: text/plain\n\n");
    printf("Hello, World\n");
}
```

```
zig build-exe -O ReleaseSmall -target wasm32-wasi hello.c -lc
```

**Comment by itowlson** [comment]
Observations:

* The function that it fails to find is consistently the entry function.

A few things that _didn't_ help:

* Tried a debug build and it didn't make any difference.
* I noticed that Zig calls functions by index - it doesn't emit names.  So I tried hacking in a name for the entry func via the .wat file but that didn't seem to help either.
* Invoking `wasmtime run --invoke _start` works fine, so it's not the explicit entry point name.

**Comment by itowlson** [comment]
Okay, `unknown` is a red herring.  That's just the (unknown) module name, being written to the standard Display implementation for `wasmtime::Trap`.

I'm wondering if this is ye olde process exit woe.  The generated Wasm calls the `proc_exit` WASI function, which traps.  We saw this, I recall, in Krustlet, where a Rust program that returned a `Result` (or was it that it called the stdlib process exit?  can't remember) would call `proc_exit` that at the time _actually terminated the process_ and now just traps.  Are we treating the (benign) exit trap as an error trap?

**Comment by itowlson** [comment]
Yes

`TrapReason::I32Exit(status) => write!(f, "Exited with i32 exit status {}", status)`

which is exactly what we see in the Spin/Wagi error.

**Comment by itowlson** [comment]
Okay that's definitely what's going on.  Not sure of the correct fix yet, and I'm starting to flag.  In Krustlet we patched the WASI import table to map `proc_exit` to something less fatal.  But I feel like there ought to be a trap handler somewhere.

**Comment by itowlson** [comment]
We should be able to get the trap from the result of `Func::call`, and just pass over it if it's an error, but that method wraps the Trap in an `anyhow::Error`!  It looks like we can get back to the trap via `root_cause` and a `downcast_ref` though.

**Comment by itowlson** [comment]
Side note: we should aim to pass module names to Wasmtime for diagnostic purposes.  I thought Wagi did this so it might be that the `I32Exit` trap with Wasmtime doesn't associate a module name.  Something to look into.
