### ISSUE TITLE
Hot reload of Wasm artifact(s)

### ISSUE THREAD

**Issue by mreferre** [fermyon/spin#324]
A quick tests I have done seems to indicate that Spin does not support hot reloading of Wasm artifacts. The use case would be to have a fleet of Spin "servers" with a remote file system mounted where the Wasm artifacts leave and an update to the app would be as simple as re-provisioning the artifact(s) on the shared volume. This works today if you restart the Spin process (it apparently does not hot reload the new file/version). I think this would be a very useful feature but I don't have a good feeling re if this is a "yeah we will get there" or a "this is just technically impossible with the current state of the art". 

Thoughts? I personally think this would be a useful feature (in some circumstances, surely not if your updates require blue/green or canary etc).

**Comment by itowlson** [comment]
There's some discussion of this in #148 - certainly something we're thinking about, but as your last paragraph notes it's something we need to approach carefully!

For now, we have a sample Node script that can restart if a file changes - see the `spin` script in https://github.com/fermyon/spin/blob/main/docs/package.json.

**Comment by mreferre** [comment]
Thanks. Good to know. To be clear (and to check if I am understanding correctly), that issue is more for external files that are consumed by a Spin-ned application (not for a change of the Wasm module itself). However, the same technique can be applied to Wasm artifacts when they change. For now this is possible via an external application/process that runs and "watches" Wasm artifacts changes but possibly, in the future, it could/should be implemented as a feature flag in Spin that would be able to "auto-reload" when it detects a change. 

Am I getting it right? Thanks for the super fast turn around BTW.

**Comment by radu-matei** [comment]
As you correctly point out, there are two types of files we could watch for changes:

- WebAssembly modules (from the `source` field in the Spin component manifest) — we currently create a module from the source and create pre-instances at startup, i.e. we only read the `.wasm` file once, then, for each new request, we use the pre-instance to create the final instance that handles the request. 
- external static assets (from the `files` field in the Spin component manifest) — as @itowlson points out, at startup we _copy_ all static assets in a temporary directory and _mount the temporary directory_. This means that, as observed in #148, changes in the current directory are not reflected in the Spin application until a restart.

Thinking about a solution that would hot-reload Wasm sources, this would somehow need to tie into the execution context instantiation workflow (which is currently executed when building the execution context):

https://github.com/fermyon/spin/blob/6d650ef75cddb93d6c46f876226b269d28ab769d/crates/engine/src/lib.rs#L119-L143\

Would a `--reload` (or similar) flag to `spin up` that watches for file changes and _restarts_ Spin address this issue for you, even if not in the most performant way, for now?

**Comment by mreferre** [comment]
Your first bullet points confuses me a bit because you are talking about the `source` folder but I thought what Spin cares about would be only the `target` folder containing the compiled artifacts. 

Having that said, yes, a `--watch` or `--reload` parameter for `spin up` that would auto-reload what needs to be reloaded to serve a brand new version of the module transparently is what I was looking for. The flow I have in mind would be something like: 

-  `cargo build --target wasm32-wasi --release` 
-  `spin up --listen 0.0.0.0:3000 --reload` 
-   at this point you are serving the app 
-   tweak the source of the Rust application 
-  `cargo build --target wasm32-wasi --release` 
-  at this point you are serving the new version of the app (without having to stop / restart the spin process)

**Comment by radu-matei** [comment]
Sorry for the confusion, I meant the `source` field in the Spin component manifest (`spin.toml`):

```
...
[[component]]
id = "hello"
source = "target/wasm32-wasi/release/spinhelloworld.wasm" # this is the `source` I was referring to
```

The workflow you are describing looks good to me!

**Comment by mreferre** [comment]
Disclaimer: I know nothing about rust and your tutorial was the first time I ran a `cargo something something` so I am the last one that could comment on *how* to implement this. :)

**Comment by mreferre** [comment]
> Having an in-between bytecode layer allows you to build application architectures in rust that would not be possible when compiling directly to machine code. ***Hot reloading is a good example***. Having the VM hold onto resources like tcp streams and file descriptors allows you to exchange the business logic without even breaking a tcp connection.

From (https://news.ycombinator.com/item?id=30875310) 

:)

**Comment by miketang84** [comment]
So wish this issue could advance.

**Comment by allurefx** [comment]
Yes, a hot reload of spin would be great. I raised this in Discord and then discovered this issue already created. Changes to frontend are especially frequent (at least for me), and having to restart spin for every single change manually is inconvenient. Fermyon, please implement this, at least to do simple restarts on file changes.

As a workaround, I created this small script if anyone else wants to do something similar:
`#!/bin/sh

spin up --follow-all &
while inotifywait -qq -e modify ../client/dist; do
  killall spin
  spin up --follow-all &
done`

**Comment by dicej** [comment]
Just a quick FYI related to this issue: the `--direct-mounts` option to `spin up` allows you to modify static assets in-place and have your Spin app see the updates without restarting `spin up`.  That's useful if you're iterating on an SPA or something similar involving static content.  It's not a solution if you're iterating on the backend code, which is the point of true hot reload, but it at least addresses part of the problem.

**Comment by allurefx** [comment]
Yes, this works, thank you! Sure it is only for front-end changes, but this is where I'm iterating most right now, so it's very helpful. Thanks again, you guys are amazingly responsive.

**Comment by calebschoepp** [comment]
Just sharing a link to a prototype version of a `spin watch` command https://github.com/fermyon/spin/pull/1164

**Comment by calebschoepp** [comment]
Closing now that #1237 has merged
