### ISSUE TITLE
More troubleshooting tips

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#333]
Tracking thread for additions to troubleshooting docs.

**Comment by itowlson** [comment]
The error you get when you give a WAGI module to the Spin executor is distinctive, but unhelpful in itself.  Let's add it to the docs / troubleshooting guide.  Yes, I have been bitten by this repeatedly.

**Comment by jdbohrman** [comment]
This is great @itowlson! This is the exact type of info I'm trying to gather in the Airtable so I appreciate this.

**Comment by itowlson** [comment]
We haven't really built up a corpus of common issues and their resolution (the one mentioned here has been kludged around), so I'm closing this.
