### ISSUE TITLE
Add Badges

### ISSUE THREAD

**Issue by jdbohrman** [fermyon/spin#343]
We should probably add badges to this repo to things like:

- Discord
- Youtube
- Twitter
- Build Status
- Software Security Status
- Etc

**Comment by itowlson** [comment]
@tpmccallum @mikkelhegn Is this something you'd like to see (and feel inclined to take on)?  If not, I will close.

**Comment by tpmccallum** [comment]
Thanks @itowlson 
I hope I understand this "Add Badges" request. 
We currently link to Twitter and GitHub from all official documentation pages (in spin.fermyon.dev area) which is probably enough for now i.e. not sure about adding YouTube etc.
In saying all of this, @mikkelhegn and I (and others) are looking into making some pretty significant changes to the docs (to provide consistency across all of the docs present and upcoming). We should perhaps look at adding Discord, GitHub, Twitter to the new structure (I think the links should be at the surface (landing page) of all of the docs perhaps). So I think this can be closed, as suggested.
