### ISSUE TITLE
Build and test Go SDK in CI

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#344]
Currently, the Spin SDK for Go is not built and tested in CI, nor is any TinyGo component run as part of the integration tests.

**Comment by VishnuJin** [comment]
@radu-matei  @vdice is this already resolved ? 
https://github.com/fermyon/spin/blob/5f66daf80541363ec6d858b0462042e1104d3b64/.github/workflows/build.yml#L92-L103

**Comment by radu-matei** [comment]
Ah, you are right, @adamreese already fixed this a few weeks ago.
Thanks for checking, @VishnuJin!
