### ISSUE TITLE
Cron / timer triggered components

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#365]
It would be helpful to be able to write components and applications triggered by [a cron schedule](https://crontab.guru/).

Each component in a "cron" application would be able to define its own schedule.

**Comment by radu-matei** [comment]
@ecumene has started experimenting with this - ref https://github.com/ecumene/spin/blob/cron/crates/schedule/src/lib.rs#L77

**Comment by vdice** [comment]
Is this still intended for the upcoming v0.3.0 release?  Or should we remove the milestone for now?

**Comment by itowlson** [comment]
done https://github.com/fermyon/spin-trigger-cron

**Comment by seungjin** [comment]
Async please. 
https://discord.com/channels/926888690310053918/1219179630972502090/1219691510883418112

**Comment by itowlson** [comment]
@seungjin Completely agree, but I'm pretty sure that would need to be done in the cron trigger repo, not in Spin itself.  Could you raise an issue via https://github.com/fermyon/spin-trigger-cron/issues/new please?  Thanks!
