### ISSUE TITLE
JavaScript / TypeScript support

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#366]
JavaScript is the most popular programming language.
It would be extremely helpful to have support for it in Spin.

**Comment by Deepansharora27** [comment]
Hi @radu-matei 
For JavaScript Support, do you plan to make use of any existing toolchains ?

**Comment by radu-matei** [comment]
Oh yeah, we want to be able to reuse existing JS engines and use as much of the NPM ecosystem as possible (of course, packages that don't use the system, networking stack..)

We haven't made a lot of progress here, but the idea is to use SpiderMonkey as the JavaScript engine and do module linking with the user defined JavaScript.
ref https://github.com/bytecodealliance/spidermonkey-wasm-rs

Are you interested in collaborating on it?

**Comment by Deepansharora27** [comment]
Thanks a lot, Radu, I would love to.

But, I am not sure about the roadmap of how, to begin with, this?

**Comment by Deepansharora27** [comment]
Also by any means Can the Javy Toolchain play a role in accomplishing the goal for JavaScript Support ?

**Comment by itowlson** [comment]
@dicej @karthik2804 Okay to close?

**Comment by dicej** [comment]
The Spin JS/TS SDK can be found here: https://github.com/fermyon/spin-js-sdk
