### ISSUE TITLE
Track code coverage

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#367]
We should consider tracking code coverage for Spin.

A possible solution could be https://github.com/xd009642/tarpaulin and https://about.codecov.io.

**Comment by jdbohrman** [comment]
This is kinda relevant to #343 also

**Comment by lann** [comment]
I find tarpaulin + [this extension](https://marketplace.visualstudio.com/items?itemName=markis.code-coverage) pretty helpful.

**Comment by FrankYang0529** [comment]
I tried tarpaulin on Ubuntu 22.04. My command is `cargo tarpaulin -v --skip-clean -t 600 --out html` and it uses `Ptrace` engine to track the coverage. The coverage result is 24.47%. I will add it to the CI flow with codecov.io.

GitHub can't upload HTML files, so I add the extension `.txt`.
[tarpaulin-report.html.txt](https://github.com/fermyon/spin/files/9894122/tarpaulin-report.html.txt)
