### ISSUE TITLE
HTML anchor to link to subsections of a documentation page

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#369]
For example, https://spin.fermyon.dev/configuration#examples should scroll to the "Examples" section in the page, and it should be possible to obtain the link to such a section.

cc @flynnduism

**Comment by vdice** [comment]
I'm seeing both of the requested items being met when I nav to the aforementioned URL.  Can you confirm @radu-matei ?

**Comment by itowlson** [comment]
This looks fixed to me (same as @vdice saw).  I'm closing it - if anyone is still seeing the problem then please re-open.
