### ISSUE TITLE
Default Twitter card for documentation website

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#373]
It would be great to have a Twitter card that shows when we share links to Spin documentation, similar to those for Fermyon.com

cc @flynnduism

**Comment by flynnduism** [comment]
I'll make one of these now and open a PR to add it to the docs `<head>`.

In addition, we should add a social graphic to the repo for when `https://github.com/fermyon/spin` is shared. 
@radu-matei can you add this to the repo settings?

![github-repo-social](https://user-images.githubusercontent.com/686194/164290710-b34171cb-8579-4baa-9762-eece9140be72.png)

**Comment by radu-matei** [comment]
Done.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/13103165/164363977-cb7e1425-651a-4a25-a0ce-fe73ecc93922.png">
