### ISSUE TITLE
Make Application clonable 

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#376]
We should make `Application` clonable, such that it could be used to constrct customized `ExecutionContext`.

```rust
  --> crates/manifest/src/lib.rs:23:5
   |
14 | #[derive(Clone, Debug)]
   |          ----- in this derive macro expansion
...
23 |     pub config_resolver: Option<Resolver>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `Resolver`
   |
   = note: required because of the requirements on the impl of `Clone` for `std::option::Option<Resolver>`
   = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `spin-manifest` due to previous error
```

One approach to do this is to change the type of config_resolver to `Option<Arc<Resolver>>`

Discussed with @radu-matei on this issue this morning.

**Comment by radu-matei** [comment]
cc @lann

**Comment by lann** [comment]
I'd really like to remove `Application` from trigger initialization, but unfortunately the HTTP trigger config is currently deeply woven into the component config.

In the meantime it should be fine to wrap `config_resolver` in an `Arc`. It does currently get mutated in the `spin up` init code (which I need to find a better way of dealing with), but it shouldn't be cloned prior to that so `Arc::get_mut` ought to work there. If you don't intend to make that change I can.

**Comment by Mossaka** [comment]
@lann thanks for your response! I can get the commented code uncommented.

**Comment by lann** [comment]
I happen to be working on some related code so I'll be making this change. If you've already done it I'll take care of conflicts later.

**Comment by Mossaka** [comment]
Sure go ahead!
