### ISSUE TITLE
Server shutdown handler

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#378]
Currently the only way to exit the http server is to do "ctrl c". It would be great to add a shutdown handler that allows application to decide when to shutdown spin http server. 

I am proposing a new method called `shutdown_handle` that will return a handle to shutdown the server. 

```rust
let server = HttpTrigger::new(
    "0.0.0.0:80".to_string(),
    app,
    None,
    None,
    Some(engine.clone()),
).await
 .unwrap();

handle = server.shutdown_handle()
std::thread::spawn(move || {
    std::thread::sleep(std::time::Duration::from_secs(5));
    handle.shutdown();
});

http.run().await.unwrap();
```

**Comment by itowlson** [comment]
We definitely want to decouple trigger lifetime from process lifetime.  Another possibility is a `shutdown` method on the trigger itself, but that feels like it might run into lifetime and borrowing issues, plus the shutdown token allows more flexibility in terms of passing it up to whatever supervision layer is hosting the trigger.  So I like this approach - thanks!

When you said "propose" were you thinking you'd like to send a PR, or just suggesting the feature?  (Either is great - just want to know where to take the conversation from here.)

**Comment by lann** [comment]
Could you describe the kind of feature ("user story") this would enable?

**Comment by Mossaka** [comment]
I spawned a thread that calls `http.run().await.unwrap();` but since this is running indefinitely I want a way to kill this thread.

**Comment by lann** [comment]
Take a look at how the ctrl-c shutdown works: https://github.com/fermyon/spin/blob/061772803f8f59936a218c5420e53c707d5d9914/crates/http/src/lib.rs#L293-L302

Note that there is no explicit call to shutdown here; instead, `server` (the `Future` returned from `hyper::Server...serve`) is `tokio::select!`ed along with `shutdown_signal`. When `shutdown_signal` resolves on ctrl-c, `server` is `drop`ed, which is what shuts down the HTTP listener.

You can make your own shutdown signal with a channel; see how `on_ctrl_c` does it: https://github.com/fermyon/spin/blob/061772803f8f59936a218c5420e53c707d5d9914/crates/http/src/lib.rs#L327-L336

By `select!`ing this new signal channel along with the `Future` returned from `HttpTrigger.serve`, you can get the same effect.

**Comment by itowlson** [comment]
But how would that look from the point of view of someone hosting the trigger?  The `run()` method is opaque - how do you propose hosts inject this new signal?  (Agree that providing a way to inject a signal is a viable alternative to the "yield a shutter downer object" design though.)

**Comment by lann** [comment]
Oops, by `HttpTrigger.serve` above I should have written `HttpTrigger.run`. In either case, dropping the Future should (I _think_) shutdown the HTTP listener.

**Comment by Mossaka** [comment]
Just want to share to those who want to embed Spin to your applications, you can shutdown the Spin server by doing:

```rust
let server = http_trigger.run(spin_http_engine::HttpTriggerExecutionConfig::new(
    SPIN_ADDR.to_string(),
    None,
));

tokio::select! {
    _ = server => {
        log::info!(" >>> Server shut down: exiting");
    },
    _ = shutdown_signal => {
        log::info!(" >>> User requested shutdown: exiting");
    },
};
```
