### ISSUE TITLE
Feature: App integration testing harness

### ISSUE THREAD

**Issue by lann** [fermyon/spin#383]
As a parallel to #352 it would be great to have a `spin test` subcommand that can run integration tests against a Spin app. Along with being a useful user feature, we would benefit from being able to easily CI against our `examples/`.

A minimal version of this might just `spin up` the app, run a test command configured in `spin.toml`, then SIGINT the app.

**Comment by lann** [comment]
cc @radu-matei

**Comment by melissaklein24** [comment]
This has been done in https://github.com/fermyon/spin-test
