### ISSUE TITLE
Feature: Include `trigger.base` in "Serving HTTPS on address https://..." message 

### ISSUE THREAD

**Issue by lann** [fermyon/spin#385]
For apps that set it, it would be a helpful reminder of what URL to use for testing.

~Bonus points: if there is only a single http trigger component, append its `component.trigger.route`, too.~
Even better: :point_down:

**Comment by radu-matei** [comment]
ref #177 

Even for multiple HTTP components, it would be helpful to see all routes as well, in something like a "summary".
