### ISSUE TITLE
Docs: Add a note about TinyGo requiring Go "version 1.15 through 1.17"

### ISSUE THREAD

**Issue by lann** [fermyon/spin#386]
We link to the TinyGo docs, which only mention:

> We recommend Go v1.17+.

But if you have Go 1.18, it fails:

```
tinygo build -wasm-abi=generic -target=wasi -gc=leaking -o main.wasm main.go
error: requires go version 1.15 through 1.17, got go1.18
```

**Comment by 0xcodeboi** [comment]
I had recently added Go to the dev container, but defaulted to the [latest version (1.18.1)](https://github.com/fermyon/spin/blob/main/.devcontainer/Dockerfile#L15). We should probably bump that down to the latest 1.17.x release too!

https://github.com/tinygo-org/tinygo/issues/2768#issuecomment-1095453425 suggests we can change this when TinyGo version 0.23 is released
