### ISSUE TITLE
Refactor: Update loader crate (bindle get) to use AnyAuth

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#411]
The [loader crate](https://github.com/fermyon/spin/tree/main/crates/loader/src/bindle) currently uses a No Auth/in-house 'BindleTokenManager' approach when getting bindles.  This should be updated to use AnyAuth per https://github.com/fermyon/spin/pull/407#discussion_r860385119.

Follow-up from https://github.com/fermyon/spin/pull/407

**Comment by itowlson** [comment]
Fixed via #456.
