### ISSUE TITLE
Feature: allow wildcard in http allowed_host

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#421]
We should have a `allowed_http_hosts = ["*"]` option to allow all all hosts. This is dangerous but in rare cases should be useful - like handling a webhook callback.

**Comment by Mossaka** [comment]
My thought is that we should clearly document this and put a big WARNING sign when user is using the `"*"` in their component.

**Comment by lann** [comment]
I would be happier if we made the string scarier :slightly_smiling_face: , maybe something like `insecure:allow-all`?

**Comment by Mossaka** [comment]
Will this be a string in `allowed_http_hosts`, or it deserves its own component field?

**Comment by lann** [comment]
I'm fine with it going in `allowed_http_hosts`. I think we'll want to adjust the fields in the future anyway for e.g. https://github.com/deislabs/wasi-experimental-http/issues/87

**Comment by Mossaka** [comment]
updated the pr to have `insecure:allow-all`
