### ISSUE TITLE
Async Component

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#425]
If a spin component offloads some computation to an async func, what's the best way to execute it? 

Is there a plan to support async component in the future?

**Comment by lann** [comment]
We do not currently have a way to execute Wasm itself asynchronously; the best way to execute Wasm from an async function is to wrap the Wasm call in [tokio::task::spawn_blocking](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html), like the existing triggers do: https://github.com/fermyon/spin/blob/2c250311aead9efd76f5611a70e558486bc8296a/crates/http/src/spin.rs#L84

We may in the future switch to use [Wasmtime's async support](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.async_support), which would simplify this issue (but has issues of its own).

**Comment by Mossaka** [comment]
Thanks! I figured in the component implementation, something like this would work

```rust
let future = async {
   ... do work with await 
}
futures::executor::block_on(future);
```

**Comment by lann** [comment]
I _think_ `spawn_blocking` is preferable to `block_on` if many events are being handled concurrently because of Tokio's scheduler, but I don't entirely understand the behavior of `block_on` in an already-async context.
