### ISSUE TITLE
write component definition in rust/go

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#429]
spin application and components are definied in a `spin.toml` file. Is it possible to write the manifest in a programming language, like rust/go? This might require spin to provide a SDK to setup a spin app in rust or go. 

Such that we can do
`spin up -f app.rs`

**Comment by itowlson** [comment]
Could you say more about what you see as the scope and use case for this?  What would you want to be able to do with it?

**Comment by lann** [comment]
My initial reaction is that this is probably outside of core Spin's scope for now. In terms of the current architecture this could probably be implemented with a "loader plugin", which _is_ something we have discussed.

**Comment by Mossaka** [comment]
This idea probably does not make sense at all. 

I am just thinking out loud - some minor things like, the spin sdk being able to check the component target is actually there, or the ability to fetch remote component, or maybe upload the component to share with others?

**Comment by Mossaka** [comment]
I am going to close this since it's outside of the scope for now.
