### ISSUE TITLE
Feature: allow user to bring it's own wasmtime Engine

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#436]
`spin_engine::Builder` currently builds a wasmtime engine by the user. Would like to have a function to bring the engine. 

## Proposal API:

<s>removed
```rust
let exec_ctx = spin_engine::Builder::new()
  .engine(engine.clone()) // note: engine.clone() is a shadow copy
  .link_defaults()?
  ...
  .build()
  .await?
```
</s>

<s>spin could add necessary engine configs in `build()` function
```rust
let mut config = self.engine.config();
config
  .wasm_multi_memory(true)
  .wasm_module_linking(true)
```
</s>

```rust
let engine = wasmtime::Engine::default();
let builder = spin_engine::Builder::with_wasmtime_engine(config, engine.clone());
builder
  .link_defaults()?
  .add_component(...)
  .build()
  .await?
```

## Why do we want this?
Some application might have already built a wasmtime engine, and shared across different threads. They might just want to pass a reference of the engine to spin to run multiple triggers, instead of having to create a new wasmtime engine for every trigger.

**Comment by lann** [comment]
I don't think this approach works over the long term. The `ExecutionContext` depends on certain `wasmtime::Config` settings, and I expect those settings to change as the `ExecutionContext` behavior changes.

Could you give more information on your requirements? There may be another design that allows `Engine` reuse.

**Comment by lann** [comment]
@Mossaka It looks like you are only wanting to share a `wasmtime::Engine` between multiple `ExecutionContext`s, is that right? If so, I think we can get what you are looking for by extracting just the wasmtime `Config` and `Engine` construction from `Builder` into a new struct. I will take a closer look later today.

**Comment by Mossaka** [comment]
But `wasmtime::Engine` depends on `wasmtime::Config`, so it's unavoidable when I bring an engine, the configs are already inside of the engine. Could you please elaborate more on what you mean by extracting just the Config and Engine from `Builder`?

**Comment by lann** [comment]
Something like (untested):

`engine/src/lib.rs`
```rust
#[derive(Clone)]
pub struct Engine(wasmtime::Engine);

impl Engine {
  pub fn new(config: wasmtime::Config) -> Result<Self> {
    config.wasm_multi_memory(true);
    config.wasm_module_linking(true);
    Ok(Self(wasmtime::Engine::new(&config)?))
  }
}

impl Builder {
  ...
  pub fn with_engine(config: ExecutionContextConfiguration, engine: Engine) -> Result<Builder> {
   let wasmtime_engine = engine.0;
   ...
  }
  ...
}
```

So, you could construct the `spin_engine::Engine` once, then `Builder::with_engine(config, engine.clone())` for each instance.

**Comment by Mossaka** [comment]
oh no sorry if I didn't clarify. 

My application has alreaday inherited a `wasmtime::Engine`, and I want to construct a Httptrigger using this engine. So I don't want spin Builder to do `wasmtime::Engine::new()` for me since I already have an engine to pass to spin. Hope this makes more sense.

**Comment by lann** [comment]
Ah yes, that makes sense. I don't know if that is something we _want_ to support. As above, different `wasmtime::Config`s can result in very different execution behavior, so sharing a `wasmtime::Engine` between two different environments likely doesn't make sense.

**Comment by Mossaka** [comment]
Understandable. I was hoping that spin could provide a public function to add spin specific `wasmtime::Config`. This function will be invoked by application that uses spin. See here: https://github.com/fermyon/spin/pull/437/files#diff-0d42e63f6723b01964e321b7c6c180b6a252d889c02ee08d2b966a12281cccd4R203. 

> The ExecutionContext depends on certain wasmtime::Config settings, and I expect those settings to change as the ExecutionContext behavior changes.

If there is a change to the wasmtime::Config settings in the future, as long as application is using this function, it should be okay, I guess?

**Comment by lann** [comment]
Would it work if the example above had an engine getter?

```rust
impl Engine {
  ...
  pub fn inner(&self) -> &wasmtime::Engine {
    &self.0
  }
}
```
You could `.clone()` that for use in the other environment, though you'd still have the burden of config compatibility in that other env.

**Comment by Mossaka** [comment]
Let me get back to you on this. I think we could allow some "wasmtime engine profile" to be used by the application.

**Comment by Mossaka** [comment]
@lann having a engine getter works! I will adopt this design in this pr https://github.com/fermyon/spin/pull/437
