### ISSUE TITLE
Bindle server arg should be `--bindle-server`

### ISSUE THREAD

**Issue by lann** [fermyon/spin#451]
Instead of just `--server`.

What else would be impacted by this change?

**Comment by radu-matei** [comment]
I don't see anything immediate, other than updating the documentation and making sure the argument is consistent across commands.

**Comment by radu-matei** [comment]
I just thought of another place where this needs to be updated — the integration tests:

https://github.com/fermyon/spin/blob/f267af00cd0fc0f809e403163763c059c86fbbef/tests/integration.rs#L308

**Comment by lann** [comment]
> I just thought of another place where this needs to be updated — the integration tests:
> 
> https://github.com/fermyon/spin/blob/f267af00cd0fc0f809e403163763c059c86fbbef/tests/integration.rs#L308

https://github.com/fermyon/spin/pull/452/files#diff-eb771f54a1fdc1c330a82981d7d27d1202a5cbe3a59581ff67af5e3361f5f90e :slightly_smiling_face:
