### ISSUE TITLE
Global cache

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#455]
There are a few scenarios that would benefit from having a global Spin cache:

- applications run from Bindle are currently pulled every time, and having a cache would reduce network traffic significantly
- in the context of #454, local applications with a Bindle module source, the module cache would be first checked before pulling the module
- the Wasmtime module cache could also be part of this global cache

**Comment by vdice** [comment]
Now that Spin also supports [fetching a module from the web](https://developer.fermyon.com/spin/configuration#component-configuration), we have another use for caching.

**Comment by mikkelhegn** [comment]
The fileserver and redirect templates makes this somewhat more urgent, as these pre-built components are being downloaded on every `spin up`.

**Comment by radu-matei** [comment]
#1014 is adding the global cache for OCI pulls, and a follow-up will integrate with `spin up` as well.

**Comment by radu-matei** [comment]
Implemented in #1088.
