### ISSUE TITLE
Removing `.cargo` in default spin templates

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#463]
I totally understand that `.cargo` exists to allow the spin project to compile to `wasm-wasi32` by default, but this might be dangerous to do. 

I have encountered an issue today by accidently creating a spin project in my root directory, and I forgot to remove `.cargo` folder since this is hidden. And then it changes all my rust projects to target `wasm-wasi`... It is hard to find where the `config.toml` for Cargo is and to remove it. 

Since the template already says `cargo build --target wasm-wasi32 --release` in the `spin.toml` file, I believe it should be okay to remove `.cargo` folder in rust templates.

**Comment by Mossaka** [comment]
@itowlson

**Comment by itowlson** [comment]
There's probably a deeper issue here where generating into a directory that has stuff in it (such as root or home) is likely an error.  If the target directory is not empty, we should ask the user to confirm that they really want to create the app there.

(When we support generating components for an existing app, the check will have to change to "empty or contains an existing `spin.toml`", but we can figure that out at the time.)

**Comment by itowlson** [comment]
Raised #467 to confirm generating into occupied directory.

**Comment by Mossaka** [comment]
I like this #467 ! I think that creating a folder with the same name as the application makes more sense to me personally, but I also like the confirmation approach.
