### ISSUE TITLE
Implement a key/value store interface

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#47]
Spin applications should have a default key/value store implementation available at runtime, ideally following https://github.com/fermyon/wasi-experimental-toolkit.

**Comment by kate-goldenring** [comment]
@radu-matei is this still of interest given that we now support redis? Are we hoping to also support a local KV store? Should we narrow the scope of this issue?

**Comment by dicej** [comment]
This is done as of Spin 0.9.0.
