### ISSUE TITLE
`spin build` trigger validation messages are not explained

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#473]
I fouled up the Redis template so that `trigger` had a `base` field instead of `address`.

When I ran `spin build`, it said `Error: missing field `address``.

As my brain was in the "I am compiling" mindset, I assumed there was something wrong in the code, though I was puzzled by the lack of compiler context.  It didn't occur to me for a while that Spin was actually validating the trigger configuration.

Could we either ignore irrelevant fields during build, or provide a contextful message such as "Invalid trigger configuration" or "Invalid manifest file", ideally saying more about where the error occurred than just the name of what in this case was a nested field?  Even calling it `trigger.address` would have helped.

**Comment by dicej** [comment]
I think this could be a "good first issue" if we flesh it out a bit more, e.g. explaining where in the code to add context.
