### ISSUE TITLE
Release Spin v0.2

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#477]
Preparing for Spin's v0.2 release:

- [x] update the documentation: #475 
- [x] bump versions to v0.2: #476 
- [x] update https://spin.fermyon.dev (cc @vdice)
- [x] tag v0.2 (draft tag with release notes — https://github.com/fermyon/spin/releases/tag/untagged-b93e6a2a2127f2805285)
- [ ] update templates to point to the new tag

**Comment by bacongobbler** [comment]
Sounds like this can be closed now

**Comment by itowlson** [comment]
We still need to update the templates which means we need a Go SDK tag (and I want to get agreement on that rather than just haring off and doing it **grin**)

**Comment by radu-matei** [comment]
@itowlson — sure, let's create the tag so we can update the Go templates.

Thanks!

**Comment by radu-matei** [comment]
The tag seems to be created — https://github.com/fermyon/spin/releases/tag/sdk%2Fgo%2Fv0.2.0
@itowlson — I think updating the Go module files in the templates should work now?

**Comment by itowlson** [comment]
Gah, #493 did this but I had left it in Draft status, sorry.  It is ready for review.

**Comment by radu-matei** [comment]
Yay, thanks a lot, @itowlson!
