### ISSUE TITLE
`spin new` should create a new directory by default

### ISSUE THREAD

**Issue by lann** [fermyon/spin#479]
Options:

1. ~~Existing behavior (don't create a new directory). Somewhat surprising and very annoying when a bunch of files get dropped into your top-level "projects" directory~~ #467 mitigates this
2. Create a new directory by default (if `--output` isn't set)
3. Magic: if the current directory is empty, use it; otherwise, do option 2
4. Ask: prompt for the output directory, maybe with a default value from option 3

**Comment by Mossaka** [comment]
@itowlson and I discussed similar issue in https://github.com/fermyon/spin/issues/463.

**Comment by lann** [comment]
#467 makes this less annoying, but I think this would still be a nice improvement.

**Comment by itowlson** [comment]
I have a feeling that 'default to current directory' is inherited from the old 'copy an example' behaviour.  We certainly don't need to keep it.  The reason for it, I assume, was so people could create a directory, cd into it and do all their spinning there.

I'm not wildly keen on creating a new directory because it may not be obvious if it gets created into a busy place like Lann's project directory or Mossaka's root directory _grin_.  So I would definitely want to prompt rather than just create something!  Perhaps offer a choice of 'cancel, yes I really meant generate into busy directory, or pick new destination"...?

**Comment by lann** [comment]
What about something like:
```console
$ spin new http-rust
...
Project name: foobar
...
# (current directory empty)
Output directory [.]:
# (current directory full)
Output directory [./foobar]:
```

**Comment by itowlson** [comment]
The easiest thing is just to make `-o` mandatory.  If the user wants to generate into the current directory they can go `-o .`...?

**Comment by Mossaka** [comment]
I personally think `Cargo new my-project` is pretty neutral and I don't have problems with it. How about we make `spin new` to have the same semantics?

**Comment by itowlson** [comment]
So... make the output dir mandatory but make it positional rather than a flag?

**Comment by Mossaka** [comment]
A flag is a feature that allows user to specify which path to create spin project, but the default value should be current_dir/proj_name

**Comment by itowlson** [comment]
Now I'm confused, sorry.  Is this saying there should be a new positional parameter which doubles as a "project name" (when creating a new Spin app, the application name) _and_ the default for the directory, but there _should also_ be a flag parameter to override the output directory?  Apologies for being slow to understand!

**Comment by fibonacci1729** [comment]
Following what Cargo does is my preferred option as well. "Project name" if not supplied on CLI should be prompted, the output of the template is then put into a new directory named "project name"

If "--init" is specified, initialize the current directory instead of creating new dir

**Comment by itowlson** [comment]
`cargo new` _requires_ an output directory on the command line; it doesn't prompt.

```
ivan@hecate:~/experiments/cn$ cargo new
error: The following required arguments were not provided:
    <path>

USAGE:
    cargo new [OPTIONS] <path>
```

**Comment by fibonacci1729** [comment]
Sorry I meant cargo-generate.

**Comment by Mossaka** [comment]
> A flag is a feature that allows user to specify which path to create spin project, but the default value should be current_dir/proj_name

@itowlson sorry I was mistaken, yes make the output dir mendatory but make it positional. Just like `cargo new`

**Comment by fibonacci1729** [comment]
Because of https://github.com/fermyon/spin/issues/490

Instead of introducing a new variable, why not just reuse project name?

What I meant above is that "cargo new myproject" will create a crate named "myproject"

It infers the "project name" from the positional output parameter.

**Comment by fibonacci1729** [comment]
Because of https://github.com/fermyon/spin/issues/490

Instead of introducing a new variable, why not just reuse project name?

What I meant above is that "cargo new myproject" will create a crate named "myproject"

It infers the "project name" from the positional output parameter.

**Comment by itowlson** [comment]
So is this like @Mossaka's "mandatory positional parameter" and we use that for both the project name (i.e. a well-known parameter like `authors`) and the output directory?

i.e. `spin new http-rust myproject` will set the `name` parameter to `myproject` _and_ generate into a directory called `myproject`?

**Comment by fibonacci1729** [comment]
Sure. That's one way to skin the cat. I'm fi e that approach. If we do that we should remove the project name flag & the prompting of it if not specified.

**Comment by fibonacci1729** [comment]
Sure. That's one way to skin the cat. I'm fi e that approach. If we do that we should remove the project name flag & the prompting of it if not specified.  

The other way, is to just prompt if project name wasn't explicitly set via "-n" and use that as the output directory name.

**Comment by itowlson** [comment]
Hmm, I think the project name flag is currently ignored anyway... (mea culpa, should have either wired it up or taken it out before 0.2)

**Comment by fibonacci1729** [comment]
Yeah I believe you are correct. It prompts even if the "-n" is set.

**Comment by itowlson** [comment]
The combination of names and directories and options and prompts is getting overcomplicated.  We don't need to go over the top on what is just meant to be a quick scaffolding system.

I'm happy with requiring a name a la `spin new <template-id> <name>`, and both setting a well known parameter and an output directory from that.

I do think we still need a `-o` or similar flag though to generate into a directory that isn't immediately below the current directory.  E.g. `spin new http-rust myproject -o ~/tests/myproject`.  Would that meet everybody's needs?

**Comment by ejmg** [comment]
Hi there, I was looking to claim this issue but after getting Spin setup + poking around the CLI, I realize that #510 closes this (and comments as much, actually).

**Comment by fibonacci1729** [comment]
Thanks @ejmg ! I believe @itowlson completed this already. Ill close this issue.
