### ISSUE TITLE
Update release workflow to automatically upload artifacts

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#483]
The current [GitHub workflow for releases](https://github.com/fermyon/spin/blob/main/.github/workflows/release.yml) only uploads artifacts to the GH release for the `canary` release.  We should do similar for any vx.x.x tag such that artifacts are automatically uploaded to the corresponding GH release.

- Update [release.yml](https://github.com/fermyon/spin/blob/main/.github/workflows/release.yml) to upload the generated artifacts (binaries and checksums file) to the GH release for a given tag
- Update the [release process doc](https://github.com/fermyon/spin/blob/main/docs/content/release-process.md) accordingly

**Comment by Xunzhuo** [comment]
I am happy to help, please assign this to me:)
