### ISSUE TITLE
Templates and Branches

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#489]
How do we avoid collisions in the local repository if an author uses branches in a repository to manage templates?

As far as I can tell,

"Spin templates install --git remote/foo"

Will cache in the same directory as if I supplied the "--branch bar" flag on the command above.

Or am I misunderstanding how templates are cached?

**Comment by itowlson** [comment]
Templates are installed under the `id` parameter in the template manifest.  At the moment, you cannot install two templates with the same id - if the id already exists you can skip or overwrite.

Can you talk more about your intended use case?

**Comment by fibonacci1729** [comment]
OK thanks! That clears it up!
