### ISSUE TITLE
Template "project name" parameter

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#490]
It's probably safe to assume this is a required option that needs to be set via cli or through prompt before expansion.

We should disallow the redefining this parameter in a template manifest

**Comment by itowlson** [comment]
I think this is done now - @fibonacci1729 was there anything else that needed to be done for this?

**Comment by fibonacci1729** [comment]
Just verified this works per our discussions in the linked/merged PRs. Thank you! I'll close.
