### ISSUE TITLE
Spin new ignores project-name flag

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#491]
When creating a new project from a template Spin prompts for a project name ignoring the non interactive "--name/-n" option. If the flag is set we shouldn't prompt

**Comment by itowlson** [comment]
We might end up dropping the flag anyway.  Waiting on the outcome of #479.

**Comment by itowlson** [comment]
Current proposal over at #479 is that the format should be `spin new <TEMPLATE> <NAME>` with output directory defaulting to `./<NAME>` and overridable via optional `-o` flag.

We must document the magic parameter name to which the name gets assigned.
