### ISSUE TITLE
Accept a values file for spin new

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#492]
Right now a user has to either work through the prompt or manually set KEY=VALUE strings through the CLI to satisfy the parameters defined in a template. 

It'd be nice to pass a values.toml in the non interactive experience to avoid long CLI incantations

**Comment by mooori** [comment]
I would like to pick this up.

**Comment by fibonacci1729** [comment]
Thank you @mooori ! Let me know if you have any questions and feel free to @ me for a review when ready.

**Comment by mooori** [comment]
When a user has a parameter in values.toml *and* passes the same parameter via `--value`, would it make sense for the value passed as option to overwrite the value in the file?

For example with `foo = 'a'` in values.toml and `--value foo=b` as command option the final entry in the map would be `("foo", "b")`.

**Comment by fibonacci1729** [comment]
Yep. I agree. Explicit CLI definitions should take precedence.
