### ISSUE TITLE
Should `spin deploy` prompt for missing credentials?

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/spin#500]
Related to https://github.com/fermyon/spin/issues/499 - Right now the user has to pass environment variables to `spin deploy`. This results in user's passwords being stored in environment variables, or in their `~/.bash_history` if passed on the CLI through the `--hippo-password` flag.

As a username/password is mandatory, the workflow should be changed to allow the user to prompt for that information if not already provided, similar to `hippo login`.

```
$ spin deploy
Username: bacongobbler
Password: *******
Successfully deployed application! See Traefik dashboard for IP address of app.
```

It would be great if that information was persisted somewhere (OSX Keychain?) so future `spin deploy` invocations reuse that username/password.

**Comment by vdice** [comment]
@bacongobbler as of spin v0.6.0, `spin login` appears to prompt for missing creds (when login type is un/pw) and it appears there is some form of host persistence, albiet of the login token (arguably better than storing creds) -- for instance, on my machine, I see config placed in `~/Library/Application Support/fermyon/config.json`.

With this in mind, do we want to either close this issue, re-word or other?

**Comment by bacongobbler** [comment]
Good catch! Yes, this can be closed.
