### ISSUE TITLE
`spin deploy`: subsequent deploys result in error

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/spin#503]
From /examples/http-rust, If I do:

```
$ spin deploy
```

Update spin.toml to 2.0:

```
version = "2.0.0"
```

Then run

```
$ spin deploy
```

I receive an error saying the application already exists.

We should check for the existence of the app and channel, proceeding to use those if already created. Spin should only fail out when the invoice has already been pushed to bindle, or if Spin could not register the revision.

**Comment by michelleN** [comment]
@bacongobbler Could you post the exact error you're getting?

**Comment by michelleN** [comment]
This was resolved as part of the digest work spin application versions #570.
Summary:
- Any time the app changes, spin deploy will generate a digest of the spin.toml file and all components and assets references in the file and append that as build info to the version. This ensures if you've changed the app, you don't have to change the version in the spin.toml file and can proceed with deploy
- Can now use the `-e` or `--deploy-existing-bindle` to deploy an existing bindle to override the error described above
