### ISSUE TITLE
`spin deploy` with bindle ID "bacongobbler/myapp" or "fermyon.com/myapp" fails

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/spin#504]
This is the same issue as present in https://github.com/deislabs/hippo/pull/723. The bindle "storage ID" and the application name validation regexes differ slightly. Certain bindle IDs are not valid application names. We need to relax this constraint in Hippo, or "sanitize" the bindle ID before submitting it as an application name.

https://github.com/fermyon/spin/blob/fcb88ae6371c932530c03fa653b7eb865eb82aca/src/commands/deploy.rs#L206

**Comment by bacongobbler** [comment]
https://github.com/deislabs/hippo/blob/f0828b0aa6f2f2777a0ff22616f5bb95e7abc400/src/Application/Apps/Commands/CreateAppCommandValidator.cs#L13-L15

https://github.com/deislabs/hippo/blob/f0828b0aa6f2f2777a0ff22616f5bb95e7abc400/src/Application/Channels/Commands/CreateChannelCommand.cs#L52-L54

**Comment by dicej** [comment]
@bacongobbler I'm going through some old issues and found this.  Has this been addressed yet, or does it still need attention?

**Comment by itowlson** [comment]
@bacongobbler bumping this.  It looks from my reading of the Spin code that like the application name remains unsanitised on the client, and that the requirement is still there on the Hippo side, so I'm keeping it alive, but if you have time to comment on priority and next steps, that would be super useful.

**Comment by itowlson** [comment]
Closing in the light of the OCI work - please reopen if anyone wants it to stay on our radar.
