### ISSUE TITLE
Chaining HTTP components

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#519]
Currently, the HTTP response of the HTTP component that handles a particular route is directly sent back to the client.

If you wanted to execute another component defined in the application manifest, you would need to make an outbound HTTP request to its route, and orchestrate that from the initial component (manually make requests, handle the responses).

The application manifest redesign (#516) offers an interesting opportunity to explore chaining requests:

```
[application.trigger.http]
base = "/"
[[trigger.http]]
route = "/hello"
# not actually implemented
chain/services/components/name-that-isnt-terrible = ["foo", "bar", "baz"]

[[component]]
id = "foo"

[[component]]
id = "bar"

[[component]]
id = "baz"
```

Instead of directly returning the result of `foo` to the client, we could explore chaining the result to `bar`, and then to `baz`, which would return the response.

I suspect this would be a new executor for the HTTP trigger, and I'm wondering if the signature for all components in the chain (regardless of whether it's the first or last) could be very similar to the current Spin HTTP interface.

**Comment by fibonacci1729** [comment]
I smell interceptors.

**Comment by Mossaka** [comment]
A eventing framework like `fn foo(in: Event) -> Result<Event>` fits this model perfectly.

**Comment by radu-matei** [comment]
@Mossaka — when we talked about this, we had a bit of a hard time identifying potential use cases for such a feature — ironic, since I proposed it...

Do you have use cases in mind for something like this?
Thanks!

**Comment by radu-matei** [comment]
In the months since this was opened, we haven't really identified use cases that this would enable that either middleware or outbound HTTP wouldn't be able to address.

Closing for now, but happy to re-evaluate if we have use cases that would benefit from this.
