### ISSUE TITLE
`vergen` fails in Docker

### ISSUE THREAD

**Issue by ecumene** [fermyon/spin#530]
I tried building in Docker and got stuck at the build script. I also followed #168 and had the same problem... 

https://github.com/ecumene/spin/blob/docka/Dockerfile

```
#11 735.2       Finished release [optimized] target(s) in 12.40s
#11 735.2   thread 'main' panicked at 'failed to extract build information: could not find repository from '/app'; class=Repository (6); code=NotFound (-3)', build.rs:59:28
#11 735.2   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#11 ERROR: process "/bin/sh -c cargo build --all-features --release" did not complete successfully: exit code: 101
```

It seems to fail right here:
https://github.com/fermyon/spin/blob/ec9a74b14d2af7cff860122eba067ecaf44ca0d1/build.rs#L59

Here's the full action log:
https://github.com/ecumene/spin/runs/6644633741?check_suite_focus=true

And the action.yml:
https://github.com/ecumene/spin/blob/docka/.github/workflows/publish-docker.yml

**Comment by lann** [comment]
I suspect that the spin repo's `.git` dir isn't being copied into your image; I think `vergen` expects it to be there at build time. Do you maybe have a global `dockerignore` file that excludes `.git` from your images?

**Comment by radu-matei** [comment]
Did you end up working around this issue, @ecumene?

Last time I checked, using https://github.com/fermyon/spin/blob/main/.devcontainer/Dockerfile I could build Spin, but that might have changed.

If that Dockerfile still works, you could do a multi-stage build and copy the built binary from there.

**Comment by ecumene** [comment]
That seems to have worked! I wonder what's different between the initial images though. 

```diff
+FROM --platform=linux/amd64 debian
-FROM mcr.microsoft.com/vscode/devcontainers/rust:0-${VARIANT}
```
