### ISSUE TITLE
Working with multiple endpoints

### ISSUE THREAD

**Issue by econesag** [fermyon/spin#532]
Hello, I 'm currently testing spin with rust to develop a simple API REST. I searched in the documentation but i didn't find a way to used multiple endpoint's inside the same .rs. This work can be done by using multiple .rs of course, but I'm wondering if it's possible to define it without using a match.

My current work is like this:

```rust
fn hello(req: Request) -> Result {
  println!("{:?}", req.headers());
  match req.method() {
      &Method::POST => {
        Ok(http::Response::builder()
        .status(200)
        //.header("foo", "bar")
        .body(Some("POST!\n".into()))?)
}
  &Method::GET => {
    Ok(http::Response::builder()
      .status(200)
      //.header("foo", "bar")
      .body(Some("GET!\n".into()))?)
  }
  &Method::DELETE => {
    Ok(http::Response::builder()
      .status(200)
      //.header("foo", "bar")
      .body(Some("DELETE!\n".into()))?)
    }
  }

  Ok(bad_request())
}

fn bad_request() -> Response {
  http::Response::builder().status(400).into()
}
```

But what I want is something like this:

```rust
#[http_component]
fn hello_get(req: Request) -> Result {
  println!("{:?}", req.headers());
  Ok(http::Response::builder()
    .status(200)
    //.header("foo", "bar")
    .body(Some("GET!\n".into()))?)
}

#[http_component]
fn hello_post(req: Request) -> Result {
  println!("{:?}", req.headers());
  Ok(http::Response::builder()
    .status(200)
    //.header("foo", "bar")
    .body(Some("POST!\n".into()))?)
}

#[http_component]
fn hello_delete(req: Request) -> Result {
  println!("{:?}", req.headers());
  Ok(http::Response::builder()
    .status(200)
    //.header("foo", "bar")
    .body(Some("DELETE!\n".into()))?)
}
```

Is this possible? How can I do it?

**Comment by fibonacci1729** [comment]
Thanks for the issue @econesag ! Great question.

Currently only a single function can be annotated with "http_component". I agree it would be really convenient to allow multiple annotated functions to act as endpoints however there are some constraints due to code generation and macro processing that currently won't allow this. 

We are still exploring ways to improve the ergonomics of writing components that handle multiple routes and would love suggestions that result from your experience!

**Comment by ejmg** [comment]
Not to cross too many streams, but [Rocket](https://rocket.rs) (the web framework) relies heavily on macros for [decorating and declaring route endpoints (along with a lot of other things)](https://github.com/SergioBenitez/Rocket/tree/v0.5-rc/core/codegen), so there /might/ be something to take from its architecture wrt macro processing and component declarations within the same module.

**Comment by radu-matei** [comment]
Hi, @econesag, thanks a lot for the request!

As @fibonacci1729 mentioned, we are exploring how to achieve this with our Rust SDK — I _think_ #222 is requesting this exact feature, right?

@ejmg — it would be great if we could learn from the way Rocket does this — do you have experience writing something like this?

Closing in favor of #222 — feel free to comment there, or suggest reopening this issue if you think they are different.
