### ISSUE TITLE
Enforce integration test properties

### ISSUE THREAD

**Issue by ejmg** [fermyon/spin#535]
Following up on issue #216, PR #534 is the first step in refactoring the direct dependency on the WIT files by using the `rust-sdk` in test binaries and the related integration tests.

#534 currently changes only one test binary ([`simple-spin-rust`](https://github.com/fermyon/spin/tree/main/tests/http/simple-spin-rust)) but the integration tests dependent on it are assuming it enforces a few different properties[^1]. I've noted two of the property checks (test cases?) as follows:

1.  whether URI path contains `"test-placement"`
  + if so, access the file `test.txt` and return its contents in the body of the response.
  + if `test.txt` does not exist or cannot be accessed, return a 500 error.
2. if `"test-placement` is not in the URI, check whether the config toml contains a `"message"` attribute
  + if it does, return the contents of `"message"` in the body of the response.
  + if the config toml does not contain a `"message"` attribute, return a 500 error.

This is just for the integration tests that rely upon the `simple-spin-rust` test binary, but it would be good to check the other integration tests for similar checks and making sure that any refactoring keep these assertions intact.

---
[^1]: AFAICT, the assertions that currently exist do not actually check the body of the responses to make sure the contents match what is expected, but this can also be corrected along with refactoring the tests to use the rust sdk.

**Comment by radu-matei** [comment]
That makes sense, thanks for looking into this!

**Comment by rylev** [comment]
The integration tests have changed so significantly since this issue was opened that I don't think it's relevant anymore. Please let me know if you disagree, and we can reopen.
