### ISSUE TITLE
Add a way to exclude patterns from `files` patterns

### ISSUE THREAD

**Issue by lann** [fermyon/spin#554]
Per https://github.com/fermyon/spin-fileserver/issues/11, it is easy to accidentally include unwanted files in a `files` glob pattern. We should think of a mechanism to exclude some files from a glob, perhaps something like a `exclude_files` pattern. It might be nice for this to even default to `["**/.*"]` or similar.

**Comment by ejmg** [comment]
Poking around, it looks like this would mostly concern `spin-loader` but what other crates would be affected by making an addition to spin component configuration options?

Also, how should `exclude_files` be resolved with `files`? My gut says erring towards anything captured by `exclude_files` is excluded, even when `files` also matches on the given asset.

**Comment by itowlson** [comment]
1. `publish` might also be affected, though I think it uses `loader` for most of that resolution.  And `manifest` defines the actual on-disk format; you'd presumably need to add something to that.

2. Anything not mentioned by `files` is already skipped, so any exclusion feature needs to take precedence.

**Comment by itowlson** [comment]
Correction, `manifest` is not used for serialisation and should not be affected.

**Comment by ejmg** [comment]
I have a PR that I was going to try knocking out before considering this one, are the API changes between crates significant enough that I should just wait it out?

**Comment by lann** [comment]
If you're ready, go for it. I'll handle any conflicts.

**Comment by ejmg** [comment]
If that's the case, my proposed/anticipated plan of action:

- I'll update more integration tests to help fulfill #216 and #535 
- In this process, I will have the excuse/chance to setup an integration test that checks spin's asset loading functionality
- I'll open a corresponding PR off of this work (finished or unfinished) with my attempt at adding `exclude_files` as a config option

I have some other stuff on my plate right now (interview prep) but I should have some progress on this by sometime this Monday.

If anyone else is itching to tackle this issue before that time, please just say as much :slightly_smiling_face:

**Comment by FrankYang0529** [comment]
Hi, I would like to take this after # 618 is merged. Thank you.
