### ISSUE TITLE
Template version affinity

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#555]
When you do a `spin templates list` and there are no templates, it suggests you run `spin templates install --git ...`.  This hits HEAD, which causes problems if you are on a release build and there have been breaking changes to the templating stuff in `main` since that release.

Our original thought was to change the suggestion to specify a branch.  This can be a bit tricky because it requires Spin to know it is a tagged release build, which is hard to do without contacting the server, which seems heavyweight for a message.

An alternative approach is to smartly default the branch.  That is, if the user runs `spin templates install --git ...`, we look for `spin/templates/<version>` instead of HEAD.  If that doesn't exist, we fall back to HEAD.  (Of course, if a user wants to use the HEAD templates from a tagged release, they can still write `spin templates install --branch HEAD`.)

This is nice because it allows third-party repos that contain templates to also mark version compatibility, though it does require coordination on their part.  I _think_ the fail-forward strategy mostly works correctly, though it's problematic if the third party doesn't backfill on a change.  (Consider the following: Bob tagged at 0.6. There is a breaking change in 0.8, which Bob updates and tags. If Alice is on 0.7, she will get HEAD, which is broken for her.)

**Important:** This requires us to update the version in Cargo.toml _immediately_ after doing a release rather than when we get to the next one.  (Otherwise we will keep installing the last released version of the templates, even when we are on a local or canary build.)  Are we okay with that?

Thanks to @lann for discussion around this!

**Comment by itowlson** [comment]
A possible solution for the "skipped version" approach is to embed a "compatible with" constant in Spin, so that if the current version check fails, it could check the "compatible" version before defaulting to HEAD.  The trouble though is ensuring that the "compatible with" constant gets updated.

**Comment by lann** [comment]
Original issue: #517
