### ISSUE TITLE
Add template version tag on release

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#567]
As part of a release we should add the `spin/templates/vX.Y` tag so that users of the Spin release build pick up compatible versions of the templates even if we subsequently make a breaking change.

Should we also tag the Go SDK, or do we want to do that manually only when we make a breaking change?

**Comment by vdice** [comment]
@itowlson we now have automation for [pushing the templates tag](https://github.com/fermyon/spin/blob/main/.github/workflows/release.yml#L276) on each release (see also https://github.com/fermyon/spin/blob/main/docs/content/release-process.md).  Does this cover the intention of the original issue?

**Comment by vdice** [comment]
As mentioned above, we have some automation around the initial functionality mentioned and we can iterate as needed.  Closing this, but feel free to re-open if I've missed something.
