### ISSUE TITLE
spin new: flag to accept defaults where available

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#591]
At the moment, spin new prompts for fields like description. If the fields it prompts for are not required by the manifest file, it'd be nice to disable the prompt and leave those optional fields empty. I think this will give us a more streamlined spin new experience.

**Comment by deepto98** [comment]
Hi, can I pick this up? Can you please point me to the files I would need to look at?

**Comment by michelleN** [comment]
`new.rs` holds the top level logic for the spin new command. --> [https://github.com/fermyon/spin/blob/main/src/commands/new.rs](https://github.com/fermyon/spin/blob/main/src/commands/new.rs)

We'll also need to confirm which fields can be omitted. @fibonacci1729 @itowlson - ya'll have any thoughts on this issue?

**Comment by itowlson** [comment]
Everything in HTTP has sensible defaults.  Not sure about Redis.  The question is what we want users to think about and what not...

If the request is simply to _remove_ the prompt, you shouldn't need to change `new` to make a change like this.  Each template defines its own set of questions - you should be able to delete the questions out of the template manifest (and replace the substitutions in the `content` directory with the desired fixed values, or remove the entries).

If the request is to _allow an empty response_ to the prompt, that would require changes in the template subsystem, `crates/template`, specifically `run.rs` (and probably in the template schema, `template.rs`).  Again, shouldn't need anything in `new` itself.

**Comment by karthik2804** [comment]
@deepto98 Just wanted to check in with you if you were still working on this issue.

**Comment by radu-matei** [comment]
@karthik2804 — I think it would be ok if you wanted to have a look at this issue.
Thanks!

**Comment by karthik2804** [comment]
@radu-matei  I will pick this one up.
