### ISSUE TITLE
Why different

### ISSUE THREAD

**Issue by miketang84** [fermyon/spin#598]
Hi, I read that in https://github.com/bytecodealliance/wit-bindgen/blob/main/WIT.md#item-func, the function identifier is `func`, but in the source code of the spin, such as https://github.com/fermyon/spin/blob/main/wit/ephemeral/outbound-redis.wit, it is `function` rather than `func`, why ?

**Comment by lann** [comment]
The keyword was renamed [quite recently](https://github.com/bytecodealliance/wit-bindgen/pull/232). The upgrade is in #574 which I would expect to merge in the next week or so.
