### ISSUE TITLE
CI: Bump template versions and commit changes on tag pushes

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#599]
In https://github.com/fermyon/spin/pull/586 we updated the [release-process.md](https://github.com/fermyon/spin/blob/main/docs/content/release-process.md) doc with steps around bumping the SDK versions on a new Spin release and then following up with bumps to the template projects and committing the resulting changes.

Let's see if we can just have this be another automated step in the [release.yml](https://github.com/fermyon/spin/blob/main/.github/workflows/release.yml) GH workflow.

**Comment by FrankYang0529** [comment]
I would like to take this, but I have one question: which GitHub account should we use to commit in [step 7](https://spin.fermyon.dev/release-process)? Thank you.

**Comment by vdice** [comment]
@FrankYang0529 Excellent!  Which GH action are you thinking of using?  Can we utilize the usual/default `secrets.GITHUB_TOKEN` for creating a Pull Request from an action?

**Comment by FrankYang0529** [comment]
I would like to use [git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action). Let me check whether I can use `GITHUB_TOKEN`.

**Comment by radu-matei** [comment]
We have @fermybot for this if we need an account to commit to the repository.
