### ISSUE TITLE
Make `files` mounts read-only by default

### ISSUE THREAD

**Issue by lann** [fermyon/spin#605]
They are currently writable, but not persistent. It might be less confusing to make them read-only by default with an explicit `allow_transient_writes = true` or something if necessary.

**Comment by lann** [comment]
Context: https://github.com/fermyon/spin/pull/147#discussion_r822268913

**Comment by FrankYang0529** [comment]
For this issue, if users give `allow_transient_writes = true`, do we need to watch files change and copy them to `temp` directory again?

**Comment by lann** [comment]
> For this issue, if users give `allow_transient_writes = true`, do we need to watch files change and copy them to `temp` directory again?

Not for _this_ issue, no, but that is something we have discussed before: https://github.com/fermyon/spin/issues/148, https://github.com/fermyon/spin/issues/324#issuecomment-1090169857

**Comment by FrankYang0529** [comment]
I would like to take this issue, so I want to confirm change area. For both local and bindle loaders, files in the `temp` directory are read-only by default. If users give `allow_transient_writes = true`, we will allow them to update files like the current implementation. Do I misunderstand anything? Thank you.
