### ISSUE TITLE
Deploy: raw JSON in output if Hippo login fails

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#614]
```
# URLs etc set via EVs
13:21 $ ../../target/debug/spin deploy --hippo-password NOTMYPASSWORD
Error: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Login failed.","status":400,"detail":"Login failed: "}
```

Our other errors are more plain textish (it would be good to have JSON output options but then you wouldn't prefix the JSON with the `Error:` text, and that's a different and much broader concern anyway!)

**Comment by itowlson** [comment]
Would be useful to identify it as originating from Hippo as well (for when Bindle has auth and we can fail to log into that too _whee_)

**Comment by lidongjies** [comment]
Hi @itowlson, can I pick this up?

**Comment by itowlson** [comment]
@lidongjies That would be great - thanks!

**Comment by radu-matei** [comment]
The fix for this issue was merged — thank you so much for your contribution, @lidongjies!
