### ISSUE TITLE
Docs site errors out with latest spin-fileserver and bartholomew modules

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#620]
When I attempt to run the spin docs site locally using spin built from the most recent commit (https://github.com/fermyon/spin/commit/9a49057535a879ffa600a1e2732186310b1e477a at time of writing) with updated `bartholomew.wasm` and `spin_static_fs.wasm` modules, the site errors out.

## Prep

1. Build spin from this repo via `make build`, ensure it is in your user's `PATH` 
1. Clone https://github.com/fermyon/spin-fileserver, build the module via `cargo build --release`, move the module to `docs/modules` in this repo
1. Download the latest [v0.3.0 ](https://github.com/fermyon/bartholomew/releases/tag/v0.3.0) version of the [bartholomew.wasm](https://github.com/fermyon/bartholomew/releases/download/v0.3.0/bartholomew.wasm) and move the module to `docs/modules` in this repo
1. Run the site: cd to `docs` and run `npm install && npm run spin`

## Expected

Site runs locally and returns 200 on GET requests, serving the expected docs

## Observed

Site returns 500 on GET requests, with the following error seen from `npm run spin`:

```
$ npm run spin

> spin-docs@0.1.0 spin
> nodemon --watch content --watch static --watch templates --ext md,rhai,hbs,css,js --verbose --legacy-watch --signal SIGINT --exec 'spin up --file spin.toml'

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGUSR2 to 8921 to restart
[nodemon] watching path(s): content/**/* static/**/* templates/**/*
[nodemon] watching extensions: md,rhai,hbs,css,js
[nodemon] starting `spin up --file spin.toml`
[nodemon] spawning
[nodemon] child pid: 8944
[nodemon] watching 56 files
Serving http://127.0.0.1:3000
Available Routes:
  bartholomew: http://127.0.0.1:3000 (wildcard)
  fileserver: http://127.0.0.1:3000/static (wildcard)
2022-07-08T19:14:36.367005Z ERROR spin_http_engine: Error processing request: component is not compatible with Spin executor - should this use the Wagi executor?

Caused by:
    failed to find function export `canonical_abi_free`
```

```
$ curl -vvv localhost:3000
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 0
< date: Fri, 08 Jul 2022 19:20:04 GMT
<
* Connection #0 to host localhost left intact
```

**Comment by dicej** [comment]
I'm guessing this is related to #574 -- v0.3.0 of bartholomew.wasm is not compatible with `spin` HEAD due to the `wit-bindgen` upgrade.  You'll need to either rebuild bartholomew.wasm with `spin` HEAD or use the `spin` v0.3.0 release.

**Comment by vdice** [comment]
Ah, thanks @dicej.

Indeed, if using `spin` HEAD,  it looked like both modules needed updating for the site to function properly.  I ensured the spin-sdk dep for both was pinned like so:

```
spin-sdk = { git = "https://github.com/fermyon/spin", rev = "9a49057535a879ffa600a1e2732186310b1e477a"...
```
After rebuilding and placing the modules in `docs/modules`, the site functions as intended.

I can also confirm that when I switch back to `spin` v0.3.0 and use the modules built from their respective HEAD commits, the site also functions as intended.

**Comment by vdice** [comment]
I suppose a follow-up here might be to define the process/vision of how we want to ensure this docs site and its module deps are compatible for a given tag (and/or spin.toml version?)

Brainstorming a bit, maybe we'd want to add steps to the [release process](https://github.com/fermyon/spin/blob/main/docs/content/release-process.md) around ensuring that the docs modules are updated for compatibility prior to cutting a new spin tag?  Then perhaps also updating the spin-sdk version to point to this next spin tag in each module's repo and then cutting releases for these components?  Not sure of the proper ordering here... a bit of a chicken/egg problem.

Other thoughts?

**Comment by dicej** [comment]
@vdice see also #615 for related discussion.  The issue isn't so much with the release process as it is about what happens _between_ releases.  Specifically, we've made a braking change since we released `spin` v0.3.0, which means modules built with v0.3.0 won't work with `spin` HEAD.

Is there any particular reason to use `spin` HEAD for a task like this, rather than the latest release?  If not, the easiest thing would be to use the latter.  Late, when we're ready to release v0.4.0, we'll definitely want to update all the modules everywhere, but probably not before that.

**Comment by vdice** [comment]
> Is there any particular reason to use spin HEAD for a task like this, rather than the latest release?

That's a good question.  One scenario is to dogfood spin HEAD itself for deploying spin apps (eg such as the staging/canary version of spin's docs site itself) to try to catch any bugs/unexpected behavior prior to the next release.  Naturally, we can revisit/tweak this strategy if needed in the near-term.

**Comment by radu-matei** [comment]
@vdice — is there anything we need to track from this issue, or can we close it?

Thanks!

**Comment by vdice** [comment]
@radu-matei thanks for the nudge -- this can be closed.
