### ISSUE TITLE
Test: Feature gate the e2e tests

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#626]
(Where e2e tests refer to all of the currently-named integration tests that rely on dependencies such as the `bindle-server`, `nomad` and `Hippo.Web` binaries.)

Can we feature gate the newly added tests? Something like,
  ```rust
  #[cfg(feature = "e2e-tests")]
  mod e2e {
       ... all new test code goes here ...
  }
  ```

  Then adding the feature to Cargo.toml:
  ```toml
  ...
  [features]
  e2e-tests = []
  ```

  Add a make target for `test-e2e` that invokes the test with the e2e-tests feature enabled.
  
  Why? This way the original integration tests can be run locally until we figure how to
  ensure the installation of e2e prerequisites.

_Originally posted by @fibonacci1729 in https://github.com/fermyon/spin/issues/607#issuecomment-1179282331_

**Comment by kate-goldenring** [comment]
Hey @vdice and @fibonacci1729. I am happy to take this one on.
