### ISSUE TITLE
`spin templates list` is returning an error

### ISSUE THREAD

**Issue by technosophos** [fermyon/spin#637]
I have a bunch of Spin templates added from both Git and local directories. When I run `spin templates list`, I get the following:

```console
$ spin templates list  
Error: Failed to list templates

Caused by:
    0: Failed to read template from /Users/technosophos/Library/Application Support/spin/templates/target/metadata
    1: Failed to read template manifest file /Users/technosophos/Library/Application Support/spin/templates/target/metadata/spin-template.toml
    2: No such file or directory (os error 2)
```

If I look in the indicated location, I don't see a `metadata` file, either:

```console
$ ls ~/Library/Application\ Support/spin/templates
http-c_c328011daf311449f512a99cc0e60bbcae479c2b9d0792609b69834a0aec067f
http-go_542a3fc5dc9e0b05d458dfc9bf5b41d8e6a2a4c5e4c511c2ec00857cef32a60d
http-grain_1ef84acf426b8c0289ce9752020d3dbaf1557ceedcd088e5245a745038297642
http-rust_0e3cdf0278c98f7b80e4615a3c7918514619850f1f557ea8d7de7f9f26080c0e
http-swift_223fcdcf4254bfb6da2e008f9def1bd63b705cb343eff62555092af7ff07dab8
http-zig_2ce7dec1c50ca2a2f88375512cae18bb990c78538943575f51e504488ec2ef74
redis-go_f683d8322a04d723fbb1c04ff38f985330eb1a158e4c75db7cc890c665747431
redis-rust_2eaa9f1af54cf8452806b2a88fbd209fe0ee1d93921db19e3664aa4bf7e3b83d
target
$ ls ~/Library/Application\ Support/spin/templates/target
# This space intentionally left blank
```

**Comment by itowlson** [comment]
I wonder if your local source contained a `/templates/target` directory which was a build output but got blindly copied by the installer, though I _think_ that would result in a decorated name (but maybe not if there was no template manifest?).  We should:

1. Add some checks at install time and copy only directories that contain valid-ish templates.
2. Not fail on non-template-ish directories in the template store (e.g. warn and move on).
3. Provide a way to clean up the template store if it does get into a woeful state.

**Comment by itowlson** [comment]
Seems like it should be decorating all names; I wonder if something got built in the `/templates` dir somehow and created `target` that way.

**Comment by technosophos** [comment]
I just discovered that the `target/` directory was created automatically by another tool, running a command that should have been a no-op.

**Comment by itowlson** [comment]
Awesome, thanks.  I've want to prevent installing a bad template (besides I've already written the code for it); the work to pass airily or glibly over a bad directory is in progress.
