### ISSUE TITLE
Make `spin --version` more obvious at unreleased commits

### ISSUE THREAD

**Issue by lann** [fermyon/spin#650]
For example, with recent checkout of Spin `spin --version` gives: `spin 0.4.0 (7404232 2022-07-15)
`. For someone not already familiar with this it isn't obvious that this includes code committed _after_ the `0.4.0` release.

**Comment by radu-matei** [comment]
I agree.
I've also seen the convention to append `-dirty` (or perhaps something a bit more pleasant-sounding) if there are local changes that have not been committed, which I liked because it made it even more obvious that you have local changes.

**Comment by lann** [comment]
[This issue on the semver repo](https://github.com/semver/semver/issues/701) suggests bumping the patch version immediately after a release and adding a prerelease tag, e.g. `0.4.1-beta.0`. As noted in the comments, its a little annoying that version `0.4.1` may never actually be released, but maybe it's still the least-bad option.

**Comment by lann** [comment]
I guess you could also then bump the minor revision as soon as you have incompatible changes - bumping the version to `0.4.0-something` with the wasmtime upgrade would have made sense.

**Comment by lann** [comment]
Maybe. I think the main point is that it's odd for the version to include 0.4 _after_ 0.4 is released. It may be that we actually need to update our release process

**Comment by itowlson** [comment]
I think this is now done?
