### ISSUE TITLE
Build failed following Spin quickstart document

### ISSUE THREAD

**Issue by tzutoo** [fermyon/spin#654]
OS: Windows 11 Professional
cargo --version
cargo 1.62.0 (a748cf5a3 2022-06-08)

Steps to reproduce:
$ git clone https://github.com/fermyon/spin -b v0.4.0
$ cd spin
$ rustup target add wasm32-wasi
$ cargo install --path .

Error message:
`error[E0308]: mismatched types
   --> src\commands\deploy.rs:181:13
    |
181 |             ChannelRevisionSelectionStrategy::UseRangeRule,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `hippo_openapi::models::channel_revision_selection_strategy::ChannelRevisionSelectionStrategy`, found enum `ChannelRevisionSelectionStrategy`
    |
    = note: perhaps two different versions of crate `hippo_openapi` are being used?

error[E0609]: no field `apps` on type `hippo_openapi::models::app_item_page::AppItemPage`
   --> src\commands\deploy.rs:255:27
    |
255 |         let app = apps_vm.apps.iter().find(|&x| x.name == name.clone());
    |                           ^^^^ unknown field
    |
    = note: available fields are: `items`, `total_items`, `page_index`, `page_size`, `is_last_page`

Some errors have detailed explanations: E0308, E0609.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `spin-cli` due to 2 previous errors
error: failed to compile `spin-cli v0.4.0 (C:\dev\spin)`, intermediate artifacts can be found at `C:\dev\spin\target``

**Comment by itowlson** [comment]
There's a known issue with `cargo install` where it doesn't pick up the lockfile so can use the wrong version of dependencies.  The workaround is to use `cargo install --locked`.  Please let us know if that still doesn't work though!

**Comment by itowlson** [comment]
(Or do `cargo build --release`, which _does_ respect the lockfile, but doesn't put it on your PATH.)

**Comment by charliethacker** [comment]
I had the same issue and cargo build --release,  worked for me on windows 11 and on WLS.

**Comment by tzutoo** [comment]
> (Or do `cargo build --release`, which _does_ respect the lockfile, but doesn't put it on your PATH.)

`cargo install --locked` reported the following error:
Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.

`cargo build --release` worked for me!

**Comment by Crell** [comment]
I had the exact same experience as @tzutoo.  `cargo build --release` worked, `cargo install --locked` gave me an error to use the line from the docs instead (which also failed as in the OP).

**Comment by vdice** [comment]
Thanks @Crell and @tzutoo for relaying your experiences here.

@itowlson how do you think we might update the problematic section in the docs, seeing as the potential workaround of `cargo install --locked` also may lead to errors?

**Comment by itowlson** [comment]
Yeah we should update it to `cargo install --locked --path .` (though waiting on user confirmation that this worked for them as well as for me!).  Sent #676.

**Comment by vdice** [comment]
Thanks, @itowlson !

**Comment by Crell** [comment]
`cargo install --locked --path .` works for me as well.

So it seems the error message for just using `cargo install --locked` is misleading, as it doesn't include the switches you used in its "use this instead" directive.  So the fix for the docs is probably just adding `--locked` to the current command, as @itowlson's PR does.
