### ISSUE TITLE
Missing protocol in `allowed_http_hosts` gives misleading error at runtime

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#658]
Create a `spin.toml` with the following:

```
allowed_http_hosts = [ "spin.fermyon.dev" ]
```

Now make an outbound HTTP call to `https://spin.fermyon.dev`.

It fails with error 2, "invalid URL."

This happens because the allow checks attempts to parse all allowed hosts as URLs, and in this case fails with "relative URL without base".  This is mapped to the InvalidUrl error from `http-types.wit` at https://github.com/fermyon/spin/blob/b54bb8639aff95636580b9431c692b0068bf7f26/crates/outbound-http/src/lib.rs#L48.  So of course the user tries to figure out what was wrong with _their_ URL.

We should perform any required validation of `allowed_http_hosts` when loading the `spin.toml` file and fail immediately, rather than waiting until runtime and then returning an error that implies the request was bad.

**Comment by lidongjies** [comment]
Need to do the same check for allowed_http_hosts before pushing to bindle server?

**Comment by itowlson** [comment]
That's a good idea.  We could (and probably should) do it when loading from a bindle, but at that point it's unfixable...

**Comment by Mossaka** [comment]
Do we have any forms of manifest verification in load time? I am happy to take this task.

**Comment by Mossaka** [comment]
Figuring out at which layer to validate would be hard. I would improve the error messages for this issue and leave a more proper validation infras to be designed later.
