### ISSUE TITLE
Add `vault` config provider

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#661]

**Comment by radu-matei** [comment]
@fibonacci1729 — would you mind expanding a bit on the context for this issue?

Thanks!

**Comment by fibonacci1729** [comment]
Spin supports a [trait](https://github.com/fermyon/spin/blob/main/crates/config/src/provider.rs#L9) for accessing configuration dynamically when an application is running.

Currently, the only implementation is an [environment provider](https://github.com/fermyon/spin/blob/main/crates/config/src/provider/env.rs#L9) that will fetch from the host the environment constant associated with a key.

For secrets and sensitive configuration managed outside the host environment (such as [Vault](https://www.vaultproject.io/)) we could/should provide an implementation of the above trait to fetch dynamically from the secure host.
