### ISSUE TITLE
Outbound HTTP component ignores `params` field

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#663]
`http-types.wit` defines the `request` type to have a member `params` which is documented as `// The HTTP parameter queries, represented as a list of (name, value) pairs.`

If you set this on an outbound request, it is ignored - no query string is included the URL.

We should either respect `params`, or remove it from the outbound request type.

**Comment by lann** [comment]
> remove it from the outbound request type

We should consider removing it entirely (moving it into SDKs); param parsing can be subtly different in different languages.

**Comment by radu-matei** [comment]
One thing to consider if removing is that we are reusing the HTTP request and response type definitions across the HTTP trigger and the outbound HTTP implementation.

**Comment by lann** [comment]
Yeah, I'm suggesting removing it from everywhere. Using url form encoding for params is "just" a (very common) convention.

**Comment by rajatjindal** [comment]
this is also impacting tweet embedding in `bartholomew`. 

if i understand correctly, the consensus is to remove the params parameter from wit types file and make corresponding changes in sdk's?

**Comment by lann** [comment]
If we're removing `params` this is _not_ a good first issue.

**Comment by lann** [comment]
For outbound HTTP the `params` field is currently non-functional but it looks like the query part of the request URI should be working; at least, I don't see in the code that it is being removed.

**Comment by itowlson** [comment]
Current behaviour from testing:

* Inbound
  * The original query string is included in `url`
  * The `params` field is populated
* Outbound
  * If you include a query string in `url` it is preserved verbatim (as Lann predicted)
  * If you set `params` it is ignored

**Comment by lann** [comment]
> * Inbound
>   * The original query string is included in url

Well that's good. I propose we:

1. Switch our SDKs to parse the query
1. Document that `params` is deprecated
1. Drop `params` the next time we make breaking changes to the http interfaces (after streams support lands, if not sooner)

**Comment by itowlson** [comment]
I will send a PR for 1 and 2.

**Comment by itowlson** [comment]
Slight correction: if you include a query string on an outbound request, _Spin_ leaves it alone.  But if you're using the Rust SDK, _that_ strips it out (before passing the request to Spin).

**Comment by itowlson** [comment]
After discussion, we believe we can parallel-run a new WIT with the existing one by using the Joel Trick TM at the ABI level and hiding it in the SDKs at the application level.  It will need some planning but we think it can be a non-breaking change.

**Comment by rylev** [comment]
If #1871 is accepted, this can be closed as we would freeze the Spin specific `http` interface (including this `params` field) but move to `wasi-http` for newer applications.

**Comment by tschneidereit** [comment]
@rylev given that #1871 has been accepted, can we close this?
