### ISSUE TITLE
`spin up`: hot reload when component files change

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/spin#666]
As a user of [bartholomew](https://github.com/fermyon/bartholomew), I'd like `spin up` to reload when I change any of the site's content.

For comparison, here's `hugo server`: https://gohugo.io/commands/hugo_server/

If this should be rejected in favour of `bartholomew` introducing its own `serve` command, that's okay too.

**Comment by radu-matei** [comment]
ref #148, #324

As a workaround, we have been using a script similar to this for watching changes and restarting — let me know if this doesn't satisfy your current use case.


 https://github.com/fermyon/spin/blob/e5b4a8dc536d874498e1f3bed274519ff413b066/docs/package.json#L33-L36

**Comment by bacongobbler** [comment]
Thanks. Closing as a duplicate of #148.
