### ISSUE TITLE
Reuse connection in outbound PosgreSQL implementation

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#667]
The outbound Redis implementation currently creates a new connection for each operation: https://github.com/fermyon/spin/blob/360ad620543baa26bf96f76c4ed596894fb73024/crates/outbound-redis/src/lib.rs#L45-L57

Ideally, when using the same connection multiple times in the same module, the underlying connection would be reused. This means (I suspect) introducing a resource field for the connection, and maintaining that as state in the host component.

A guest module would be able to connect to two different servers by creating two different connections.

A similar improvement could be made for the outbound PostgreSQL implementation.

**Comment by radu-matei** [comment]
The outbound Redis implementation has been patched thanks to @FrankYang0529.

Updating the issue title to reflect that the PostgreSQL implementation is the one needing a patch to reuse connections.

**Comment by radu-matei** [comment]
The outbound Redis implementation has been patched thanks to @FrankYang0529.

Updating the issue title to reflect that the PostgreSQL implementation is the one needing a patch to reuse connections.

**Comment by etehtsea** [comment]
This one can be closed I think.
