### ISSUE TITLE
Spin SDK should use new outbound HTTP implementation based on the component model

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#674]
Currently, the Spin SDK for Rust uses the old ["WASI experimental HTTP" implementation](https://github.com/deislabs/wasi-experimental-http) as the default option for sending HTTP requests.

https://github.com/fermyon/spin/blob/391f3fb8eb8deddbed40cd42957734b3dd6bc37c/sdk/rust/src/lib.rs#L9

The Rust SDK should use the same HTTP from https://github.com/fermyon/spin/tree/main/crates/outbound-http by default.

Notice that this does not impact whether we support the old API in Spin — rather, the default Rust SDK should use the new one instead.

**Comment by lann** [comment]
> Notice that this does not impact whether we support the old API in Spin — rather, the default Rust SDK should use the new one instead.

Plan as of today is to drop the `wasi-experimental-http` API.

**Comment by radu-matei** [comment]
To expand on this a bit — when we started the `wasi-experimental-http` library, there wasn't anything else that we could have used. 

It uses a hand-crafted WITX definition and implementation, and it has language support just for Rust (which for Spin will be superseded by addressing this issue) and AssemblyScript (for which we could consider supporting the new HTTP API in the future).
