### ISSUE TITLE
Feat: Update existing Hippo app on each spin deploy

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#683]
Currently, it appears that spin [deletes the Hippo app](https://github.com/fermyon/spin/blob/10fb784060a473aba7e3fc8fc226ddb6e6f4fc1a/src/commands/deploy.rs#L165) on each new `spin deploy` invocation for a given Spin app.

I'd propose this causes unecessary churn at the Nomad level, because each time a Hippo app is created, a new Nomad job is created.  With repeated deploys of the same Spin app, this leads to a stacking up of Nomad jobs, which, even if stopped, continue to take up resource (CPU/Mem) space unless they are manually purged or until they are GC'd by Nomad -- and the default GC threshold is [4 hours](https://www.nomadproject.io/docs/configuration/server#job_gc_threshold).  This can quickly take up valuable space on a smaller host.

Hippo supports updating an existing app with a new revision.  Can we update `spin deploy` to utilize this?  Then the same Nomad job can continue to be re-used through multiple revisions.

**Comment by bacongobbler** [comment]
hippo-cli 0.16 has been released, introducing the `patch_channel` and `put_channel` APIs. cc @kate-goldenring

**Comment by vdice** [comment]
Closed via https://github.com/fermyon/spin/pull/728 -- thank you @kate-goldenring and @bacongobbler !
