### ISSUE TITLE
Could `spin build` propagate text colour?

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#688]
When I do a build using the actual tool, I get errors and warnings in red and yellow - they jump out at me and make it clear something's gone wrong.

When I use `spin build`, they are displayed in white, same as the other text.  Unless the message is very large, it (and the summary, and the "Build command failed" message) get lost in the noise of build progress messages.

Would it be possible to propagate the colours emitted by the build tools we invoke?

**Comment by radu-matei** [comment]
After looking into this a bit more, this is not controlled by `spin build` — for example, try running the command for the Rust example in this repository and you will see the coloured output.

Rather, I think it is dependent on the external command `spin build` is calling, and whether _it_ makes additional checks that disable colours.

(for example, .NET tooling checks whether the output has been redirected, in which case it disables colours — this can usually be controlled with an environment variable, `DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION=1` for .NET specifically).

So in the end, I don't think we can reliably set anything in `spin build`, so I am going to close this — but feel free to reopen it if you think we can improve the experience here.

Thanks!
