### ISSUE TITLE
`spin build` should say if there is nothing to build

### ISSUE THREAD

**Issue by lann** [fermyon/spin#700]
```console
$ spin build
Successfully ran the build command for the Spin components.
```

...is a little confusing when there are no build commands to run.

**Comment by jim4067** [comment]
Would love to try hacking on this.

**Comment by radu-matei** [comment]
@jim4067 — that would be great!
Here is the part in the build logic that you can start looking at — https://github.com/fermyon/spin/blob/d81a37b4b0349f7286c43c27ee5b60d202ac3426/crates/build/src/lib.rs#L12-L31

Let us know if there is anything we can help with.

Thanks!
