### ISSUE TITLE
GitHub's Ubuntu 18 image is being deprecated

### ISSUE THREAD

**Issue by lann** [fermyon/spin#708]
https://github.com/actions/runner-images/issues/6002

We saw an intentional "brown-out" today which broke the release build. It looks like they are ["revising the schedule" on those due to push-back](https://github.com/actions/runner-images/issues/6002#issuecomment-1222477506), but we need to keep track of this as it impacts the Linux distro compatibility of our binary releases.

**Comment by radu-matei** [comment]
We use that for the release job — https://github.com/fermyon/spin/blob/main/.github/workflows/release.yml

Do we need to create the release binary in a container instead?

**Comment by lann** [comment]
> GirHub
:facepalm: 

> Do we need to create the release binary in a container instead?

Yeah it might be that simple. I just saw the error and wanted to make sure this was captured.

**Comment by vdice** [comment]
I've moved this from Investigating to the Backlog in an attempt to bump the priority a bit.  Looks like we're still using the `ubuntu-18.04` image in our [release.yml](https://github.com/fermyon/spin/blob/main/.github/workflows/release.yml#L17) and it looks like the target date for dropping support is 4/1/23.

**Comment by vdice** [comment]
@FrankYang0529 thanks for investigating and testing out the udpate to 22.04!  I think what we need to check here is that the spin artifact built from the updated pipeline runs as intended on each platform.

**Comment by lann** [comment]
I don't know of anything blocking an upgrade now.

**Comment by FrankYang0529** [comment]
I tested spin with ubuntu 22.04 on EC2 and it looks fine, so I create a PR for it.

```bash
$ sudo apt update
$ sudo apt install build-essential -y
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ rustup target add wasm32-wasi
$ git clone https://github.com/fermyon/spin && cd spin
$ cargo build --all-features --release --features openssl/vendored
$ sudo mv target/release/spin /usr/local/bin/
$ cd ~
$ spin --version
spin 0.6.0 (3b482ba 2022-10-27)
$ spin templates install --git https://github.com/fermyon/spin
$ spin new http-rust myapp && cd myapp
$ spin build
$ spin up
$ curl -i http://localhost:3000
HTTP/1.1 200 OK
foo: bar
content-length: 14
date: Wed, 02 Nov 2022 15:09:58 GMT

Hello, Fermyon

```

**Comment by lann** [comment]
Our main concern is with older systems running release artifacts. Iirc there may have been a glibc issue at one point in addition to the openssl issue.

**Comment by lann** [comment]
https://github.com/fermyon/spin/issues/168

**Comment by lann** [comment]
It looks like this was pushed back to April, which matches the 18.04 end of support. I think we can put this off until close to then and then update to 20.04.

**Comment by lann** [comment]
https://github.com/fermyon/spin/pull/982
