### ISSUE TITLE
`allowed_http_hosts` requires protocol but ignores it

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#720]
If I write `allowed_http_hosts = ["https://localhost:3001"]` I can still make a request to `http://localhost:3001/` and it works.

If we are to require a protocol, shouldn't that be enforced?  I assumed this was why we required a protocol rather than just a hostname.

**Comment by itowlson** [comment]
Also, any port the operator specifies is ignored, e.g. if I write `allowed_http_hosts = ["https://localhost:4444"]` then make a request to `http://localhost:3001/`, it is allowed.

This is certainly in line with the name "hosts" but maybe we should validate that no port is given, or an operator might be led into a wrong assumption about what permissions they are granting.

**Comment by itowlson** [comment]
Proposal for this and #722:

* `allowed_http_hosts` contains a list of host names (domain names).
  * For now, we will also accept schemes for backward compatibility; as today, they will be ignored, but they are no longer required or desired.
* A port may optionally be specified with a host
  * A host may be listed multiple times with different ports.
  * If a host is listed with *no* port, then we will accept URLs without ports (so implicitly port 80 or 443 according to URL scheme).
  * If a host is listed with a *specific* port, then we will accept URLs with that specific port.
* We will maintain a deny-list of ports that may *never* be specified.  If one of these ports appears in `allowed_http_hosts`, it will fail validation.
  * At the moment the only port scheduled for the deny-list is 25 (SMTP).

Feedback welcome!

**Comment by lann** [comment]
`587` and `2525` are other common smtp ports

**Comment by mikkelhegn** [comment]
> We will maintain a deny list of ports that may never be specified. If one of these ports appears in allowed_http_hosts, it will fail validation.

I don't think this should be enforced by Spin, but rather the infrastructure where a Spin application would eventually run. In most platforms that would be a firewall run more generally applied, and not be configured on a per-application basis.

**Comment by mikkelhegn** [comment]
It would be nice if the `allowed_http_hosts` attribute would accept wildcards for protocol, domain, and port - e.g., `*://*.my.domain:*`. I think this will be particularly useful during development.

This proposal could be a separate issue :-)
