### ISSUE TITLE
Update version in installer as part of release process

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/spin#733]
The https://spin.fermyon.dev/release-process has a number of steps which ensure that a new release is comprehensive.

The new Spin installer [1] has the version of Spin as an environment variable (in the install.sh). 

It would be great to add one more item to the checklist of the `release-process` which requests that the `install.sh`'s variable of `VERSION="vx.x.x"` is updated as part of the release.

[1] https://github.com/fermyon/spin/pull/729

**Comment by mikkelhegn** [comment]
This should be implemented in the installer script with this commit: https://github.com/fermyon/spin/pull/729/commits/591525bac3334d8762f2f6064ccc30074feb220e

**Comment by kate-goldenring** [comment]
@mikkelhegn are you saying that the script has been updated to resolve this issue since it automatically pulls latest now? If so, @tpmccallum is this issue okay to close?

**Comment by mikkelhegn** [comment]
It defaults to latest and gives you options to use tagged releases including Canary.

**Comment by mikkelhegn** [comment]
@tpmccallum - can this be closed?

**Comment by itowlson** [comment]
Okay it's been 18 months, I'm calling it: yes we can close this
