### ISSUE TITLE
Release: Solution for automated template updates and tag

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#736]
We've added some really nice automation (thank you @FrankYang0529!)  for updating the spin templates on a new release and having our ci bot push the resulting commit.

Alas, unfortunately, the DCO bot check that is required as part of our branch protections will fail, as it doesn't have a chance to run in this automated scenario -- despite the commit being signed-off and GPG-signed (and thus fully compliant.)

The 1 approving reviewer also appears to block, so there may be 2 hurdles here:

`remote: error: Required status check "DCO" is expected. At least 1 approving review is required by reviewers with write access.`

Here's the failure from a recent tag push: https://github.com/fermyon/spin/runs/8161608149?check_suite_focus=true

Let's find a solution so that we can keep this automation.

**Comment by vdice** [comment]
Since we're currently blocked by two branch protections that we're not willing to disable (DCO bot and approving reviewer), we could potentially revise our strategy and instead of having CI attempt to merge straight to main with the updates, it creates a PR instead.  We lose automation of the final templates tag push -- well, maybe there's a way to add it in a different place, perhaps monitoring for particular changes to certain directories (templates, etc).  But pushing that tag after merging of the PR is fairly low-effort.

**Comment by rajatjindal** [comment]
we did something similar for `krew-index` version updates. We have a bot `krew-release-bot` that opens the PR on new tag push (the bot account had signed the dco) and then another bot to verify if it is just a version update and auto-approve and merge.

one such sample pr is here: https://github.com/kubernetes-sigs/krew-index/pull/2562
