### ISSUE TITLE
Add `build` setting to example manifest in intro docs

### ISSUE THREAD

**Issue by coderoflagos** [fermyon/spin#744]
In the 'Spin Manifest' section of the introduction page, I noticed the code snippet under it does not have the` [component.build] `section that shoild have the `command = "cargo build --target wasm32-wasi --release"` code  below it.

**Comment by lann** [comment]
The build command isn't required, its just a convenience so you can build with `spin build`. Given the current organization of that introduction I don't think its really necessary, but arguably we could be using templates there in the intro anyway...

**Comment by itowlson** [comment]
@coderoflagos Given Lann's comments, how do you feel about this?  Happy to accept a PR if you are keen to see it, but if you're happy with Lann's reply then should we close this?  Thanks!
