### ISSUE TITLE
Update: Need to show how to setup Spin with Intel-Based Macs.

### ISSUE THREAD

**Issue by coderoflagos** [fermyon/spin#745]
I also had this problem earlier on because I did not find a section that could help explain how to set up with the Intel-Based Macs release.

**Comment by mikkelhegn** [comment]
@coderoflagos - could I ask you to test the script in this PR for that case? https://github.com/fermyon/spin/pull/729

That PR will also update the quickstart to make this easier.

**Comment by coderoflagos** [comment]
No qualms, doing that right away.

**Comment by vdice** [comment]
Shall we close this issue now that we have [an install script](https://developer.fermyon.com/spin/install#installing-spin)?
