### ISSUE TITLE
Add http-csharp template to the defaults

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#752]
When you run the `spin template list` command for the first time, you are guided on how to install templates from the Spin repo. This however does not include the templates from the .net sdk: https://github.com/fermyon/spin-dotnet-sdk/tree/main/templates

It would be great to have that template as part of the default set of templates, the CLI suggests

```
🐟 > spin templates list
You have no templates installed. Run
spin templates install --git https://github.com/fermyon/spin
to install a starter set.

mikkel on laptop ~
🐟 > spin templates install --git https://github.com/fermyon/spin
Copying remote template source
Installing template redis-rust...
Installing template http-grain...
Installing template http-swift...
Installing template http-c...
Installing template http-rust...
Installing template http-go...
Installing template http-zig...
Installing template redis-go...
Installed 8 template(s)
```

**Comment by itowlson** [comment]
My reasoning for not doing this was that the .NET SDK is extremely early-stage at this point.  I would prefer to leave it as a separate install for now.

Longer term, we need to have a think about what templates get 'blessed' into the Spin repo vs which users can install if they're interested (this will be a consideration particularly for third-party templates and SDKs).

**Comment by radu-matei** [comment]
We also want to consider moving all templates out of the Spin repository itself.

**Comment by itowlson** [comment]
Closing this one as won't do.  We can and should continue to reassess which templates are in the "suggested" repo (whichever that is) as the various integrations mature.

**Comment by mikkelhegn** [comment]
Thx Ivan, do you think the next step would be to create a SIP for this?

**Comment by itowlson** [comment]
That sounds like a good plan.  We should figure out a policy the criteria to bless:

* A Fermyon-supported template (that is, a template that we have committed to maintain)
* A third-party template to be blessed (that is, a template that we would rely on someone else to maintain) - this might be "never" of course!
