### ISSUE TITLE
End to end `spin deploy` failing on Windows

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#774]
The setup for configuring a local installation of the platform is currently failing on Windows:

https://github.com/fermyon/spin/actions/runs/3087099411/jobs/4992111875

```
ParentContainsErrorRecordException: D:\a\_temp\a453c273-5a3d-4e60-95f0-fa6de281eb13.ps1:2
Line |
   2 |  (New-Object System.Net.WebClient).DownloadFile("https://github.com/de …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403)
     | Server failed to authenticate the request. Make sure the value of Authorization header is formed
     | correctly including the signature.."

Error: Process completed with exit code 1.
```

**Comment by vdice** [comment]
@radu-matei @rajatjindal is this still ocurring?  I'm assuming we've updated/increased our Windows testing but not sure if this scenario is covered (and successful) now or not.

**Comment by rajatjindal** [comment]
I think windows e2e tests were disabled completely due to disk issues. This is on my todo list for next week.
