### ISSUE TITLE
Ability to search the docs site

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#775]
Some of the detailed reference information for Spin is found in-line in the existing articles. It would be great to have a search feature on the docs website to search for specific terms, and not rely on the navigation pane only.

**Comment by vdice** [comment]
I believe we can close this one out now that Spin docs are hosted at https://developer.fermyon.com/, which has search courtesy @karthik2804 🎉 .  If so, I'll let @karthik2804 or @mikkelhegn do the honors 😄
