### ISSUE TITLE
Add Spin HTTP C++ template

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#78]
The templates directory should contain a template for writing C++ HTTP components.

An example on how to write a C++ module based on a WIT definition can be found here — https://github.com/fermyon/wasi-experimental-toolkit/tree/main/tests/modules/cache-cpp

**Comment by dicej** [comment]
@radu-matei I could take a crack at this.  Can you clarify what you mean by "the templates directory", though?  I don't see such a directory in the spin repo.  I do see a crates/templates directory, which I assume is related but not what you're referring to here.

**Comment by radu-matei** [comment]
Back when the issue was created, there used to be one..
Now we have an `examples` directory, which this would go into.

See https://github.com/fermyon/wasi-experimental-toolkit/tree/main/tests/modules/cache-cpp for an example of how this would look like.

**Comment by radu-matei** [comment]
Added in #433
