### ISSUE TITLE
Bindle manifests still use camelCased keys

### ISSUE THREAD

**Issue by lann** [fermyon/spin#806]
Looks like this was missed back in https://github.com/fermyon/spin/pull/157 and hasn't been a problem until recent testing.

**Comment by lann** [comment]
This looks promising: https://crates.io/crates/serde_alias

**Comment by lann** [comment]
It turns out the only field that really matters here is `allowed_http_hosts` / `allowedHttpHosts`.

Fixing this will require updating hippo, which does expect `allowedHttpHosts`:

https://github.com/deislabs/hippo/blob/c9c09e9df6b38787e7817754ce6660bad566dc57/src/Infrastructure/Services/BindleService.cs#L63

https://github.com/deislabs/hippo/blob/627b51e1ef368349c964353e7dab591157ce9278/src/Application/Common/Interfaces/BindleService/RevisionComponent.cs#L23

**Comment by itowlson** [comment]
Closing in the light of the OCI work - please reopen if you think we should keep it around.
