### ISSUE TITLE
spin bindle push failed

### ISSUE THREAD

**Issue by bitoceango** [fermyon/spin#811]
when I push my spin to bindle ,i get a error

```
spin bindle push --file spin.toml

Error: Failed to push bindle to server

Caused by:
    0: Failed to push bindle from '/var/folders/qz/yslvsynn7759ymsywz9krplh0000gp/T/.tmpfFWXhC' to server at 'http://localhost:8080/v1'
    1: Invalid TOML
    2: expected a table key, found a left brace at line 1 column 1
```

my bindle server toml

```
address = "127.0.0.1:8000"
bindle-directory = "/var/run/bindle"

```
my bindle server start by 

> ./bindle-server --config-path ./server.toml   --unauthenticated

my spin create by

> spin new http-rust spin-hello-world

I change nothing in the spin.toml

```
spin_version = "1"
authors = ["xingyuntian <xingyuntian@lixiang.com>"]
description = ""
name = "spin-hello-world"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-hello-world"
source = "target/wasm32-wasi/release/spin_hello_world.wasm"
[component.trigger]
route = "/hello"
[component.build]
command = "cargo build --target wasm32-wasi --release"

```

**Comment by itowlson** [comment]
If I read this correctly, you are running your Bindle server port 8000 and the command is pushing to port 8080 - is that right?  If so, is there something else running on 8080, maybe something that might be returning a JSON response?

If I'm misunderstanding and the addresses do match, could you try turning on logging (`RUST_LOG=spin=trace`), and could you also try doing a `spin bindle prepare` and sharing the generated invoice?  Thanks!

**Comment by bitoceango** [comment]
Yes， it is my mistake, thank you very much for your prompt reply

**Comment by itowlson** [comment]
Great, thanks for letting us know!  I'll close the issue.
