### ISSUE TITLE
Where in the docs should the install script direct people?

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#812]
The install script currently tells people to go to https://spin.fermyon.dev/quickstart/ "for the next steps".  The first four headings on that page tell people two different ways to install Spin plus how to build it from source - which are definitely not the next steps if you've just run the install script!

Should we link people more directly to the post-installation app creation stuff?

**Comment by mikkelhegn** [comment]
We should - this heading would be the one "Creating a new Spin application from a template". Once the docs move to developer.fermyon.com we can link to that heading.

**Comment by mikkelhegn** [comment]
That page (https://spin.fermyon.dev/quickstart/) has now been updated so it only has one reference to install, then moves to using templates, creating an application, etc.

**Comment by vdice** [comment]
With https://github.com/fermyon/spin/issues/812#issuecomment-1290418677 in mind (and anticipating the install script fix in https://github.com/fermyon/developer/pull/173, is this eligible to close?

**Comment by mikkelhegn** [comment]
I think it is. Will go ahead and close.
