### ISSUE TITLE
spin login when cloud API returns non-200 status code

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#850]
`spin login` when using the first 'Sign in with GitHub option' appears to return/print the page contents even when the response code is not 200 (I imagine this is fine for 2xx and perhaps redirects?)

I'd expect it _not_ to print the page contents when the intended url returns any other status code, and that it print some generic error message, etc.

For example:

```
$ spin login --url https://my-cloud-url
What authentication method does this server support?

1. Sign in with GitHub
2. Sign in with a username and password

Enter a number: 1
Error: Bad Gateway
```

Or, a more decorated error page might be returned, in which case raw html will be printed:

```
$ spin login --url https://my-cloud-url
What authentication method does this server support?

1. Sign in with GitHub
2. Sign in with a username and password

Enter a number: 1
Error: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Not Found...
```

**Comment by FrankYang0529** [comment]
Looks like we return error content here.
https://github.com/fermyon/spin/blob/f94e397a7c5f83a753e3333ec3d9eed2a440261a/crates/cloud/src/client.rs#L289

We can get [this content in `format_response_err`](https://github.com/fermyon/cloud-openapi/blob/350f67d7abf3cab9da83a44ba93ff5bfc2ad8b29/clients/rust/src/apis/mod.rs#L5-L9). Do you prefer to return the error status code?

**Comment by vdice** [comment]
Thanks @FrankYang0529.  Yes, I think it might be wiser to print the status code instead and perhaps include some generic "failed to login to the server" message.  WDYT?
