### ISSUE TITLE
Missing `Contributing.md` file

### ISSUE THREAD

**Issue by karthik2804** [fermyon/spin#852]
The file that guides users on how to contribute to this repository is missing.

**Comment by mikkelhegn** [comment]
There is a contributing.md file in the root, which directs to https://spin.fermyon.dev/contributing/, which redirects to https://developer.fermyon.com/spin/contributing

**Comment by mikkelhegn** [comment]
@karthik2804 - do you want to propose a change to the above?

**Comment by karthik2804** [comment]
That solves the issue.
