### ISSUE TITLE
multipart/form-data in outbound http request body

### ISSUE THREAD

**Issue by Joera** [fermyon/spin#854]
Hi i would like to make an outbound http request that requires body to be multipart/form-data, specifically: [https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-dag-put](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-dag-put)

Any ideas how i would go about doing this? 

Thanks, Joera

**Comment by itowlson** [comment]
You'd need to use your language's facilities to build a suitable request body.  What language are you writing in?  If it's one we know we may be able to offer pointers (if not you could try our Discord at https://discord.gg/AAFNfS7NGf).

**Comment by Joera** [comment]
Thanks, i'll teleport to discord.
