### ISSUE TITLE
Cannot run install script - `curl https://spin.fermyon.dev/downloads/install.sh | bash`

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#858]
`curl https://spin.fermyon.dev/downloads/install.sh | bash` doesn't work.

The install script has been moved to `https://developer.fermyon.com/downloads/install.sh`. We recommend you user the `--location / -L` flag for curl to ensure it follows any redirects.

Both of the following commands will work:
`curl -L https://spin.fermyon.dev/downloads/install.sh | bash` or
`curl -L https://developer.fermyon.com/downloads/install.sh | bash`

**Comment by vdice** [comment]
Closed by https://github.com/fermyon/developer/pull/173
