### ISSUE TITLE
Deploy a http outbound application on Fermyon cloud, return "error code 1005"

### ISSUE THREAD

**Issue by CHCP** [fermyon/spin#874]
Hi there, 
   Fermyon cloud is a great WASM application, I would like to test and use it.

  I created a http outbound application from template and example, it is works well on my local laptop, 
but there is an "error code: 1005" when I deploy this to Fermyon cloud an invoke the url.

 Http outbound is not support by Fermyon cloud yet? Thank you.

The spin.toml:
```
spin_version = "1"
authors = ["Gordon"]
description = "my http"
name = "myhttp"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "myhttp"
source = "target/wasm32-wasi/release/myhttp.wasm"
allowed_http_hosts = ["https://some-random-api.ml"]
[component.trigger]
route = "/outbound"
[component.build]
command = "cargo build --target wasm32-wasi --release"
```

The http outbound code:
```
use anyhow::Result;
use spin_sdk::{
    http::{Request, Response},
    http_component,
};

/// A simple Spin HTTP component.
#[http_component]
fn myhttp(_req: Request) -> Result<Response> {
        let mut res = spin_sdk::outbound_http::send_request(
            http::Request::builder()
                .method("GET")
                .uri("https://some-random-api.ml/facts/dog")
                .body(None)?,
        )?;
        res.headers_mut()
            .insert("spin-component", "rust-outbound-http".try_into()?);
        println!("{:?}", res);
        Ok(res)        
}

```

**Comment by vdice** [comment]
Hi @CHCP, glad to hear you're testing out Spin and Fermyon Cloud and thanks for filing this issue.

The app is actually running successfully (as you've seen/confirmed when running locally) and it looks like the `https://some-random-api.ml` host is returning this error code/message when requests originate from the `fermyon.app` domain.  I have a feeling we've maxed out their inbound request limit per origin domain and they've temporarily blocked requests from fermyon.app 😅   We'll want to look into how long this might be and update our outbound examples to use a different host.

Meanwhile, if you'd like to try using a different host and confirming that the same app runs as intended on Fermyon Cloud, you can update the following two values in the example app  with new URLs of your choosing.

- `allowed_http_hosts` in the app's [spin.toml](https://github.com/fermyon/spin/blob/main/examples/http-rust-outbound-http/spin.toml#L11)
- the `uri` vlaue in the app's [lib.rs](https://github.com/fermyon/spin/blob/main/examples/http-rust-outbound-http/src/lib.rs#L13)

Then, rebuild and redeploy.

For example, I happened to recently use:

- `https://timeapi.io` for `allowed_http_hosts` and
- `https://timeapi.io/api/Time/current/zone?timeZone=GMT` in `lib.rs`

Here's that app: https://spin-outbound-http-esgzr1tx.fermyon.app/outbound

Hopefully this helps unblock further forays into Spin/Fermyon Cloud and thanks again for letting us know about the 1005s.

**Comment by CHCP** [comment]
Hi @vdice 
Thanks for your help, it is works now.
