### ISSUE TITLE
Build from http-go template, return errors "undeclared name: get"

### ISSUE THREAD

**Issue by rts-gordon** [fermyon/spin#880]
Hi there,
I am testing golang wasm for Fermyon Cloud, but get some compile errors, can you please to take a look at this. Thanks a lot.

Environment:
Windows 10, Golang 1.18, Tinygo 0.25.0, Binaryen: 110

Spin new from http-go template, did not modify any code, run spin build:
```
spin build
Executing the build command for component gohttp: tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go
# github.com/fermyon/spin/sdk/go/http
C:\Users\User\go\pkg\mod\github.com\fermyon\spin\sdk\go@v0.6.0\http\http.go:31:9: undeclared name: get
C:\Users\User\go\pkg\mod\github.com\fermyon\spin\sdk\go@v0.6.0\http\http.go:38:9: undeclared name: post
C:\Users\User\go\pkg\mod\github.com\fermyon\spin\sdk\go@v0.6.0\http\http.go:45:9: undeclared name: send
Error: Build command for component gohttp failed with status Exited(1).
```

**Comment by itowlson** [comment]
Thanks for letting us know about this.  I just tried it on my Windows machine and it built and ran successfully.  My versions look the same as yours so I'm not sure what the difference could be.  The functions it's reporting as 'undeclared' are defined in the `http/outbound_internals.go` file within the Spin Go SDK, and Go is clearly finding the SDK all right.  There is some C interop happening within `outbound_internals.go`, so there could be an environmental difference there (I'm not sure how Go/C interop works); but even if there was, I wouldn't expect it to cause 'undeclared name' errors for Go functions.

@adamreese or any of our other Go wizards: any idea what could cause this?

**Comment by adamreese** [comment]
Will it build after running `go get github.com/fermyon/spin/sdk/go`?

**Comment by CHCP** [comment]
Hi @adamreese 
  Yes, I have download go sdk for fermyon via "go get github.com/fermyon/spin/sdk/go", but there are still the same errors.

  Thanks for your attention.

**Comment by dennisg** [comment]
I stumbled upon the same. Was able to fix it by inspecting my env vars and noticing that my
`CGO_ENABLED` was set to `0`

Can you please try: `GCO_ENABLED=1 spin build` ?

**Comment by radu-matei** [comment]
Ah, yes, the Spin SDK is built using CGO, so having that set to `0` means the SDK cannot be properly built.

Please let us know if that solves it, and thanks a lot for the help, @dennisg!

**Comment by itowlson** [comment]
Something to add to the command if we can do so portably, otherwise to the docs and the build prerequisites (if and when we ever have them!).

**Comment by rts-gordon** [comment]
Hi @dennisg @radu-matei  @itowlson 
 It is works use this command "CGO_ENABLED=1 spin build". It is wonderful if we can update the documents and the build prerequisites. 

  Thanks for all of your help.
