### ISSUE TITLE
`spin deploy` with expired token switches you to production cloud

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#881]
I was logged into a test environment but my token had expired.  I did a `spin deploy` which prompted me to log in.  But it tried to log me into Fermyon Cloud rather than my test environment.  This is unexpected and non-obvious.

This would likely affects only internal Fermyon users at the moment.

**Comment by vdice** [comment]
Adding a bit of further context for the contributor who works on the fix.

The bug, as mentioned, occurs when `spin deploy` is invoked in combination with use of the default deployment environment (e.g. configuration persisted in `config.json` in the OS-appropriate fermyon application dir):

```
$ cat /Users/vdice/Library/Application\ Support/fermyon/config.json
{
  "url": "http://hippo.212.2.246.65.sslip.io/",
 ...
  "expiration": "2023-01-04T18:01:05Z"
}

$ spin deploy

Copy your one-time code:

ITPtynkD

...and open the authorization page in your browser:

https://cloud.fermyon.com/device-authorization

Waiting for device authorization...
^C
```
The command should check the value of the `url` field in the configuration and prompt for a login using that, as it does correctly when using a non-default env:
```
$ export FERMYON_DEPLOYMENT_ENVIRONMENT=vdice

$ spin deploy
Your login to this environment has expired
Run `spin login --environment-name vdice` to log in again
```

**Comment by itowlson** [comment]
I dunno if this is still a thing but if it is then it's a thing for cloud-plugin.  Closing here, we can recreate there if it becomes bothersome enough
