### ISSUE TITLE
Improve template discoverability and categorisation

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#919]
From @mikkelhegn (https://github.com/fermyon/spin/issues/629#issuecomment-1326572845):

> What I believe we should achieve with this is when a person, who is educating themselves by exploring Spin using the CLI, will be able to easily identify what a given Spin template gives them in terms of functionality and availability in programming languages. If I'm a developer who prefers writing code in Go, I can easily identify the templates (using `spin new`, `spin add` and `spin templates list`, that are available for Go, sorted by their key features (e.g., type of trigger). I am also able to find a reference to a document (a link), where I can find more information about the specific template (e.g., if it's a pre-built component, a link to the components GitHub repo would be a good example. If it's an http-trigger component, a link to the description of http-triggers would be a good option).

Starting a new issue for this so we can talk about this independently of the "application build dependencies" issue.

**Comment by itowlson** [comment]
A detail to consider here (as with the parent issue) is "day one vs day two."

Day one is component creation time.  A user walks up to Spin and goes "okay I want to make a Web application in Go" or "okay my application needs to serve CSS files."  This is where templates come in, and where the template UI can help via filtering and categorisation.

Day two is when the template output has scrolled off the screen.  A user walks up to an _existing_ application and goes "how the heck do I get the full URL" or "how the heck do I do set operations."  This is where usage links should _remain_ readily discoverable, rather than relying on the user to work back to the template.  (This is not to say they shouldn't be presented along with the other template discoverability stuff - just that they should not be part of the template UI _only_.)

**Comment by itowlson** [comment]
Regarding template discoverability, one idea that I've been mulling is tags.

A template could be annotated with any number of tags, e.g. trigger type, language, use case.  These need not be particularly structured, though trigger and language could be.  Then the user could type `spin templates list --tag http --tag go` and see only templates with those tags.

We could go even further and allow the user to write `spin templates list http` and it would filter to tag matches (and, I'd suggest, name matches).  However, this wouldn't work so well for `spin new` and `spin add`, because in `spin new http go` you couldn't tell whether the second argument was an additional filter or a project name.

**Comment by itowlson** [comment]
Distinguishing a language (rather than having it as just another tag) would open the way for users to set a preferred language via an environment variable, so they only ever needed to see templates compatible with their preferred language.

(Though more generally one could imagine the environment variable as 'filter' rather than specifically 'language.')

**Comment by mikkelhegn** [comment]
> Day one is component creation time. A user walks up to Spin and goes "okay I want to make a Web application in Go" or "okay my application needs to serve CSS files." This is where templates come in, and where the template UI can help via filtering and categorisation.

I think we could make a reference (a link) for each template, which will contain the explanation of e.g., the build dependencies, and I believe that would be of great help for users to have a successful experience on day one. A comparison could be made to a package manager, where every package has a small docs site (e.g. npm). This aligns well with the parent issue.

> Day two is when the template output has scrolled off the screen...relying on the user to work back to the template.

Yes, users need to be directed to the official docs to get answers beyond day one, so the small template overview page is not enough. I don't see these as mutually exclusive.

**Comment by mikkelhegn** [comment]
> Regarding template discoverability, one idea that I've been mulling is tags.

> Distinguishing a language

I think both of these are great suggestions, and makes it easier for developers, especially when the list of templates grows.

**Comment by itowlson** [comment]
Definitely not mutually exclusive!

**Comment by michelleN** [comment]
I love the idea of adding tags as a first step. I think we could add in the language preference environment variable on top of that later on.

**Comment by michelleN** [comment]
>I think we could make a reference (a link) for each template, which will contain the explanation of e.g., the build dependencies, and I believe that would be of great help for users to have a successful experience on day one. A comparison could be made to a package manager, where every package has a small docs site (e.g. npm). This aligns well with the parent issue.

Would adding a README to each template directory in [spin/templates](https://github.com/fermyon/spin/tree/main/templates) and linking back to that be satisfactory?

**Comment by michelleN** [comment]
On tags, do you envision them to be added to the `metadata/spin-template.toml` file @itowlson ?

**Comment by itowlson** [comment]
Yes, that's what I'd expect, but open to other thoughts!

**Comment by michelleN** [comment]
Open question on template documentation. How does a user see that link in the spin new UI? rather, where should they see that link? in `spin templates list` with/without some flag? in `spin new` with/without some flag?

**Comment by mikkelhegn** [comment]
`dotnet new` is one example to look at.

```
Template Name         Short Name    Language    Tags
--------------------  ------------  ----------  -------------------
ASP.NET Core Web App  webapp,razor  [C#]        Web/MVC/Razor Pages
Blazor Server App     blazorserver  [C#]        Web/Blazor
Class Library         classlib      [C#],F#,VB  Common/Library
Console App           console       [C#],F#,VB  Common/Console
```

In that experience a shortname is also the id, and is how it's referenced in [documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new). We could have a convention for the links: developer.fermyon.com/spin/templates/http-rust - or something like that. Not sure if it's easily discoverable, but the `spin new` command could add that info as a help.

**Comment by vdice** [comment]
With https://github.com/fermyon/spin/pull/1119 and potentially https://github.com/fermyon/spin/issues/1151, do we consider the goals of this issue met?  Or are there other items we'd like to track?

**Comment by mikkelhegn** [comment]
I think there is still work to do to connect templates with documentation, and to add tags to all the existing templates. Not sure if you want separate issues for those tasks?

**Comment by fibonacci1729** [comment]
@mikkelhegn tags have been added to all existing templates; documentation went out with 0.9.0 I believe.
