### ISSUE TITLE
Make log output to stdout default

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#928]
When running Spin locally in a development loop, I always use `--follow-all` to have my logs written out to the console.

From conversations I've heard others not discovering this option, e.g.:

> Debugging in spin was an initial pain point until finding the log directory. Did not find about follow-all until pretty late

I'd like to propose that writing logs to stdout becomes the default behavior, and that a new option to only output to log files gets introduced, e.g. `--silent` or `--no-stdout`.

**Comment by radu-matei** [comment]
Is that "make writing to standard output default and _not_ write to a log directory", or do we want both?

**Comment by mikkelhegn** [comment]
My preference would be default to both, if completeness is important, having switches being `--logging file-only` `--logging stdout-only` could be the way to go.

**Comment by etehtsea** [comment]
###### TLDR
I would like to propose the following:
- Default: to write into STDOUT/STDERR (only) (`The Twelve Factor App` [justifies this behavior](https://12factor.net/logs)).
- If `-L`/`--log-dir` is provided without value: write to the default directory.
- If `-L`/`--log-dir` is provided with value: write into the specified directory.

Nice to have:
- To provide the default directory in the help output:

```
    -L, --log-dir <APP_LOG_DIR>
            Log directory for the stdout and stderr of components
```

```
    -L, --log-dir <APP_LOG_DIR>
            Log directory for the stdout and stderr of components [default: $HOME/.spin/<component-name>]
- Expose global (that makes sense across all trigger types) trigger args in the `up`/`build --up`` help output (please see rationale below)

The problem with `--follow-all` could be the UX issue because there it's hidden in the `--help`.

My expectation when I run `build --up -h` is to see `up` args included in the help output.

```
$ spin build --up -h
spin-build 
Build the Spin application

USAGE:
    spin build [OPTIONS] [UP_ARGS]...

ARGS:
    <UP_ARGS>...    

OPTIONS:
    -f, --file <APP_CONFIG_FILE>    Path to spin.toml
    -h, --help                      Print help information
    -u, --up                        Run the application after building
```

Then `spin up` is missing `trigger` args:

```
$ ./target/release/spin up -h        
spin-up 
Start the Spin application

USAGE:
    spin up [OPTIONS]

OPTIONS:
    -b, --bindle <BINDLE_ID>
            ID of application bindle

        --bindle-password <BINDLE_PASSWORD>
            Basic http auth password for the bindle server [env: BINDLE_PASSWORD=]

        --bindle-server <BINDLE_SERVER_URL>
            URL of bindle server [env: BINDLE_URL=]

        --bindle-username <BINDLE_USERNAME>
            Basic http auth username for the bindle server [env: BINDLE_USERNAME=]

    -e, --env <ENV>
            Pass an environment variable (key=value) to all components of the application

    -f, --file <APP_CONFIG_FILE>
            Path to spin.toml

    -h, --help
             

    -k, --insecure
            Ignore server certificate errors from bindle server

        --temp <TMP>
            Temporary directory for the static assets of the components
```

But the trigger command is hidden from the subcommands list:

```
./target/release/spin --help
spin 0.6.0 (db3a68d 2022-11-30)
The Spin CLI

USAGE:
    spin <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    add          Scaffold a new component into an existing application
    bindle       Commands for publishing applications as bindles
    build        Build the Spin application
    deploy       Deploy a Spin application
    help         Print this message or the help of the given subcommand(s)
    login        Log into the server
    new          Scaffold a new application based on a template
    plugin       Install/uninstall Spin plugins
    templates    Commands for working with WebAssembly component templates
    up           Start the Spin application
```

The only way to figure out about trigger args (besides the developer docs) is to notice it when spin is started with `RUST_LOG=spin=trace`:

```
 RUST_LOG=spin=trace ../../target/release/spin build --up
Executing the build command for component hello: cargo build --target wasm32-wasi --release
    Finished release [optimized] target(s) in 0.01s
Successfully ran the build command for the Spin components.
2022-12-01T12:03:12.920883Z TRACE spin_cli::commands::up: Running trigger executor: "/spin/target/release/spin" "trigger" "http"
2022-12-01T12:03:12.927711Z TRACE spin_http: Constructed router for application spin-hello-world: {Exact("/hello"): "hello"}    
Serving http://127.0.0.1:3000
2022-12-01T12:03:12.927763Z  INFO spin_http: Serving http://127.0.0.1:3000    
Available Routes:
  hello: http://127.0.0.1:3000/hello
    A simple component that returns hello.
^C2022-12-01T12:03:14.428816Z  INFO spin_trigger::cli: User requested shutdown: exiting
```

So `--follow-all` is available in the `spin trigger <trigger-type> -h` output, but it's hard to figure out the existence of `spin trigger -h` at all.

**Comment by itowlson** [comment]
@etehtsea this seems like a bug in `up`.  There are some trigger-specific arguments like `--listen` that are only shown if a `spin.toml` with that trigger is present.  But `--follow-all` is generic and should always be shown.

We should also maybe add a message to `spin up --help` _without_ a `spin.toml` to say "additional options may be available in the presence of a manifest" (yes with less terrible wording).

**Comment by itowlson** [comment]
...oh, and also `spin build` at the very least should mention that "if `--up` is present then `up` options are also available - see `spin up --help` for details" (again with better wording)

**Comment by etehtsea** [comment]
If it's nothing urgent, I can take a look into it

**Comment by itowlson** [comment]
Well, it looks like trigger options _used_ to be surfaced if there was a `spin.toml` present (https://github.com/fermyon/spin/issues/815) but have fallen off again.  I'll raise a separate issue for that.
