### ISSUE TITLE
Support TLS for outgoing Postgres

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#936]
Connecting to a Postgres server using 'outbound-pg' currently doesn't support TLS. https://github.com/fermyon/spin/blob/c368fce72261339b6de908e22b81cf21217a8181/crates/outbound-pg/src/lib.rs#L242

This prevents a Spin application from using e.g. [Neo](https://neon.tech/)

**Comment by etehtsea** [comment]
I'll open a PR soon

**Comment by etehtsea** [comment]
Should be fixed by https://github.com/fermyon/spin/pull/1003
