### ISSUE TITLE
request to add `spin plugin list` command

### ISSUE THREAD

**Issue by rajatjindal** [fermyon/spin#937]
it will be nice to list the `plugins` available to install (or already installed?)

**Comment by kate-goldenring** [comment]
listing available plugins (in the plugins repo) vs installed ones in fairly different on the implementation side. Do we want to support both? We could do the following:
`spin plugin list`: lists installed plugins
`spin plugin search`: displays all plugins available in plugins registry

**Comment by kate-goldenring** [comment]
`apt list` lists the catalog and `apt list --installed` lists installed so we may want to model after that since we have been consistent with apt so far
