### ISSUE TITLE
Remove `spin plugin update` and fetch latest on `spin plugin install`

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/spin#939]
`spin plugin --help` and `spin templates --help` should have similar subcommands listed. Instead of a `spin plugin update` command to get the latest plugins from the `spin plugins` repo, `spin plugin install` should fetch latest and then install. Related to: https://github.com/fermyon/spin/issues/937

```sh
kagold@MacBook-Pro spin % spin templates --help
spin-templates 
Commands for working with WebAssembly component templates

USAGE:
    spin templates <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    help         Print this message or the help of the given subcommand(s)
    install      Install templates from a Git repository or local directory
    list         List the installed templates
    uninstall    Remove a template from your installation
```
VS
```sh
kagold@MacBook-Pro spin % spin plugin --help
spin-plugin 
Install/uninstall Spin plugins

USAGE:
    spin plugin <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    help         Print this message or the help of the given subcommand(s)
    install      Install plugin from a manifest
    uninstall    Remove a plugin from your installation
    update       Fetch the latest Spin plugins from the spin-plugins repository
    upgrade      Upgrade one or all plugins
```

**Comment by itowlson** [comment]
Uh, I can't remember!  I suspect it dates back to when we defaulted to installing from `main`, and the idea was not to disturb the user's working templates unless they asked us to.  But now we install from a version-appropriate tag, and so it would perhaps be better to overwrite by default.  But honestly I'm not sure!

**Comment by kate-goldenring** [comment]
I can see it being useful for airgapped or edge scenarios where you only want to pull when necessary

**Comment by itowlson** [comment]
But the (templates) implementation is to pull the entire Git repo anyway.  It's absurdly profligate even if all it ends up doing is going "welp there's nothing to install."

_teeters on the edge of the 'how can we just download the bit we need' rabbit hole again_

**Comment by kate-goldenring** [comment]
Doesnt it only pull it if it (`.git`) isnt found locally? The airgapped scenario i anticipate would be shipping the templates directory and plugins directory with the spin binary so it would never pull from remote

**Comment by itowlson** [comment]
Templates are disconnected from their origin.  The `install` command pulls the repo to a temp drectory, copies the templates into the store, and then deletes the cloned repo.  This is (1) to achieve a flat namespace for the templates and (2) to avoid crufting up the user's storage with full clones of all source repos.

**Comment by kate-goldenring** [comment]
This makes a good point. I am not sure why we are retaining the plugins repo locally. I think we were modeling a bit after apt here but I dont see why we need to entire repo locally when we are just installing one plugin. We could similarly use tempdir and then delete it. @karthik2804 do you remember our reasoning here?

**Comment by itowlson** [comment]
Heh, I hope I'm not making points - more just clarifying how the templates system works as built.  The disconnection brings weaknesses too.  E.g. it means a user who wants to update a template has to remember where it came from and "re-install" it.  Or, say, there's no way for `spin new` to check back on the source and say "hey this template is out of date, shall I grab the new version before you run it."  It's definitely not a model I'm trying to persuade you to follow.  If I'd had more time and willpower, I would likely have made different tradeoffs!

**Comment by kate-goldenring** [comment]
This is the thread that lead to the decision: https://github.com/fermyon/spin/pull/712#discussion_r953016347 
It was to avoid the scenario of homebrew which had costs from doing clones every time

**Comment by kate-goldenring** [comment]
I think given that we originally made decisions we did to match what most package managers do (https://github.com/fermyon/spin/pull/712#discussion_r953016347), I think we should stick with the decisions we made and understand that templates and plugins are different (https://github.com/fermyon/spin/pull/941#pullrequestreview-1209019379) and may not need to have similar user experiences and they are dissimilar in many ways.
