### ISSUE TITLE
Add aliases to `plugin` and `templates` subcommands for plurality

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/spin#942]
Having aliases for the singular and plural of `plugin/s` and `template/s` subcommands would help reduce user error.
See https://docs.rs/clap/latest/clap/struct.Arg.html#method.alias

**Comment by raymundovr** [comment]
Hi, can I work on this one?

**Comment by itowlson** [comment]
@raymundovr Sure - thanks!

**Comment by raymundovr** [comment]
@itowlson have submitted a PR, let me know if that's a correct approach.

**Comment by itowlson** [comment]
I think it depends.  Were you thinking of sending another PR to change the 'default' plurality @raymundovr?  If so, then there's little point raising a new issue for 'part 2' (unless that would be useful to you).  But if we're parking this as 'done for now' - which is 100% reasonable, as your merged contribution fulfils what was asked for - then we should close.

**Comment by raymundovr** [comment]
hi @itowlson, just wanted to corroborate after the PR comments, up to you.

**Comment by itowlson** [comment]
Cool, I'll close this - thanks!
