### ISSUE TITLE
Improve error messaging on missing import

### ISSUE THREAD

**Issue by lann** [fermyon/spin#946]
This doesn't give you a whole lot to go on if you have more than one component:

```
Error: unknown import: `wasi_experimental_http::close` has not been defined
Error: exit status: 1
```

**Comment by radu-matei** [comment]
Would printing the component where this is coming from be enough to address this issue?

**Comment by itowlson** [comment]
I'd suggest also some wording along the lines of "you need to rebuild the app/module with a version of the Spin SDK that matches the Spin binary" (could even say what version that is...!).

**Comment by lann** [comment]
Yeah some special-casing for specific imports works be nice.
