### ISSUE TITLE
Runtime logging SIP

### ISSUE THREAD

**Issue by etehtsea** [fermyon/spin#962]
From discussion in https://github.com/fermyon/spin/pull/705#issuecomment-1340331897

### Related PRs/issues

- https://github.com/fermyon/spin/pull/938
- https://github.com/fermyon/spin/issues/928
- https://github.com/fermyon/spin/issues/693
- https://github.com/fermyon/spin/issues/608
- https://github.com/fermyon/spin/issues/389

**Comment by itowlson** [comment]
@etehtsea Is this something you're planning to write, or would you like me or one of the other Fermyon folks to make a start and put something up for feedback?

**Comment by etehtsea** [comment]
@itowlson I'm hoping to come up with something this week

**Comment by michelleN** [comment]
@etehtsea Can this issue be closed or are there parts you are still working on / want to work on?
