### ISSUE TITLE
Add `spin up` option to mount static asset directory directly

### ISSUE THREAD

**Issue by dicej** [fermyon/spin#964]
Currently, `spin up` always copies static assets into a temporary directory and mounts that into the host.  This creates friction when iteratively developing static assets (e.g. SPAs) since `spin up` must be restarted each time any asset changes in order for the updated asset to be served.

I'm proposing that we add an option, e.g. `--direct-mount` to mount the asset directory directly instead of using a temporary directory, so that changes on the host filesystem are immediately visible to subsequent app invocations, with no restart required.

**Comment by itowlson** [comment]
It would be good to ponder the behaviour on patterns/individual files.  Many users will read a `--direct-mount` flag as implying that _all_ files, including loose ones, are also directly mounted, but as far as I know that would require mounting the entire containing directory, which is what the copy sought to avoid.

I wonder if this could instead by tackled by Radu's much-requested "hot reload" flag, which would provide for hot reload of loose files plus allow it to reflect changes in component Wasm as well as in assets.  I'm not sure if that's prohibitively more complex though!

**Comment by dicej** [comment]
I was thinking the (documented) behavior would be that `--direct-mount` only works for locally-loaded apps using only directory mounts with no excluded files, and anything else causes an error.

I agree that a general hot reload option that works for everything, including loose files and Wasms, but I'm guessing that would be significantly more work.  This proposal just solves a useful subset of that problem, which I _think_ should require a lot less effort.  I'm in the middle of prototyping this now, so we should soon know whether that's true.

**Comment by itowlson** [comment]
Yeah, if it errors on patterns then at least it's failing safe!  Sounds good - thanks!
