### ISSUE TITLE
Expunge `Error: exit status: 1`

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#966]
Some `spin up` errors get an extra line `Error: exit status: 1` appended to them.  I think this happens when `spin up` succeeded in handing off to `spin trigger ...` but the trigger command then errored out.

Is is possible to remove this?  It's no biggie, just a bit cluttery.

**Comment by itowlson** [comment]
This turns out to be a little bit nasty because if `UpCommand::run` returns an error, the Rust stdlib is hardwired to print `Error: ...`.  But if it _doesn't_ return an error, the Rust stdlib returns exit code 0.  So when `spin trigger ...` fails in a way such that we want to propagate that failure but silently, the Result type probably isn't going to work for us.

(Yes, there is a function to exit the process with a given exit code, but it bypasses destructors and stuff.  Let's not eh.)

We could return a `Termination` but it might need a bit of reorganising to keep using the nice `?` operators for the bulk of `UpCommand::run`.  And then `SpinApp::run` would get angry with us because _it_ expects to return a Result.

So maybe more effort than it's worth.

_(obligatory THIS WOULD HAVE BEEN EASY IN INSERT LANGUAGE OF CHOICE remark)_

**Comment by dicej** [comment]
Possibly naive question: why does `spin up` run `spin trigger` as a child process rather than run the trigger directly in-process?

**Comment by dicej** [comment]
> See #417.

Thanks.  So to summarize: the intention is that various trigger executors will be implemented as separate executables rather than as part of Spin itself, hence the process spawning.

**Comment by michelleN** [comment]
@itowlson is this still an issue or has this been resolved? If you have a way for me to reproduce the problem, I'm happy to look into it.

**Comment by itowlson** [comment]
@michelleN No, this has not been resolved.

An example repro is to run two Spin applications at the same time.  The second one will find the port in use and fail:

```
# While a Spin app is running in another terminal
ivan@hecate:~/testing/dioxus-demo$ spin up
Logging component stdio to ".spin/logs/"

Serving http://127.0.0.1:3000
Available Routes:
  dioxus-demo: http://127.0.0.1:3000 (wildcard)
2023-07-19T21:50:12.816162Z ERROR spin_trigger::cli: Trigger executor failed
Error: Unable to listen on 127.0.0.1:3000

Caused by:
   0: error creating server listener: Address already in use (os error 98)
   1: Address already in use (os error 98)
Error: exit status: 1
```

Note the _two_ `Error:` lines.  The first, `Error: Unable to listen on 127.0.0.1:3000`, is the actual error reported by the trigger (and is fine).  The second, `Error: exit status: 1`, is a spurious line added by `spin up`.
