### ISSUE TITLE
project name requested twice in spin new prompt

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#976]
The first line of the prompt and the third line of the prompt are essentially the same.
```
src/spin [main] $ spin new http-rust
Enter a name for your new project: hello
Project description: hello rust
Project name: hello
HTTP base: /
HTTP path: /...
```

**Comment by fibonacci1729** [comment]
@michelleN I'm not able to repro this using the canary release. I see:

```
spin [main] $ spin new http-rust
Enter a name for your new project: foobar
Project description: whatever
HTTP base: /
HTTP path: /...
```

**Comment by michelleN** [comment]
@fibonacci1729 and I paired for a bit and figured out it had to do with me having old templates. When I removed the entire templates directory and re-installed via the `spin new` prompt, everything worked as expected with no duplicate prompt for project name.
