### ISSUE TITLE
Don't update CI Rust toolchain without a PR

### ISSUE THREAD

**Issue by lann** [fermyon/spin#978]
Its good to keep the CI Rust toolchain up-to-date, but it should be done via automated PR a la dependabot rather than implicitly always fetching the latest toolchain.

@michelleN @fibonacci1729

**Comment by lann** [comment]
Might be able to cobble together something with https://github.com/dtolnay/rust-toolchain, which allows expressions like `toolchain: stable 2 weeks ago`. That plus a weekly build plus "stable now" would at least give us a grace period.

**Comment by endocrimes** [comment]
We could use [Renovate](github.com/renovatebot/) (e.g https://github.com/Turbo87/renovate-config/blob/master/rust/updateToolchain.json)

**Comment by itowlson** [comment]
There's a Renovate app for GitHub but I don't have permissions to install it in the Fermyon account.

https://github.com/marketplace/renovate

**Comment by itowlson** [comment]
Propose to close because CI now pins to a version.
