### ISSUE TITLE
Print description of logging behavior on `spin up`

### ISSUE THREAD

**Issue by lann** [fermyon/spin#993]
"How can I see logs?" is a recurring question in Discord. We should _at least_ print a description of how to find logs on `spin up`, maybe something like:

```
Writing app output to <path>; pass --follow-all to see it here on the console.
```

Ref https://github.com/fermyon/spin/issues/928, https://github.com/fermyon/spin/pull/974#discussion_r1050794287

**Comment by michelleN** [comment]
Now that we've made `follow-all` the default experience, can we close this issue or do you think more should be done here?

**Comment by michelleN** [comment]
Feel free to re-open
